### ISSUE TITLE
Avoid potential pitfall of forgotten `done` parameter

### ISSUE THREAD

**Issue by ptomato** [jasmine/jasmine#1040]
With the `done` syntax for asynchronous tests, it's possible to inadvertently write something like this:

```js
it("is an async spec", function() {
  setTimeout(function() {
    expect(true).toBeFalsy();
    done();
  }, 1000);
});
```

This spec will pass without encountering the expectation. Is there a way that Jasmine could issue some sort of early warning in a case like this?

One way would be to warn if a spec executed no expectations, but that would only solve the problem for specs and not for forgetting the `done` parameter on a `beforeEach()`, for example.

**Comment by magcius** [comment]
Another way would be to require explicitly async or sync tests, as in:

```js
it.async("is an async spec", function (done) {
  setTimeout(function() {
    done();
  });
});
```

With a warning if the arity isn't what's expected. This would also work for `beforeEach()`.

**Comment by slackersoft** [comment]
The HTML reporter should be reporting (to the `console`) when no expectations are made in a spec. You can see the logic for this [here](https://github.com/jasmine/jasmine/blob/master/src/html/HtmlReporter.js#L353), and any other reporter for Jasmine should be able to do something similar.

I think it might make sense to allow projects using Jasmine the ability an option to get this kind of check up front. I'm not sure about the `.async`/`.sync` interface, since we don't really have anything else like that at the top level. I'm also not really sure where the logic should go without adding more places that know about the extra param. I'd be happy to review a pull request that takes a crack at this or further discussion here about mechanisms and interfaces for this.

Thanks for using Jasmine!

**Comment by magcius** [comment]
We're using the `ConsoleReporter`.

**Comment by ptomato** [comment]
In my opinion, checking whether a spec has expectations can help, but won't solve the issue of the same problem happening in `beforeEach`.

The most failsafe way to solve it would be, in my opinion, to check whether a `done` variable is referenced when there isn't any such name in scope. However, that seems kind of ridiculous in practice as you'd basically have to run a linter over the spec before executing it.

Another way would be to have a syntax that's harder to get wrong and more obvious when you do, something like this:
```js
it("is an async spec", function (proceed) {
    setTimeout(proceed, 1000);
}, function () {
    expect(true).toBeFalsy();
});
```
That way, if you forgot the `proceed` parameter, but provided a function to be called after proceeding, then Jasmine would be able to know that you messed up. I don't know if changing the syntax is an option for you at all, though, or if the above has the same problem as `it.async` in that it's not similar to anything used elsewhere in Jasmine.

I don't have any better ideas right now, and I'd probably not want to start a pull request based on either of the above. But let me know if either general direction makes sense to you.

**Comment by kapke** [comment]
What about passing `thenable` as second argument to `it/beforeEach/afterEach` or returning `thenable` from passed callback?
Of course this doesn't solve problem (especially second option) but it looks to be more save and easy to track from user perspective. Most of JS programmers are familiar with promises so it looks to be natural to start supporting them.

**Comment by ptomato** [comment]
Do you have an idea of how some sample code with your idea would look like? Could we get away with it without including a promise implementation in Jasmine?

**Comment by kapke** [comment]
First option (passing thenable) would look like as follows:
```js
describe('sth async', function () {
  beforeEach(new jasmine.Promise((resolve, reject) => {
    this.foo = 'bar'
    resolve();
  });

  it('should be async', new jasmine.Promise((resolve, reject) => {
    expect(this.foo).toEqual('bar');
    resolve();
  });
}
```
In that case we need some kind of wrapper for `Promise` (named `jasmine.Promise` in that example) to start given action only on demand. It should be easy to achieve that by using native/polyfill implementation under the hood.

There is also alternative - we can pass a `Promise` which resolves to function and that function should return another `Promise`:
```js
describe('sth async', function () {
  beforeEach(Promise.resolve(function () {
    this.foo = 'bar';
    return Promise.resolve();
  }));

  it('should be async', Promise.resolve(function () {
    return makeSomeAsyncAction()
      .then(() => expect(this.foo).toEqual('bar'));
  }));
});
```
Probably this one is the easiest to implement and the easiest to make checking for returned value.

Second option (returning `thenable`) would look like:
```js
describe('sth async', function () {
  beforeEach(function () {
    this.foo = 'bar';
    return Promise.resolve();
  });
  
  it('should be async', function () {
    expect(this.foo).toEqual('bar');
    return Promise.resolve();
  });
}
```
As you can see - second option is almost the same as using `done` parameter because omitting `return` statement makes spec synchronous.

**Comment by kapke** [comment]
There is also one more advatange of supporting promises in any of proposed ways: it's possible to add `.catch` on end od promise chain for every async spec which makes error handling easier (in default errors in promises are not handled and very often I see errors `Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`.

As I have some spare time I can start work on that issue but it would be nice to have some feedback about design and proposed interface.

**Comment by rdy** [comment]
I have some experimental code where I have added an additional it that expects a promise to be returned. It looks great if you are using ES7 style promises.

```
    describe('when clicking the rules tab', () => {
      beforeEachAsync(async () => {
        await page.click('.rules-tab');
      });

      itAsync('renders a rules page', async () => {
        await page.waitForExist('.rules-page');
      });
    });
```
I'd be happy to share the code, we' re planning to publish the module as a separate way to add promises to jasmine, until the team is ready to add more in depth support for it. The problem as I see it is that not all browsers properly support promises natively and Jasmine still supports very old versions of IE. It might need to be an opt in kind of thing.

**Comment by mattburrell** [comment]
@rdy it'd be great to see code for `itAsync`, Ryan.

**Comment by mattburrell** [comment]
@rdy Ok I've found it under your [repositories](https://github.com/rdy/jasmine-async-suite). Thanks!

**Comment by slackersoft** [comment]
Ultimately, what I think we want to do for Jasmine, is have exceptions that are thrown in asynchronous code get associated with the currently running spec. I'm going to close this in favor of a more general solution like the one in #529.

Thanks for using Jasmine!
