### ISSUE TITLE
Add getMock() functionality to mock classes (to work with ECMA6/ TypeScript classes)

### ISSUE THREAD

**Issue by vladimir-ivanov** [jasmine/jasmine#1050]
Would be useful when working with angular2/typescript to be able to stub all methods in one go.

**Comment by slackersoft** [comment]
Can you describe more what the interface for this would look like and how it would behave? Based on what you've said, I don't understand what is needed.

**Comment by vladimir-ivanov** [comment]
class LifeCycle {

    constructor(anotherRealClassInstance) {
        this.dependency = anotherRealClassInstance;
    }

    init() {
        //body here
    }

    change() {
        //body here
    }

    destroy() {
        //body here
    }
}


class LifeCycleConsumer {

    constructor(lifeCycleInstance) {
        lifeCycleInstance.init();
    }
}

const lifeCycleMock = jasmine.mock(LifeCycle) //or jasmine.getMock(LifeCycle);

const lifeCycleConsumer = new LifeCycleConsumer(lifeCycleMock);


lifeCycleMock.expects("init").atLeast(1);
lifeCycleMock.onInit.verify();
`

**Comment by vladimir-ivanov** [comment]
an easy shortcut to spyOn / stub all dependency methods

**Comment by kapke** [comment]
I wrote some time ago simple piece of code resolving that problem. The idea was as follows: 
1. Fiind all method names in prototype chain starting from given constructor(s) - I had some kind of mixins in project so I needed to provide several constructors. 
2. Deduplicate them
3. return `jasmine.createSpyObj(name, methods)`

I that idea fits you I can start new branch with that code under `j$.getMock`.

**Comment by vladimir-ivanov** [comment]
This works for me and gives me what I need, would be nice to be part of jasmine?

      
let lifeCycleMock = getMock(LifeCycle);

function getMock(mockedClass) {
            Object.getOwnPropertyNames(mockedClass.prototype).forEach(m => spyOn(mockedClass.prototype, m));

            return new mockedClass();
        };

lifeCycleMock.init.and.callFake(() => "I am fake");

new LifeCycleConsumer(lifeCycleMock);

expect(lifeCycleMock.init.calls.count()).toEqual(1)

**Comment by kapke** [comment]
The code I've mentioned above is here:
https://github.com/skygate/CodeSamples/blob/master/js/pretender/pretender.js

As it creates jasmine mock object we don't call any of original methods (in some not so rare cases it would cause very strange behaviour).

**Comment by vladimir-ivanov** [comment]
code looks good, thanks
However I am trying to avoid using jasmine.createSpyObj(), as that won't return the same type of object as the one being mocked (need to do some testing later to confirm that). 
Also jasmine.createSpyObj - you won't be able to add / modify specific method behaviour after mock constructor is called.
E.g. with spyOn() - you can do this
lifeCycleMock.init.and.callFake(() => "I am fake"); or .returnValue etc - by default all methods stubbed, then the ones you are interested in -> you simply call it after the stubbed / mocked object is created (and before calling the methods).

Still thinking a method like that should exist in jasmine itself. E.g. Sinon has got one, all backend testing frameworks etc (nice shortcut to stub all methods).

**Comment by kapke** [comment]
Ok, got your point of view. I also think that method like that should be part of jasmine (look at comment from past week).

For type of mocked object - there we can use `Object.create` or something similar to assign prototypes properly which should result with right types.

I use the solution I presented above for testing real application and I'm able to add behaviour in the same way you presented, e.g.:
```lifeCyclemock.init.and.callFake(() => 'I am fake');```

**Comment by slackersoft** [comment]
Since Jasmine is implemented entirely in ES5, I don't think it makes sense for it to know much about different possibly `class` constructs (either TypeScript or ES6), since we wouldn't be able to guarantee type safety of the returned stub object.

That said, the object returned by `jasmine.createSpyObj` is just an object with a bunch of attributes that are spy objects, and thus can always have their behavior changed just by calling `.and` on them again. Jasmine does this in some of its own specs (e.g. https://github.com/jasmine/jasmine/blob/master/spec/core/integration/EnvSpec.js#L396).

This seems like the kind of thing that we would like to have be able to be provided as an extension. Since it sounds like it can be now, I think that is how we want to handle it. We would be happy to discuss things that Jasmine could do in order to make this work better.

I'm going to close this, as I don't think we're looking to implement something like this in Jasmine itself for the time being. Thanks for using Jasmine!
