### ISSUE TITLE
Microsoft Edge crashes when using array .toEqual on arrays multiple times

### ISSUE THREAD

**Issue by BenoitZugmeyer** [jasmine/jasmine#1056]
I recently updated a lot of unit tests from jasmine 1 to 2, and now my tests aren't running on Edge anymore. The UI starts showing then I've got a "This page is having a problem loading" page error. After a lot of fiddling, I found that it was caused by calling toEqual with an array (`expect(...).toEqual([...])`) multiple times (but a very few calls is enough to reproduce the error).

I made a video to illustrate the issue: http://paste.graou.eu/896249ea611b4f80aee3d62e4e44fe4a.webm . In this example I have to refresh two times to crash Edge, but with a lot more tests the issue is reproducible everytime.

Here is the code I used: http://paste.graou.eu/77512d1a469845219357333b78937be3.tgz

I bisected jasmine repository and it looks like a regression from 53b0752ff00733c87e3714769e5cece0f7de84f3 , but I can't explain why. Reverting this commit solves the issue.

Edge version: 20.10240.16384.0 (from a Win10 http://modern.ie VM)
jasmine version: 2.4.1 (tried on master too, same issue)

Is it a known issue? Should I avoid using a modern.ie VM? Am I the only one facing this issue?

**Comment by slackersoft** [comment]
I just tried your example spec with SauceLabs on Edge 20.10240 and it's seems to be working fine with all of the lines in the spec. I refreshed the page a number of times and it loaded and ran the specs immediately every time. It seems odd that it would be a modern.ie VM issue, but I am unable to reproduce it, so I'm not sure is going on with Edge.

In this case I think basically what is happening is the commit you referenced is removing a check for arrays, such that if they both say they are arrays (`className === '[object Array]'`) then Jasmine will actually do a recursive check, where before it would not. I don't know if SauceLabs is maybe running a very slightly newer version of MS Edge than is in the modern.ie VM such that this issue is now fixed in Edge.

I'd be happy to review anything that seems to be Jasmine directly causing issues, but right now this seems like it is probably a problem in MS Edge itself.

Thanks for using Jasmine!

**Comment by BenoitZugmeyer** [comment]
Thank you very much for the quick answer. I will come back to you soon with our real test suit, with which I can reproduce the issue everytime even on an up-to-date Edge version on a real computer. In the meantime, I'll try to work on a PR.

**Comment by BenoitZugmeyer** [comment]
Well, I just realized the issue was solved in b59cacf13173dc89eda174bcf57c54377c56b266 . I should have tried with the master version first, my bad. Sorry for the noise, I'll wait for the next release!
