### ISSUE TITLE
Link to individual tests by id instead of full GWT

### ISSUE THREAD

**Issue by logankd** [jasmine/jasmine#1065]
Qunit has a link like: http://localhost:49313/test/unit/index.aspx?testNumber=510
to contrast Jasmine creates links like http://localhost:52734/unittests/tests.aspx?spec=Given%20sort%20model%20when%20sorting%20And%20setting%20the%20sort%20option%20And%20it%20updates%20the%20sort%20option%20should%20set%20orderBy%20to%20ascending

Proposal: Add ids to each test and links like QUnit to reduce query string length.

**Comment by slackersoft** [comment]
Jasmine currently generates ids for all suites and specs, but they are generated as the suite is compiled from your spec files. This means that the id for a given spec could change from run to run if other specs are added to the suite. However, the full description of a given spec is less likely to change without a specific change from the user writing the spec. This is why we use the full description instead of the id.

Are you seeing something not work properly with the long query string?

Thanks for using Jasmine!

**Comment by logankd** [comment]
Everything is working, it was just an it to make it easier to look at as I ran a single spec. Your explanation is plenty for me. I didn't think of them changing as specs are added/removed.

Thanks for looking at this and your work on Jasmine!
