### ISSUE TITLE
Custom equality doesn't work with toHaveBeenCalledWith()?

### ISSUE THREAD

**Issue by awong9** [jasmine/jasmine#1100]
```
describe("custom equality", function() {
  var eq = function(a,b) {
    return a==b;
  };

  beforeEach(function() {
    jasmine.addCustomEqualityTester(eq);
    spyOn(console, 'log');
  });
  it('should work with toEqual()', function() {
    expect('1').toEqual(1);
  });

  it('should work with toHaveBeenCalledWith()', function() {
    console.log('1');
    expect(console.log).toHaveBeenCalledWith('1');
    expect(console.log).toHaveBeenCalledWith(1);

  });
});
```
Using jasmine-standalone 2.4.1

**Comment by slackersoft** [comment]
This is happening because when `toHaveBeenCalledWith` checks for argument equality, it has 2 arrays of arguments in order to handle multiple functions with multiple arguments. Because of that, and because in javascript `[1] != [1]` you may want to change your custom equality tester to only work on things that aren't arrays, something like this should give you the behavior you are expecting: 

```javascript
jasmine.addCustomEqualityTester(function(a, b) {
  if (!(a instanceof Array) && !(b instanceof Array)) {
    return a == b;
  }
});
```

Closing this, as I believe this is the desired behavior. By returning a non-`undefined` value from your equality tester, you are telling Jasmine that you know how to compare the two objects. Thanks for using Jasmine!
