### ISSUE TITLE
Feature request for spyOn - pass method directly instead of using string constant for identification

### ISSUE THREAD

**Issue by stefaneidelloth** [jasmine/jasmine#1117]
If I spy on a method with

spyOn(parent, 'methodToSpyOn')

and the name of the method changes during refactoring, I have to manually
adapt the string argument. 

Therefore I suggest to include a method like

spyOnMethod(self, self.methodToSpyOn);

that does not use a string constant for the identification but retrieves the method directly. 
When changing the method name during refactoring, my IDE will be able to adapt the argument automatically.

A method with only one argument would be even better, but I guess
this is not possible since the parent needs to be known:

spyOnMethod(self.methodToSpyOn);

Here is a first draft for an implementation:

    function spyOnMethod(parent, methodToSpyOn) {
      var methodName = getMethodName(); 
      return spyOn(parent, methodName);

      function getMethodName() {
        var foundAttributeName = null;
        var attributeNames = Object.keys(parent);
        _.forEach(attributeNames, function (name) {
          var attribute = parent[name];
          if (attribute === methodToSpyOn) {
            foundAttributeName= name;
          }
        });
        return foundAttributeName;
      }
    }

**Comment by glebec** [comment]
The parent does not need to be known. You can use an alternate syntax to spy on any function.

```js
var spy = jasmine.createSpy().and.callFake(obj.method);
```

By the same token you can replace a method with such a spy.

```js
obj.method = jasmine.createSpy().and.callFake(obj.method);
```

**Comment by stefaneidelloth** [comment]
Thanks for your reply. Well, what I mean is that if I only pass the method to the helper function, I do not know how to replace the method since I don't know the parent ( = "obj" in your example):

    function spyOnMethod(methodToSpyOn){       
        var parentObj = getParentByReflection(methodToSpyOn);  // <== this is not possible as far as I know
        var methodName = getMethodNameByReflection(parentObj, methodToSpyOn); 
        parentObj[methodName] = jasmine.createSpy().and.callFake(obj.method);
   }

**Comment by slackersoft** [comment]
In order to install and uninstall a spy on an existing object, Jasmine needs to know that object. This also means that by simply replacing `obj.method` yourself as @glebec suggests, Jasmine won't be able to remove the spy once the spec completes and it will remain spied upon for any further specs in your suite.

If you call `createSpy` without a name parameter, you also lose some better error messages when you check `toHaveBeenCalled`.

I think the `spyOnMethod` potentially creates too many options when trying to spy on a method, for not very much gained. It potentially causes confusion as to which way a user should spy.

Closing this. Thanks for using Jasmine!
