### ISSUE TITLE
Add a way to specify custom reason for disabled suites

### ISSUE THREAD

**Issue by grushler** [jasmine/jasmine#1132]
Currently we can provide custom reason for pending specs using `pend()`. How do we do the same for suites where we disable it using `xdescribe`? See http://stackoverflow.com/questions/37791690/any-way-to-provide-reason-to-a-disabled-suite-in-jasmine for more details. Thanks!

**Comment by Gerg** [comment]
It looks like `Suite` has a `pend` method on it: https://github.com/jasmine/jasmine/blob/04bb56a5b553e005dd615f12a6892e5395c9dfb5/src/core/Suite.js#L45

From my testing it doesn't seem to do anything currently. I would be happy to look at a PR that makes `pend` work for Suites.

**Comment by slackersoft** [comment]
The `pend` function for Suites and Specs isn't really exposed in the Jasmine interface. Both are meant as the internal way that Jasmine marks them as having been `x`ed out with `xdescribe` or `xit`. Neither of those calls accept a reason (they'll default to `marked pending with xit` or something) because they are meant to be a short term measure to limit the specs that you're running, not a longer term way to turn the specs off.

If you want to specify a reason for pending the spec(s) you should use `pending` possibly in a `beforeEach` (`beforeAll` _might_ work) to pend all the specs with a reason.

See also #1175 and the merged PR #1225 which makes `xdescribe` use its pending state correctly.

Closing this, `pending` is the way to specify a message for this. Thanks for using Jasmine!
