### ISSUE TITLE
Asynchronous beforeEach / beforeAll

### ISSUE THREAD

**Issue by tonyxiao** [jasmine/jasmine#1145]
Jasmine's `it` is able to handle `async`. However `beforeEach`, `beforeAll`, and `describe` do not seem to handle async functions properly. Sometimes test setup is asynchronous. Suggestions?

**Comment by Gerg** [comment]
Can you provide an example of what you mean by "do not seem to handle async functions properly?" `beforeEach`, `afterEach`, `beforeAll`, and `afterAll` all support async testing via the `done` callback. Also, can you give an example why you might want `describe` to be executed asynchronously?

See documentation here: http://jasmine.github.io/2.4/introduction.html#section-Asynchronous_Support

**Comment by tonyxiao** [comment]
@Gerg ah ok. Nvm there's actually no reason to use `describe` asynchronously since we'd want setup code to be done in `beforeAll` anyways to be more idiomatic rather than directly inside the `describe` method (which I sometimes do.). Speaking of which, is there any technical reason to use `beforeAll` rather than just write the setup code directly toward the top of the `describe` block before all the `it`s?

**Comment by tonyxiao** [comment]
And I was talking about es7 async await function support in `beforeEach`. Turns out I was using jasmine through `jest` and jest implemented additional async await support on top of its bundled version of jasmine. So never mind that either. (see https://github.com/facebook/jest/issues/1256)

**Comment by Gerg** [comment]
I see. Jasmine doesn't currently have explicit support for many ES* features (largely due to support for legacy browsers).

The code inside your `describe` is executed at a different time then code inside `beforeAll` etc (internally called "runnables"). `describe` callback functions are invoked when Jasmine is building your spec tree. Your runnables run later when Jasmine is executing the tree it built. Putting code inside the runnables also has other benefits like:
* Access to Jasmine's managed [this keyword](http://jasmine.github.io/2.4/introduction.html#section-The_<code>this</code>_keyword)
* Errors in the runnables will be linked to the correct specs
* Spies created with `spyOn` in runnables are cleaned up
* Custom matcher created in runnables are cleaned up

Thanks for using Jasmine!

**Comment by tonyxiao** [comment]
Got it. Thanks for the helpful explanation.
