### ISSUE TITLE
How to compose matchers or use built-in matchers in custom matchers

### ISSUE THREAD

**Issue by mmollaverdi** [jasmine/jasmine#1168]
I have implemented a custom wrapper type - called `Some` - (using ES6 classes) and now want to create a custom matcher - called `toBeSome` for this type.

```
class Some {
  constructor(value) { ...}
  method1() { ... }
  method2() { ... }
}
```

The custom matcher I want to create needs to accept other matchers which apply to the value inside `Some`:

```
expect(new Some(2)).toBeSome(x => x.toEqual(2))
```

I wasn't sure how to pass in built-in matchers to `toBeSome`, but I figured if I pass them as functions, I should be able to call them within my custom matcher.

My custom matcher looks like this (I've simplified it here a little bit):

```
var customMatchers = {
  toBeSome: (util, customEqualityTesters) => ({
    compare: (actual, expectedMatcher) => {
      var result = expectedMatcher(expect(actual.value));
      return result;
    }
  })
};
```

I'm expecting `expectedMatcher(expect(actual.value))` to apply the given `expectedMatcher` for me.

For example, in the case of `expect(new Some(2)).toBeSome(x => x.toEqual(2))` above, `expectedMatcher(expect(actual.value))` should become:

```
expect(actual.value).toEqual(2)
```

But it actually returns `undefined`.

It seems like built-in matchers are not defined yet when defining custom matchers?

Any idea how I can pass and use matchers in custom matchers?

**Comment by mmollaverdi** [comment]
You might ask why I just don't apply built-in matchers to the value inside `Some` in my test, e.g.:

```
expect(new Some(2).value).toEqual(2)
```

The answer is that I'm actually not exposing `value` directly in the `Some` class. The methods in `Some` class apply the given arguments to the value internally. 

My custom matchers is also going to use those methods, as opposed to accessing the value directly. The version of custom matcher I've posted above is simplified to demonstrate the problem with accessing built-in matchers; and is different to what I'm actually trying to implement.

I hope it's not all confusing.

**Comment by benchristel** [comment]
If you only need to test for equality in your matcher, you can call `util.equals(actual, expected, customEqualityTesters)`. This is what `toEqual` uses for object comparison.

**Comment by mmollaverdi** [comment]
Thanks @benchristel. No, the idea was to actually compose the matchers (use built-in matchers in custom matchers). I want to be able to pass in different matchers to `toBeSome` in different tests.

The issue with  `expectedMatcher(expect(actual.value))` (which translates to `expect(actual.value). toEqual(2)`) returning `undefined` seems to be that jasmine internally uses `addExpectationResult` to set expectation results to a variable which is then used to pass or fail a test. The expectation result doesn't actually get returned by built-in matchers.

I wonder if refactoring the jasmine code to return expectation results in addition to setting it which it currently does, would address my problem without impacting how it currently works. I might try that locally.

**Comment by mmollaverdi** [comment]
Just saw your edit above. How do you suggest I implement `withValueOf`?

**Comment by benchristel** [comment]
> How do you suggest I implement `withValueOf`?

If we assume that we can get the value of a `Some` just by accessing the value property, it would be:

```javascript
function withValueOf(some, fn) {
  fn(some.value);
}
```

But of course in reality you'd get the value some other way.

**Comment by mmollaverdi** [comment]
Good suggestion @benchristel 👍. That would work. I'm going to use it for the time being.

I won't be able to customize the failure messages though with this approach obviously. I had a play with making [`wrapCompare` function](https://github.com/jasmine/jasmine/blob/11cfaae42ab31a494e005d36f49d8c1e089fed3b/src/core/Expectation.js#L16-L69) return the `result` and a message and it "sort of" worked. I can call built-in matchers in my custom matcher with this change and use the result. I might PR that through later on.

**Comment by jaketodaro** [comment]
I have a very similar situation where I'd like to compose matchers. Let's say you want to write a custom matcher to check that a tuple contains both even numbers. You could just check for evenness manually in the custom matcher

```
var customMatchers = {
  toBeEvenTuple: () => ({
    compare: (actual) => {
      return {
        pass: actual[0] % 0 === 0 && actual[1] % 0 === 0
      };
    }
  })
};
```

But it would be better if I could do something like this...

```
var customMatchers = {
  toBeEvenTuple: () => ({
    compare: (actual) => {
      return {
        pass: expect(actual[0]).toBeEven() && expect(actual[1]).toBeEven()
      };
    }
  })
};
```

I can do this now, but if I test `[0, 1]`, I'll get a failure message that "1 is expected to be even", when really what I want is to fail with the message "Tuple [0, 1] is expected to be even". This is a trivial example where the nested matchers could be replaced with a one line boolean expression, but not all matchers can be so easily swapped out.

I'm not sure what would have to happen to make this work. Maybe custom matchers could catch failures from nested `expect` statements and fail the entire expectation, or something could be added to allow obtaining a boolean value from an `expect` statement. The latter might be better because then the matcher could have different error messages for different kinds of failures.

**Comment by slackersoft** [comment]
With the current architecture of Jasmine, a running matcher would actually need to become its own `currentRunnable` for the purpose of getting any expectation failures in child `expect`s. This is due to the desire for Jasmine to give you all of the failing expectations for your spec, which means no errors are thrown unless the option is set to `throwFailures`.

The most common use case that I have heard for custom matchers calling other matchers is `toEqual`, which as @benchristel mentioned can be done without the actual matcher now. We don't have any plans to generally allow matchers inside other matchers at this time.

Closing. Thanks for using Jasmine!
