### ISSUE TITLE
No documentation for jasmine.json

### ISSUE THREAD

**Issue by fortuna** [jasmine/jasmine#1181]
I can't find documentation for the `jasmine.json` file format anywhere, making it a big productivity drain.

I want to figure out how to exclude directories from my specs list, but can't figure out how due to the lack of documentation.

This is a core configuration file and should be easy to find.

**Comment by fortuna** [comment]
This seems to be a recurring topic: #49 #997.

Despite those issues being closed, I don't think the problem was solved. There must be a more explicit documentation about the file format that one can easily find.

**Comment by nashwaan** [comment]
I found some documentation about `jasmine.json` here http://jasmine.github.io/edge/node.html
But i could not find anywhere how to exclude certain files or folders.
My workaround is that I suffix all my spec files with `_test.js` such as `api_test.js` and `logic_test.js`.
So that i am certain that these are the only files included as in this `jasmine.json`:
```json
{
    "spec_dir": ".",
    "spec_files": [
        "./**/*_test.js"
    ],
    "helpers": [
    ],
    "stopSpecOnExpectationFailure": false,
    "random": false
}
```

**Comment by slackersoft** [comment]
The source for the [Jasmine documentation](https://jasmine.github.io) has its [own github repository](https://github.com/jasmine/jasmine.github.io). We do accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls) for our documentation, if you'd like to help out, or [issues](https://github.com/jasmine/jasmine.github.io/issues) if you have things you'd like see addressed but aren't sure how.

Closing this in favor of something in the docs repo. Thanks for using Jasmine!
