### ISSUE TITLE
Documentation for customer matchers is unclear

### ISSUE THREAD

**Issue by gotofritz** [jasmine/jasmine#1206]
Hi. In the example for the custom matcher you have this code sample

```
toBeGoofy: 
// ... time passes
  if (result.pass) {
    result.message = "Expected " + actual + " not to be quite so goofy";
  } else {
    result.message = "Expected " + actual + " to be goofy, but it was not very goofy";
  }
```

Now the test is called "toBeGoofy" and the "pass" says NOT to be goofy, while the other branch says "to be goofy". So "toBeGoofy" passes if actual is NOT goofy? It's not clear at all from the two sentences which branch of the if-statement is and which isn't goofy. It's all well and good to have fun while writing documentation, but if it's not understandable than you are missing the point. Is it not possible to have something which is more black and white? 

Thanks.

**Comment by Gerg** [comment]
Jasmine matchers will only print messages if the assertion fails. So the `result.pass` case is when the matcher succeeded, but the assertion failed because of a `not`. For example: `expect(foo).not.toBeGoofy()`. The else case is for the normal case where matcher failures result in assertion failures.

**Comment by gotofritz** [comment]
I see, it makes sense, thanks.
