### ISSUE TITLE
jasmine.getEnv().currentSpec returns undefined

### ISSUE THREAD

**Issue by prashanth-sams** [jasmine/jasmine#1212]
**Snippet for taking screenshot on Test Failure**

    	afterEach(function() {
    
    		var spec = jasmine.getEnv().currentSpec;
    		var passed = spec.results().passed();
    
    	  if (!passed) {
    	    browser.takeScreenshot().then(function(png) {
    	      writeScreenShot(png, "screenshot.png");
    	    });
    	  }
    
    		function writeScreenShot(data, filename) {
    				var stream = fs.createWriteStream(filename);
    				stream.write(new Buffer(data, 'base64'));
    				stream.end();
    		}
    
    	});

**Console error**

      Message:
        Failed: Cannot read property 'results' of undefined
      Stack:
        TypeError: Cannot read property 'results' of undefined
            at Object.<anonymous> 

----------

it returns `undefined` here,

    var spec = jasmine.getEnv().currentSpec;
    console.log(spec);

**Comment by Gerg** [comment]
What version of Jasmine are you using? As of 2.0, env.currentSpec is no longer supported.

**Comment by prashanth-sams** [comment]
@Gerg I use Jasmine 2.0 and is there any work around for this in Jasmine 2.0?

**Comment by Gerg** [comment]
You could probably make a [custom reporter](http://jasmine.github.io/2.5/custom_reporter.html) to take screenshots on spec failure. Something like https://www.npmjs.com/package/protractor-jasmine2-screenshot-reporter.

**Comment by prashanth-sams** [comment]
@Gerg I use cucumber and is there any suitable libraries for the same? Thanks!

**Comment by slackersoft** [comment]
This appears to have morphed into a question about how to use Jasmine. You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this, since the current functionality is the desired in Jasmine post 2.0. Thanks for using Jasmine!
