### ISSUE TITLE
ability to suppress "has no expectations" warnings

### ISSUE THREAD

**Issue by srittau** [jasmine/jasmine#1221]
Using Jasmine 2.5.0, I have several tests that have no expectations. Some are just testing, whether a particular asynchronous method is called (and will error out due to the timeout), others will report errors by throwing exceptions. Currently all these tests print "Spec 'Foo' has no expectations." to the browser console and "SPEC HAS NO EXPECTATIONS" to the HTML output.

The latter is a bit annoying, since it indicates a problem, where there is none. The former is more problematic as it spams the console with bogus error messages, which make it harder to recognize real problems in the console output.

One workaround is to add a "null" expectation to the tests, for example "expect(true).toBe(true)", but this makes tests harder to read and is non-obvious.

Below is a real world example:

``` javascript
describe("Foo.LoadManager", function () {
    "use strict";
    it("load() will abort another Promise", function (done) {
        let promise1, promise2,
            manager = new Foo.LoadManager();

        promise1 = new Promise(function (resolve) {
            window.setTimeout(resolve, 1);
        });
        promise2 = new Promise(function (resolve) {
            window.setTimeout(resolve, 5);
        });
        manager.load(promise1).then(() => {
            done.fail("promise1 was unexpectedly fulfilled");
        });
        manager.load(promise2).then(done);
    });
});
```

**Comment by slackersoft** [comment]
We would be happy to review a pull request to add an option to turn the warnings off. The warnings should stay on by default, since they are a smell that you're possibly not actually testing anything.

Thanks for using Jasmine!

**Comment by srittau** [comment]
I wonder what the best way to implement this is. Currently I have a helper function `expectNothing()`:

```js
function expectNothing() {
    expect(true).toBeTruthy();
}
```

Something like this could easily be shipped with Jasmine, although probably a bit more "smart": included on the expect function (`expect.nothing()`) and marking a spec instead of using the magic above.

This would be used like this:

```js
describe("a test without expectations", () => {
    it("would not output any warnings", () => {
        // elaborate test code ...
        expect.nothing();
    });
});
```

Another approach is a custom `it()` function or another argument to `it()`:

```js
describe("a test without expectations", () => {
    it("would not output any warnings", () => {
        // elaborate test code ...
    }, { noExpectations: true });
});
```

**Comment by slackersoft** [comment]
Syntax-wise, I like `expect.nothing()` a bit better than adding another optional argument to `it`, but the internal implementation of that is probably a bit trickier. Initially I was thinking something more like the existing global suite flags like throwExceptions, random, etc.

Hope this helps.

**Comment by ksvitkovsky** [comment]
I'm thinking about adding a new matcher with `compare` function that simply returns `true`. You would use it like this - `expect().nothing();`.

I prefer that approach because:
- implementation is consistent with the actual code base;
- it explicitly applies on single spec and not on whole suite;

One question though, should we silently suppress other expectations if presented or throw an error like `expected nothing but have another expectation` or do not check that case at all?

@slackersoft, ready to make a pull request on your command 😊

**Comment by Kuraisu** [comment]
I think it would be an inconsistent behavior of one single matcher to depend on neighboring matchers. But issuing a warning instead of an exception would be useful.

**Comment by andregs** [comment]
Please, is there some sort of flag to activate that warning message? I have tests with no expectations but I don't get the warning.

My setup:
```js
require("reflect-metadata");
const Jasmine = require("jasmine");
const handler = new Jasmine();

// https://jasmine.github.io/edge/node.html
handler.loadConfig({
  random: false,
  spec_dir: 'dist',
  spec_files: [
    '**/*.spec.js',
  ],
  helpers: ['helpers/**/*.js'],
  random: false
});

handler.execute();
```

Output:
```
Started
......................................


38 specs, 0 failures
Finished in 0.209 seconds
```

**Comment by sgravrock** [comment]
@andregs, the warning in question is implemented in the HTML reporter, so it's not available in Node. If you want, you can easily implement it yourself by writing a [custom reporter](https://jasmine.github.io/tutorials/custom_reporter) with a [specDone](https://jasmine.github.io/api/edge/Reporter.html#specDone) event that checks the number of passed and failed expectations and prints a warning if they're both 0. But [I'd encourage you to take a look at your testing workflow instead](https://github.com/jasmine/jasmine/issues/1467#issuecomment-352222044), since relying on a check for assertions can mask deeper problems.
