### ISSUE TITLE
Expose clearReporters() method in runner module

### ISSUE THREAD

**Issue by lonelyelk** [jasmine/jasmine#1228]
I noticed that in v2.5.2 the default reporter is no longer removed when adding a custom one. So I've found out that there is a [new method](https://github.com/jasmine/jasmine/commit/04bb56a5b553e005dd615f12a6892e5395c9dfb5). But for some reason it is not exposed in runner class. So now I have to do:

``` javascript
var Jasmine = require('jasmine'),
    jrunner = new Jasmine();

jrunner.env.clearReporters();
jrunner.addReporter(myReporter);

jrunner.execute();
```

I think it would be better to be able to drop `env`:

``` javascript
var Jasmine = require('jasmine'),
    jrunner = new Jasmine();

jrunner.clearReporters();
jrunner.addReporter(myReporter);

jrunner.execute();
```

**Comment by DerekOverlock** [comment]
This is more so related to #1216... but since that was closed I figured I'd add it here:

Looking at the source code for 2.5.2, I see:
```javascript
function Jasmine(options) {
...
this.reporter = new module.exports.ConsoleReporter();
this.env.addReporter(this.reporter);
...
}
```

With this change, we are no longer able to use configureDefaultReporter to configure the default ConsoleReporter, since a console reporter (without any configuration) is already added when Jasmine is initiated, which explains the issue in #1216. 

Relating to this issue, as noted above by @lonelyelk, this also means that this console reporter will not be replaced by a custom reporter, unless you clear the console reporter by calling `jasmine.env.clearReporters()` and then adding the desired reporter.

**Comment by slackersoft** [comment]
@DerekOverlock The `ConsoleReporter` was also refactored to allow options to be set later, which is what `configureDefaultReporter` does.

**Comment by slackersoft** [comment]
We would be happy to review a pull request to expose a `clearReporters` function on the wrapper Jasmine, so you don't have to pull out the `env` to do that.

**Comment by lonelyelk** [comment]
I'm sorry, I may be lacking experience in writing code that works in multiple environments, but it's too obscure for me. I can't seem to find any differences in `addReporter` and `clearReporters` implementations. They are always defined and mentioned together. I can't seem to find any node-require API test suite either. May be someone can direct me to a proper place?

**Comment by slackersoft** [comment]
@lonelyelk it looks like the pull request would actually be in [jasmine-npm](https://github.com/jasmine/jasmine-npm), which is the node.js wrapper around jasmine-core.

Sorry for the confusion.
