### ISSUE TITLE
feature: make main testing functions module importable

### ISSUE THREAD

**Issue by mikehaas763** [jasmine/jasmine#1235]
In a javascript, typescript or other module environment it would be ideal to import the testing functions as opposed to making them available globally.

eg
```javascript
import { describe, it } from 'jasmine';
```

Does this sound like a good idea to everyone else?

**Comment by slackersoft** [comment]
That sounds interesting, and probably the thing you want to use to provide that is the `jasmineInterface` that is loaded up by the various boot scripts. I'm not what the right way for Jasmine-Core to provide this interface since it is purely ES5. Additionally, removing the interface from the global object would be a breaking change and not something we would be able to release in the current 2.x release cycle.

**Comment by denniscollective** [comment]
It could theoretically be backwards-compatible by making it be a different require IE

```
import { describe, it } from 'jasmine/no-global'
```

which the jasmine package could then depend on and install globally.

**Comment by slackersoft** [comment]
We would be happy to review a pull request to add a different entry point into Jasmine that didn't auto install onto `global` to allow users to use imports more idiomatically.
