### ISSUE TITLE
Derivative Promises get resolved incorrectly

### ISSUE THREAD

**Issue by YelloJacket** [jasmine/jasmine#1244]
Gist:

I spy on get method of my rest service.
spyOn(restService, 'get').and.callFake(function () {
      return deferred.promise;
});  
The method I am trying to test is myService.getFormData() that returns a chained promise:

function getFormData() {
     var getPromise = this.restService.get(endPoint, params, true);
     var processedDataPromise = then(successHandle, failHandler);
     return processedDataPromise;
}
3.Back to Jasmine spec, I invoke getFormData function and make assertions:

         var processedDataPromise = myService.getFormData();
         processedDataPromise.then(function(data) {
          expect(data).not.toBeNull();

        });
deferred.resolve(testFormData);
$rootScope.$digest();

The Problem: 
The above derivative promise (processedDataPromise) does indeed get resolved. However the 'data' passed to it is undefined. Is it anything to do with $digest cycles not doing its job in Jasmine?

Why does Jasmine not pass any data to the above derived promise.? 
Further Note: The processedDataPromise is a completely new promise than the get returned promise.

It is a promise for processedData which as we can see is returned by successHandle (Definition not shown) once its parent getPromise gets resolved.

In UI everything works like a Charm.

**Comment by zion1129** [comment]
It's not really clear where the parameter/argument "data" is coming from? Where that is an anonymous function how are you passing it in? If it's being returned by myService.getFormData() I would be interested to see how you're passing it in.

**Comment by slackersoft** [comment]
Jasmine doesn't know anything about Promises. It looks like you're probably using Angular in some form, so I would take a look at their docs for how to deal with multiple chained promises in test. Many promise libraries do resolution in a `setTimeout` (or similar) so if you are using either Jasmine's built-in `clock` or some of the Angular clock testing stuff, you may need to force that to proceed to continue resolution.

Jasmine [clock documentation](https://jasmine.github.io/2.5/introduction#section-Jasmine_Clock)

I'm going to close this, since it seems like an issue with Angular or your tests, and not with Jasmine itself. In the future, you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Thanks for using Jasmine!
