### ISSUE TITLE
Test fail when calling `done(true)`

### ISSUE THREAD

**Issue by NoelBroda** [jasmine/jasmine#1254]
Hi guys!
As I was reading (https://github.com/jasmine/jasmine.github.io/issues/67), jasmine should not fail when calling done(true) or done(whatever!), but it's failing in my local env.

Do you have unit tests for done function? You should check that done should not fail when passing a parameter.

 - What version are you using?
`"karma-jasmine": "^0.3.6",`

 - What environment are you running Jasmine in (node, browser, etc)?
Browser
 - How are you running Jasmine (standalone, npm, karma, etc)?
IE, Chrome, FF, Safari

**Comment by slackersoft** [comment]
The `done` callback that is provided by Jasmine itself will ignore any parameters that are passed to it. (https://github.com/jasmine/jasmine/blob/master/src/core/QueueRunner.js#L59)

Because karma wraps some of this up, it might be worth asking the karma team about this as well.

I'm going to close this because it doesn't look like this issue is with Jasmine itself. Thanks for using Jasmine!
