### ISSUE TITLE
Wrong invocation of a callback

### ISSUE THREAD

**Issue by marco-a** [jasmine/jasmine#1272]
- What version are you using?
I am using `jasmine v2.5.3 and jasmine-core v2.5.2`.

 - What environment are you running Jasmine in (node, browser, etc)?
I am using `babel-node`.

 - How are you running Jasmine (standalone, npm, karma, etc)?
As far as I know I'm running it `standalone`.

 - If possible, include an example spec that demonstrates your issue.
See the repository I created: https://github.com/marco-a/jasmine-bug.

`$ npm install`
`$ npm test`

You should see one test failing:

![bug](https://cloud.githubusercontent.com/assets/1594477/22515855/3a9892b6-e8a4-11e6-9ff1-b6ddaffb3904.png)

But I'm not even calling the said callback in my second test case!

Also strange: if you comment out some of the tests then it suddenly works again?!

AFAIK the method under test does not have an internal state.

Or am I maybe doing something wrong?

**Comment by marco-a** [comment]
Okay I maybe got the fail: Is it possible that calling `done` does not immediately exit the test case?

**Comment by slackersoft** [comment]
The `done` callback simply tells Jasmine that this spec is complete and it is safe to move on to the next spec. This means that if there is still async work going on after `done` is called, it will still get invoked at some point. We have explored a bit around trying to stop the outer execution once `done` is called, but haven't really found a good way to accomplish this.

I'm going to close this, since it sounds like you're encountering what is the currently expected functionality. Thanks for using Jasmine!
