### ISSUE TITLE
Cannot show test progress in the browser

### ISSUE THREAD

**Issue by skyshore2001** [jasmine/jasmine#1285]
**Problem**

I use jasmine 2.5.2 to test my back-end web APIs via ajax *sync* call in each "it" block.
When the test starts, the browser enters no response status with blank screen.

As the tests last long time, I want the progress feedback (result like "."/"X"/"*" shows after each case completes) and a manual stop-test feature (see https://github.com/jasmine/jasmine/issues/1284)

I don't want to write the cases in async mode as it makes code complex.

**Environment**

- What version are you using?
2.5.2

- What environment are you running Jasmine in (node, browser, etc)?
Browser.

- How are you running Jasmine (standalone, npm, karma, etc)?
Standalone

**Comment by slackersoft** [comment]
Jasmine should print out dots, x's, and *'s as each spec completes. However, this is best effort rendering, due to javascript's threading model (or lack thereof). This means that if your specs or code under test are still working and not letting the `HTMLReporter` get its contents redrawn, you won't be able to see the updates.

I would either look into making your suite use async XHR, to get some of those benefits, or test your backend API without using a browser (framework may differ based on the backend language).

Closing this. Thanks for using Jasmine!
