### ISSUE TITLE
Jasmine hangs for a few min when trying to assert an object with circular reference

### ISSUE THREAD

**Issue by DzmitryShylovich** [jasmine/jasmine#1288]
**Current behavior**
There's a data structure `DebugElement` (wrapper around a native element with additional info useful for debugging). When you test to see if `DebugElement` doesn't exists `expect(de).toBeFalsy()` browser hangs for a few mins (as far as I understand Jasmine will keep cycling with a circular reference as it tries to print out the DebugElement to compare it to false).

**Expected behavior**
Should take a reasonable amount of time to execute the test.
Can it be addressed somehow inside Jasmine or should I change `DebugElement` impl?

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/GGECfSqptOXadysFDUh6?p=preview

**Comment by slackersoft** [comment]
It looks like the matcher is executing fine, but the [PrettyPrinter](https://github.com/jasmine/jasmine/blob/master/src/core/PrettyPrinter.js) is taking a while to print out the object. The PrettyPrinter should skip over circular object graphs, and print out a message. You should also be able to set your `jasmine.MAX_PRETTY_PRINT_DEPTH` to something lower than the default of `40` since it looks like that object is quite wide but not necessarily very deep.

The Jasmine PrettyPrinter will also look for a custom `toString` (or `jasmineToString` if you want it for specs only) that will pre-empt any recursing.

If those aren't sufficient, you'll probably need to change something else about the `DebugElement` implementation to make it more amenable to printing in Jasmine.

Hope this helps. Thanks for using Jasmine!

**Comment by DzmitryShylovich** [comment]
> jasmineToString if you want it for specs only

👍 Thank you very much!
