### ISSUE TITLE
toHaveBeenCalledWith() crashes test environment when matching large objects

### ISSUE THREAD

**Issue by smasala** [jasmine/jasmine#1291]
**Problem:**
toHaveBeenCalledWith() matcher with large objects

**Outcome:**
crashes the entire environment (PhantomJS) or runs recursively (Chrome).

**Workaround**
create a custom equality tester (jasmine.addCustomEqualityTester) before "toHaveBeenCalledWith()" is called. This leads to the EqualityTester failing rather than the environment crashing :)

**Setup:**
- Angular2
- Jasmine 2.5.2

**Example:**

Some sort of injectable service
```
@Injectable()
class EventService {
    broadcast(name: string, ...args: any[]) {
		//do something
	}
}
```

A big/complex object to match like an Angular component
```
class Angular2Component {

	someFunction() {
		injectedEventService.broadcast("myEventName", this);	//this being the component itself
	}

}
```

Now the Test
```
describe(() => {

    it("myTest", inject([EventService], (eventService: EventService) => {
	
		spyOn(eventService, "broadcast");
		//createComponent
		component.someFunction();
		
		expect(eventService.broadcast).toHaveBeenCalled(); // true

		// When the second argument isn't passed, the equlity matcher crashes the 
                // environment
		expect(eventService.broadcast).toHaveBeenCalledWith("myEventName")
	
                // Also crashes the environment when the argument amount is correct but one value is
                // not correct
                expect(eventService.broadcast).toHaveBeenCalledWith("someOtherEventName", jasmine.any(Angular2Component));

	}));

})
```

**Comment by smasala** [comment]
**Custom equality tester workaround**
```
jasmine.addCustomEqualityTester((first, second) => {
    let test1: boolean = first[0] === second[0]; //test name
    let test2: boolean = first[1].constructor.toString() === second[1].expectedObject.toString();
    return test1 && test2;
});
expect(eventService.broadcast).toHaveBeenCalledWith("myEventName", jasmine.any(Angular2Component));
```

**Comment by slackersoft** [comment]
Jasmine equality comparison (which is used for the `toHaveBeenCalledWith` matcher that comes with Jasmine) should handle circular objects correctly, and passing in something with `jasmine.any` should short-circuit most of the equality stuff anyways.

I notice in your initial comment though, that you are calling `hasBeenCalledWith` and not `toHaveBeenCalledWith` as you are in your workaround. `hasBeenCalledWith` is _not_ part of Jasmine and may not correctly use Jasmine's equality logic.

**Comment by smasala** [comment]
@slackersoft - Ah, typo! I've tested the example again and narrowed the error down further. The crash with big objects only happen when the expect fails (updated initial example).

**Comment by slackersoft** [comment]
If the error only occurs when the matcher fails, it is probably that the [PrettyPrinter](https://github.com/jasmine/jasmine/blob/master/src/core/PrettyPrinter.js) is crashing while trying to print out the object. The PrettyPrinter should skip over circular object graphs, and print out a message. You should also be able to set your `jasmine.MAX_PRETTY_PRINT_DEPTH` to something lower than the default of `40` since it looks like that object is quite wide but not necessarily very deep.

The Jasmine PrettyPrinter will also look for a custom `toString` (or `jasmineToString` if you want it for specs only) that will pre-empt any recursing.

Hope this helps. Thanks for using Jasmine!

**Comment by smasala** [comment]
Thanks @slackersoft

**Comment by smasala** [comment]
@slackersoft Somehow, although these options work, they are still not great. 

1. I could set the MAX_PRETTY_PRINT_DEPTH property and then reset the property each time I want to check a circular object
2. I could give each circular object I want to check a custom function (toString/jasmineToString)

Both solutions are quite error-prone. The best option would be if Jasmine skipped printing the entire graph and printed a simplified message for each argument where `jasmine.any` is expected.

```
expect(eventService.broadcast).toHaveBeenCalledWith("correctArgument", jasmine.any(Angular2Component));

//output
Expected spy broadcast to have been called with [ 'correctArgument', <jasmine.any(Angular2Component)> ] but actual calls were [ 'wrongArgument', Angular2Component ].
```

**Comment by slackersoft** [comment]
Circular objects should always break out of the prettyprint as soon as Jasmine sees the same object again. The `any` matcher already defines its own `jasmineToString` to help alleviate this problem from this end, and unfortunately the pretty printer has no way to know that the object being printed is doing so because it was compared against an `any`.

We could also look into lowering the default `MAX_PRETTY_PRINT_DEPTH` to help with this problem in the base case, since 40 seems a bit high, but I'm not sure what would be a good default.

**Comment by smasala** [comment]
I see, the `expect` fails and the pretty printer is called afterwards?

What about formatting the string return value from `JSON.stringify(myBigObject)` on circular objects instead of iterating them?

**Comment by slackersoft** [comment]
I don't think this is necessarily a circular reference problem, since the pretty printer should detect actual circular references and display something to that effect. `JSON.stringify` tends to behave even worse, either throwing an `Error` or traversing the circular reference. Most likely the object being printed is just _super_ large.

Hope this helps. Thanks for using Jasmine!

**Comment by smasala** [comment]
Might be of help....

With Crockford's cycle lib: `JSON.stringify(JSON.decycle(myBigObject))` I was able to print out the large Angular component. If we utilise his method and limit it to the `MAX_PRETTY_PRINT` ( as the decycle was still quiet big :) ) we should have readable output that doesn't crash with large objects :+1: 

https://github.com/douglascrockford/JSON-js/blob/master/cycle.js

**Comment by slackersoft** [comment]
Jasmine's pretty printer should detect and not descend into circular references correctly. See: https://github.com/jasmine/jasmine/blob/41a813521ba5cf407ea595c8327a63cb266833f3/spec/core/PrettyPrintSpec.js#L82 for the specs on this. So this almost certainly isn't an issue with actually circular objects, but simply objects that are very large. Jasmine additionally has its own pretty printer that isn't just `JSON.stringify` because that would lose information (like constructors, etc.) that would cause two objects to be considered different to Jasmine and we want to be able to print that info out to the user.

The `MAX_PRETTY_PRINT_DEPTH` setting is more meant to be set once for your entire suite and not necessarily moved up and down by different specs, so you should be totally fine to just set it once in a helper file before the suite starts running.

The default `MAX_PRETTY_PRINT_DEPTH` isn't something we can really change during the 2.x release cycle as it could have negative effects for projects with deep, but not wide, objects that print in a reasonable time. But a new default value probably makes sense in 3.0 in the future.

**Comment by smasala** [comment]
Yea, I agree. I don't think changing `MAX_PRETTY_PRINT_DEPTH` is the answer - especially not in 2.x. 

I think this problem may be solvable by tweaking `util.arrayContains`. The function only does a simple `equals` (===). However, if the `search` item is inside an `array` item in `this.seen` then it is not found and thinks it hasn't been `seen` yet, it then misses the circular reference although the 2 items point to the same object. This also means that the same object can be placed multiple times inside ´this.seen` when dealing with multidimensional arrays.

Alternatively one could flatten the array `seen` so that it is not multidimensional and circular references are found (recursion is tricky here though - maybe a depth flatten maximum would be needed (`MAX_PRETTY_PRINT_DEPTH`?). Maybe Crockfords method with WeakMaps maybe handy here?

**Comment by avoerman** [comment]
I think this is related, but doing a simple:

`expect(aLargeObject).toBeFalsy()` 

causes a nasty crash, giving a "RangeError: Invalid string length" trace. This only happens on a _failed_ test, so it leads me to believe it's the same pretty print issue.

fortunately there's an easy workaround for this case:

`expect(!!aLargeObject).toBe(false)` 

¯\_(ツ)_/¯

**Comment by nburwell** [comment]
I just ran into this on 2.6.4 with `expect(aLargeObject).not.toEqual(anotherLargeObject)` too. I confirmed that using jasmine#master with 4c491b2 my test works (though it takes 7.4 seconds to run just the one test!).  Alternatively if I bump down the `MAX_PRETTY_PRINT_DEPTH` setting my test will pass on 2.6.4.

Now, our test should be re-written as we don't need to compare the entire objects, but this was working fine in all versions previous to 2.6.0, and I confirmed it was due to an out of memory issue in the PrettyPrinter trying to walk the entire object, which did have circular references too. I'm sure many others with large, existing Jasmine test suites are going to hit this too.

Would be great to get a new version released with this fix in it, at least as a safe guard for others running into this issue.  Related: is there a reason the `MAX_PRETTY_PRINT_DEPTH` is set to 40 (which seems really high, and clearly is not preventing out of memory issues at that level), can that be bumped down in master too?

**Comment by janpaul123** [comment]
I ran into this as well and fixed it in our default setup (https://github.com/remix/remix-jasmine-setup), but I am wondering why you wouldn't bump down `MAX_PRETTY_PRINT_DEPTH` in 2.x. I doubt that projects with deep objects would be that significantly helped by a value of 40 over 10 or 20 or so, while on the other hand it seems that quite a few people have run into entire browser crashes because of this. To me the latter seems to outweigh the former.
