### ISSUE TITLE
Spying on ES module properties

### ISSUE THREAD

**Issue by bensampaio** [jasmine/jasmine#1296]
I'm using webpack 2 with babel to transpile my code. With webpack 1 it was possible to spy on module properties since import/export were converted to CommonJS but webpack 2 is now compliant with the ES standard. Which means I can no longer spy on a module property because the module is frozen. Does jasmine provides a way to spy on module properties? Or is there a workaround for this?

**Comment by senyaak** [comment]
How about [that](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Proxy)?

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Spies are implemented by overwriting the existing properties on the object, so if things are not modifiable, Jasmine won't be able to spy on them. I'm going to close this since it doesn't sound like an issue with Jasmine itself, but we would be happy to talk about functionality that could be added to Jasmine, if possible, to support this.

Thanks for using Jasmine!
