### ISSUE TITLE
jasmine.DEFAULT_TIMEOUT_INTERVAL at odds with actual execution times

### ISSUE THREAD

**Issue by TheMetalCode** [jasmine/jasmine#1297]
- What version are you using? 2.5.2
- What environment are you running Jasmine in (node, browser, etc)? node
- How are you running Jasmine (standalone, npm, karma, etc)? gulp-wdio (so WebdriverIO using Jasmine as the test runner)

This is not a blocking issue for me at all - I've learned that the jasmine.DEFAULT_TIMEOUT_INTERVAL needs to be set fairly high for web UI tests. What has me curious, though, is that the run times I see in my console don't seem to have much relation to my configured timeout, and that makes it hard for me to understand (and communicate to others) what exactly is going wrong when I get timeout errors. To illustrate: Here is a jasmine.DEFAULT_TIMEOUT_INTERVAL failure where the timeout was set to 20000.

![jasmine-timeout-wut](https://cloud.githubusercontent.com/assets/1831850/24273814/b85e26ca-0fe1-11e7-8184-a80cd6dfbfb0.png)

So for a 20 second timeout:
- The test itself had a 28 second runtime.
- The suite had a 43 second runtime.
- The entire command (using `time` to measure) had a 49 second runtime.

So some questions arise:
- What exactly is jasmine.DEFAULT_TIMEOUT_INTERVAL measuring?
- At what point does it start waiting and counting to 20000 (or whatever one has configured the timeout to be)?

I'm open to the possibility that the webdriverio context might be muddying the waters here, but it at least seems like it's related to jasmine itself so I wanted to start here.

**Comment by slackersoft** [comment]
`DEFAULT_TIMEOUT_INTERVAL`, or the custom timeout passed to a given `it`, is the number of milliseconds that will be passed to `setTimeout` to interrupt an async spec. Due to the nature of `setTimeout`, this means your spec may not be immediately interrupted after exactly that amount of time.

The suite runtime is the amount of time it took to actually `execute` your suite, and doesn't include any time to require or set up the suite.

I hope this helps. Thanks for using Jasmine!

**Comment by TheMetalCode** [comment]
@slackersoft That helps immensely - thank you!
