### ISSUE TITLE
Two questions regarding code implementation.

### ISSUE THREAD

**Issue by ghost** [jasmine/jasmine#1303]
Hi,
In toBeFasly.js:
```
return {
    pass: !!!actual
};
```
Is it just a personal style or there is a deep reason to use `!!!` instead of one `!`?

In toBeDefined.js:
```
return {
    pass: (void 0 !== actual)
};
```
Is it just a personal style or there is a deep reason to use `void 0` instead of `undefined`?

**Comment by slackersoft** [comment]
My best guess for the `!!!` thing is some odd browser behavior from long ago (or maybe not that long), but I'm not totally sure.

The `void 0` vs `undefined` thing is because it is possible in some browsers to assign a value to the `undefined` global and using `void 0` makes sure we really get something that is `undefined`.

In the future you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using Jasmine!
