### ISSUE TITLE
What about having something like an overloaded method of toBeCloseTo() for cases with a precision value of 0?

### ISSUE THREAD

**Issue by toubou91** [jasmine/jasmine#1305]
For example, the following `toBeCloseTo(1.17, 0)` would be more readable (imho) if it was just `toBeCloseTo(1.17)`, because method's name itself declares that it's not an actual equality, but an "almost equal". Having that said, the method's `precision` argument is only useful for cases that the user has the need to **explicitly** declare the amount of decimal points to be checked for possible equality.

**Comment by slackersoft** [comment]
Wouldn't `toBeCloseTo(1.17, 0)` be the same as `toEqual(1.17)`? The latter would be much more descriptive of the intent of the test and should probably be used instead for that case. To that end, this doesn't sound like something we want to add to Jasmine at this time, since it seems to lead to more confusion, as it isn't necessarily obvious that a precision of `0` is used.

Closing this for now. Thanks for using Jasmine!
