### ISSUE TITLE
.clock().mockDate() is one month off

### ISSUE THREAD

**Issue by emersonthis** [jasmine/jasmine#1307]
When I use mockDate() to simulate a specific date it's a month off...

```
    xit("cookie_expiration() is 30 days out", function () {
        console.info(new Date()); // Fri Mar 31 2017 16:21:28 GMT-0700 (PDT)
        var baseTime = new Date(2016, 10, 1, 0, 0, 0, 0);
        jasmine.clock().mockDate(baseTime);
        console.info( new Date() ); // Tue Nov 01 2016 00:00:00 GMT-0700 (PDT)
       ...
    });
```

 - What version are you using?
2.5.3

 - What environment are you running Jasmine in (node, browser, etc)?
node (unit test)

 - How are you running Jasmine (standalone, npm, karma, etc)?
karma

**Comment by slackersoft** [comment]
Javascript actually uses 0-based months [see MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date). This means that your `baseTime` variable is actually set to November 1, not October 1 as you might be expecting.

I'm going to close this issue since this is not something under Jasmine's control, but a function of Javascript itself. Hope this helps. Thanks for using Jasmine!
