### ISSUE TITLE
expect(spy) Causes Error While expect(obj["functionName"]) Functions as Expected

### ISSUE THREAD

**Issue by daryllabar** [jasmine/jasmine#1309]
I'm running Jasmine npm 2.5.3, and running the unit test via a web browser.  The Spec Runner is testing multiple JS files, and when I run all tests, I get a test that fails, that shows the name of the test being in a completely different file, than the stack trace shown.

Here is the code from the stack trace:
![image](https://cloud.githubusercontent.com/assets/9728423/24783743/2c474e32-1b1c-11e7-80b7-dd3fe2ea5766.png)

It is failing on this
``` TS
expect(get).toHaveBeenCalledTimes(expectedCalls);
```
line.

If I run either test one at a time, no issues.  I did figure out that if I change the line that is in error to not reference the spy directly, there are no issues:

``` TS
expect(webApi[spyFunctionName]).toHaveBeenCalledTimes(expectedCalls);
```

I would have thought that ```expect(get)``` and ```expect(webApi[spyFunctionName]))``` would have been equivalent in this case.
Am I not understanding how spies work, or did I stumble onto a bug?

Here is the stack trace in case it is helpful:
```
Expected spy GetList to have been called 0 times. It was called 1 times.
    at stack (http://localhost:1130/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1640:17)
    at buildExpectationResult (http://localhost:1130/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1610:14)
    at Spec.expectationResultFactory (http://localhost:1130/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:655:18)
    at Spec.addExpectationResult (http://localhost:1130/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:342:34)
    at Expectation.addExpectationResult (http://localhost:1130/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:599:21)
    at Expectation.toHaveBeenCalledTimes (http://localhost:1130/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1564:12)
    at http://localhost:1130/test/spec/Allgnt.RestLibSpec.js:166:34
```

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Given that you appear to be getting an extra call to the spy when you run the full suite, you probably either have some other spec that ends up with a callback or something registered. Additionally, I would recommend against having that kind of logic in your specs if at all possible, since this forces your tests to be very explicit about the state they want.

Hope this helps. Thanks for using Jasmine!

**Comment by daryllabar** [comment]
I assumed this was a bug since I thought my calls to expect on the spy should have been equivalent in both cases.  Thanks for your time, I'll post in a different place.
