### ISSUE TITLE
Mocks' toHaveBeenCalledWith method behaves incorrectly with promise arguments

### ISSUE THREAD

**Issue by austinmckinley** [jasmine/jasmine#1314]
Calling a mock with a promise will make any later assertions on that mock's calls with other promises it was not called with fail.

In other words, calling a mock with a promise will make that mock behave as if it were called with any other promises, even when it was not called with another promise.

 - jasmine and jasmine-core version 2.5.2
 - Running with Karma through Chrome 56.0.2924.87

Failing reproduction spec:
```
    it('verifies a method was not called with promise2 as a parameter', () => {
        const promise1 = new Promise(resolve => resolve({
            data: 'foo'
        }))
        const promise2 = new Promise(resolve => resolve({
            data: 'bar'
        }))

        const someMock = jasmine.createSpy('something')
        someMock(promise1)

        expect(someMock).not.toHaveBeenCalledWith(promise2)
    })
```

In Chrome, running promise1 === promise2 and promise1 == promise2 returns false for both cases.

Please let me know if additional info would help :)

**Comment by slackersoft** [comment]
Jasmine's equality logic (which is used for `toHaveBeenCalledWith` as well as `toEqual`) doesn't just use `===` or `==`, but attempts to do a deep compare of the two objects. Since the two `Promise`s have the same constructor and `Object.keys` doesn't return anything for a `Promise`, Jasmine doesn't really know what else to check to see if they are equal.

I would be happy to review a pull request that enabled Jasmine to correctly test equality for a `Promise` (while still working in environments where there is no `Promise`).
