### ISSUE TITLE
Error: it expects a function argument; received [object Undefined]

### ISSUE THREAD

**Issue by UziTech** [jasmine/jasmine#1328]
[ensureIsFunction](https://github.com/jasmine/jasmine/blob/4b696fbf266bdfa720cfdbdde4ca6c1b692cbde3/src/core/Env.js#L312) throws an error when `it`, `describe`, etc. are called with their function arguiment as `undefined` which [acording to the documentation](https://jasmine.github.io/2.6/introduction.html#section-17) is allowed.

**Comment by slackersoft** [comment]
A spec is allowed to not have a function to execute (it makes it `pending`), but the other functions don't make sense without that. This was added to fix #1004 which is specifically caused by not passing a function in.

If you are seeing this error when using `it` or `xit`, I would be happy to talk more and fix that issue. Otherwise, we have really just specified what will happen in a previously unspecified case.

Hope this helps. Thanks for using Jasmine!

**Comment by UziTech** [comment]
Yes I am seeing this when I try to pass `it` an undefined variable.

I fixed the pull request and added a check for `undefined` along with the check for `arguments.length` in `it` and `xit`

**Comment by slackersoft** [comment]
Ah, I misunderstood. Accidentally passing in a variable whose value is currently `undefined` is what this new functionality is trying to save you from. Explicitly passing `undefined` to an `it` seems like something is probably going wrong in your suite. If you don't want the spec to run, you should use `xit`.

**Comment by UziTech** [comment]
when patching `it` like [jasmine-promises](https://github.com/matthewjh/jasmine-promises) or dynamically creating tests it is sometimes necessary to pass a variable that could be undefined and let it skip that test.

I suppose you could test for that call `it` without a second variable, but at the very least this is a breaking change.
