### ISSUE TITLE
Not able to create spy on method

### ISSUE THREAD

**Issue by tak2ashokkumar** [jasmine/jasmine#1387]
My service is : 

      var testappserviceone = angular.module('testappserviceonemodule',[])
        testappserviceone.factory('testappServiceone',[ function(){
        return function (x,y) {

             function addobj (x,y){
                 return x+y;
             }

             return{
                add:addobj
             }
        }
       }]);

 My test suite is : 

    describe('testappserviceone add method functionality', function(){
        beforeEach(function () {
            spyOn(testappServiceone(10,15),'add').and.callThrough();
        });

        it('testappServiceone add method functionality', function() {
            testappServiceone(10,15).add();
            expect(testappServiceone(10,15).add).toHaveBeenCalled();
        });
    });

The Exception I am getting is : 

    Error: <toHaveBeenCalled> : Expected a spy, but got Function.
    Usage: expect(<spyObj>).toHaveBeenCalled()

I think spy() is not creating a spy object . Please help me in understanding and solving this problem.

**Comment by sgravrock** [comment]
It looks like `testappServiceone` returns a new object each time it's called. So your `beforeEach` function calls `testappServiceone`, spies on the returned object's `add` method, and then throws that object away. Then the test calls `testappServiceone` and tries to verify calls on the returned object's `add` method, but it doesn't work because it's an entirely different object than the one that was spied on.

One way to fix this would be to have `testappServiceone` return the same object every time it's called. That should be an option since `testappServiceone` doesn't appear to use the parameters passed to it.

I hope this helps. Thanks for using Jasmine!

**Comment by tak2ashokkumar** [comment]
Thank you for proposing solution.

**Comment by MarcLoupias** [comment]
You should use a `service`, not a `factory`, a `factory` is used when you want to execute some code before the injector instanciate the service singleton. It is not the case in your code. So you don't need to use a `factory` and you `should` use a service.

The `x` and `y` args in the constructor method are useless and unused. When you inject your service in another `service` or a `controller` or a `directive`, the injector have already instantiated the service for you. You cannot pass args to it. To do this, to configure a service, you need to use a `provider`.

You want to configure a service passing data to it before the injector instantiate your service ? Use a `provider`.

You want to execute some code before the injector instantiate your service ? Use a `factory`.

In all other cases, use a `service`.

See [this discussion](https://groups.google.com/forum/#!topic/angular/hVrkvaHGOfc).

For the testing part, the only things to test here is the `add` function logic. Testing that `add` function is bind to `addobj` function is an overkill.

**Comment by slackersoft** [comment]
It sounds like this has become a discussion about using angular and testing and not about an issue with Jasmine itself, so I'm going to close it.

Thanks for using Jasmine!
