### ISSUE TITLE
Clarify suite failed expectations and exceptions

### ISSUE THREAD

**Issue by bcaudan** [jasmine/jasmine#1409]
## Current Behavior
* Failed expectation or exception during beforeAll:
All children specs are reported as failed with the beforeAll failure. 
It could be easier to spot the issue if it is clearer that the issue comes from beforeAll.

* Failed expectation or exception during afterAll:
Failure is added as a failed expectation for the suite.

* Exception during suite declaration:
An extra spec is added with the encountered exception.

## Possible Solution
* For beforeAll failures, disable specs and children suites in order to not report them.
* Add beforeAll failed expectations in `suite.failedExpectations` (like afterAll does).
* Add beforeAll, afterAll and suite declaration exceptions in a new `suite.exceptions` field.

In order to display it in a generic way, we could add an extra field `origin` in suite failed expectation and exception filled with "beforeAll", "afterAll" or "suite declaration".

## Context
I am maintaining [jasmine-spec-reporter](https://github.com/bcaudan/jasmine-spec-reporter) and it would be very nice to provide the most specific and consistent information for these cases.

I would be glad to help if you think that it could be useful.

**Comment by slackersoft** [comment]
The suite declaration failure spec came about because Jasmine didn't always support expectations at the suite level. Only once `beforeAll` or `afterAll` exist is something like that even possible.

The `beforeAll` expectation failures are passed on to the child specs in an effort to do best effort on getting them reported to users, since `suiteDone` didn't have any expectation information until then. Failures in `afterAll` can't have that happen, because all of the children have by definition already reported success or failure and can't be modified after that.

So that's why it is the way it is now. That said, I think it would be useful to _add_ an `origin` field to the Expectation object passed to the reporters, which could be ignored by reporters who don't care. I don't think we want to change how failures are reported, since that would break existing reporters.

For 3.0 it might make sense to review how these types of errors are reported, once we can make a breaking change. I've made [a story](https://www.pivotaltracker.com/story/show/150118881) in tracker for the 3.0 changes, but I'd be happy to review a pull request to add an `origin` field to expectations.

Hope this helps. Thanks for using Jasmine!

**Comment by bcaudan** [comment]
Just a few questions to be sure to understand your answer:

>  I don't think we want to change how failures are reported, since that would break existing reporters.
So we do not report differently failed expectations and exceptions, right?

Then for:
* failure in beforeAll
* exceptions in suite declaration
are you ok to report them in suite failed expectation object?

And for failures in beforeAll what about disable specs and children suites in order to not report them?

**Comment by slackersoft** [comment]
Basically, for 2.x I don't think we want to change the mechanism by which anything is reported. So exceptions stay as failed expectations, `beforeAll` failures still cascade down to specs, and suite declaration exception is still a spec with a failure in it.

We also don't want to change the default way that failures are handled in `beforeAll`, but I think it would be interesting to look into having the `stopSpecOnFailedExpectation` flag work for `beforeAll`. It would need some tweaking so that a failure in one spec wouldn't cause others specs not to run.

Hope this helps!

**Comment by sgravrock** [comment]
I like the idea of adding an `origin` field to expectations. I'm not so sure about disabling specs inside a suite with a `beforeAll` failure, though. The `disabled` state has been overloaded to have a wide variety of meanings over time. It's provided fertile ground for bugs and plenty of confusion for reporter authors, and I don't think using it in yet another scenario is going to help the situation. In particular, using the disabled state to mean both "the user focused on a set of specs that didn't include this one" and "this spec didn't run because of a `beforeAll` failure" seems dangerous.

There are at least two valid ways to look at a suite with a `beforeAll` failure: As a suite that failed without running anything, or as N specs that each failed. I think what we want to do here is make things easier for reporter authors that take the former viewpoint without making things harder for reporter authors that take the latter viewpoint. I particularly want to avoid anything that would cause old reporters to report success when a suite fails, even in a major release.

**Comment by slackersoft** [comment]
The `origin` field on expectations proved to be harder to implement that we initially expected. We have however done some work to make all errors at the suite level report the same way (on the suite) instead of either making a spec you've never heard of, or cascading the failure down to the children.

This work is in the 3.0-features branch, and will be included in Jasmine 3.0. Closing. Thanks for using Jasmine!
