### ISSUE TITLE
Making toThrowError work with async function

### ISSUE THREAD

**Issue by DamienCassou** [jasmine/jasmine#1410]
Is there a way to leverage `toThrowError` in the context of an async function throwing an error?

**Comment by slackersoft** [comment]
Without some heavy reworking, I don't think this is possible in Jasmine right now. If I'm understanding you correctly you want to do something like:

```javascript
expect(async function() {
  throw new Error('bar');
}).toThrowError();
```

In order to correctly handle and match an error thrown in an `async` function, the matcher, would also have to be `async` so you could `await` the statement in your spec. You could probably write your own matcher to do this, or just get a hold of the Promise that is returned and check for rejection.

Hope this helps. Thanks for using Jasmine!

**Comment by ivanbtrujillo** [comment]
Hi, for me throwError doesn't work neither. I tested it by calling the async function as a promise and checking the error on the .catch statement.

**Comment by sgravrock** [comment]
It's even worse than that -- an async matcher system could only be used inside of async tests. We'd either have to support two separate matcher systems (normal and async) or force users to convert every existing synchronous test to be async. I think that would be unfair to our users even if we did it as part of a major release. Especially not when there are straightforward (if clumsy) workarounds.

Since we're very unlikely to make `toThrowError` work with async functions, I'm going to close this.

**Comment by khuslen** [comment]
To get similar functionality, I used a work around that I found on issue [#1377](https://github.com/facebook/jest/issues/1377) of Jest.
```
it('to throw error', async () => {
            let errorMessage = 'No error thrown.';
            try {
                await functionToThrowError();
            } catch (error) {
                errorMessage = error.message;
            }
            expect(errorMessage).toBe('An error was thrown.');
        });
```

**Comment by xfg** [comment]
I think need add this feature to next major release.

**Comment by SLaks** [comment]
You can use https://jasmine.github.io/api/3.3/async-matchers.html:

```js
await expectAsync(aPromise).toBeRejected();
await expectAsync(aPromise).toBeRejectedWith({prop: 'value'});
```

**Comment by alucic** [comment]
As of Jasmine 3.5 you can use `toBeRejectedWithError`
https://jasmine.github.io/api/3.5/async-matchers.html

Examples:
```javascript
await expectAsync(aPromise).toBeRejectedWithError(MyCustomError, 'Error message');
await expectAsync(aPromise).toBeRejectedWithError(MyCustomError, /Error message/);
await expectAsync(aPromise).toBeRejectedWithError(MyCustomError);
await expectAsync(aPromise).toBeRejectedWithError('Error message');
```
