### ISSUE TITLE
Behaviour of the “this” keyword

### ISSUE THREAD

**Issue by toaster** [jasmine/jasmine#1416]
After reading https://jasmine.github.io/2.8/introduction.html#section-The_%3Ccode%3Ethis%3C/code%3E_keyword I expected `this` to be empty for every single `beforeEach`/`it`/`afterEach` run. But when testing with jasmine 2.8 (on node 6.10) I found that it is only reinitialized for different spec files.

Thus it has no advantage over normal variables except that it has not to be declared.

If being reset on every `it` cycle it would become really good because one has not to worry about cleaning up the fragments of earlier specs.

Therefore I suggest that _either_:

- `this` should be reinitialized on every `beforeEach`/`it`/`afterEach` cycle. This would disable the current available possibility to use it to share data from `beforeAll`, but that could be done with variables instead.

_or_:

- `this` should be replaced by two global context objects (like `spec` and `suite`) which serve the purpose of `this` in the spec and suite context. `spec` would then be cleared on every `it` cycle while `suite` would be cleared on every spec file, only.

**Comment by slackersoft** [comment]
Jasmine doesn't have a concept of a _file_ when running your specs, only specs and suites that contain them. Because of the hierarchical nature of suites, it's possible that a parent suite sets a property on the `this` that you're seeing further down the tree. If you're using `beforeAll` or `afterAll` this gets even trickier, but without that this is basically what happens:

Each `Spec` object gets a new context object when Jasmine begins executing it. Execution of a `Spec` involves running any `beforeEach`s, then the `it` itself, then any `afterEach`s. After the `Spec` finishes execution, the context object goes out of scope and can thus be garbage collected. This purpose here is to allow objects to be shared between a `beforeEach` and the associated `it`s (with each `it` getting its own copy) without having to use closure scoped variables, which can bloat the amount of memory your suite uses.

`beforeAll` and `afterAll` start allowing some of the things on the `this` to be shared between specs in a given suite.

Hope this helps. Thanks for using Jasmine!

**Comment by toaster** [comment]
Okay, got the file thing. But, why does the following suite fail:

```javascript
'use strict';

describe("“this” behaviour #1", () => {
  it("is empty #1", () => {
    expect(this.foo).toBeUndefined();
    this.foo = "#1";
    expect(this.foo).toBe("#1");
  });

  it("is empty #2", () => {
    expect(this.foo).toBeUndefined();
    this.foo = "#2";
    expect(this.foo).toBe("#2");
  });
});
```

Output with node 6.10:
```
Started
.F

Failures:
1) “this” behaviour #1 is empty #2
  Message:
    Expected '#1' to be undefined.
  Stack:
    Error: Expected '#1' to be undefined.
        at UserContext.it (/Users/tilo/work/test/jasmine/spec/test_spec.js:12:22)

2 specs, 1 failure
Finished in 0.011 seconds
```
```

**Comment by slackersoft** [comment]
This is because you're using [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) which bind their own `this` and ignore the one that Jasmine is passing in. If you change the specs to use `function() {` instead of `() => {` they should behave as expected.

Unfortunately there isn't anything that Jasmine can do about this.

Hope this helps. Thanks for using Jasmine!

**Comment by toaster** [comment]
Mea culpa! Sorry for bothering you with this.

But one more thing: Couldn't be a global variable a replacement for `this` which would work with arrow functions, too?

**Comment by slackersoft** [comment]
I don't think that a global variable is the right solution to this problem. I understand your disappointment in not getting the correct `this`, but maintaining the correct state on a global variable doesn't seem worth the complexity. You can either use the `function` keyword or closure variables (if you still want to use fat arrow).

I'm going to close this, since it's not really an issue with Jasmine. Thanks for using Jasmine!
