### ISSUE TITLE
Since Jasmine 2.7.0, it's not possible to spyOn(window, 'Function')

### ISSUE THREAD

**Issue by Narretz** [jasmine/jasmine#1430]
## Expected Behavior
It should be possible to `spyOn(window, 'Function')` 
Note that this is the Function constructor, not a user-defined function.

## Current Behavior
jasmine throws a hard error that keeps the spec and suite from completing:
```
TypeError: Function.prototype.apply is undefined   jasmine.js:4236:11
clearTimeout jasmine.js:4236:11
  attempt/cleanup< jasmine.js:4247:11
  once/< jasmine.js:4172:9
  attempt jasmine.js:4306:7
  QueueRunner.prototype.run jasmine.js:4217:20
  QueueRunner.prototype.execute jasmine.js:4199:5
  queueRunnerFactory jasmine.js:909:7
  TreeProcessor/this.execute jasmine.js:5187:7
  Env/this.execute jasmine.js:983:7
  window.onload boot.js:144:5
```

Same happens for `window.Function = jasmine.createSpy().and.callThrough();`

## Suite that reproduces the behavior (for bugs)

```javascript
it('should do something', function() {
  spyOn(window, 'Function');
  expect(true).toBe(true);
});
```
Live repro here: http://plnkr.co/edit/sCxS40pqfQuHdeKuZnNM?p=preview

In the plnkr, if your revert to 2.6.4 it works.
  

## Context
We are using `spyOn(window ...` in the AngularJS test suite to check if the Function constructor is accessed, see https://github.com/angular/angular.js/blob/e58bcfab99450d2c4777d87a7ddfea19b9f38b5c/test/AngularSpec.js#L1041

We test this with karma. For some reason, in the karma setup, the 2.6.4 tests also fail. Not sure why it works in the plnkr.

## Your Environment

* Version used: 2.8.0, 2.7.0. Worked last in 2.6.4
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sgravrock** [comment]
Jasmine needs to be able to make some basic assumptions about the environment that it operates in. In particular, it has to be able to assume that core objects provided by the runtime, as well as its own code, have not been modified. There's no way to guarantee any particular behavior in the face of code that replaces things like `Function`. In this case, Jasmine relies on the presence of `Function.prototype.apply` to ensure compatibility with browsers that don't provide an `apply` method on `setTimeout` and `clearTimeout`. Jasmine <= 2.6.4 didn't hit that particular code path when running synchronous tests. Jasmine >= 2.7.0 does.

Normally my advice would be to find a more direct way to assert what your tests really mean, but it looks like your tests really are all about verifying calls to `Function`. So you might try something like this:

```
it('should not call Function', function() {
  var wasCalled = false;
  var realFunction = Function;
  window.Function = function() {
    wasCalled = true;
  };
  
  try {
    doSomething();
  }
  finally {
    window.Function = realFunction;
  }
  
  expect(wasCalled).toBe(false);
});
```

Note that the the test is synchronous, the mock is installed and removed within the test rather than in `beforeEach` and `afterEach`, a hand-rolled mock is used in place of Jasmine spies, and all assertions happen after the real `Function` is restored. That combination should ensure that no Jasmine code runs while the mock is in place.

I'd be happy to review a pull request that makes Jasmine more robust in the face of code that modifies the environment. But I don't want to set the expectation that we're going to actively support, or make any compatibility guarantees about, test code that modifies things like `Function`.

**Comment by Narretz** [comment]
Thanks for the explanation. If spying on window.Function was never actively supported then this is fine with me. Although this should be documented somewhere. Or is it already?

**Comment by sgravrock** [comment]
The documentation is due for a major overhaul as part of 3.0. We can certainly consider adding some notes about this sort of thing.
