### ISSUE TITLE
jasmine.createSpy() with no arguments - is it discouraged?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [jasmine/jasmine#1438]
Coming from the world of Sinon where `stub()`/`spy()` doesn't take in a string name, `jasmine.createSpy("methodName")` seems unnecessary:

```javascript
const stubLogger = () => {
    const clock = lolex.createClock();
    const { setTimeout } = clock;
    const onLog = jasmine.createSpy("onLog");

    const logger = new Logger({ onLog, setTimeout });

    return { clock, logger, onLog };
};
```

All the `jasmine.github.io` samples pass a string to `createSpy`, and the TypeScript definition marks `name` as mandatory:

```typescript
function createSpy(name: string, originalFn?: (...args: any[]) => any): Spy;
```

Is it discouraged to not pass a name? I'd prefer not to unless there's a good technical reason?

**Comment by sgravrock** [comment]
The spy's name is used by the matchers to build failure messages. So if you don't pass it, you might get failures with messages like `Expected spy unknown to have been called.` or `Expected Object({ s: spy on unknown }) to equal 'something else'.` instead of something more readable. Other than that, I don't think there's any harm in omitting it.

**Comment by JoshuaKGoldberg** [comment]
Thanks for the clarification! I'll update the TypeScript typings.

If you could put this somewhere in the Jasmine docs, IMO that would be useful too.
