### ISSUE TITLE
extend createSpyObj to support properties

### ISSUE THREAD

**Issue by Plondrein** [jasmine/jasmine#1442]
## Expected Behavior
Currently i cant create nicely spy object full of methods, but what if i need to mix some properties and methods?

## Current Behavior
currently createSpyObj creates only methods 

## Possible Solution
another array argument 'propertyNames' just like ;methodNames' could solve problem.
Properties would return default values until i use spyOnProperty.

## Context
That's my typescript,  i hope it could be less ugly:

```typescript
let mockRouter: jasmine.SpyObj<Router>;

mockRouter = jasmine.createSpyObj('mockRouter', ['navigateByUrl']);

mockRouter = {
  ...mockRouter,
  events: Observable.of(...routerEvents),
} as jasmine.SpyObj<Router>;
```

**Comment by sgravrock** [comment]
That seems like a nice feature to have. I'd be happy to review a pull request that adds it.

**Comment by ninjamyst** [comment]
This would be very helpful as we have many objects we want to mock that have getter properties.

**Comment by sergiojoker11** [comment]
Is this achievable? This feature would make code more readable... and our life easier in turn.

**Comment by sergiojoker11** [comment]
https://github.com/jasmine/jasmine/pull/1569

**Comment by felpel** [comment]
@sergiojoker11 any updates on your end to complete your current PR? Would be very neat to have this feature out of the box, my test classes would be cleaner.

**Comment by sergiojoker11** [comment]
@felpel Yes, I am planning on addressing the comments later this week. I swear I will!

**Comment by szabolcssimonyi** [comment]
any progress on this? this feature would be very usefull

**Comment by slackersoft** [comment]
@szabolcssimonyi  You can see the current state of @sergiojoker11's pull request #1569.

**Comment by MarcinusX** [comment]
Is it possible to achieve the same result until the feature is released?

**Comment by benelliott** [comment]
@MarcinusX there are workarounds in the original post and my comment above.

**Comment by MarcinusX** [comment]
@benelliott Oh! I understand now! I thought that `events` was something specific to the issue but it is just overriding the field. Thank you!

**Comment by rcavezza** [comment]
Does this pull request need someone to come in and finish it? This is something I can use in my codebase and it looks like this is close to the finish line, but fell through the cracks a few months ago.

**Comment by sergiojoker11** [comment]
@rcavezza Yes, it does need someone to finish it. By the time when the code review was done, I didn't understand the proposed changes and didn't have the time. So, please, feel free to take it over and finish it.

**Comment by Daniel-Marcelo** [comment]
What

> ## Expected Behavior
> Currently i cant create nicely spy object full of methods, but what if i need to mix some properties and methods?
> 
> ## Current Behavior
> currently createSpyObj creates only methods
> 
> ## Possible Solution
> another array argument 'propertyNames' just like ;methodNames' could solve problem.
> Properties would return default values until i use spyOnProperty.
> 
> ## Context
> That's my typescript, i hope it could be less ugly:
> 
> ```ts
> let mockRouter: jasmine.SpyObj<Router>;
> 
> mockRouter = jasmine.createSpyObj('mockRouter', ['navigateByUrl']);
> 
> mockRouter = {
>   ...mockRouter,
>   events: Observable.of(...routerEvents),
> } as jasmine.SpyObj<Router>;
> ```

What exactly is the purpose of the rest/spread operator in this case? Without, the compiler gives out stating that instance variables are missing. But it works fine after adding. Just looking for a bit more clarity on why this works.

**Comment by elliot-nelson** [comment]
I wonder if this is a case where a potential new feature exposes (makes worse) holes in existing features.

Today, `let spy = createSpyObj('foo', [...])` makes sense only because it's possible to easily update the plans of any methods you create in your tests.  `spy.bar.and.throwError`, etc.

That doesn't exist with spyOnProperty.  Using spyOnProperty on existing objects (mocking individual properties) is therefore _trickier_ than mocking individual methods: you need to save a pointer to the actual spy returned because you cannot get it back again to update the plan.

Two potential things to fix:

- Maybe we need to be opening up access to property spies.  I'm not sure exactly how, but maybe if you spy on `object.prop (get)`, we add `object.prop_.get` to the object?  A non-enumerable new prop?  I suppose nothing is guaranteed to work for ALL code under test, so perhaps a universal `getSpy(object, prop/method, [accessType])` is what is missing.

- If we fix that, then the original proposal (a list of props) is fine.  If not, it's useless because you can't set any plans!  So a possible improvement is a new interface for createSpyObj that includes plans... something like this, instead of the arrays:

```
createSpyObj('obj', {
    foo: plan => plan.returnValue(3),
    bar: true, // spy with no plan (default)
    baz: {
        get: plan => plan.returnValue(43),
        set: plan => plan.stub
    }
})
```

**Comment by slackersoft** [comment]
The current version of `createSpyObj` already takes an object for the functions to spy on, so I'm not sure about the right way to check the difference between "this is a function that returns a function" and "this is a function that I would like to have a complex spy on".

Given that, I think it would make more sense to add a `jasmine.getSpy` type of function instead of extending more things onto existing objects outside of Jasmine's control. I still think it is probably fine to allow `createSpyObj` handle properties since you can at least default to a `stub` or define a return value.

**Comment by felpel** [comment]
> @felpel Yes, I am planning on addressing the comments later this week. I swear I will!

@sergiojoker11 leaving me hanging, mate

**Comment by scote** [comment]
Any new when it will be released?

**Comment by slackersoft** [comment]
Jasmine 3.5 is out now. The ruby release is taking a bit longer, but should be done shortly

**Comment by rcollette** [comment]
Is there any way to change the previously assigned value of a property spy that was assigned using an object parameter of createSpyObj?

```
obj = createSpyObj('someName',[],{theProperty:value});
```
Of course `obj` has a lot more methods and properties which is why I don't want to create over and over again.  I just want to change the return value of `theProperty`

I've tried assigning an arrow function as the property value , returning another variable.  I've tried calling `.and.` on the property.   I've tried setting the property directly but I am told it is a setter only.   I'm stumped.

**Comment by elliot-nelson** [comment]
There's no intuitive way to do that currently (although hopefully that will improve!)

Most straightforward would be to get the property descriptor directly and update the getter, for example:

```js
Object.getOwnPropertyDescriptor(obj, 'theProperty').get.and.returnValue(37);
expect(obj.theProperty).toEqual(37);
```

There is another tactic that I would _expect_ to work, but doesn't:

```js
jasmine.getEnv().allowRespy(true);
spyOnProperty(obj, 'theProperty', 'get').and.returnValue(37);

// => Error: theProperty is not declared configurable
```

In my opinion this is actually a bug in createSpyObj and I'll file a separate issue.

**Comment by peitschie** [comment]
@rcollette I just hit this today as well. Here's a function I wrote to help with this:
```
function getPropertyGetterSpies(obj: T) {
  const spies = {};
  for (const [name, descriptor] of Object.entries(Object.getOwnPropertyDescriptors(obj))) {
    spies[name] = descriptor.get; //  as jasmine.Spy
  }
  return spies;
}

// Usage:
const myObj = jasmine.createSpyObj("myObj", [], ["property1"]);
const getterSpies = getPropertyGetterSpies(myObj);
getterSpies.property1.and.returnValue(2);

expect(myObj.property1).toBe(2);
```

**Comment by rcollette** [comment]
Similarly, eliminating the `getEntries()` call and `forEach` loop, and doing setter expectations or getter mocking.

```
const theObj = jasmine.createSpyObj("theObj",[],["thePropertyName"]);
const setter = Object.getOwnPropertyDescriptors(theObj).thePropertyName.set;
expect(setter).toHaveBeenCalledWith(expected);
// or for getter mocking
Object.getOwnPropertyDescriptors(theObj).thePropertyName.get.and.returnValue(theValue);
```

**Comment by rcollette** [comment]
I am also finding that getters are not enumerable causing properties not to be recognized when used with Angular TestBed (DI).

To work around that I have had to do:

```
    oktaAuthService = createSpyObj<OktaAuthService>('oktaAuthService', ['loginRedirect', 'logout'], {
      $authenticationState: authenticationState
    });
    Object.defineProperty(oktaAuthService, '$authenticationState', {
      ...Object.getOwnPropertyDescriptor(oktaAuthService, '$authenticationState'),
      enumerable: true
    });
```

See also:
https://github.com/angular/angular/issues/33657#issuecomment-583152366
