### ISSUE TITLE
How to await async functions wrapped with spyOn() ?

### ISSUE THREAD

**Issue by angularsen** [jasmine/jasmine#1443]
In my test code I got `undefined` returned for some async functions wrapped with `spyOn()`.
I then created a codepen to reproduce, and here it times out.
https://codepen.io/anon/pen/wPvLeZ

Can I use `spyOn()` with async functions and how do I await them?

**Comment by sgravrock** [comment]
You can `spyOn` an async function just like any other. There are a couple of issues with the code you provided that are stopping it from working. First of all, `spyOn` replaces methods on objects. It doesn't work with free functions. Second, `spyOn` replaces the original method with one that, by default, doesn't do anything but record that the call happened. Call `.and.callThrough()` on the spy if you want it to behave the same way as the original method So instead of this:

```
async function getAsync() {
  await delayAsync(50);
  return "async result";
}

// ...
const getAsyncWithSpyOn = spyOn(getAsync, 'getAsync');
expect(await getAsyncWithSpyOn()).toEqual("async result");
```

You probably want something more like this:

```
var someObject = {
  getAsync: async function() {
    await delayAsync(50);
    return "async result";
  }
}

//...
spyOn(someObject, 'getAsync').and.callThrough()
expect(await someObject.getAsync()).toEqual("async result");
```

Finally, asynchronous test functions can either be declared `async`, return a promise, or take a `done` callback. Since yours are `async` they don't need to take a callback.

[Here's a passing version of your demo](https://codepen.io/anon/pen/eemMeZ). I hope this helps.

**Comment by angularsen** [comment]
Wow, thanks for the thorough feedback. My bad on the codepen, I did actually have an object in my own test code so that is probably why the behavior was different.

Thanks for the tip on `.and.callThrough()`, I didn't catch that in the docs so hopefully someone else might find this issue useful when searching later.

**Comment by 2rhop** [comment]
@sgravrock thanks a lot you are saving my work today!!
