### ISSUE TITLE
toEqual doesn't display given failure message

### ISSUE THREAD

**Issue by willwsharp** [jasmine/jasmine#1457]
When using the toEqual matcher and passing in the optional expectationFailOutput message, the message will not display when the assertion fails.
## Expected Behavior
The expectationFailOutput message should display for .toEqual when the assertion it is attached to fails.

## Current Behavior
the expectationFailOutput message does not display for .toEqual when the assertion it is attached to fails.

## Possible Solution
Not sure why this is happening; perhaps it was changed in a recent build.

## Suite that reproduces the behavior (for bugs)
https://codepen.io/willwsharp/pen/LOvxJd?editors=1010

## Context
It's very helpful to immediately see which assertion failed when working in specs with multiple assertions.

## Your Environment
Jasmine 2.8

**Comment by slackersoft** [comment]
Jasmine does not have a concept of an `expectationFailOutput`. This functionality has [been discussed](https://github.com/jasmine/jasmine/issues/641#issuecomment-54736801) elsewhere, but the fact that other matchers do seem to support something like this a side effect of those matchers _not_ supplying a custom message.

Closing this, since this isn't actually supported functionality of Jasmine itself. Thanks for using Jasmine!

**Comment by adame11** [comment]
Please re-open this ticket! .toEqual() is the only matcher (that I know of) that does not support the "undocumented" feature of a custom error message. Others DO support a custom error, such as 

`.toBe(true, "this is a custom error")`

and this makes failures on these a pain to debug! I don't know how anyone lives without the custom error messages in the first place. They are essential to me.

**Comment by slackersoft** [comment]
Any matcher that supplies its own `message` will not display any information it doesn't explicitly know about. If no explicit `message` is provided by a matcher, Jasmine will look at all of the arguments that were passed and attempt to make a message out of those. This is entirely accidental as far as Jasmine is concerned, which is why we haven't tried to add explicit support for this to things like `toEqual`.

However, I do hear the need for some way to tell Jasmine some sort of description of the value being checked, but I don't think it will be as an additional argument to the matcher itself. I'm leaning more toward something like #641, but I think `because` might be the wrong word for it. I would prefer something that will work for all matchers without them having to build in support for it in customizing their failure messages further.

**Comment by MattiJarvinen-BA** [comment]
It's very common to add that message as part of the assert matcher. IMHO we should strive for simplicity and use existing common assert syntax patterns.

As last parameter:
- PHPUnit https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertCount
- MSUnit https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.assert.areequal?redirectedfrom=MSDN&view=mstest-net-1.2.0#Microsoft_VisualStudio_TestTools_UnitTesting_Assert_AreEqual_System_Object_System_Object_System_String_
- NUnit http://nunit.org/docs/2.2.7/equalityAsserts.html

As first parameter:
- JUnit http://junit.sourceforge.net/javadoc/org/junit/Assert.html

**Comment by slackersoft** [comment]
Jasmine 3.3 includes [`withContext`](https://jasmine.github.io/api/edge/matchers.html#withContext) as the officially supported way to specify additional information about the expectation without worrying about which matcher you are using.

**Comment by twopelu** [comment]
Angular applications <= 6.0.0 come with Jasmine 2.X.X, not 3.X.X, which means that many Angular users have to update the version just to use withContext(). This might be a problem.

Also, this particular case could make that some people tend to use toBe instead of toEquals, which can lead to further problems as it is known that some people get confused about these two.

In the other side, it makes sense that all methods toBe, toEqual, etc. behave the same with the custom messages, isnt it? Would you plese reconsider reopening this ticket please?
