### ISSUE TITLE
Hide disabled specs/gray balls in the html report

### ISSUE THREAD

**Issue by mkj28** [jasmine/jasmine#1458]
## Expected Behavior
When running single spec- expected to only see html reporter only show focused spec. This used to be the case in 2.2.0, not anymore in 2.5.0 for example.

## Current Behavior
It shows all the specs - which if you have thousands of tests makes the UI/run slow.

## Possible Solution
`display: none;` in jasmine.css for disabled specs like in https://github.com/AlexBerson/karma-jasmine-html-reporter/commit/f263fa642dd34a384b164ea323f1249204f0e45b ?

## Suite that reproduces the behavior (for bugs)
N/A for this issue?

## Context
Debugging/running single spec while watching html is painfully slow on newer versions of Jasmine.

## Your Environment
* Version used: 2.8.0, 2.5.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 62, node 7
* Operating System and version (desktop or mobile): N/A
* Link to your project: N/A I guess?

<img width="1545" alt="2017-12-05_2324" src="https://user-images.githubusercontent.com/2279299/33649653-92c59fc2-da13-11e7-98a4-7e6d4477bab0.png">

**Comment by sgravrock** [comment]
First off, I'd suggest upgrading to 2.8.0 before trying anything else. There have been a lot of changes to how focused specs are handled since 2.5.0, and although none of them do the specific thing you're asking for, they might improve performance in your situation.

Beyond that, this is one of those areas where the needs of people with large test suites are somewhat in conflict with the needs of people with fewer test suites. We show the gray dots for disabled specs to help users understand what's going on. A suite with one spec and a suite with many specs one of which is focused are different things and it's helpful to display them differently. This is particularly valuable since a change in the number of dots can be the only indication of a newly introduced syntax error in a spec file.

While we're unlikely to revert the change to show disabled specs, I think it would be reasonable to make it configurable and/or to automatically disable it when there are more than some large number of specs. I'd be happy to review a pull request that does that.

**Comment by mkj28** [comment]
> First off, I'd suggest upgrading to 2.8.0 before trying anything else

yep, as noted above - it's the same in 2.8.0

> make it configurable and/or to automatically disable it when there are more than some large number of specs

that makes sense!!

**Comment by slackersoft** [comment]
Closing this, it looks like it got merged in with #1561, but the original issue never got updated.
