### ISSUE TITLE
While using 'fit' all other 'it' tests are skipped. How to make 'it' run?

### ISSUE THREAD

**Issue by pbalan** [jasmine/jasmine#1463]
Hi,
I am not sure if this is an expected way but while using [fit](https://jasmine.github.io/api/2.6/global.html#fit) all other [it](https://jasmine.github.io/api/2.6/global.html#it) tests are skipped. How to make 'it' run?

I searched on google and didn't find any answers and also looked in the documentation with no luck. Have posted a [question](https://stackoverflow.com/questions/47806018/why-my-tests-run-using-fit-while-it-does-not-run-when-i-use-it-in-jasmine) on stack overflow.

Thanks.

**Comment by slackersoft** [comment]
As the documentation page you linked to says, "If suites or specs are focused, only those that are focused will be executed." `fit` is specifically to focus the current runs of your suite to _only_ run specs and describes that have been focused (with either `fit` or `fdescribe`). You can have multiple `fit`s or `fdescribes`, but if you want to run your full suite, you should not have any.

I'm going to close this since this is the desired functionality. Hope this helps. Thanks for using Jasmine!

**Comment by pbalan** [comment]
Thanks. Its a great library 👍 I figured out my issue I posted on stack overflow as well. I shall reply to my own question later when I am able to do so.
