### ISSUE TITLE
Is it possible to define specs during configuration time?

### ISSUE THREAD

**Issue by mfidemraizer** [jasmine/jasmine#1466]
I'm wondering if there's some hidden gem so I can do something like this: 

```
jasmine.addSpec(x => {
     x.describe("foo", () => {
             x.it("bar", () => {
                   // Stuff here
             })
     })
})
```

**Comment by mfidemraizer** [comment]
I want to add that I'm wondering if this is possible because I'm working with `.mjs`/ES modules in Node, using `--experimental-modules` flags, so I can't run my tests with Jasmine because it tries to load my specs using `require` (CJS) instead of `import` (ESM).

**Comment by slackersoft** [comment]
I think you might want to use the [library directly](https://jasmine.github.io/edge/node.html#section-Using_the_library) from Jasmine-NPM. This will let you control when `jasmine.execute()` is called so it isn't until after you've otherwise loaded all your specs.

Right now Jasmine just installs itself on whatever the global object is in the context it is being run (`global` in nodejs, `window` in a browser) to make itself available. At some point, we'd like to move to something more friendly to modules of all sorts, but I don't think that is going to come any time too soon.

Hope this helps. Thanks for using Jasmine!

**Comment by mfidemraizer** [comment]
@slackersoft This is enough. I can define the whole tests in a module default function which may take `describe`, `it` and others as arguments.
