### ISSUE TITLE
Failing test with no expectations

### ISSUE THREAD

**Issue by francittadini** [jasmine/jasmine#1467]
## Expected Behavior
Would you agree on failing a test that doesn't have any expectations?

## Possible Solution
Maybe adding: 
`result.status = 'failed'`

after this line:
https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine-html.js#L107

Thanks!!

**Comment by sgravrock** [comment]
There are some legitimate use cases for tests without assertions, for instance:

* A test that verifies that an asynchronous process completes.
* A test that verifies that something doesn't throw an exception. (Using `.not.toThrow` is arguably better, but the no-assertion form of this test is very common.)
* A test for behavior that doesn't apply in the current environment, e.g. Node-specific functionality in a browser or vice versa.

Those might seem like edge cases but in my experience most test suites for nontrivial programs end up with at least a couple of them. That includes Jasmine's own test suite. We've seen more interest from the community in coming up with ways to suppress the "spec has no expectations" warning than in turning it into an error.

Also, having an assertion in a test is a means to an end, not an end in itself. To be correct a test needs to fail in the expected way when the functionality that it verifies is broken. The only way to be sure of that is to actually see it happen. If you've made sure that your test fails correctly, either by working test-first or by breaking the code under test, then you don't need a tool to check for the presence of assertions. If you haven't done that, then you shouldn't have much confidence in the test whether a tool has checked it for assertions or not.

We're unlikely to make this change because it would break many existing test suites, it makes some use cases more awkward, and could provide a false sense of security. But if you really want to expose tests without expectations in a more obvious way than a console message, you could write a custom reporter that checks the expectation count in its `specDone` event and does something suitably noticeable.

**Comment by francittadini** [comment]
Thanks for the response 😃

**Comment by CWSpear** [comment]
What about making it configurable? So the some 40 tests I just discovered were false positives in our test suite could have been caught sooner...

**Comment by slackersoft** [comment]
Given that Jasmine already provides a way to see specs that don't have any expectations without any configuration, while still allowing the use cases where you might intentionally leave them out, I'm not sure we want to add an additional option to cause specs without expectations to fail.

Hope this helps. Thanks for using Jasmine!

**Comment by dstj** [comment]
@slackersoft You mention that Jasmine has a way "out of the box" to list tests without expectations. Can you elaborate? I haven't found how in the documentation.

For example, my Karma runner page mentions `20 specs, 0 failures, randomized with seed 62124`, but I've got one `SPEC HAS NOT EXPECTATIONS` around the middle on the page, in green mind you, just like a successful test. It's also counted as a successful test. So without doing `CTRL+F`, I would probably miss it... @francittadini requests seem legit to me.

Maybe simply adding `19 specs, 0 failures, 1 has no expectation, randomized with seed 62124` would do the trick. Is it already possible with jasmine making that a Karma issue?

**Comment by slackersoft** [comment]
By default Jasmine's HTML Reporter will add the 'SPEC HAS NO EXPECTATIONS' message to the beginning of the spec and log a message with `console.error`.

Even these warnings aren't features that everyone wants, so this isn't something we can change to fail for everyone. I'd be happy to review a pull request that adds another option like 'stop execution on spec failure' called something like 'fail specs with no expectations'. Oddly, I think the easiest way to implement that will be to add an expectation failure to the spec with the appropriate message just before the Spec object marks itself complete and successful.

**Comment by nasreddineskandrani** [comment]
@slackersoft if no one do this PR soon. I l (got a baby this week less time for this now my side)

**I have one question:**
look inside this stackblitz 
https://stackblitz.com/edit/testing-false-positiv?file=src%2Fapp%2Ftest-b%2Ftest-b.service.spec.ts

the result is:
```
...1
SPEC HAS NO EXPECTATIONS ...1a
```

The second spec is flagged as `NO EXPECTATIONS` so it helps to know the test is useless.
Now if i uncomment the line 33 adding a fake expect the one in the subscribe is not reached but not detected this time the result become:
```
...1
...1a
```
You think we can adjust the code of the library to detect this case?

**Comment by slackersoft** [comment]
@nasreddineskandrani if you're doing asynchronous work in the code you're testing (say with events and subscriptions), you should probably look at Jasmine's [async support](https://jasmine.github.io/tutorials/async) to ensure your tests don't complete before you've finished executing everything.

Hope this helps. Thanks for using Jasmine!

**Comment by nasreddineskandrani** [comment]
@slackersoft it's exactly what we are doing. 
the only thing is that the `done` do prevent it but do not detect it :) we need to go check test by test.
if something is missed during review and a junior dev do not use `done` we are open to problems.

**Comment by slackersoft** [comment]
I'm not really sure how Jasmine would go about detecting the use of a particular type of `subscribe` function in a given test to guarantee that it was an RxJS type `subscribe` and not just some function in your codebase that had the name. Jasmine's existing functionality for detecting a spec that completes asyncronously, allows a spec to explicitly call a `done` callback, return a `Promise`, or declare the `async function` when calling `it`, so you might be able to provide some sort of wrapper for your codebase that maps over to one of those.

**Comment by nasreddineskandrani** [comment]
sure i agree better to let this outside of jasmine.
for now, we are trying to be careful on review to make sure when needed we use `done` to have a timeout error in case of false positiv.

**Comment by mswilson4040** [comment]
I can't find any update on this, so commenting here. My use case is identical to @CWSpear. I have a couple of hundred tests that were all passing. However, after looking more closely at the results, I see some tests are showing the "_SPEC HAS NO EXPECTATIONS ..._" message. Turns out, those are false positives.

From what I'm reading, there are legitimate use cases for specs without expectations (I get that). But, I have hard requirements that all tests must have at least one expectation. With that being said, I need some way to enforce that. Is it still the case that there is no configuration to make this happen?

IMO, adding some text to say "SPEC HAS NO EXPECTATIONS" and relying on developers to actually look for that blurb of text is unrealistic and will never actually happen.

This seems like a very basic configuration setup.

**Comment by mswilson4040** [comment]
I stand corrected. Looks like there was a new property introduced that solves this issue:

`failSpecWithNoExpectations`

Example:
```
...
client:{
      ...
      jasmine: {
        ...
        failSpecWithNoExpectations: true
      }
    },
```
docs are [here](https://jasmine.github.io/api/3.5/Configuration.html)
