### ISSUE TITLE
Feature Request: differentiate tests that have run 0 expect

### ISSUE THREAD

**Issue by sound-matt** [jasmine/jasmine#1471]
It would be cool to see the tests that are in success because they have run 0 expect from the ones that are in success because they actually run some expects. It would be even cooler to have a count of the expect run.

Exemple:
```js
it('should warn', () => {
    // 0 expect here
});

it('should success', () => {
    expect(true).toBe(true);
});

// Success: 1 expect run
it('should success again', () => {
    if (true) {
        expect(true).toBe(true);
    } else {
        expect(null).toBe(null);
    }
});
```

**Comment by sgravrock** [comment]
If you're using the HTML reporter in a released version of Jasmine, you should see warnings logged to the console and the words "SPEC HAS NO EXPECTATIONS" prepended to the name of any spec that doesn't  have any expectations. 

We'd prefer not to have Jasmine output more detailed information about expectation counts because it would just be unnecessary noise for most users and [relying on that information can mask deeper testing workflow problems](https://github.com/jasmine/jasmine/issues/1467#issuecomment-352222044). However, if you find that information useful, you can write a [custom reporter](https://jasmine.github.io/2.8/custom_reporter.html) that outputs it in the way that you want. Have a look at the `specDone` event, specifically `passedExpectations` and `failedExpectations`.

**Comment by sound-matt** [comment]
Thank you :smiley:

**Comment by slackersoft** [comment]
Closing this as it sounds like current functionality is enough for this use case. Thanks for using Jasmine!
