### ISSUE TITLE
Maps comparison always passes in IE11

### ISSUE THREAD

**Issue by Volox** [jasmine/jasmine#1472]
This is the same bug as #1257 but happens only in IE11

## Possible Solution

Also take care of the unsupported `Map`/`Set` methods and contructor in IE11 [see Kangax table](http://kangax.github.io/compat-table/es6/#ie11)
- keys
- values
- entries

## Suite that reproduces the behavior (for bugs)
```javascript
it('Test', function() {
  const map1 = new Map();
  map1.set(1, 2);
  const map2 = new Map();
  map2.set(1, 3);
  map2.set(2, 3);
  expect(map1).toEqual(map2);
});
```

## Your Environment

* Version used: ~2.8.0
* Environment name and version: IE11
* Operating System and version: Windows 10

**Comment by slackersoft** [comment]
Unfortunately, the things that IE 11 leaves out of make it nearly impossible to do a comparison of two `Set`s or `Map`s. Jasmine isn't in the business of manipulating your javascript environment (unless you explicitly tell it with spies or the mock clock), because this wouldn't be a good indication of how your code would run in that environment. If your code needs to run in IE11 and needs to use `Set` or `Map`, you'll need to provide your own polyfills to add the functionality to make them work.

Hope this helps. Thanks for using Jasmine!

**Comment by Volox** [comment]
Why impossible?

For `Map` and `Set` you can use the `forEach` method to get the contents and do the comparison using that one.

**Comment by slackersoft** [comment]
I missed that one before. We would be happy to review a pull request to make `Map` and `Set` equality comparison fall back to use `forEach` where `keys()` or `values()` aren't available. The checkers for Jasmine's tests should also be updated so the specs will actually run in these environments.

Sorry for the confusion. Thanks for using Jasmine!
