### ISSUE TITLE
Why doesn't jasmine support using async function for describe method?

### ISSUE THREAD

**Issue by LvChengbin** [jasmine/jasmine#1487]
When I am using an `async` function as the second argument of `describe` function, I got an error message about using `AsyncFuntion`. Is there some reasons I cannot use async function or it's just an issue with the type checking?

**Comment by slackersoft** [comment]
The `function` passed to `describe` is executed during loading of your suite, and isn't expected to have anything asynchronous when defining _which_ specs should be run.

If you have async setup work that needs to be done before the specs are actually executed, you should use `beforeAll` and an async mechanism there to do the setup.

If you *really* need to wait for some async process to finish before actually _defining_ your specs, you'll need to also provide a [custom boot](https://jasmine.github.io/edge/custom_boot.html) file to cause Jasmine to wait until you've finished defining all of your specs before `execute`ing the Environment.

Hope this helps. Thanks for using Jasmine!

**Comment by mehdhi** [comment]
Hello slacker, the link for the custom boot is broken https://jasmine.github.io/edge/custom_boot.html

**Comment by slackersoft** [comment]
Looks like the comment might have been deleted, but I was moving some things around in the documentation and temporarily broke the link to custom boot. It should be fixed now.

**Comment by LvChengbin** [comment]
@slackersoft okay, thank you so much.

**Comment by joet87** [comment]
I full don't understand this comment" If you have async setup work that needs to be done before the specs are actually executed, you should use beforeAll and an async mechanism there to do the setup." . 

I need to call a SigninApi() that does a rest call and return few authorization token in beforeEach . I only want execute 'it' only after the  token have be returned. So far I cannot get the beforeEach to wait for the call to return instead test starts after making the signInApi() call. I tried sever ways to make it wait,  but none of them seem to work. 

Does beforeEach support waiting on async calls  or can elaborate or provide example of " an async mechanism there to do the setup."

**Comment by slackersoft** [comment]
Jasmine supports 3 ways for a `beforeEach`, `afterEach`, `it`, `beforeAll`, or `afterAll` to be asynchronous.

1. The function passed should receive a `done` callback that is invoked when all work is finished.
1. The function returns a `Promise` that is resolved when all work is finished
1. The function uses the `async` keyword and appropriately `await`s all async work.

Hope this helps. Thanks for using Jasmine!

**Comment by thomann061** [comment]
@joet87 Here's an example of doing async setup:

```javascript
const fetch = () => {
  return Promise.resolve(10);
}

describe('async function test', () => {

  let data = null;

  beforeEach(async () => {
    console.log(`\nbeforeEach is fetching async.....`);
    data = await fetch();
    console.log(`The data: ${data}`);
    console.log(`Done fetching!\n`);
  })

  it('should run after beforeEach', () => {
    console.log(`Running after beforeEach.....`);
    console.log(`Got the data: ${data}`);
  })
})
```

Output:
```
beforeEach is fetching async.....
The data: 10
Done fetching!

Running after beforeEach.....
Got the data: 10
```

**Comment by yacovg** [comment]
> @joet87 Here's an example of doing async setup:
> 
> ```js
> const fetch = () => {
>   return Promise.resolve(10);
> }
> 
> describe('async function test', () => {
> 
>   let data = null;
> 
>   beforeEach(async () => {
>     console.log(`\nbeforeEach is fetching async.....`);
>     data = await fetch();
>     console.log(`The data: ${data}`);
>     console.log(`Done fetching!\n`);
>   })
> 
>   it('should run after beforeEach', () => {
>     console.log(`Running after beforeEach.....`);
>     console.log(`Got the data: ${data}`);
>   })
> })
> ```
> 
> Output:
> 
> ```
> beforeEach is fetching async.....
> The data: 10
> Done fetching!
> 
> Running after beforeEach.....
> Got the data: 10
> ```

How can I use data in it method?
it(`should run after beforeEach - ${data.name}`, () => {
   ...
  })

**Comment by slackersoft** [comment]
Dynamically naming your specs seems like a test smell to me. Ideally, you should know enough about what the `it` is testing when you write it to give a good enough name, and not need to rely on data returned by some other part of your production code to determine what to call the test. Jasmine gathers the names of all your specs and suites (`describe` and `it`) when the suite is compiled before anything has been run, so you can't use any information created during execution of the suite.

**Comment by wraiford** [comment]
I humbly ask that this be reopened and reconsidered. Many (most?) functions nowadays are async and disallowing nested async `describe` blocks severely reduces dynamic test composition.

**Comment by sgravrock** [comment]
The problem is that it's not possible to support async `describe` blocks without massively breaking backwards compatibility. `describe` is synchronous, so it can't wait for an async callback to finish. And we can't make `describe` async because it's normally called from synchronous code that Jasmine doesn't control. (Your own code, Node's CommonJS module loader, a browser's script tag loader, etc). Queueing up `describe` fns to be executed later in an async context isn't an option either because it would break common idioms that rely on the `describe` fn being called immediately.

If you need to generate specs based on asynchronously loaded data in 2023, your best bet is to us the `jasmine` package to run your specs in Node, write them as ES modules, and use top-level `await` to fetch the data before calling `describe`. For browser usage, the custom boot option mentioned above remains possible.

**Comment by wraiford** [comment]
> The problem is that it's not possible to support async `describe` blocks without massively breaking backwards compatibility. `describe` is synchronous, so it can't wait for an async callback to finish. And we can't make `describe` async because it's normally called from synchronous code that Jasmine doesn't control. (Your own code, Node's CommonJS module loader, a browser's script tag loader, etc). Queueing up `describe` fns to be executed later in an async context isn't an option either because it would break common idioms that rely on the `describe` fn being called immediately.

Thanks for the clarification. From the thread thus far, it sounded like it was feasible but was decided against because of opinions about testing. I totally understand if just too much code depends on legitimate synchronous assumptions.

> If you need to generate specs based on asynchronously loaded data in 2023, your best bet is to us the `jasmine` package to run your specs in Node, write them as ES modules, and use top-level `await` to fetch the data before calling `describe`. For browser usage, the custom boot option mentioned above remains possible.

I have implemented a workaround for my code that creates pseudo-`describe` blocks using `withContext` (a great function that solves a previous minor pain point for me in the version of mocha/chai I am migrating away from).

All this said, I can tell you from my POV there is a huge opportunity for a testing framework that unifies isomorphic testing in both node and browser contexts. Of course there is crazy configuration required in the ES+CJS world atm, but I'm sticking with Jasmine because I now have it working with TS + ES6 + Browser & Node using bleeding edge TS .mts/.mjs + Node v19 (for isomorphic Webcrypto using `globalThis`). None of the other testing frameworks I tried enabled me to get this working (jest, mocha, karma, etc.), which doesn't mean it can't be done of course...but it ain't easy. This synchronous-only `describe` block is the only real hiccup AFAICT, and in context isn't a big deal. So thank you for Jasmine as it is and all of your hard work! 🥂

**Comment by sgravrock** [comment]
I just put together a proof of concept of support for top-level await in jasmine-browser-runner. That might not be as clean from a user's perspective as letting `describe` callbacks be async. But combined with the exiting support for top-level await in the jasmine package, I think it covers the major remaining use case for async `describe`.

The fly in the ointment is that Safari 14 doesn't support top-level await. So shipping the feature now would mean having to have two completely separate script loading subsystems for different browsers. I'm inclined to hold off on that until the next major release, when we'll drop support for Safari 14.

**Comment by wraiford** [comment]
Wow, I appreciate how you're still looking into this. I think async everywhere will ultimately benefit everyone, and this definitely includes top level await. Looking through my tests, I think already had to work around not having this available, but in my case a file-level `describe` block with an async `beforeAll` might be equivalent. There are probably performance benefits of top-level await for larger projects, but I can't speak to those.

IMO the benefit of async `describe` blocks, in addition to uniformity with regards to the lib's users' expectations, is to enable true composability of testing, taking full advantage of JS's closures. The end goal is to have test clauses with subclause organization.

Overall, I am currently very happy with Jasmine's overall simplicity for getting it up and going for testing in both Node and the browser. Many frameworks make this claim, but I found them extremely difficult to get going with a barebones esm-based package approach. Your Getting Started documentation, however, actually matched expectations for me, which is easier said than done, because of course the ever changing landscape of JS (now further complicated with moving from cjs to esm).

I think the primary failure point that still hasn't been addressed is my [other issue on using import maps with the browser runner](https://github.com/jasmine/jasmine-browser-runner/issues/28) (though I see you've responded there).

**Comment by sgravrock** [comment]
For anyone encountering this issue later: top-level await is supported in `jasmine-browser-runner` 2.0 as well as all versions of the `jasmine` package that support ES modules.
