### ISSUE TITLE
Jasmine Timeout error in  jasmineBoot,js file 

### ISSUE THREAD

**Issue by Artirobo** [jasmine/jasmine#1493]
Uncaught TypeError: Cannot assign to read only property 'setTimeout' of object '[object Object]'
throws at  jasmine boot.js file 
the line is 107:21
 window.clearTimeout = window.clearTimeout;

**Comment by slackersoft** [comment]
Unfortunately, I don't really have enough information here to help solve your problem.

- What version of Jasmine are you using?
- What browser (name and version) are you running Jasmine in?
- How are you running Jasmine (e.g. via Karma, the ruby gem, etc)?

Thanks for using Jasmine!

**Comment by Artirobo** [comment]
i am being using the jasmine 2.9.1 and  i am using jasmine in chrome Version 64.0.3282.140   and  i am using jasmine to test lightning component in salesforce

**Comment by slackersoft** [comment]
Based on [this talk](https://www.salesforce.com/video/294751/) and the [associated repo](https://github.com/keirbowden/LtgJasmineUnitTesting), it sounds like the `window` object that Jasmine receives when booting in the Lightning Locker Service is actually a secure window where these timing functions are not writable. He suggests in the video that you comment customize your boot.js and remove (or comment out) those lines.

Hope this helps. I'm going to close this issues since it doesn't look like an issue with Jasmine itself. Thanks for using Jasmine!
