### ISSUE TITLE
Jasmine does not handles exception in static instances

### ISSUE THREAD

**Issue by vIceBerg** [jasmine/jasmine#1519]
Hi!

I don't know if the title is correct... but here's my case.

I'm using Typescript by the way...

I have a class with static members of it's own class... Here's the code:

```
export class StaticClass {
	public static readonly instance: StaticClass = new StaticClass();

	constructor() {
		throw new Error('Static class error');
	}
}
```

Here's my test
```
import { StaticClass } from './static-class';

describe('test static instance class', () => {
	it('should works', () => {
		expect(StaticClass.instance).toBeDefined();
	});
});

```

Here's my jasmine.json
```
{
	"spec_dir": "dist",
	"spec_files": [
		"**/*[sS]pec.js"
	],
	"stopSpecOnExpectationFailure": false
}
```

It's obvious that the test should fail, the constructor throws an exception. But when I run this test, Jasmine outputs nothing. 

```
MBA:test-jasmine vincent$ ./node_modules/.bin/jasmine --config=jasmine.json
MBA:test-jasmine vincent$ 
```

AS soon as I remove the Error, it works.
```
MBA:test-jasmine vincent$ ./node_modules/.bin/jasmine --config=jasmine.json
Randomized with seed 90625
Started
.


1 spec, 0 failures
Finished in 0.013 seconds
Randomized with seed 90625 (jasmine --random=true --seed=90625)
```

Should'nt Jasmine outputs something in this case, instead of... nothing? It's maybe a lower-level problem, but it took me quite a while to analyse what was doing on.

Thanks

VB

**Comment by slackersoft** [comment]
Load time errors are not being reported correctly in Jasmine 3.0, but we've got a fix in the works. The difference you're seeing is because the static instance is most likely constructed when the file is `require`d and not when the test is actually run, so the error you're looking for will never show up in your spec, unless you were to lazily construct the instance object.

Hope this helps. Thanks for using Jasmine!
