### ISSUE TITLE
jasmine-core NPM package has 2.99.1 instead of 3.0.0 under latest tag

### ISSUE THREAD

**Issue by devoto13** [jasmine/jasmine#1520]
Run `npm info jasmine-core dist-tags` to investigate package metadata. It will say that `latest` is 2.99.1, but there is version 3.0.0 published! Also `jasmine` package returns 3.0.0 as latest: `npm info jasmine dist-tags`.

Because of this NPM will install jasmine-core@2.99.1 when version is omitted and `npm outdated` won't report that new version is available.

## Expected Behavior

```
$ npm info jasmine-core dist-tags
{ latest: '3.0.0' }
```

## Current Behavior

```
$ npm info jasmine-core dist-tags
{ latest: '2.99.1' }
```

## Possible Solution

Maintainers change `latest` tag to point to 3.0.0 :smile:

**Comment by slackersoft** [comment]
This should be fixed now. It looks like NPM just assumes that the most recently released (by date) version of a package it the one that should be installed as latest, and it doesn't look at the actual version numbers at all. Since we patched 2.99 with a 2.99.1 after 3.0 was released, NPM thought that would be better.

```
$ npm info jasmine-core dist-tags
{ latest: '3.0.0' }
```

Thanks for reporting this, and thanks for using Jasmine!
