### ISSUE TITLE
Jamsine

### ISSUE THREAD

**Issue by smritiz** [jasmine/jasmine#1528]
There is no directive with "exportAs" set to "matButtonToggleGroup"
<mat-button-toggle-group (ngModelChange)="changeView($event)" [ngModel]="currentView" [ERROR ->]#group="matButtonToggleGroup">
            <mat-button-toggle matTooltip="GanttChart" value="ganttch"): ng:///DynamicTestModule/ActionsComponent.html@2:94
There is no directive with "exportAs" set to "bs-mdbPopover" (" 

        <span style="width:170px" placement="bottom" [ERROR ->]#pop1="bs-mdbPopover" [mdbPopover]="popTemplate" mdbRippleRadius class="changeFilter pull-right selec"): ng:///DynamicTestModule/ActionsComponent.html@50:53
The pipe 'search' could not be found ("pan>
                </li>
                <li (click)="changeuser(user);pop1.hide()" *ngFor='let [ERROR ->]user of auth.subordinates | search:{ string: filterText, type: "user" }' [class.active]="currentFilte"): ng:///DynamicTestModule/ActionsComponent.html@117:71
The pipe 'search' could not be found (" <ul class="list-group">
            <li (click)="changeplan(invit.plan);pop1.hide()" *ngFor='let i[ERROR ->]nvit of currentUserPlans  | search: { string: filterText, type: "filter" }' [class.active]="currentPl"): ng:///DynamicTestModule/ActionsComponent.html@143:74

**Comment by sgravrock** [comment]
This looks like an error message from an Angular application, not Jasmine. Assuming that it's your own code, you're probably better off asking for help on Stack Overflow or in an Angular forum. But note that you're more likely to get a helpful response if you [include enough information for readers to understand the problem](https://stackoverflow.com/help/how-to-ask) rather than just copying and pasting an error message.

Closing as this doesn't appear to have anything to do with Jasmine.
