### ISSUE TITLE
Cannot test non exported function of file.

### ISSUE THREAD

**Issue by hir06** [jasmine/jasmine#1538]
I have a .ts file which has few non-exported functions. 
I am unable to test this since the scope of this function is not clear (Closure function).

```
Eg.
export function b(){
a()
}
function a(){
}
```

Here I am unable to test this function a(). However, I were able to spy on same with
jasmine.createSpy('a')

**Comment by slackersoft** [comment]
I like to think of functions that aren't exported as being `private` in scope. This means that they're inaccessible to anyone else in the system and can't be called or overwritten or messed with in any other way. Because of this, they also aren't available to test code to invoke or spy on. If the functions are _truly_ private in scope and shouldn't be available outside the context of the one file, you will need to test them via the public interface (exported functions). Your other option is to make them public so they can be tested directly, either in the existing file, or as another module that your current one depends on.

Additionally, your `jasmine.createSpy('a')` call doesn't actually do anything to replace the `a()` function inside the module under test, it simply returns a new spy with the internal name of 'a'. If you want to install a spy over an existing function, you should use [`spyOn`](https://jasmine.github.io/api/edge/global.html#spyOn).

Hope this helps. Thanks for using Jasmine!
