### ISSUE TITLE
Information on automatic generation of Jasmine Unit test cases

### ISSUE THREAD

**Issue by akhileshtripa** [jasmine/jasmine#1544]
## Are you creating an issue in the correct repository: Yes

Hello Folks,
We are trying to generate jasmine test cases automatically from developed java script code. Any idea if someone of you have developed some utility or recommendation?

Thanks.
Akhilesh T 
+91 8130652060

**Comment by slackersoft** [comment]
In general, I would shy away from using a tool to automatically generate tests. These tests can only represent the current actual state of the system, and not the desired functionality. They are also less likely to be discoverable and maintainable by the actual humans working in the code, since they didn't write them themselves.

That said, I am sure there are tools that exist to perform this action for you. We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself. Next time you have a "How to use jasmine?" question please use the [jasmine-js group](https://groups.google.com/group/jasmine-js). 

Closing. Thanks for using Jasmine!
