### ISSUE TITLE
Customize PrettyPrinter

### ISSUE THREAD

**Issue by UniverseHan** [jasmine/jasmine#1545]
Hello I wanna customize PrettyPrinter. I wanna see result of toHaveBeenCalledWith 

like
```
Object({
  key: value,
  key: value2,
})
```

instead of
```
Object({key: value,key: value2});
```

I searched the internet I wan't able to make error message like above.So I tried to modify PrettyPrinter little bit. I changed code jasmine code. But I don't want to do it. I achieve this by decorating PrettyPrinter not directly modifying it.

But I found that I couldn't access PrettyPrinter in my code because PrettyPrinter is private in pp function.

It there any way to customize it or another way to prettify error message of toHaveBeenCalledWith or 
object compare. I don't want to add matcher for toHaveBeenCalledWith because It is very hard work..

ps. Is there any reason it's impossible or hard to prettify `toHaveBeenCalledWith` reported message? or Is there any option already for it?

Thank you for reading.

**Comment by whyboris** [comment]
You might be looking for a `reporter` to do this job: https://www.npmjs.com/package/karma-jasmine-diff-reporter
Specifically look for their `pretty` option, which should result in something like this:
![image](https://user-images.githubusercontent.com/17264277/39207105-1d6ae3a4-47cd-11e8-98dd-7ec6c796a6ba.png)

**Comment by UniverseHan** [comment]
That doent work for toHaveBeenCalledWith in jasmine nodejs environment.

**Comment by slackersoft** [comment]
Customizing the pretty printer is something we've been thinking about for a while, but haven't figured out a good way to do it. Where the pretty printer lives right now makes things a bit tricky, since it needs to output something that is useful both in a console format and in a web page without knowing which context it is running in. Possibly even both at the same time, if you're running in a browser via selenium or something and want to potentially see both versions.

Another workaround you might be able to try for spy argument assertions is checking number of calls and using `toEqual` for argument checking to get the more descriptive output it provides.

```javascript
expect(mySpy.calls.count()).toEqual(1);
expect(mySpy.calls.mostRecent().args).toEqual(['foo', {}]);
```

We would also be happy to review a pull request to allow some sort of custom formatters similar to custom equality testers (tracker story: https://www.pivotaltracker.com/story/show/152892751) or a pretty formatter that knows how to deal with different newlines depending on the environment.

Hope this helps. Thanks for using Jasmine!

**Comment by sgravrock** [comment]
Closing due to prolonged inactivity. The landscape around pretty printing has changed a bit since this issue was filed, so it would be best for anyone who's still interested in PrettyPrinter customization to open a new issue.
