### ISSUE TITLE
jasmine tests run in random order

### ISSUE THREAD

**Issue by dudaming** [jasmine/jasmine#1550]
Hi,
We are using wdio-jasmine-framework to run our e2e test, but we found out the test steps run in random order.

Same issue has been reported in wdio-jasmine-framework.
https://github.com/webdriverio/wdio-jasmine-framework/issues/124

**Comment by slackersoft** [comment]
The default configuration for random order was changed in a major version release of Jasmine (3.0), because we knew it would be a breaking change for many suites. Jasmine supports the ability to turn the randomization off, but it is up to the wrapping framework to pass this option through to Jasmine.

Closing this, since this is the current desired functionality for the 3.x release of Jasmine. Hope this helps. Thanks for using Jasmine!

**Comment by dudaming** [comment]
Hi, 
Thanks for the reply. 
Could you please tell me which parameter should I change to disable this?

**Comment by slackersoft** [comment]
Jasmine's config file has a `random` flag that you can set to false. I'm not sure how to get the WebDriverIO runner to pass that to the underlying Jasmine environment, sorry.
