### ISSUE TITLE
ability to spyOn multiple funtions

### ISSUE THREAD

**Issue by shivasai09** [jasmine/jasmine#1553]
```
let func1  = spyOn(component.prototype , func1)
let func2  = spyOn(component.prototype , func2)
```

right now why jasmine is not allowing to spyOn multiple funtions ?

it is only allowing to spyOn one funtion at a time.. 
how to unit test  when a scenario come ,where one function is calling other funtion

**Comment by slackersoft** [comment]
What sorts of errors are you getting when you try to spy on more than one function? Your example code doesn't look like it will work at all, since you're passing in a variable that you haven't yet initialized as the name of the function to spy on. If you have a function that you want to test that it correctly calls two other functions:

```javascript
function Component() {}
Component.prototype.foo = function () {};
Component.prototype.bar = function () {};

function doStuff() {
  var component = new Component();
  component.foo();
  component.bar();
}
```

You should be able to test it like so:

```javascript
it('calls foo and bar', function() {
  spyOn(Component.prototype, 'foo');
  spyOn(Component.prototype, 'bar');
  doStuff();
  expect(Component.prototype.foo).toHaveBeenCalled();
  expect(Component.prototype.bar).toHaveBeenCalled();
});
```

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
Closing this since we haven't gotten enough information to indicate an issue in Jasmine.
