### ISSUE TITLE
How to know in the test if expectation failed or not?

### ISSUE THREAD

**Issue by GuyMograbi** [jasmine/jasmine#1554]
Sometimes I find it useful to know inside the test if an expectation failed or not. 

Currently, I just repeat the matcher logic in the test. For example

```javascript
expect(1+1).toBe(3); // log failure in reporter
if (1+1 === 3){ // decide on future test steps
   ... // only relevant if 1+1 === 3
}else{
   ... // relevant if 1+1!==3
}
```

However it would be nice to be able to reuse a matcher instead. For example something like this:

```javascript
if (expect(1+1).toBe(3)){ // real failure to be shown in reports
   ... // skip these steps as they are not relevant in this case
} else {
   ... // move on to these steps since 1+1 is not 3. 
}
```

Or with promises

```javascript
expect(someAsyncThing()).toBe(3).then(()=>{...}).catch(()=>{...})
```

I just can't seem to find a way to know if an expectation failed or not. Is there a way to know this?

**Comment by GuyMograbi** [comment]
@sgravrock thanks for the reply. 

My project would like to add A/B testing on some features and the decision about some tests is that they will be able to handle the flow regardless of testing changes. 

So for example if page X appears earlier in the flow due to a test, we should still be able to handle this. 

currently we are doing 

```
   browser.getCurrentUrl().then((url)=>{
     if (url.endsWith('/url1')){ // this line used to be 'expect' previously
         // .. 
     } else if (url.endsWith('/url2')){ ... }
     throw Error('unknown url [' + url + ']');
   })
```

Similarly if elements are present or not. 

It would be nice to write something like 

```
expect(browser.getCurrentUrl()).toMaybeContain('/url1').then({
  ...
});

expect(browser.getCurrentUrl()).toMaybeContain('/url2').then({
 ... 
});

// .. do some common stuff to both versions

expect(browser.getCurrentUrl()).toContain('/url3'); // ... on with the flow
```

And then preferably somehow to write a reporter that will be able to say "url1 one failed, but that's ok because url2 worked" 
or possibly "this test failed because both scenarios failed". 

Hope this makes it clearer.

**Comment by slackersoft** [comment]
This functionality seems like it would be hard to implement in a general way, and probably also hard to use correctly.

If Jasmine were to return the status of an expectation, as the original suggestion, you might be able to change course after that, but the failure would already have been recorded and the spec would still fail.

Extending `expect` with some sort of "maybe" syntax doesn't indicate why you might use the feature and makes it far too easy to write a spec that should fail but doesn't. This is worse than having a spec that should pass but doesn't, because you won't even notice.

Additionally, it kind of sounds like the `if` statements most directly express the _intent_ of the functionality, which is to check which A/B test branch was delivered, and respond accordingly.

This doesn't sound like functionality we want to have in Jasmine itself at this time, but if you have another suggestions that would make writing and extension for something like this easier, we'd be happy to discuss that more. Thanks for using Jasmine!

**Comment by GuyMograbi** [comment]
@slackersoft Thanks for the reply. I understand your considerations. 

Perhaps there is a way to access the matchers without `expect`? 
Basically any way that would allow me to reuse a matcher without the need to reimplement the logic would be nice.

**Comment by sgravrock** [comment]
Apologies in advance if I've misunderstood what you're doing or am about to get some math wrong.

It sounds like you care about testing both the A path and the B path, but each time you run the test it will only exercise one of them, right? So it's worth thinking about how many times you'd have to run your tests to get a high enough probability of exercising all the paths you care about. For instance, if there's an equal chance of getting A or B on any given run, then running a test like the one you described twice would give only a 50% chance of exercising both paths. If you have many tests, each of which can independently get either A or B, the problem compounds. In any case you'd end up with a test suite that's probabilistic rather than deterministic: if it's run X times it has a Y% chance of verifying everything that you want it to, where Y is always less than 100.

The approach I'd take in your situation is to put the A/B switch under the control of my tests somehow, and then write two tests: One that puts the system into the A state and then verifies the A path, and another that does the same thing with B. That way I could be confident that a single test run had exercised both paths. I realize that setting that up can be extra work when doing end to end testing, which your code sample hints at, but I'd consider it time well spent in most situations.

If you do want to stick with the probabilistic approach, I think sticking with simple if statements that have explicit conditions would be clearer than trying to reuse matchers somehow:

```
var url = browser.getCurrentUrl();
if (url.indexOf('/url1') !== -1) {
   ...
} else if (url.indexOf('/url2') !== -1) {
   ...
} else {
   throw new Error('Expected a URL of /url1 or /url2 but got ' + url);
}
```

The virtue of that approach, at least to my eyes, is that the control flow is obvious no matter how much or how little the reader knows about Jasmine.

I hope this helps.

**Comment by eyecatchup** [comment]
Another use case where it might be useful:

```js
it('ALL database GET routes should return their correct status code', function(done) {
    const async = require('async');
    const mongoose = require('mongoose');
    const Route = mongoose.model('Route');

    Route.find({
        method: 'get'
    }, function(err, routes) {
        async.each(routes, function (route, callback) {
            let statusCode = 200;
            if (route.statusCode) {
                statusCode = route.statusCode;
            }

            request.get(base_url + route.path, function(error, response) {
                expect(response.statusCode).toBe(statusCode);
                callback();
            });
        }, done);
    });
});
```

Given the test above, we can not get the information on which route the expectation fails. In order to achieve this, we'd need to add something like:

```js
request.get(base_url + route.path, function(error, response) {
    if (response.statusCode !== statusCode) {
        console.log(route.path);
    }
    expect(response.statusCode).toBe(statusCode);
    callback();
 });
```

**Comment by slackersoft** [comment]
Please also check out the new [`withContext`](https://jasmine.github.io/api/edge/matchers.html#withContext) helper for expectations (and async expectations), as I think this should help differentiate your expectations.

Hope this helps. Thanks for using Jasmine!

**Comment by elliot-nelson** [comment]
I think I have an alternate use case for this feature (or maybe, it's a feature like it?)

The gist is that sometimes, it's helpful when _testing jasmine add-ons_ to be able to test whether code will generate a test failure.  In large projects, you end up bolting on some additional wrappers and test harnesses and the like and that code usually needs testing too.  You need to be able to write a spec like this:

```
describe('integrationTestHelper', function() {
    it('fails with jasmine.getEnv().fail if express server cannot start', function() {
        spyOn(integrationTestHelper, 'startServer').and.throwError();
        expect(integrationTestHelper(function() { })).toFailWith({
            pass: false, message: 'Spec aborted, integration environment not ready.'
        });
    });
});
```

For some custom frameworks I've worked on, I've seen copied and pasted a matcher to provide this functionality... the important guts are (cringe):

```
compare: function (actual, expectedResult) {
  var testResults = [];
  var originalAddExpectationResult = jasmine.Spec.prototype.addExpectationResult;
  jasmine.Spec.prototype.addExpectationResult = function (...result) {
      testResults.push(result);
  };

  actual();

  jasmine.Spec.prototype.addExpectationResult = originalAddExpectationResult;

  if (jasmine.matchersUtil.equals(testResults, expectedResults)) {
      // ....
  }
}
```

I wonder if something similar could be provided by Jasmine, _without_ the scary prototype monkey patch.

**Comment by slackersoft** [comment]
@elliot-nelson this seems like a different use case than the original poster had in mind. I think if you're writing a custom matcher for Jasmine, I would test it by call the `compare` function on the matcher directly and inspecting the output. This is what Jasmine itself does to test its own matchers and doesn't require any scary code clobbering.

Ultimately, I think that exposing the `pass` status out to the spec currently being run is more likely to encourage poor usage and hard to debug false positives, than the converse. In general, Jasmine prefers to prevent false positives. The failure mode I'm particularly looking at is a spec where an expectation fails that shouldn't, but because you're checking the outcome and entering a different branch of your test, the test reports as passing when it _should_ be failing.

Hope this helps.

**Comment by henrahmagix** [comment]
> The failure mode I'm particularly looking at is a spec where an expectation fails that shouldn't, but because you're checking the outcome and entering a different branch of your test, the test reports as passing when it _should_ be failing.

@slackersoft I agree that this is bad: the test should fail for any expectation that fails. I use https://godoc.org/github.com/stretchr/testify/assert a lot and it does exactly that: it allows you to branch in your tests, but it still reports a failure if the assertion failed.

I keep coming across cases in my Jasmine tests where I would like to do the same. I think returning the `pass` status without affecting the result of the spec would be a wonderful addition to Jasmine.

For one thing, it would cut down on the failure output and avoid errors being raised. For example, the failure output of this:
```js
if (expect(actual).toBeDefined()) {
  expect(actual.myString).toEqual('A string value');
  expect(actual.myMethod()).toEqual('A method return value');
}
```
would be shorter and more readable than this:
```js
expect(actual).toBeDefined();
expect(actual.myString).toEqual('A string value');
expect(actual.myMethod()).toEqual('A method return value');
```
which actually raises a TypeError.

**Comment by slackersoft** [comment]
If you primarily want to suppress further expectation failure messages from showing up, you might want to look into the [stopSpecOnExpectationFailure](https://jasmine.github.io/setup/nodejs.html#configuration) configuration option.

**Comment by dlaliberte** [comment]
I found this thread looking for a solution to a similar problem.  I would like to use withContext on tests that have been written separately and also call expect()...etc, so (assume) I cannot add a withContext(msg) call in the middle of those other tests.  

Instead, I wanted to do something like this:

```
const injectWithContext =
    (test: Function, msg: string, ...args: AnyDuringMigration[]) => {
      expect(() => test(...args)).withContext(msg).toPass();
    };
```
And it could be called like this:

`injectWithContext(myTest, 'some message', arg1, arg2)`

Is there any way to write the `toPass` method?  Or any code that does the equivalent, maybe with a custom matcher?   The best I can come up with is to (maybe?) cause any failure in the test to throw errors and catch the throw in my injectWithContext by using .not.toThrow().

**Comment by sgravrock** [comment]
I think all the use cases identified in this thread fall into these categories:

* Things that can be done with [`withContext`](https://jasmine.github.io/api/5.1/matchers.html#withContext)
* Things that can be done with [the `stopSpecOnExpectationFailure` configuration property](https://jasmine.github.io/api/5.1/Configuration.html#stopOnSpecFailure)
* Things that can be accomplished with [`throwUnless`](https://jasmine.github.io/api/5.1/global.html#throwUnless) (which is new since the previous activity in this thread)
* Using matcher results to implement conditional logic in tests

I think all but the last one are reasonably well served by existing features.

I stand by my previous concerns about probabalistic testing (i.e. tests that verify this scenario or that one depending on what happens at runtime). Experience has softened some of my stances, but this isn't one of them. Having worked on teams that have taken that approach and seen the damage it can do, I'm more convinced that it would be harmful for Jasmine to provide slick syntax to do that sort of thing. We shouldn't make it impossible (and we aren't: there's still the language's  built-in conditional logic) but we also shouldn't add features that have the main effect of encouraging it. I think `throwUnless` takes us about as far down that road as it's responsible to go.
