### ISSUE TITLE
possibility to mark describe/it's to run mandatory, also when there are focused tests

### ISSUE THREAD

**Issue by zwingliernst** [jasmine/jasmine#1580]
We run our login in a spec as a test (because in Protractors "onPrepare" no expect-statements may run).
When now working on another spec/describe/it of the application under test I'd like to mark this describe and/or it as focused, so when I run, only login and the part I'm working on gets executed.
Because of the number of tests and people working on the code, it's quite time consuming and error prone to focus/unfocus manually all "mandatory" describe/it blocks to ensure, that the application under tests reaches the one "describe/it" we're currently working on.

## Expected Behavior
Possibility to mark describe/it as "mdescribe"/"mit" (mandatory describe/it). These parts shall not be ignored by a focused test execution, but shall not define a focused execution on its own.

## Current Behavior
No possibility to define/mark describe/it-blocks that need to be executed also in focused execution.

## Suite that reproduces the behavior (for bugs)

```javascript
/*abstract structure of my idea 
in our case all those describes are in different files and get called via a caller-function*/
mdescribe("login", function() {
});
mdescribe("create customer", function(){
});
describe("add tax data", function(){
});
describe("add address data", function(){
});
fdescribe("add category tags", function(){
});
```

**Comment by slackersoft** [comment]
Have you tried using [`beforeAll`](https://jasmine.github.io/api/edge/global.html#beforeAll) for the shared setup instead of a `describe` that has to be run in the appropriate order? The `beforeAll` will be run as part of you Jasmine suite (not just Protractor) so `expect` should work as well.

**Comment by zwingliernst** [comment]
I thought of it as well, but face a couple of issues with:
- in "afterEach" there are relevant actions, that are to be executed also for the login
- in the Reporting "beforeAll" doesn't trigger a report while "it" does
- The login was a slightly simplified example. I also need to execute some basic test cases (like create customer, add income values) in order to run the it I'm working on. So there are (data-)dependencies. One test case creates the data, that I need in another.

What do you think of the idea, closing the gap between xit (ignore me) and fit (only me), by adding a mit (I run in normal and focused mode)?

**Comment by slackersoft** [comment]
For the same reasons we moved to making randomized execution order the default in 3.0, that we don't want to include a feature like this into Jasmine itself. Ideally, each test should be isolated from any/all other specs in your suite.

If you're using a previous test primarily because the test code would be duplicated, you might try defining a function that can execute that code in all of the relevant places. If it's primarily because of suite execution time, I would figure out which parts can/should be pulled out to something like a `beforeAll` possibly with a single `it` for some of the expectations that everything there was set up correctly.

I don't think this is something we're going to add to Jasmine at this time, so I'm going to close this. Thanks for using Jasmine!
