### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined thrown

### ISSUE THREAD

**Issue by greengumby** [jasmine/jasmine#1583]
Hi,
Jasmine: 2.0.4
This error is logged to console sometime afterEach completes and sometime beforeEach starts. 

Uncaught TypeError: Cannot read property 'classList' of undefined thrown

Any ideas how to diagnose?
Cheers
Jeremy

**Comment by slackersoft** [comment]
Jasmine pre-3.0 doesn't use `classList` since some of the supported browsers don't support it. (The only place I even see Jasmine 3.x using it is in the `toHaveClass` matcher).

Maybe you have some async code that is still running after your test has completed. Newer versions of Jasmine have better support for different ways of testing asynchronous code, supporting Promises and the `async` keyword.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
Closing this since we haven't seen any further discussion in a number of months.
