### ISSUE TITLE
spy on an objects object

### ISSUE THREAD

**Issue by sirishasriramineni207** [jasmine/jasmine#1586]
This is a netsuite based unit test. So we generally use apis. I am new to jasmine. I have an api which is in a window. So this returns an object. I have to spy on that object.

 function userEventBeforeLoad_addCusRecWf(type){
nlapiGetField("custentity_cybersource_error_code").setDisplayType("hidden");
}

so here I have to spy on setDisplayType("hidden");
I need to check if it is actually hidden or not. Is there a way to do that.
nlapiGetField is in window.
i.e 
window.nlapiGetField = function(){
return{
setDisplayType: function()
}
}

**Comment by slackersoft** [comment]
It really depends on what exactly you're trying to test for.

If you want to test that the `custentity_cybersource_error_code` has been hidden, you might want to get it again in your test and inspect it to see if it is hidden. This will depend on what the api you're using provides for this kind of inspection. It might allow you to do something like:

```javascript
expect(nlapiGetField("custentity_cybersource_error_code").getDisplayType()).toEqual("hidden");
```

If that isn't possible, you might be looking at doing something like providing yourself a mock version of the api and using spies. In order to spy on function that the `nlapiGetField` function returns, you're going to have to spy on that function as well, or invert the dependency and inject the function into your code under test so you provide a fake that way.

If possible, I would still recommend trying to check the actual state of the component under test instead of mocking.

Hope this helps. Thanks for using Jasmine!

**Comment by sirishasriramineni207** [comment]
Thanks for the answer.
It is helpful.
