### ISSUE TITLE
specStarted called even when a spec will not run and no way of knowing it will not run?

### ISSUE THREAD

**Issue by jensakejohansson** [jasmine/jasmine#1607]
I'm running test cases with Jasmine/Protractor. My issue is that I want some code to be executed before each spec in every spec-file. If I use beforeEach it means that I would have to have this setup-code called explicitly in every spec file. Instead I thought that I could add a reporter and use the specStarted and there add this generic setup/restore-code.

However, when I focus the test I'm currently working on with 'fit' the specStarted is still called for those test that are not focused (and that will not be run). The result metadata that's given to specStarted doesn't seem to include any information that could help my code identify that this spec will not be run (is not focused) so the setup-code can be skipped. If I explicitly exclude a spec (xit) I can check result.pendingReason and exit the function, but it doesn't help in the opposite case I have here...

Can't the result passed to specStarted include information whether a spec will be excluded or included in the current test run?

**Comment by slackersoft** [comment]
You should be able to have a `beforeEach` outside of any `describe`s. I often have a specHelper.js file that Jasmine will load that has this kind of global setup and teardown logic that should be executed for all specs in the suite. If protractor is breaking this functionality (which I doubt), you should take that up with them.

As for the reporter callbacks, we went back an forth on this and decided that the `...Started` events wouldn't include status information because we didn't want to introduce a transient status for specs that are about to be run and will find their status during execution. Additionally, reporter callbacks aren't meant to change the way the tests themselves run, as that is why `beforeEach`, `afterEach`, `beforeAll`, and `afterAll` all exist.

Hope this helps. Thanks for using Jasmine!

**Comment by jensakejohansson** [comment]
I think I did try your suggestion at first, but as far as I understood it Protractor breaks that functionality. I think someone came to the same conclusion in another forum. The solution for now is to have the global setup in a function that I have to invoke in the beforeEach in every spec-file. I means a little code duplication, but I guess I'll have to live with it...

**Comment by slackersoft** [comment]
Another thing to check is that your version of Protractor is using the a recent version of Jasmine. There have been issues in past versions with global `before[Each|All]` and `after[Each|All]` not fully behaving properly. I would also be happy to hear what Protractor is trying to work around in Jasmine that would cause them to turn off some of Jasmine's built-in functionality.

**Comment by slackersoft** [comment]
It sounds like this is largely an issue with Protractor and not necessarily Jasmine itself. We also haven't heard anything from the community in a while, so I'm going to close this.
