### ISSUE TITLE
By init standalone have only one  string in trace

### ISSUE THREAD

**Issue by DK-2013** [jasmine/jasmine#1608]
https://github.com/jasmine/jasmine/blob/6b9ae2db7e565a7261d667beb735651360aa5ca9/lib/jasmine-core/jasmine.js#L517

Why trace.frames[2]?
If open default SpecRunner.html got here only trace.frames.length = 1

**Comment by slackersoft** [comment]
Can you give me a bit more context on when you're seeing Jasmine enter this code and have fewer than 2 frames? What browser are you using? Do you have a bit more of a stack trace to help determine what is happening in Jasmine?

If you're just probing in and calling this directly it is entirely possible it doesn't work in different circumstances, since it is a private method.

**Comment by slackersoft** [comment]
Closing this since we haven't heard anything further.
