### ISSUE TITLE
Deprecated jasmineEnv configuration breaks plugins

### ISSUE THREAD

**Issue by nasvillanueva** [jasmine/jasmine#1617]
## Expected Behavior
Since jasmine-core@3.3, [configuration object is introduced to Env](https://github.com/jasmine/jasmine/commit/92d0882a3202e51a866c7b0dfed5393a0e9fe338). Plugins like karma-jasmine, still uses the old style configuration.

## Current Behavior
It prevents runners to run jasmine.

## Possible Solution
Instead of deprecating it right away, a warning should suffice for the time being, to let plugin maintainers to migrate to the new configuration.

## Environment
We're using karma, jasmine, and karma-jasmine to run tests.

**Comment by nasvillanueva** [comment]
karma-runner/karma-jasmine#221

**Comment by cenfun** [comment]
same issue here
{
    "message": "TypeError: this.deprecated is not a function\n    at Env.throwOnExpectationFailure (C:/Projects/horseshoe-cli/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1079:12)\n    at setOption (C:/Projects/horseshoe-cli/node_modules/karma-jasmine/lib/adapter.js:354:7)\n    at ContextKarma.start (C:/Projects/horseshoe-cli/node_modules/karma-jasmine/lib/adapter.js:343:5)\n    at ContextKarma.loaded (http://localhost:9890/context.js:168:14)\n    at http://localhost:9890/context.html:167:22",
    "str": "TypeError: this.deprecated is not a function\n    at Env.throwOnExpectationFailure (C:/Projects/horseshoe-cli/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1079:12)\n    at setOption (C:/Projects/horseshoe-cli/node_modules/karma-jasmine/lib/adapter.js:354:7)\n    at ContextKarma.start (C:/Projects/horseshoe-cli/node_modules/karma-jasmine/lib/adapter.js:343:5)\n    at ContextKarma.loaded (http://localhost:9890/context.js:168:14)\n    at http://localhost:9890/context.html:167:22"
  }

**Comment by slackersoft** [comment]
The old functions haven't been removed, only deprecated. It looks like the error is caused because the way that karma-jasmine is setting the configuration options is breaking the Jasmine environments link to its own `this` such that reporting the deprecation is failing. The purpose of this change was to explicitly leave the old configuration mechanism functioning, but reporting the deprecation for removal in the future. It looks like karma-jasmine is relying on the happenstance of the functions previously only using closure scoping to set the options, but they now need to be called with an appropriate `this`.

Hope this helps.

**Comment by nasvillanueva** [comment]
Ah, that makes sense. I'll close this ticket then. Thank you.

**Comment by johnjbarton** [comment]
I know you can't do anything about this now, so this is just feedback for the future. 

Adding the new configure() API at 3.3 and simultaneously adding deprecation messages is very unpleasant for downstream apps like karma-jasmine.  We can't use the new API because we need to support 3.x including 3.2; we don't want the deprecation messages because users will complain; we don't want to support both because we already have limited resources.   So in effect this becomes a breaking API change for us.

**Comment by slackersoft** [comment]
@johnjbarton sorry about this. I'm not sure what the fully correct answer here is. I added the deprecation warnings to give as much lead time for fixing them before things _actually_ break and the methods are removed, and I know I'll forget to do it later if I wait a release or two.
