### ISSUE TITLE
Add warning and resolution for OOM by result tracking

### ISSUE THREAD

**Issue by DirkToewe** [jasmine/jasmine#1631]
Let's look at the following spec:

```js
const spec = it('should not run out of memory',
  () => new Promise( (resolve,reject) => {
    let i=0
  
    setInterval( () => { // <- keep test from freezing up
      const t0 = performance.now()
      do {
        if( 0 === i%1e6 )
          console.log( i.toString().padStart(12) )
        expect(i).toBeGreaterThan(-1)
        ++i
      }
      while( (performance.now() - t0) < 500 )
    }, 0)
  }
))
```

The spec is asynchronous merely to prevent the browser from freezing up using `karma-jasmine`. The stopping condition was removed to simplify the example. Note that You are going to have to increase the timeout durations to reproduce the results.

You - as developers and/or seasoned users of Jasmine - may already know what happens when this spec is executed: Chrome runs out of memory at around 2gb at <b>i = 31*10<sup>6</sup></b>, the browser tab crashes and the test fails silently, i.e. no warnings or errors are logged to the console.

The cause for the memory "leak" is likely that Jasmine creates a result object for every single expectation that passed. This hypothesis is based on the fact that monkey-patching `Spec::addExpectationResult` fixes the memory "leak":

```js
spec.addExpectationResult = (pass, ...args) => {
  if( ! pass )
    Object.getPrototypeOf(spec).addExpectationResult.call(spec, pass, ...args)
}
```

For someone like me, who's new to Jasmine however, this memory "leak" is terribly confusing. I realize that this is not an actual leak since keeping track of passed results is intended. The out-of-memory error _without feedback_ however is likely not intentional.

Which brings me to the following suggestions:
  1. Could a warning be emitted when `Spec::result.passedExpectations` exceeds a threshold, say <b>10<sup>6</sup></b>?
  2. Ideally said warning would point to a setting that allows one to drop passed expectations from the spec. In my experiments, specs ran just fine with the monkey patch above.

#### Environment
Involved:
  * node@v10.14.1
  * karma-jasmine@2.0.1
  * jasmine-core@3.3.0

Likely not involved:
  * karma-webpack@3.0.5
  * karma-spec-reporter@0.0.32
  * karma-chrome-launcher@2.2.0

OS: Ubuntu 18.04 64x
Browser: Chrome 71.0.3578

**Comment by slackersoft** [comment]
I think that getting a check like this truly correct is going to be a bit of a challenge. If you really want a message just _before_ Jasmine uses up all of your memory (even if only looking at `passedExpectations`), you'll need to check across all specs and suites being run, and not just the length of the array on the current spec.

That said, I would be happy to review a pull request to add an option to not save the actual passed expectations. Turning this option on should not impact the display of the "Has no expectations" message in the HtmlReporter, so I would expect the `result` object to have at least a simple count instead of an array.

**Comment by DirkToewe** [comment]
Thank You for the response @slackersoft. The warning would not have to be exact science. My idea was rather that there is some threshold for the number of `passedExpectations` beyond which a warning might be in order, along the lines of "There is an unusually large number of passed expectations. Too many expectations might cause Browsers to crash (silently)."

When it comes filing a PR, I sadly don't feel up for the task. There's only roughly 6 months of JS experience under my belt and the JS way/kind of programming is quite different from what I'm used to. In addition to that jasmine is an intricate project with plugins relying on it. My fingers are crossed that somebody else might be willing to work on this.

**Comment by slackersoft** [comment]
The issue I'm most worried about is tracking the `passedExpectations` across all Specs and Suites since these are currently saved as a single array for each. This would mean a separate set of bookkeeping to know how many `passedExpectations` have been saved across the entire Jasmine suite, or a limit per Suite/Spec.
