### ISSUE TITLE
Feature request: Include (custom) expectation message in both passed and failed expectations

### ISSUE THREAD

**Issue by GCHQDeveloper911** [jasmine/jasmine#1634]
I appreciate this is something of a duplicate of #1127, but the response there of "Jasmine doesn't expect you to really print messages for expectations that were met" doesn't really help.

I'm guessing that many users like me will have tests that produce multiple expectations. Some might argue this is not good practice - and they may have a point - but the fact is, that's what many people will do. Furthermore, sometimes these varied expectations can include somewhat "dynamically" generated actual / expected values - it would be massively beneficial to be able to see the actual values used in the successfully executed expectation. 

Beyond this, it would be useful to have a custom message for reporting purposes. A stream of "Passed. Passed. Passed. Passed." is meaningless to interested parties. Something that says "Passed - found 3 doughnuts left after having 4 before that, because we ate one" would be far more useful / meaningful.

Clearly a number of users have looked into what would be required to support this sort of thing. Can we revisit this as an idea? If someone submitted a PR that offered it, would the PR immediately be rejected?

**Comment by slackersoft** [comment]
See [my comment](https://github.com/jasmine/jasmine/issues/971#issuecomment-156576842) in the #971 (referenced from #1127) about some of the difficulties related to this. The main issue is that a given matcher doesn't know whether the user has inserted `.not` into the call chain, and as such is unable to provide the message you suggest. There are also some memory usage concerns around passed expectations and how much memory they should be expected to take up from other members of the community, so I'm hesitant about adding more information back into these.

Hope this helps. Thanks for using Jasmine!

**Comment by GCHQDeveloper911** [comment]
I've made a few simple changes to improve the reporting - I don't believe there will be any impact on memory usage - with your approval I'll submit a PR and let you take a look. I've not done anything earth shattering(!), but hopefully something that you and others would agree makes sense / could prove beneficial. FWIW, We're using webdriverio, and I'm going to be submitting a PR there for some similar changes, but there is (unless I'm very much mistaken!) no interdependency between my changes there, and here.

**Comment by slackersoft** [comment]
If you want to report additional context around an expectation, you should also take a look at the new [`withContext`](https://jasmine.github.io/api/edge/matchers#withContext) matcher helper. Additionally, Jasmine doesn't report (and doesn't expect you to report) on expectations that were successful. This includes expectations that use `.not` in them.

Additionally, the more data stored in the result object for a spec and suite the more quickly Jasmine's memory usage goes up in larger suite, which then causes them to execute slower. The main reason passed expectations are reported at all was to allow users to see if they accidentally had a spec without any expectations at all, and the nicest internal architecture for that was to provide the passed expectations along with the failed.

**Comment by slackersoft** [comment]
My biggest concern around actually showing a message for an expectation that is successful is what the messages _should_ look like in that case. Remember that a given matcher doesn't necessarily know whether it was invoke with `.not`, so it should always provide an error message that would be correct assuming that the current state is failing and that Jasmine will do the correct thing based on the outer context.

An example might help.

```
expect(1).toBe(1);
```

If the `toBe` matcher provided its own `message` in this case it would read `expected 1 not to be 1`, because that is what would need to be reported for `expect(1).not.toBe(1)`.

```
expect(1).not.toBe(2);
```

The message here is `expected 1 to be 2`, because that is what would be reported for `expect(1).toBe(2)`

Jasmine changes these both to read "passed" because otherwise the message indicates a comparison that was not actually done.

**Comment by GCHQDeveloper911** [comment]
I appreciate the concern over a "misleading" pass report - indeed I encountered this problem when I first tried reporting passed expectations in more detail. However, either I am misunderstanding the context / scope, or perhaps toEqual and toBe are just lucky examples, however, with my locally modified jasmine-core, I have tried toEqual and toBe, even using withContext, and got:

test snippet:
'''
        expect(0).withContext('blah a').toBe(0);
        expect(1).withContext('blah b').not.toBe(1);
        expect(2).withContext('blah c').toBe(0);
        expect(3).withContext('blah d').not.toBe(0);
'''

results snippet:
'''
[chrome #0-0] blah b: Expected 1 not to be 1.
[chrome #0-0] Error: blah b: Expected 1 not to be 1.
[chrome #0-0]     at <Jasmine>
[chrome #0-0]     at <Jasmine>
[chrome #0-0]     at UserContext.it (/home/user/WDIO/test.js:20:45)
[chrome #0-0] blah c: Expected 2 to be 0.
[chrome #0-0] Error: blah c: Expected 2 to be 0.
[chrome #0-0]     at <Jasmine>
[chrome #0-0]     at <Jasmine>
[chrome #0-0]     at UserContext.it (/home/user/WDIO/test.js:21:41)
[chrome #0-0] Passed: blah a: Expected 0 to be 0.
[chrome #0-0] Passed: blah d: Expected 3 not to be 0.
[chrome #0-0]
'''

The expectation statement, with and without 'not' is the same for both 'toBe', and 'toEqual', with or without a 'withContext'. 

Or do I need to try other comparators that might not work so well? Or have I missed your point completely?!

**Comment by slackersoft** [comment]
You are correct that the actual version of `toBe` doesn't actually have this problem because it doesn't provide its own `message`, but relies on higher level Jasmine context to provide the message (which includes whether `.not` was used). I used `toBe` in my example because the failure mode is easier to demonstrate, we all know what the message should look like for `toBe`. The concept here is really that if the matcher does its own work to provide an error message, Jasmine expects it to be correct for if the current state is a failure.

Sorry for the confusion from the example.

**Comment by sgravrock** [comment]
Closing since I don't see how we can make this work without a pretty major breaking change to custom matchers. At this point in Jasmine's evolution I don't think that would be wise.

Folks who want this feature so that they can see what values were used in passing assertions prior to a failure might find the [debug logging feature](https://jasmine.github.io/api/4.5/jasmine.html#.debugLog) useful.
