### ISSUE TITLE
Report duration of each spec

### ISSUE THREAD

**Issue by johnjbarton** [jasmine/jasmine#1646]
In larger test suites or systems, test time becomes an issue. Understanding whether the issue is say lots of time in one test or too many tests, a record of the duration of each test would be very helpful.

## Expected Behavior
The test report includes `testDuration` for each spec.

## Current Behavior
No duration report.

## Possible Solution
Just before execution it(), store `performance.now()`.
Just after, compute the delta between the `performance.now()` and the stored value.
Add the result to the specDone reporter callback result as `testDuration`

**Comment by slackersoft** [comment]
It would be nice to be able to get timing output for specs. Jasmine's current reporters only do timing calculations on the entire suite (and not with `performance.now` because of browser compatibility). I would be happy to review a pull request that updated [`Timer`](https://github.com/jasmine/jasmine/blob/master/src/core/Timer.js) and [`HtmlReporter`](https://github.com/jasmine/jasmine/blob/master/src/html/HtmlReporter.js) to support and show timing information for each spec, as long as this doesn't break the `Timer` interface. The [`ConsoleReporter`](https://github.com/jasmine/jasmine-npm/blob/master/lib/reporters/console_reporter.js) in jasmine-npm should also be able to be updated in the future.

I would also be happy to see the `Timer` use `performance.now()` where it is available, either as part of the same PR, or standalone.

**Comment by johnjbarton** [comment]
> Jasmine's current reporters only do timing calculations on the entire suite

As far as I can tell, the current reporters only report the time for the overall jasmine run (all suites).

I see now that each reporter could be updated to start/stop a timer on the specStarted/specDone.

I was thinking more along the lines of measuring the duration in jasmine and adding the value to the `result`. Each reporter needs a bit more display logic, but they share the duration calculation.  WDYT?

**Comment by slackersoft** [comment]
Moving the timing calculation into the actual execution of Jasmine is definitely a bigger task, which is really the main reason to look at leaving it in the reporters for now. I'm also wary of having the core of Jasmine managing too many things, but I agree that putting timings on the result makes it easier for other reporters and things to use that information without having to calculate it themselves.

**Comment by wood1986** [comment]
#1657
