### ISSUE TITLE
Getting the current test name in jasmine

### ISSUE THREAD

**Issue by karanjitsingh** [jasmine/jasmine#1647]
as of jasmine 2.0 `jasmine.getEnv().currentSpec` no longer works, is there any way of getting the test name without doing 

```javascript
var spec = it('test', function()  {
    //
});
```

**Comment by slackersoft** [comment]
This functionality was explicitly removed in 2.0. You can see a bit more discussion in #611. The Jasmine teams opinion has been that there shouldn't be logic in your spec itself (including `beforeEach` and `afterEach`) that depends on the actual name of the spec being executed. Generally your specs will be more reproducible and less dependent on each other if you fully recreate the world for them (or share the world explicitly with `beforeAll` and `afterAll`), than by trying to name particular global scope things to the particular test being executed.

**Comment by karanjitsingh** [comment]
Thanks

**Comment by dmrickey** [comment]
Garbage answer. Sometimes the test currently being executed is needed to debug things on a global scope. Not everyone writes good tests. And tests can still pass while logging errors. If someone writes a poor test, if this existed, I could just put a breakpoint in the global error handler and take a look at which test is current. Now I have to come up with another solution. And no, the test isn't in the current call stack because of a myriad of other reasons.
