### ISSUE TITLE
spyOn() breaks Jasmine with when returning rejected Promise

### ISSUE THREAD

**Issue by pe8ter** [jasmine/jasmine#1648]
When using this pattern in a spec

```javascript
spyOn(foo, 'bar').and.returnValue(Promise.reject('NO!'));
```

the entire test run fails even if the spied function never gets called.

This is similar to https://github.com/jasmine/jasmine/issues/1590, but different enough that I thought it warranted a separate item (in my case my spy creates correctly). Feel free to close this if you think it is too similar.

## Expected Behavior
The test run should pass because both the spec and tested code do not actually throw any exceptions or await on rejected Promises.

## Current Behavior
The spec succeeds but the test run fails (the Node.js process exits with code 1). When I use jasmine-console-reporter module it reports `An error was thrown in an afterAll`.

## Suite that reproduces the behavior

Here is the complete test file. Notice that the spied function is in a branch that cannot get called: 

```javascript
const foo = {
    bar: async () => 0
}

const baz = {
    quux: async () => {
        if (false) {
            await foo.bar();
        }
    }
};

describe('some suite', () => {
    it('some spec', async () => {
        const spy = spyOn(foo, 'bar').and.returnValue(Promise.reject('NO!'));
        await baz.quux();
        expect(spy).not.toHaveBeenCalled();
    });
});
```

## Context
We have a test where we need to verify that one code path isn't taken given some conditions. To make the test fail in a controlled manner, we added a spy with this rejected Promise pattern if the tests hits this undesired code path.

## Your Environment

* jasmine: **v3.3.1**
* jasmine-core: **v3.3.0**
* Environment: **Node.js v8.15.0**
* OS: **macOS Mojave, Version 10.14.3 18D42**

**Comment by sgravrock** [comment]
Simply creating a rejected promise is enough to trigger Node's unhandled rejection event if the rejection is never handled, even if you don't do anything with the promise. Jasmine then turns the unhandled rejection into a failure, because unhandled rejections *almost* always indicate that something went wrong with the test or the code under test. You can see that more clearly with this stripped-down test, which produces the same failure:

```
it('fails', () => {
    Promise.reject('NO!');
});
```

If I understand your use case correctly, you don't want the unhandled promise to cause a failure unless `foo.bar` is called. There are a couple of ways to do that. I think the cleanest is to create the promise only if the function is called:

```
it('some spec', async () => {
    const spy = spyOn(foo, 'bar').and.callFake(() => Promise.reject('NO!'));
    await baz.quux();
    expect(spy).not.toHaveBeenCalled();
});
```

Another approach is to explicitly handle the failure by `await` ing the promise inside a `try` block in the test, but that's messier and more verbose.

**Comment by pe8ter** [comment]
> Simply creating a rejected promise is enough to trigger Node's unhandled rejection event if the rejection is never handled, even if you don't do anything with the promise

Wow, TIL. I wonder if there's a way for Jasmine to capture this and report the spec as failed, as opposed to passing the spec and failing the whole test run.

This is turned into more of a support item than a bug report. Thanks for taking the time.

**Comment by pe8ter** [comment]
Closing because my original concern was addressed.

Thanks again!
