### ISSUE TITLE
[Feature] Use "skip" / "todo"

### ISSUE THREAD

**Issue by dominique-mueller** [jasmine/jasmine#1650]
Jest 24 introduced the possibility to mark tests as "todo" / "to be skipped" (see https://github.com/facebook/jest/issues/1605). This is very helpful in situations where
- a test is to be fixed later on
- when laying out all test cases before actually implementing them

I'd love to see such a functionality in Jasmine as well!

**Comment by slackersoft** [comment]
Jasmine currently supports [`xit`](https://jasmine.github.io/api/edge/global.html#xit) to stop the spec from running at all. You can also call [`it`](https://jasmine.github.io/api/edge/global.html#it) without providing a callback to layout tests before implementing them. I believe this is basically the functionality you're looking for, but I'm happy to discuss interface changes for this existing functionality.

Hope this helps. Thanks for using Jasmine!

**Comment by sgravrock** [comment]
I'm going to to ahead and close this, since we think that existing functionality will meet your needs and we haven't heard anything in quite some time. Feel free to reopen and provide more information if you disagree.

**Comment by Elias-Graf** [comment]
Is it possible to "forward" bindings? I landed here because I was looking for this. E.g. I want to expose the `(click)` attribute of the "main" button inside the component. And I thought: "Hey, why not expose every attribute of the button".

In React you can do something like that, see the following code:

```tsx
export interface CustomButtonProps
  extends React.DetailedHTMLProps<
    React.ButtonHTMLAttributes<HTMLButtonElement>,
    HTMLButtonElement
  > {
  bg: string;
}

export function CustomButton(props: CustomButtonProps) {
  const { bg } = props;

  return <button style={{ backgroundColor: bg }} {...props}></button>;
}
```

Yes the extended type is a bit ugly, but that might be because I lack the knowledge of the name of the actual button props.
