### ISSUE TITLE
Content Security Policy eval restriction incompatibility in j$.isError_

### ISSUE THREAD

**Issue by kpreid** [jasmine/jasmine#1653]
I attempted to update my project from using Jasmine v2.5.2 to v3.3.0, and found that test execution would stop with this error in the console:

`EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' 'unsafe-inline'".`

Investigating, commit 46cc48ccfa27ebfdc92fcdf865d81bf1af1f37aa introduced `j$.isError_` which does

    if (value && value.constructor && value.constructor.constructor &&
      (value instanceof (value.constructor.constructor('return this')()).Error)) {
      ...

which is a form of string eval in disguise.

Based on issue #1325's resolution, I assume that Jasmine is intended to be able to run under an `unsafe-eval`-restricting Content Security Policy, and so I request that this code be modified to not use eval, or to fall back to returning false if the eval fails.

**Comment by slackersoft** [comment]
I would be happy to review a pull request that allows the same level of `Error` detection while allowing the code to be run with in this type of context. Note that the thing this code is doing is finding the actual `Error` constructor from whichever context the value object came from. This is primarily useful in the `toThrowError` matcher when the Error might have come from an `iframe` or other global.

**Comment by elliot-nelson** [comment]
A possible solution would be to catch EvalError around this check for Error inheritance in window/iframe, and assume false.  I'd imagine this is not a common situation and at least the test won't be blowing up.

An alternative would be to see if we really need to be this careful.  Looking at existing internal uses of `.isError()`, I don't think a strict Error is necessary - for example, we could take "duck-typed" definition of "if it's got a .constructor that is a function, a .message that is a string, and a .stack that is a string, it's an Error".  This allows user created fake errors but I don't know if that matters.

**Comment by slackersoft** [comment]
We shouldn't relax the constraint around being an actual `Error` for everyone because a certain setup doesn't let Jasmine check properly. Catching a thrown `Error` and returning false seems fine for now for a CSP, but it might be nice to evaluate another way to get the relevant global object for the object we're checking to be an `Error`.

**Comment by elliot-nelson** [comment]
Thanks for pointing me at the original PR!  Good to have context.

In my opinion, there "shouldn't" be a way to get ahold of a global object from another context without a CSP.  If I could find one, I'd consider it potentially temporary (likely to be closed in one or more browsers in the future).  But I guess it's worth looking around.

I'll offer a (more reliable?) alternate duck typing approach, just so it's out there: maybe instead of allowing a duck-typed instance, we allow a duck-typed constructor.  That is:

    value instanceof Error || (value.constructor && value.constructor.captureStackTrace && value.constructor.stackTraceLimit)

I'm pushing back only because I don't think the phrase "is an actual Error" really means anything in JavaScript.  Even if we allow no duck-typing, any instanceof check can be fooled with:

    var object = new Date();
    object.__proto__ = Error.prototype;
    console.log(object instanceof Error);   // => true

So, given that any user can fool the check at will if they _want_ to, our only real obligation in this check is to make sure the user won't fool it by accident.

**Comment by slackersoft** [comment]
It doesn't look like `captureStackTrace` or `stackTraceLimit` are supported by Firefox and possibly other browsers as well, so it doesn't seem like that check would work consistently across all environments.

I don't think your example of "fooling" `instanceof` is exactly correct. What you've done is write some Javascript to set the prototype of your object, thus turning it into an `instanceof` Error. Remember that Javascript has prototypal inheritance and not class based inheritance.

**Comment by sgravrock** [comment]
This should be fixed in 3.9 for Chromium-based browsers and in 4.0 for all others. (Release date TBD for both of those.) Given the gradual demise of browsers that don't always set the `stack` and `message` and the fact that false positives (but not false negatives) from `isError_` are mostly harmless, we're able to be a bit less strict about things and move away from the `eval`-based approach. See #1910 for details.
