### ISSUE TITLE
Implement a way to add a timeout for a specific describe block

### ISSUE THREAD

**Issue by maximedupre** [jasmine/jasmine#1668]
## Expected Behavior
    // Default timeout for all specs becomes 20000. 
    const TIMEOUT = 20000;

    describe('...', () => { ... }, TIMEOUT);

## Current Behavior
    describe('...', () => {
        // Timeout needs to be added for all the individidual tests
        const TIMEOUT = 20000;

        it('should do A', () => { ... }, TIMEOUT)
        it('should do B', () => { ... }, TIMEOUT) 
        it('should do C', () => { ... }, TIMEOUT) 
    });

## Context
To avoid duplication

**Comment by slackersoft** [comment]
You should be able to accomplish something like this now by setting the `jasmine.DEFAULT_TIMEOUT_INTERVAL` in a `beforeAll` (and `afterAll` to revert). I like the idea of some kind of option like you suggest, but I think this syntax could be confusing because it is _so_ similar to the `it` syntax but works differently.

If the `beforeAll`/`afterAll` workaround seems insufficient, I would be happy to review a pull request to add an `options` argument to `describe` that could take an option to set the default timeout for all children.

Hope this helps. Thanks for using Jasmine!
