### ISSUE TITLE
Question: is it possible to not have fdescribe/fit cause jasmine to exit with a non zero exit code?

### ISSUE THREAD

**Issue by silkentrance** [jasmine/jasmine#1670]
As of now, I will have to use

```
./node_modules/.bin/jasmine --config=./jasmine.json test/*spec.js || exit 0
```

which is a working work around, however, I'd rather would like to use a configuration that states that focused tests are fine and must not cause the build to fail, e.g.

```
{
  "failOnFocusedTests": false
}
```

with focused suites this is different, as this will cause all the other suites from being skipped/not run, but within a single suite, aka "describe", these focused tests should not cause the build to fail.

**Comment by slackersoft** [comment]
Can you give me an example of the deprecation message you're seeing. From my quick search through the codebase there shouldn't be any message about deprecated functionality around `fit`/`fdescribe`. The various libraries that execute your Jasmine suite should be printing out something like `Incomplete: fit() or fdescribe() was found`. This is to help catch issues where someone might have accidentally committed a focused spec or suite which would disable anything not in an `fit` or `fdescribe` from running.

Because focused specs/suites are usually used while debugging an issue locally, and because they have the potential to turn off the entire suite except for one test, Jasmine reports a non-`0` exit code to specifically to cause CI systems to note the failure. Jasmine generally attempts to err on the side of reporting a potential error in your suite instead of allowing it to pass when you might not expect it to. Because of this, I'd like to hear a bit more about the use case for allowing a suite with focused specs and suite to succeed.

Hope this helps. Thanks for using Jasmine!

**Comment by silkentrance** [comment]
Oh, I just updated jasmine, and there is no longer a deprecation warning, instead the following message is printed:

Incomplete: fit() or fdescribe() was found

and the tests are exited with a non zero exit code

**Comment by silkentrance** [comment]
I have changed the title.

**Comment by slackersoft** [comment]
I would still like to hear more about _why_ you would like to allow Jasmine to exit cleanly when (potentially) most of your suite has not been run. This behavior was very intentionally added in 3.x in order to help users find times when they had accidentally commited their suite with an `fit` or `fdescribe` and inadvertently disabled the rest of their specs.

**Comment by silkentrance** [comment]
Over at testdeck https://github.com/testdeck/testdeck/issues/180 we are currently working on an integration for jasmine.

While everything is working so far, we need to show that all of the features are working and we would like to do that in process rather than in separate processes.

While the latter works, I would prefer the in process solution as it is much faster, similarly to what we did with the integration for jest.

**Comment by slackersoft** [comment]
Assuming you are programmatically creating a Jasmine object from the wrapper package (just jasmine on npm, not jasmine-core), you should be able to pass a handler to `onComplete` to override the default exit code setting. The callback will receive a boolean value indicating whether the suite as a whole was successful. (Note that the `exitCode = 4` behavior for a suite that calls `process.exit` before it has completed is not currently overridable)

Hope this helps.

**Comment by silkentrance** [comment]
@slackersoft Thank you very much for the information. I will look into this once we have the new testdeck up and running. Closing.

**Comment by djungowski** [comment]
I agree, that it would be nice to be able to disable it - at least temporarily
Use-case: If you're running the tests using a filewatcher, it's rather annoying that the tests officially fail each time when you have them run when debugging an old or writing a new test suite
