### ISSUE TITLE
SpyObj and returnValue TypeError on version 3.4.0

### ISSUE THREAD

**Issue by Vibrat** [jasmine/jasmine#1675]
## Are you creating an issue in the correct repository?

jasmine.SpyObj -> and.returnValue(val: void) which invokes TypeError. The expected behavior is `returnValue(val: any)` so that it can return value for mockup method or object. 

**Jasmine Version: 3.4.0**

## Expected Behavior

```javascript
jasmine.SpyObj -> and.returnValue(val: any);
```

## Current Behavior

```javascript
jasmine.SpyObj -> and.returnValue(val: void);
```

## Suite that reproduces the behavior (for bugs)

```javascript

 it("Should DataEditorService works correctly with method init and update", () => {
    // mock dataService method
    let testData = { name: "hello" };
    dataServiceSpy.init.and.returnValue(testData);
});

```

## Your Environment

* Version used: 3.4.0 (previous version 3.3.0 works fine)
* Environment name and version (e.g. Chrome 39, node.js 5.4): Windows 10 
* Operating System and version (desktop or mobile): Desktop

**Comment by slackersoft** [comment]
The behavior for `returnValue` hasn't changed in quite some time, and definitely not in the 3.4 release. Additionally, it looks like your problem is possibly mostly with the typings for Jasmine which are provided by [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine) and not Jasmine itself.

If you have any additional information on where exactly you're seeing the error, that would also help me investigate.

Hope this helps. Thanks for using Jasmine!

**Comment by sgravrock** [comment]
We haven't heard anything new about this issue in quite some time, and it appears not to be an issue with Jasmine itself, so I'm going to go ahead and close it. I suggest opening an issue at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine) if you're still having trouble.
