### ISSUE TITLE
spyOnAllFunctions is not spying on any function.

### ISSUE THREAD

**Issue by mdarefull** [jasmine/jasmine#1677]
I'm using ngxs in angular and I'd like to create a spy of the whole store.
For that, I try:
`spyOnAllFunctions(storeSpy)`

But it doesn't seem to be working.
This is the class I'm trying to spy on:
https://github.com/ngxs/store/blob/master/packages/store/src/store.ts

By debugging into the 'spyOnAllFunctions', I get into this method:
```
this.spyOnAllFunctions = function(obj) {
...
 for (var prop in obj) {
   if (Object.prototype.hasOwnProperty.call(obj, prop) && obj[prop] instanceof Function) {
     var descriptor = Object.getOwnPropertyDescriptor(obj, prop);
     if ((descriptor.writable || descriptor.set) && descriptor.configurable) {
       this.spyOn(obj, prop);
     }
   }
 }
...
};
```

and I verify that the first part of the first if is returning false for each of the Store methods (dispatch, reset, select, ...)

## Expected Behavior
I would expect the spyOnAllFunctions to be equivalent to calling:
`jasmine.createSpyObj<Store>(['dispatch', 'select', ...]); `
by passing every method.
Is there something I'm missing here?

## Current Behavior
spyOnAllFunctions returns the same passed object and using 'and' on any of the methods, results in undefined:
`storeSpy.reset.and.callThrough();`

**Comment by slackersoft** [comment]
The current `spyOnAllFunctions` behavior looks like it is only looking for functions that are directly on the object (not inherited from the prototype). See #1421 and #1581. Since the store you're using is a `class` the compiled javascript will have those functions be on the prototype and thus `hasOwnProperty` will return false. Theoretically if you pass in `Store.prototype` to `spyOnAllFunctions` you'll get the prototype back with all functions spied upon, however they will be spies for all instances of the `Store` not just the one you have a reference to locally.

I would be happy to review a pull request to create a spy object from a prototype which would probably accomplish what you're looking for here. I envision usage should look something like (open to better naming):

```javascript
var myMock = createSpyObjectFromPrototype(MyConstructor.prototype);
```

Hope this helps. Thanks for using Jasmine!

**Comment by elliot-nelson** [comment]
A thought:

Let's say I have an object created by an external API -- like `const s3 = new AWS.S3()`, as an example.  This thing has a mix of inherited prototype methods, specifically-created and bound functions, and various other properties.  What I want is to spy on anything looking like a function with one command.

The `createSpyObjectFromPrototype` method you describe doesn't really work, because `createSpyObjectFromPrototype(AWS.S3.prototype)` won't actually look like the complex object created by the real constructor.

My suggestion would be to enhance `spyOnAllFunctions` so that it starts with the passed object, and then recursively walks up `Object.getPrototypeOf(object)`, gathering all property names that meet the `hasOwnProperty && descriptor.writable` checks at each level.  Stop once you reach `undefined` or `Object.prototype` (don't spy on methods in `Object.prototype`).  Once you have all the properties, then spy on them all on the passed object.

I think this gives the user what they want 99% of the time (but I might be missing a bad corner case).

**Comment by slackersoft** [comment]
That seems reasonable, and I can't think of a use-case where walking the prototype chain might break an existing test.

**Comment by elliot-nelson** [comment]
I am working up a PR for this and expect to have it up before Tuesday, May 14.
