### ISSUE TITLE
toEqual() not show expectationFailOutput in console log

### ISSUE THREAD

**Issue by rebajz** [jasmine/jasmine#1682]
fit('some text', async() => {
        let components = element.all(by.xpath('//button'));

        await browser.get('http://localhost:3339/buttonpage');
        expect(await components.count()).toEqual((19), 'some text for fail ' + await components.count());
    });

in console is visible only:
- Expected 20 to equal 19.

for example toBe() show correctly fail message

**Comment by tymfear** [comment]
@rebajz you should use the `withContext` method:
```javascript
await browser.get('http://localhost:3339/buttonpage');
expect(await components.count())
.withContext('some text for fail ' + await components.count())
.toEqual(19);
```

Failure output is not supported for toEqual method. Please see [docs](https://jasmine.github.io/api/3.3/matchers.html).

**Comment by slackersoft** [comment]
In fact, none of Jasmine's matchers officially support the extra argument (`expectationFailOutput` in [community types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine/index.d.ts#L467)), but many of them happen to also print that out because of the laxness of how default failure messages are generated.

Closing this.
