### ISSUE TITLE
Arraybuffer does not work correctly with toEqual

### ISSUE THREAD

**Issue by dankurka** [jasmine/jasmine#1687]
## Expected Behavior
Two arraybuffers are compared with their content in jasmine

## Current Behavior
Two different ArrayBuffers with different values but same length compare equal in jasmine.

Example passes even though it should not:
```javascript
describe('Arraybuffer', () => {
  it('equal different Arraybber', () => {
    const buffer1 = new ArrayBuffer(4);
    const buffer2 = new ArrayBuffer(4);
    const array = new Uint8Array(buffer1);
    array[0] = 1;
    expect(buffer1).toEqual(buffer2);
  });
});
```

**Comment by slackersoft** [comment]
It looks like `ArrayBuffer` by itself doesn't really have enough information to do the comparison with the object directly. I'm also not totally sure it makes sense to compare them directly, because there isn't even a really good way to know what types of data are being stored. A poor comparison could potentially cause equality where it wasn't expected.

There are two things you should be able to do in the mean time to get correct comparisons based on the values:

1. Convert both sides of  the check to a typed array like `Uint8Array`
1. Provide your own [custom equality tester](https://jasmine.github.io/tutorials/custom_equality) for `ArrayBuffer`.

I would also be happy to review a pull request to add support in Jasmine itself. I would expect to probably use [`DataView`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView) to retrieve values of unknown types. This would also lead to direct support of `DataView` in comparisons as well.

Hope this helps. Thanks for using Jasmine!

**Comment by dankurka** [comment]
Hi Gregg,

thanks for taking a look. Indeed I was supplying my own custom equality tester that compares the buffers by comparing them as Uint8Arrays, but ensuring that its installed in all tests is error prone and relies on code reviews.

Let me send a patch to jasmine to address this properly.

**Comment by dankurka** [comment]
Would you mind taking a look at the pull request. I am unsure on how we are going to handle calling the Uint8Array ctor.

**Comment by slackersoft** [comment]
> but ensuring that its installed in all tests is error prone and relies on code reviews.

You should be able to provide the custom equality tester in a global `beforeEach` outside of any `describe` calls and have it apply to all of your specs. If that isn't working, I would definitely like to fix that.
