### ISSUE TITLE
CONTRIBUTING Guide is obsolete?

### ISSUE THREAD

**Issue by elliot-nelson** [jasmine/jasmine#1702]
The CONTRIBUTING guide still refers to ruby gem installs, running `rake jasmine`, etc.  I think this is obsolete (not sure about the VirtualBox stuff though).

## Expected Behavior
Contributing guide describes how to set up nodejs environment, how to get the various WebDriver launchers (Chrome, Firefox, Safari, PhantomJS, etc.), and how to run unit tests in each browser and nodejs.

Also, at least a vague list of what is tested in the _CI build_ (travis) might be helpful -- like, what browser and version targets should be hit for a change to jasmine to be considered successful?  Also, the USE_SAUCE stuff is a little confusing -- often in branch builds none of that stuff runs at all.  Is this on purpose or a mistake?

## Current Behavior
No mention of webdriver/launcher installs or configuration.

**Comment by slackersoft** [comment]
Thanks for the heads up. The ruby stuff should still work, it just isn't the only way to accomplish the browser tests anymore. The CI build is a bit complex because all of the SauceLabs configuration is in secret variables on Travis, so they aren't available to malicious Pull Requests. In order to still show a "green" build for PRs, we silently skip the builds that would otherwise run with SauceLabs.

If you have any other details you'd like to see in there, I'm happy to take a look at a pull request or see some specifics in this issue.
