### ISSUE TITLE
Browser error handling loses information.

### ISSUE THREAD

**Issue by johnjbarton** [jasmine/jasmine#1728]
The browser onerror handler has multiple arguments:
```js
window.onerror = function(message, source, lineno, colno, error) { ... }
```
But jasmine seems to defeat the feature by only passing a single argument 
```js
QueueRunner.prototype.execute = function() {
    var self = this;
    this.handleFinalError = function(error) {
      self.onException(error);
    };
    this.globalErrors.pushListener(this.handleFinalError);
    this.run(0);
  };
```

Then only the last handler is used:
```js
    var onerror = function onerror() {
      var handler = handlers[handlers.length - 1];

      if (handler) {
        handler.apply(null, Array.prototype.slice.call(arguments, 0));
      } else {
        throw arguments[0];
      }
    };
```

How can we get the full stack?

**Comment by prantlf** [comment]
This affects errors thrown from asynchronous functions. They never include the stacktrace.

I created a [minimum project `bug-jasmine-no-async-stacktrace`](https://github.com/prantlf/bug-jasmine-no-async-stacktrace) reproducing this issue.

This is an example of arguments passed to `window.onerror` in Chrome. Instead of the first string, the last `Error` instance should be used:

    arguments: Arguments
      0: "Error: Crashing..."
      1: "http://localhost:9876/base/test-jasmine/index.test.js"
      2: 4
      3: 9
      4: Error
        columnNumber: 9
        fileName: "http://localhost:9876/base/test-jasmine/index.test.js"
        lineNumber: 4
        message: "Crashing..."
        stack: "crash@http://localhost:9876/base/test-jasmine/index.test.js:4:9
                @http://localhost:9876/base/test-jasmine/index.test.js:37:7"
