### ISSUE TITLE
Expectation when using both done and async functions?

### ISSUE THREAD

**Issue by jjoekoullas** [jasmine/jasmine#1731]
Hello,

I have a weird issue.  I have a test with a before each, which is an async function.  Inside that async function, is some asynchronous work that accepts a callback.  So, my beforeEach looks like `beforeEach(async function(done))`.

Strangely I have a test that is failing and when inserting some logging statements, I see the test is running before the beforeEach has completed.

What is the expectation for mixing async functions and the done parameter?  I'd expect the done parameter to supercede the completion of the promise returned by the function.

**Comment by sgravrock** [comment]
Jasmine doesn't support mixing callback-style and async/await in a single function. The basic expectation is that each asynchronous function will tell Jasmine that it's finished at most once. The code above tells Jasmine that it's done twice: once when the returned promise resolves, and once when the `done` callback is called. In that situation all bets are off, just like if a callback-based function called `done` multiple times. Jasmine makes some efforts to protect its internal state against corruption when an asynchronous function finishes multiple times but doesn't guarantee any particular behavior.

In practice, Jasmine is likely to consider the function done and move onto the next thing the first time it's told that the function is done. But that's liable to change in the future and shouldn't be relied on. (Also, it's easy for subtle changes in your code to change the order in which the two ways of indicating completion happen.)

I'm going to guess that you're mixing the two approaches because your function needs to call an `async` function in addition to the callback-based work that you mentioned. If that's the case, you could wrap the callback-based part in a promise:

```
beforeEach(async function() {
   const value = await someAsyncFunction();

   return new Promise(function (resolve, reject) {
      someCallbackThing(value, resolve);
   });
});
```

Or if you prefer to stick with callbacks:
```
beforeEach(function(done) {
   someAsyncFunction().then(
      function(value) {
         someCallbackThing(value, done);
      },
      function(err) {
         done.fail(err);
      }
   );
});
```

I hope that helps.

**Comment by jjoekoullas** [comment]
That seems an unnecessary restriction.  If, as a consumer, I accept a done parameter but happen to return a Promise - it seems reasonable to assume things are done when I call done - regardless of the completion of the promise.

That said, your suggestion of just turning the internal callback into a promise is a good one.
