### ISSUE TITLE
toHaveBeenCalledWith and asymmetric equality tester multiple arguments doesn't work

### ISSUE THREAD

**Issue by gizm0bill** [jasmine/jasmine#1739]
I expect when writing using an custom asymmetric equality tester to be able to test calls to functions with multiple arguments, but this fails as seen here:
https://codepen.io/gizm0bill/pen/PMpMZg (line 33)
Is this intended behaviour? Am I getting the functionality wrong?

**Comment by sgravrock** [comment]
The `toHaveBeenCalledWith` matcher compares each of its arguments against the corresponding argument from each actual call. So an expectation like this:

```
expect(customer.callNumber).toHaveBeenCalledWith(phoneNumberMatching('123-456-7890', '+1'));
```

means "Expect customer.callNumber to have been called with exactly one argument, which matches `phoneNumberMatching('123-456-7890', '+1')`". The expectation fails because `customer.callNumber` was called with two arguments, not one.

It's possible to make the tests pass by changing the expectation to either of these forms:

```
expect(customer.callNumber).toHaveBeenCalledWith(phoneNumberMatching('123-456-7890', '+1'), '+1');
expect(customer.callNumber).toHaveBeenCalledWith(phoneNumberMatching('123-456-7890'), '+1');
```

But I suspect that neither of those does what you want, or else you wouldn't have bothered to write the asymmetric equality tester in the first place. If you need to do an asymmetric equality test that operates on multiple arguments to a spy, I'd suggest writing a [custom matcher](https://jasmine.github.io/tutorials/custom_matcher) e.g. `toHaveBeenCalledWithPhoneNumberMatching` which might use `phoneNumberMatching` internally.
