### ISSUE TITLE
ExpectAsync uses the same warning color as no expectations

### ISSUE THREAD

**Issue by spacemonaut** [jasmine/jasmine#1752]
## Expected Behavior
Jasmine's HTML reporter displays a row of pips along the top as indicators for executed tests. There is a Good color (green) and a Warning color (yellow).

Tests that have no expectations produce a Warning-colored pip. Tests that include an `expect` statement produce a Good-colored pip. Tests that include an `expectAsync` should also produce a Good-colored pip.

## Current Behavior
Tests that include an `expectAsync` and no `expect` produce a Warning-colored pip. This makes them look like they need action when they do not; they are perfectly good tests. These are false positives.

The below test suite should have 3 Good-colored pips, and only 1 Warning-colored pip for the test with no expectations. (Code for this suite is further down.)

![firefox_2019-09-22_12-02-14](https://user-images.githubusercontent.com/4585677/65386241-e31ce080-dd30-11e9-82bc-80505ec3ffba.png)
![2019-09-22_12-02-20](https://user-images.githubusercontent.com/4585677/65386242-e57f3a80-dd30-11e9-99ea-3f149692c2ad.png)
![2019-09-22_12-02-25](https://user-images.githubusercontent.com/4585677/65386243-e57f3a80-dd30-11e9-973f-0f2c64cf5687.png)
![2019-09-22_12-02-30](https://user-images.githubusercontent.com/4585677/65386244-e57f3a80-dd30-11e9-93a0-7a1258e26838.png)
![2019-09-22_12-02-35](https://user-images.githubusercontent.com/4585677/65386245-e57f3a80-dd30-11e9-998b-793490c9676b.png)

## Possible Solution

If a test contains `expectAsync` that should be sufficient to produce a Good-colored pip.

## Suite that reproduces the behavior (for bugs)

```javascript
describe('test', () => {
  it('has expect', () => {
    expect(true).toBeTruthy();
  });
  
  it('has both expect and expectAsync', () => {
    expect(true).toBeTruthy();
    expectAsync(Promise.resolve(true)).toBeResolved();
  });
  
  it('has expectAsync', () => {
    expectAsync(Promise.resolve(true)).toBeResolved();
  });
  
  it('has no expectations', () => {
    return true;
  });
});
```
## Context

I maintain a repository with several hundred tests. Many use only `expectAsync` because of the async nature of the behaviours being tested. This means in a perfectly healthy test run we will see many Warning-colored pips showing up in the HTML reporter. We *want* to treat warnings as errors and correct every test that has warnings, but the fact is all of these tests showing warnings are perfectly adequate tests that need no correction at all.

Whenever a test does get added that genuinely has warnings we will be prone to overlook it because it's in a sea of other false positives. We need to be able to notice that straight away and correct it. This means we need `expectAsync` tests to not be recognised with the same color as tests with genuine warnings.

## Your Environment

* Version used: Jasmine 3.5
* Environment name and version: Node 12, Chrome 77. But I reproduced the above test suite behaviour in a fiddle using Jasmine's latest release (currently 3.5): https://jsfiddle.net/x0bs5odt/
* Operating System and version: Desktop; Mac 10.14 or Windows 10. But this gets reproduced in a fiddle just fine as well.
* Link to your project: It's private. Here's a fiddle for reproduction which uses Jasmine's latest release (currently 3.5): https://jsfiddle.net/x0bs5odt/

**Comment by slackersoft** [comment]
That definitely sounds like a bug, we would be happy to review a pull request to fix the coloring of the summary dots in HtmlReporter.

**Comment by sgravrock** [comment]
I took a closer look and found that the problem is different than any of us thought at first glance. The HTML reporter does the right thing with the async expectations if it knows about them. But in this case they're happening after each spec has completed and been reported. In other words, the sequence of events is:

1. The spec returns `undefined` rather than a promise, signalling to Jasmine that it's finished synchronously. 
2. Jasmine tells reporters that the spec completed with no expectations.
3. The reporter shows "test has no expectations", because it didn't (yet).
4. The async expectation runs.

You can see that by changing any of the async expectations so that they should fail, e.g. by replacing a `toBeResolved` with `toBeRejected`. The failure won't be reported.

The good news is that you can fix this by either awaiting or returning the promise that's returned by each `expectAsync` call, e.g.:

```
  it('has expectAsync', async () => {
    await expectAsync(Promise.resolve(true)).toBeResolved();
  });
```
or:
```
  it('has expectAsync', () => {
    return  expectAsync(Promise.resolve(true)).toBeResolved();
  });
```

The bad news is that a missing return or await  and easy to miss, which makes `expectAsync` a bit of a footgun. (This isn't a surprise -- it's a big part of why I dragged my feet on adding async expectations for so long.) I've added some code to try to detect late async expectations and report them as errors.

**Comment by sgravrock** [comment]
I think the above mentioned change to report late async expectations as errors takes care of this, and we haven't heard anything new in quite some time. So I'm going to go ahead and close this. Feel free to open a new issue with more information if you don't think the problem is solved.
