### ISSUE TITLE
Error when running jasmine through VTFS

### ISSUE THREAD

**Issue by EnZWebAppZ** [jasmine/jasmine#1753]
Error : 

2019-09-24T15:04:39.9703183Z Jasmine started
2019-09-24T15:04:45.9873578Z ##[error](node:17572) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Is there anyway I can suppress or fix this issue without having to upgrade jasmine versions?

my package.json : 
    "jasmine-core": "~2.6.2",
    "jasmine-custom-message": "^0.8.2",
    "jasmine-custom-reporters": "^1.2.1",
    "jasmine-reporters": "^1.0.0",
    "jasmine-spec-reporter": "~4.1.0",
    "jasmine2-custom-message": "^0.9.3",

The warnings come up when I try to run them through TFS and they show up as errors.

**Comment by slackersoft** [comment]
Jasmine-core doesn't use any kinds of `Buffer` itself, so it is possible that this is being caused by one of many other Jasmine-related dependencies. Additionally, Jasmine 2.6 is over 3 years old at this point, and I might expect other things to start to have similar issues if you're running in on newer versions of Node.js.

**Comment by sgravrock** [comment]
I'm going to go ahead and close it since it has to do with an old unsupported version of Jasmine and we haven't heard anything new about this issue in some time. If you're still having the same problem after updating Jasmine and related packages to the latest versions, feel free to open a new issue.
