### ISSUE TITLE
variable in beforeAll

### ISSUE THREAD

**Issue by rebajz** [jasmine/jasmine#1754]
Why this not working?

`describe('example', async () => {
    beforeAll(async () => {
        this.someVariable = await methodReturnBooleanPromise();
    });
    if (this.someVariable === true) {
        it('case for true', async () => {
            console.log('not working');
        });
        it('next case for true', async () => {
            console.log('not working');
        });
    }
    if (this.someVariable === false) {
        it('case for false', async () => {
            console.log('not working');
        });
    }
});`
outside beforeAll is still this.someVariable = undefined

this working correctly

`describe('example2', async () => {
    beforeAll(async () => {
        this.someVariable = true;
    });
    it('some it', async () => {
        if (this.someVariable === true) {
        console.log('true');
        }
        if (this.someVariable === false) {
            console.log('false');
        }
        if (this.someVariable === undefined) {
            console.log('undefined');
        }
    });
});`

when change "it" to "describe", again not working
`describe('example3', async () => {
    beforeAll(async () => {
        this.someVariable = true;
    });
    describe('some describe', async () => {
        if (this.someVariable === true) {
        console.log('true');
        }
        if (this.someVariable === false) {
            console.log('false');
        }
        if (this.someVariable === undefined) {
            console.log('undefined');
        }
    });
});`

**Comment by slackersoft** [comment]
The behavior you're seeing is because of how Jasmine builds and executes your test suite. The first thing that happens in it loads all of your files and all of the `describe` callbacks are called to establish the suite hierarchy and where all `beforeEach`, `beforeAll`, `it`, etc are in the hierarchy so they can be executed correctly. Then once all scripts are loaded, Jasmine executes each of the specs with their associated `beforeEach`es and `afterEach`es, when `beforeAll` and `afterAll` are present specs that share them are all executed as a group in between the appropriate callbacks.

This all means that when Jasmine is executing the `function` you pass to `describe`, none of the other functions have been invoked yet, so any variables that get set in there don't yet exist.

Hope this helps. Thanks for using Jasmine!

**Comment by rebajz** [comment]
ok I understand, but I think it would be better this:
when user have in suites more files, execute one by one this files, not load describes. Why?

for example - first file contains function, where is created some variable, help file, or other. Second file contain function, where read variable, file or something else from previous file.

Why? we have many hardware devices. Each device have different options. I will try in first file (init), when contain some options. If yes, variable is set to true, if not, variable is set to false.

Second file (with tests) read variable. If is variable as true, test run with many IT block. If is variable as false, test run only one IT block (check in tree menu is not link for open page).

We use async/await. But Jasmine not wait for all data from first file. From first file still running test, and from second file is started beforeAll().

Because this not working, i do only one file test in suites, In beforeAll i create varibale with this.something and in IT block i have in each fit if case. It is lot of same code. Second problem is in test report. Many IT is set as passed, because nothing is tested. I try add to else case method pending(). - this do next problem - when IT call pending method, IT is as faulted status.

**Comment by rebajz** [comment]
import {browser} from 'protractor';
import {someSteps} from '../../../Libs/libs';
let continueTest;
let usedDevice = browser.params.runDevice;
describe('some test', async () => {
    beforeAll(async () => {
        continueTest = await someSteps.initDevice(); // return is Promise<boolean>
    }, TIME_LIMIT);
    if (continueTest) {
        it('xxx1',async () => {
          console.log('some test');
        });
it('xxx2',async () => {
          console.log('some test 2');
        });
    } else {
          it('Device not support this option', async () => {
console.log('only one it where is tested only some item is not in tree menu';
            }
        });
    }
});

**Comment by slackersoft** [comment]
Jasmine has a bit of a similar problem with environment setup due to our browser support matrix. Some browsers (mostly IE) don't support some features that Jasmine does (`Map`, `Set`, `Promise`, maybe others). What we've done for our specs is, we created some helper files that when loaded check for the availability of a particular feature and effectively set a global variable somewhere. We can then check that variable during the execution of the suite and set the pending status if the feature is not available.

See [anySpec.js](https://github.com/jasmine/jasmine/blob/master/spec/core/asymmetric_equality/AnySpec.js#L33) and the underlying [checkForMap.js](https://github.com/jasmine/jasmine/blob/master/spec/helpers/checkForMap.js) for a bit more in the way of implementation details.

**Comment by slackersoft** [comment]
The current solution for this in Jasmine is to do the check inside the `it` itself and call `pending` with a message the the functionality you're looking for isn't supported by the current environment. Given how Jasmine currently works, I don't think this is something that we're looking to make any big changes to.

I'm going to close this. Thanks for using Jasmine!
