### ISSUE TITLE
spyOnAllFunctions spies on constructors

### ISSUE THREAD

**Issue by elliot-nelson** [jasmine/jasmine#1760]
Currently, using `spyOnAllFunctions` on a module that has a mix of functions and classes breaks the class constructors.

## Example Behavior

```
class RetryableError extends Error {
    retry() { }
}

const API = {
    RetryableError,
    makeRequest: () => {}
};

describe('API', function () {
    it('works', function () {
        spyOnAllFunctions(API);

        new API.RetryableError().retry();
        // -> Error: "retry" is not a function (the new returns {})

        API.RetryableError.and.callThrough();

        new API.RetryableError().retry();
        // -> Error: Class constructor RetryableError cannot be invoked without 'new'
    });
});
```

## Possible Solution
It seems like the best solution is to ignore constructors, because once you spy on one, you can't "fix it" with `.and.callThrough()` (and in general, spying on constructors is an anti-pattern).

## Your Environment
* node 8.x, 10.x
* jasmine 3.4.0/3.5.0

**Comment by sgravrock** [comment]
The problem is, how does Jasmine determine whether a given function is a constructor or not? A constructor is simply a regular (non-arrow, non-shorthand-member) function that gets called with the `new` keyword. As far as I know there's not any difference identifiable at runtime between a function that we think of as a constructor and one that we don't. 

I'd be happy to be proven wrong on this. But I can't help noticing that the various `isConstructor` functions that I've been able to find all define "constructor" to mean one of the following:

* A function that isn't an arrow function or a shorthand member
* A function that doesn't throw when you call it with `new` and no arguments

I doubt that either of those definitions is what you, or anyone else who isn't in the middle of writing an `isConstructor` function, have in mind.

**Comment by slackersoft** [comment]
I think I would rather work to fix this type of issue by allowing `spyOn(thing, 'SomeConstructor').and.callThrough()` to do the right thing and invoke the original constructor with `new`. This would mean detecting use of the `new` keyword when the spy is invoked and passing that down to the `SpyStrategy` to do the actual invocation correctly.

I would be happy to review a pull request to add `new` detection to spy invocations.
