### ISSUE TITLE
Doesn't support multiple async function mocks in beforeEach

### ISSUE THREAD

**Issue by theomarshanti** [jasmine/jasmine#1761]
## Expected Behavior
As a developer writing Unit Tests for an Angular component,
Given I am testing a function that calls 2 separate async functions on 2 separate services in the ngOnInit
And I write 2 mocks for these methods in the `beforeEach()`
Then I expect both mocks to come into effect.

## Current Behavior
Only the mock that gets executed first in the parent function comes into effect. The next function is not mocked.
In the below example, the mock for getSomeData will be executed, since it comes first in the ngOnInit function. 

## Suite that reproduces the behavior (for bugs)
```
~demo.component.ts~
export class DemoComponent implements OnInit {
  constructor(private firstService: FirstService, private secondService: SecondService) {};
  ngOnInit() {
     this.data = await firstService.getSomeData().toPromise();
     if(this.data) {
        await secondService.doSomethingWithThatData(this.data).toPromise();
     }
  }
}
```

```
~demo.component.spec.ts~
describe('Demo Component', () => {
  let component: DemoComponent;
  let fixture: ComponentFixture<DemoComponent>;
  let firstService: FirstService;
  let secondService: SecondService;
  let getSomeDataSpy: any;
  let doSomethingWithThatDataSpy: any;
  beforeEach(()=> {
    TestBed.configureTestingModule({
        ..
     });
  });

  beforeEach(()=> {
    fixture = TestBed.createComponent(DemoComponent);
    component = fixture.componentInstance;
    firstService = TestBed.get(FirstService);
    secondService = TestBed.get(SecondService);

    getSomeDataSpy = spyOn(firstService, 'getSomeData');
    getSomeDataSpy.and.returnValue(of("some data" ));

    doSomethingWithThatDataSpy = spyOn(secondService, 'doSomethingWithThatData');
    doSomethingWithThatDataSpy.and.returnValue(secondService({}));

    fixture.detectChanges();
  })
  it('should create', () => {
    expect(component).toBeTruthy()
  })
})
```

## Context
Because there was no mention of this limitation anywhere, I had to debug this with a team for a few hours. We finally circled in on the problem and then just to be able to test this feature, we had to rewrite it from `async/await` notation to `subscriber` observable notation. This means (1) we wasted a lot of time; (2) we sacrificed our coding conventions; & (3) we need to smoke-test that feature again since we've changed the logic in it.

## Your Environment
"@angular/cli": "8.0.6",
"jasmine-core": "^3.4.0",
"jasmine-spec-reporter": "^4.2.1",
"karma": "^4.3.0",
"karma-chrome-launcher": "^3.1.0",
"karma-cli": "^2.0.0",
"karma-coverage-istanbul-reporter": "^2.1.0",
"karma-jasmine": "^2.0.1",
"karma-jasmine-html-reporter": "^1.4.2",
"karma-parallel": "^0.3.1",

**Comment by slackersoft** [comment]
Jasmine doesn't have any limitations on how many spies can be instantiated (async or otherwise). If I had to guess here, it looks like you might have an ordering problem with your Angular setup. I'm also not entirely sure what your `toPromise()` function is doing to the returned result, but that plus the fact that your spies don't seem to return anything async-ish makes me wonder if that is part of the issue.

If you can work up an example that doesn't use Angular but still demonstrates the issue, that will help me figure out what Jasmine might be doing incorrectly here.

Thanks for using Jasmine!

**Comment by theomarshanti** [comment]
Thanks for the response, @slackersoft 

Some clarifications -
The logic in the codebase is actually quite different from that example. I just simplified it for sake of easy understanding. 
The services each perform HTTP calls and so are indeed async-ish
The `toPromise()` is an [rxjs](https://www.learnrxjs.io/operators/utility/topromise.html) function that converts an RxJS observable into a Promise, allowing us to `await` for it rather than pass in a callback.

I think this issue is tied to Jasmine-Angular testing of components.
Would there a better channel to post that to?

**Comment by sgravrock** [comment]
The thing that jumps out at me is that the method where the problem is occurring, `ngOnInit`, is asynchronous. But the `beforeEach` function and the test are both synchronous. It's highly likely that the test finishes and Jasmine destroys all the spies before any of the code after the first `await` in `ngOnInit` runs. (You can probably prove this by adding some `console.log` calls in appropriate places.)

You'll probably want to make your `beforeEach` async, and add one or more `await`s to it so that any test code that's meant to work with a fully initialized component doesn't run until after `ngOnInit` is done.

**Comment by theomarshanti** [comment]
Sorry for the delay - 
Yes @sgravrock is exactly correct. I created a new project + demo'd that out, and indeed it worked. Thanks all.
