### ISSUE TITLE
Modify ng update behavior

### ISSUE THREAD

**Issue by SAkhil95** [jasmine/jasmine#1767]
## Are you creating an issue in the correct repository?

- When in doubt, create an issue here.
- If you have an issue with the Jasmine docs, file an issue in the docs repo
  here: https://github.com/jasmine/jasmine.github.io
- This repository is for the core Jasmine framework
- If you are using a test runner that wraps Jasmine, consider filing an issue with that library if appropriate:
  - [Jasmine npm](https://github.com/jasmine/jasmine-npm/issues)
  - [Jasmine gem](https://github.com/jasmine/jasmine-gem/issues)
  - [Jasmine py](https://github.com/jasmine/jasmine-py/issues)
  - [Gulp Jasmine Browser](https://github.com/jasmine/gulp-jasmine-browser/issues)
  - [Karma](https://github.com/karma-runner/karma/issues)
  - [Grunt Contrib Jasmine](https://github.com/gruntjs/grunt-contrib-jasmine/issues)

## Expected Behavior

**ng update jasmine-core** updates,
1. "jasmine-core"
2. "@types/jasmine"
3. "@types/jasminewd2"
4. "jasmine-spec-reporter"

## Current Behavior

**ng update jasmine-core** updates,
1. "jasmine-core"

## Context

I have to do ng update for each and every item separately which again would cause compatibility issues due to version mismatch. 

## Your Environment

* Version used: 3.5.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): N/a
* Operating System and version (desktop or mobile): Desktop
* Link to your project: N/a

**Comment by slackersoft** [comment]
I'm not able to find a whole lot of information on how exactly the angular cli goes about finding what to update, but based on https://angular.io/cli/update, I'm guessing it's probably a reasonably thin wrapper around the `npm` command. This would mean that when you run `ng update jasmine-core` you are telling the `ng` command to update the `jasmine-core` package. Since `jasmine-core` doesn't have any dependencies, there is (presumably) no real way for the `ng update` command to find any of the other related packages to update them as well.

I'm not sure there is anything we could do within this repo to actually change the behavior of the `ng update` command you've specified. I would recommend checking in on a more angular specific forum.

Hope this helps. Thanks for using Jasmine!

**Comment by SAkhil95** [comment]
Thanks for the detailed information @slackersoft 

I will reach out to Angular.
