### ISSUE TITLE
Testing Asynchronous function that throw error

### ISSUE THREAD

**Issue by brucebrit** [jasmine/jasmine#1768]
jasmine : 3.4.0

```
export class FileIntegrityService{

  constructor() { }

  getCheckSum_MD5(filePath: string, cbFn:(string)=>void){
      let hash = crypto.createHash('md5')
      
   
      let s = fs.createReadStream(filePath)
    
      s.on ('data', (data)=>{
        hash.update(data)
      })

      s.on ('end', ()=>{
        let checksum = hash.digest('hex')
        cbFn(checksum)
      })
    
      s.on ('error', (err)=>{
        throw err
      })
  }

}

```
As shown in below spec,  the first argument for the service.getCheckSum_MD5 is passed in with a text file name that does not exist, hence the event error should occur, throwing an err in the function.
My unit testing test has failed. But why? 

*Assuming the above logic for **getCheckSum_MD5** is not written by me, and hence could not change the logic

```
it('non-existent file should throw error 1', async () => {
      //const service: FileIntegrityService= TestBed.get(FileIntegrityServiceService);
      let service = new FileIntegrityService()
      await expect (service.getCheckSum_MD5("non-existent.txt", undefined)).toThrow()
      
  });
```

**Comment by sgravrock** [comment]
If you can't change `getCheckSum_MD5`, then I'm afraid I don't see a reasonable way to write the test you want. The problem is that you're trying to verify that `getCheckSum_MD5` reports errors to its caller, and it doesn't actually do that.

When the test above runs, the sequence of events is something like this:
1. Jasmine calls the test function, which calls `getCheckSum_MD5`, which calls `fs.createReadStream` and registers some event handlers.
2. `getCheckSum_MD5` and the test function return.
3. Jasmine concludes that the test is finished and reports the result.
4. At some later time, the stream's error event fires and the callback executes the `throw err` statement. The exception isn't caught because any functions that might have tried to catch it have already returned.
5. Because the exception isn't caught, it gets routed to the global Node.js `uncaughtException` event.
6. Jasmine's `uncaughtException` handler fails the test suite.

This isn't specifically a Jasmine problem. If you tried to write application code that handles errors from `getCheckSum_MD5` you'd likely run into the same issue. For instance, if I run this code:

```
try {
	console.log('calling');
	new FileIntegrityService().getCheckSum_MD5('nosuch', function() {
		console.log('callback called');
	});
	console.log('call done');
} catch (e) {
	console.log('caught an error');
}
console.log('outside the try block');
```

I get this output:

```
$ node demo.js 
calling
call done
outside the try block
/private/tmp/j/demo.js:19
        throw err
        ^

Error: ENOENT: no such file or directory, open 'nosuch'
```

Note that the error is logged *after* the try block is exited, when it's too late to do anything about it.

Now, suppose you were allowed to make changes to `getCheckSum_MD5`. In that case you'd want to decide whether it should report its result using a callback or `async`/`await`. Depending on which you chose, one or the other of these tests might do the job:


```
it('calls the callback with an error when the file does not exist', done => {
	const service = new FileIntegrityService()
	service.getCheckSum_MD5("non-existent.txt", function(error) {
		expect(error.message).toEqual('the expected message');
		done();
	});
});

it('rejects the returned promise when the file does not exist', async () => {
	const service = new FileIntegrityService()
	await expectAsync(service.getCheckSum_MD5("non-existent.txt")).toBeRejectedWith('the expected message');
});
```

I hope this helps. You might also find the [asynchronous testing tutorial](https://jasmine.github.io/tutorials/async) and the [async matchers reference documentation](https://jasmine.github.io/api/3.5/async-matchers.html) useful.

**Comment by brucebrit** [comment]
Thanks for the thorough explanation. Just to ensure my understanding of your explanation is correct, one solution is not to throw error inside the getCheckSum_MD5. Instead, call the callback function with the error object as an argument. Am i right?

**Comment by sgravrock** [comment]
That's right. It's best to pass the error and the success result to the callback as separate arguments, to avoid confusion. So an example call might look like this:

```
service.getCheckSum_MD5("non-existent.txt", function(error, checksum) {
	if (error) {
		// handle the error
	} else {
		// do something with the checksum
	}
});
```
