### ISSUE TITLE
spyOn methods are forgotten inside callback blocks

### ISSUE THREAD

**Issue by dfinton** [jasmine/jasmine#1773]
## Expected Behavior
In the example code provided, I have an `async` function that calls other functions, one of which is also `async`. When I run the tests using a callback method via `.then(...)`, the mocked methods should be executed when calling the main function. The main function in my example simply returns the result from `secondNotAsyncFunction`, which I have mocked out to return the string "test3".

## Current Behavior
The unit test fails when the `expect` statement is embedded in the callback method argument to `then(...)`. When I debugged the issue, I found that the mocks that were set up by the `spyOn` function were no longer present inside the context of the callback. Only the original methods were in place.

## Possible Solution
The workaround I was able to find was to use `await` inside the unit test itself and pass the result to the expect statement without using a callback directly.

## Suite that reproduces the behavior (for bugs)
*test.js:* this contains the class being tested
```
class TestClass {
  firstNotAsyncFunction = function() {
    return 'foo'
  }

  promiseFunction = function(myValue) {
    return new Promise(((resolve) => {
      setTimeout(() => {
        resolve(`${myValue} bar`);
      }, 10);
    }));
  }

  asyncFunction = async function(myValue) {
    const myResult = await this.promiseFunction(myValue);

    return myResult;
  }

  secondNotAsyncFunction = function(myValue) {
    return `${myValue} baz`;
  }

  mainFunction = async function() {
    const firstResult = this.firstNotAsyncFunction();
    const asyncResult = await this.asyncFunction(firstResult);
    const secondResult = this.secondNotAsyncFunction(asyncResult);

    return secondResult;
  }
}

module.exports = TestClass;
```

*test.spec.js:* the broken unit test (this example just has the test for the main function for demo purposes)
```
const TestClass = require('./test');

describe('TestClass', function() {
  describe('mainFunction', function() {
    it('Runs all of the subfunctions correctly', async function() {
      const testClass = new TestClass();

      spyOn(testClass, 'firstNotAsyncFunction').and.returnValue('test1');

      spyOn(testClass, 'asyncFunction').and.returnValue(
        new Promise((resolve) => {
          resolve('test2');
        }),
      );

      spyOn(testClass, 'secondNotAsyncFunction').and.returnValue('test3');

      testClass.mainFunction().then(function(myResult) {
        expect(myResult).toEqual('test3');
      });
    });
  });
});

```

*test.spec.js:* the working unit test
```
const TestClass = require('./test');

describe('TestClass', function() {
  describe('mainFunction', function() {
    it('Runs all of the subfunctions correctly', async function() {
      const testClass = new TestClass();

      spyOn(testClass, 'firstNotAsyncFunction').and.returnValue('test1');

      spyOn(testClass, 'asyncFunction').and.returnValue(
        new Promise((resolve) => {
          resolve('test2');
        }),
      );

      spyOn(testClass, 'secondNotAsyncFunction').and.returnValue('test3');

      expect(await testClass.mainFunction()).toEqual('test3');
    });
  });
});

```

## Context
Our unit tests need to have as close to 100% coverage as possible. I had to mock some methods in a manner similar to the examples I provided and spent over a day trying to figure out why the mocks weren't working once inside the callback even though everything was inside the same scope. I had to infer the solution by stumbling upon an unrelated jasmine issue and noting a solution provider's usage of the await keyword instead of a callback to perform the test on the Promise result. https://github.com/jasmine/jasmine/issues/1443

## Your Environment
* Version used: 3.5.0
* Environment name and version: node v10 and v12
* Operating System and version (desktop or mobile): Ubuntu Linux, latest release
* Link to your project: n/a

**Comment by sgravrock** [comment]
I'm sorry that you had such a bad time with this, and I'm glad my comment in #1443 helped point you in the right direction.

The behavior that you describe is by design. The issue isn't that the spies were called from inside a callback. It's that they were called after the test finished. The sequence of events went something like this:

1. The test does some `spyOn` calls.
2. The test calls `testClass.mainFunction()`.
3. `testClass.mainFunction` goes async.
4. The test function returns.
5. Since the test function didn't take a `done` callback, wasn't declared `async`, and didn't return a promise, Jasmine concludes that the test is finished.
6. Jasmine destroys the spies so that they don't affect subsequent tests.
7. Depending on timing and other factors, some other tests might run.
8. `testClass.mainFunction` calls `secondNotAsyncFunction`, which is no longer a spy at this point.

Since the behavior you're testing is asynchronous, the test itself needs to be asynchronous so that Jasmine can know when it's actually done. The easiest way to do that is exactly what you did: declare the function `async`, and add appropriate `await` calls so that it doesn't finish until the asynchronous work is actually done.

Although it sounds like you've already got your test working, you might find the [asynchronous work](https://jasmine.github.io/tutorials/async) documentation helpful.

**Comment by Kasopej** [comment]
Your explanation really helped me right now. Had a similar problem with spies. Although in my case, I set my spy inside a setTimeOut callback, while my expect was outside in the spec body. Turns out my spy was being reset after the asynchronous call was finished.
### Failing code below
`it("and it contains a spec with a timed out operation in it", function (done) {
    spyOn(dave, "laugh");
    setTimeout(function () {
      dave.laugh();
      console.log("Asynchronous in spec");
      done();
    }, 1000);
    expect(dave.laugh).toHaveBeenCalled();
  });`
The spy has no record of the call outside the async function

### Working code
`it("and it contains a spec with a timed out operation in it", function (done) {
    spyOn(dave, "laugh");
    setTimeout(function () {
      dave.laugh();
      console.log("Asynchronous in spec");
      expect(dave.laugh).toHaveBeenCalled();
      done();
    }, 1000);
  });`
In this case, the spy correctly reports the call

### Another working sample (just to illustrate how the spy is being reset
`it("and it contains a spec with a timed out operation in it", function (done) {
    spyOn(dave, "laugh");
    setTimeout(function () {
      dave.laugh();
      console.log("Asynchronous in spec");
      done();
    }, 1000);
    dave.laugh();
    expect(dave.laugh).toHaveBeenCalled();
  });`
Straightforward case: the spy reports the second call, you can test this with toHaveBeenCalledTimes
