### ISSUE TITLE
Tests fail only locally with latest node/npm versions

### ISSUE THREAD

**Issue by fbiville** [jasmine/jasmine#1774]
Some async tests systematically fail after a node/npm upgrade, only **on my machine**.
I tried re-installing node with Homebrew, then removed it and used the official Node packager instead: same result.

## Current Behavior
When I run tests via `npm test` on https://github.com/projectriff/node-function-invoker, I get async errors such as:
```
Async function did not complete within 5000ms
```
None of my coworkers nor the [CI](https://github.com/projectriff/node-function-invoker/actions?query=workflow%3ACI) have this issue.

## Expected Behavior
I expect the tests to successfully run.

## Your Environment

* Version used: Jasmine 3.5.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Nodejs 13.5.0, npm 6.13.4
* Operating System and version (desktop or mobile): Mac OS 10.15.2
* Link to your project: https://github.com/projectriff/node-function-invoker

**Comment by sgravrock** [comment]
That error message is how Jasmine reports that one of your async tests never completed (or at least, didn't complete within the 5 second timeout). Much like a failed expectation, it almost always indicates a bug in the test or in the code under test rather than a bug in Jasmine.

I was able to reproduce your test failures using Node 13.5.0, but not 10.16.3 (the next older version I had on hand). I added some `console.log` calls to one of the failing tests, like so:

```
        describe('with badly-typed inputs =>', () => {
            beforeEach(() => {
                fixedSource = newFixedSource(["not a signal"]);
            });

            fit('emits an error', (done) => {
                streamingPipeline.on('error', (err) => {
                    expect(err.type).toEqual('error-streaming-input-invalid');
                    expect(err.cause).toEqual('invalid input type [object String]');
                    console.log("got an error");
                });
                streamingPipeline.on('finish', () => {
                    console.log("done");
                    done();
                });
                fixedSource.pipe(streamingPipeline);
            });
        });
```

When I run it, I get this output: 

```
[...]
> jasmine

Randomized with seed 74998
Started
got an error
F
```

(The "F" is Jasmine indicating that the test failed. In this case it doesn't print until after the 5 second timeout.) Note that "done" message never appears, which means that the test also never calls the `done` callback. This is the direct cause of the error message: the test never tells Jasmine that it's done. It looks as if the Node upgrade changed the behavior of `StreamingPipeline` so that it no longer fires its  `done` event in error scenarios.

By the way, when I run the same test under Node 10.16.3, I see a different problem:

```
> jasmine

Randomized with seed 22171
Started
done
.got an error
```

(The . just before "got an error" is Jasmine indicating that the test passed.) The problem here is that the `StreamingPipeline`'s `error` event, whose handler contains the expectations, fires after the test tells Jasmine that it's finished. If any of the expectations were to fail, Jasmine wouldn't be able to reliably associate them with the test in question. [Callback-style async tests need to call `done` exactly once, and calling `done` needs to be the last thing that they do.](https://jasmine.github.io/tutorials/async#callbacks)

So I suggest doing two things:
1. Figure out why `StreamingPipeline` behaves differently in Node 13, and then modify either the tests or `StreamingPipeline` accordingly.
2. Review all the async tests (especially the ones that are passing) to make sure that calling `done` is the last thing that they do.

I hope this helps.

**Comment by fbiville** [comment]
Thanks, I'll investigate.

**Comment by fbiville** [comment]
Focused a single test (one-liner: `git clone https://github.com/fbiville/node-function-invoker/ && npm --prefix node-function-invoker test`) and changed a little bit of the implementation of the streaming pipeline.

The scenario includes a streaming pipeline with a [`source`]->[`pipeline`] and the `pipeline` itself assembles [`source`]->[`unmarshaller`] and [`marshaller`]->[`source`].

In the focused test, the function does sth like this [`unmarshaller`]->[`transform`]->[`marshaller`]. And the `transform` will cause the `marshaller` to fail as it produces Symbols and Symbols cannot be marshalled.

The expected behavior is:
 - `marshaller` emits an error ✅
 - `pipeline` listens on `marshaller` `error` events and emits the error itself ✅
 - `pipeline` listens to itself on `error` events and ends the `unmarshaller` ✅
 - `pipeline` listens to `unmarshaller` `end` events and ends itself (if it's the last unmarshaller to end) ✅
 - the test sees the `pipeline` `error` event **BEFORE** the `pipeline` `finish` event ❌

For some reason I do not understand, the test **consistently** fails because the registered-in-test `finish` event is always executed first!

**Comment by fbiville** [comment]
Finally figured it out. Despite reading it multiple times in the docs, `EventEmitter`'s `emit` and `on` are completely synchronous. The first `error` handler in my streaming pipeline was in turn triggering a `finish` event which means that all `finish` listeners were executed **before** the second `error` handler had a chance.

I just switched the tests to use `prependListener('error')` and it works like a charm.

No bug at all in Jasmine, quite the contrary. It helped me revisit my wrong assumptions and learn something new!
