### ISSUE TITLE
karma-jasmine-html-reporter spec links not working

### ISSUE THREAD

**Issue by mcm-ham** [jasmine/jasmine#1775]
Coming from: https://github.com/dfederm/karma-jasmine-html-reporter/issues/26

## Expected Behavior
Click "Spec List" shows list.

## Current Behavior
Clicking "Spec List" reloads page and runs all tests again.

## Possible Solution
Update https://github.com/jasmine/jasmine/blob/7263a38c3fb04d7fb27c468cdec8ec3eb53e0766/src/html/HtmlReporter.js

With this fix:
https://github.com/Chmiel123/karma-jasmine-html-reporter/commit/20acf93b45403bd30512bae2dbd0b40f76b14496

## Suite that reproduces the behavior (for bugs)
1. npm install @angular/cli
2. ng new app
3. Change one test in app.component.spec.ts to fail
4. ng test
5. (wait for tests to compile/run) Should see "3 specs, 1 failure..."
6. Click "Spec List".

## Your Environment
* Angular: 8.2.14
* Jasmine-Core: 3.4.0
* karma-jasmine-html-reporter: 1.4.2

**Comment by slackersoft** [comment]
I don't think we want to remove the actual `href` from the links, since that is one of the things that tell browser that the `a` tag is supposed to be interactable. At a minimum this loses the default cursor change and other similar accessibility features.

Normally a link to an anchor (e.g. `#`) shouldn't actually do a navigate either. It doesn't seem to in Jasmine without Karma at least, or we would have heard about this before. If we can't figure out what might be happening with Karma, I would be happy to review a pull request to do something like `preventDefault` in the click handler for those menu links so they don't cause Karma to reload the page.

Hope this helps. Thanks for using Jasmine!

**Comment by abeninskibede** [comment]
same here

**Comment by abeninskibede** [comment]
Is there a workaround for this?

**Comment by Miguelcldn** [comment]
@abeninskibede I managed to work around it by clicking the _DEBUG_ button on the top bar. You'll have another tab where there won't be '#' refs, so clicks won't reload. I don't know the exact difference about debug mode though, but it works for me.

**Comment by abeninskibede** [comment]
Hey,
How can I install that?

**Comment by parloti** [comment]
@abeninskibede
> Hey,
> How can I install that?

See: [stackoverflow](https://stackoverflow.com/a/61017761/4233401)
