### ISSUE TITLE
Filter not working when using reporter

### ISSUE THREAD

**Issue by invertednz** [jasmine/jasmine#1785]
I cloned https://github.com/mikedfunk/jasmine-example
Then I installed jasmine-junit-reporter
When I run ```jasmine --filter="^add suite should add two numbers$" --reporter=jasmine-junit-reporter``` then six tests run
When I run ```jasmine --filter="^add suite should add two numbers$"``` only one test runs
## Expected Behavior
Only one test should run when executing  ```jasmine --filter="^add suite should add two numbers$" --reporter=jasmine-junit-reporter```

## Current Behavior
Six tests are executed

## Suite that reproduces the behavior (for bugs)
I cloned https://github.com/mikedfunk/jasmine-example
Then I installed jasmine-junit-reporter

## Context
I'm trying to run a single or set of tests and have a junit output.

## Your Environment
* Version used: Jasmine 3.5.0
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:https://github.com/mikedfunk/jasmine-example

**Comment by sgravrock** [comment]
When I add a `console.log` call to each test and run `jasmine --filter="^add suite should add two numbers$" --reporter=jasmine-junit-reporter`, I only see the logging from the one spec that matches the filter. This tells me that Jasmine is only executing the one spec. 

It looks like the problem is that jasmine-junit-reporter reports skipped specs (those with status `'excluded'`) as passed. Your best bet is probably to open an issue, or better yet a pull request, at [jasmine-junit-reporter](https://github.com/appcelerator/jasmine-junit-reporter/).

**Comment by sgravrock** [comment]
I'm going to go ahead and close this since it appears to be an issue with another library and we haven't heard anything more in some time.
