### ISSUE TITLE
Can Jasmine Tests be run in parallel at it() level

### ISSUE THREAD

**Issue by spatchamatla** [jasmine/jasmine#1786]
Can we run Jasmine test in parallel at it() level in spec file.

I got multiple it() (not dependent on other test) in describe in a single spec. So want to run these it in parallel.
```
describe("first suite", function() {
  it("first test", function(done) {
    expect(true).toBeTruthy();
  });
  it("second test", function(done) {
    expect(true).toBeTruthy();
  });
});
describe("second suite", function() {
  it("first test", function(done) {
    expect(true).toBeTruthy();
  });

  it("second test", function(done) {
    expect(true).toBeTruthy();
  });
});
```
current workaround is able to run multiple specs in parallel, but want to see if it() blocks can be run in parallel?

## Your Environment
- wdio as test runner
- Jasmine 3.5.0
- Mac OS 10.15
- chrome 80

**Comment by slackersoft** [comment]
This kind of parallelization is a bit tricky in browsers, since they generally don't really support more than one thread (without a bunch of web worker trickery), so Jasmine core doesn't really support this. If you don't need the rest of the browser set up, you can look at the `jasmine` npm package, which now has (unreleased) support for parallelization via jasmine/jasmine-npm#153

**Comment by antoniusostermann** [comment]
@slackersoft Any plans when 3.6 will be released, officially containing https://github.com/jasmine/jasmine-npm/pull/153?
