### ISSUE TITLE
How can restore or overwrite a SpyOn on this example?

### ISSUE THREAD

**Issue by didaquis** [jasmine/jasmine#1798]
On this example, both test pass if they are executed separately but the second test fail if both test are executed. 

How can I rewrite the "foo" and "bar" spies on the seconds test?

```
const utils = require('../src/destructured-imports/utils');

describe('myModule', () => {

	describe('bizz should return fake-data', () => {
		it('when foo returns true', () => {
			const fooSpy = spyOn(utils, 'foo').and.returnValue(true);
			const barSpy = spyOn(utils, 'bar').and.callFake(data => {
				expect(data).toBeTrue();
				return 'fake-data';
			});
	
			const { bizz } = require('../src/destructured-imports/myModule');
	
			expect(bizz()).toBe('fake-data');
	
			expect(fooSpy).toHaveBeenCalled();
			expect(barSpy).toHaveBeenCalled();
		});
	});

	describe('bizz should return fake-other-data', () => {
		it('when foo returns false', () => {
			const fooSpy = spyOn(utils, 'foo').and.returnValue(false);
			const barSpy = spyOn(utils, 'bar').and.callFake(data => {
                                // this code is not working if both test are executed, but works fine if first test are disabled
				expect(data).toBeFalse();
				return 'fake-other-data';
			});

			const { bizz } = require('../src/destructured-imports/myModule');

			expect(bizz()).toBe('fake-other-data');

			expect(fooSpy).toHaveBeenCalled();
			expect(barSpy).toHaveBeenCalled();
		});
	});

});

```

**Comment by sgravrock** [comment]
What you have here looks like it should work. And when I made educated guesses at the contents of `../src/destructured-imports/utils` and `../src/destructured-imports/myModule`, I was able to get both tests to pass. My guess is that something in your environment or in the code that's not shown here is important. Can you put together a minimal, self-contained system that reproduces the problem? Either a GitHub repo or a CodePen/JSFiddle/Stackblitz/whatever.

**Comment by didaquis** [comment]
> Can you put together a minimal, self-contained system that reproduces the problem?

Of course. The repo: https://github.com/didaquis/mock-spy-node-jasmine 

Remember uncomment the second test on the file `spec/myModule.spec.js` 

Thank you for your help!

**Comment by sgravrock** [comment]
Thanks for the repro. That clears things up nicely.

The key thing to understand about `spyOn` is that all it really does is set the value of the an object's property, and then set it back to its original value. You can think of it as being a little bit like this code:

```
const oldValue = target[propName];
target[propName] = createSpy();
try {
   theRestOfTheSpec();
} finally {
   target[propName] = oldvalue;
}
```

In your case the problem is that `myModule` destructures `utils`:

```
const { foo, bar } = require('./utils');
```

This creates local variables `foo` and `bar`, which capture the values of the corresponding properties of the `util` module. Since `myModule` is first imported when spies are installed on `foo`, it captures those spies. Jasmine removes the spies from `utils` at the end of the specs and restores the original values of the spied-on properties, but it's unable to do anything about the local variables in `myModule`.

You can fix things by changing `myModule.js` to not destructure `utils`, like this:

```
const utils = require('./utils'); // no destructuring

const bizz = () => {
    let fooResult = utils.foo()
    return utils.bar(fooResult)
}

module.exports = { bizz }
```

This makes `utils.foo` and `utils.bar` late-bound, so that what matters is their values at the moment when they're accessed rather than at the moment when `utils` is imported. With that done, the tests should all pass. I'd also recommend requiring `../src/destructured-imports/myModule` once at the top of the spec file rather than in each spec, to reduce the risk that the module's behavior will be affected by the order that the tests run in.

**Note:** All of the above is specific to AMD modules. Other module systems work differently. In particular, ES2025 imports don't actually destructure, so spying on an exported module property will actually affect the corresponding "local variable" in another module. E.g. with Babel, this code:

```
import {foo, bar} from './utils';

const bizz = () => {
    let fooResult = foo()
    return bar(fooResult)
}
```

actually compiles to this:

```
var _utils = require("./utils");

var bizz = function bizz() {
  var fooResult = (0, _utils.foo)();
  return (0, _utils.bar)(fooResult);
};
```

**Comment by didaquis** [comment]
Thanks!
