### ISSUE TITLE
Spying on ES modules with typescript > 3.9

### ISSUE THREAD

**Issue by nico1510** [jasmine/jasmine#1817]
With typescript 3.8 or lower the following code has always worked:

```typescript
import * as foo from 'someModule';
spyOn(foo, 'someExport');
```
Starting with typescript 3.9 however, module exports are [no longer enumerable](https://github.com/microsoft/TypeScript/pull/32264). There is an open issue in the typescript repo for this (see https://github.com/microsoft/TypeScript/issues/38568). Since the `set` property is no longer available, the above code fails when it reaches this [check](https://github.com/jasmine/jasmine/blob/b4cbe9850fbe192eaffeae450669f96e79a574ed/src/core/SpyRegistry.js#L53).
This problem is also present in other testing libraries (see https://github.com/sinonjs/sinon/issues/2258).

Ideally we could find another way to spy on those modules because I don't think typescript will revert this change as it is according to the spec and should never have worked.

**Comment by sgravrock** [comment]
If I understand it, the key problem isn't that exports are no longer enumerable. It's that they're no longer *settable*. Unfortunately I don't see how this can be fixed in Jasmine. We can only play by the rules of the language, and that means that when TypeScript tells the language that a property is immutable there's no way for Jasmine to change it. 

https://github.com/angular/angular-cli/issues/17207 might be worth a read if you haven't already seen it. There's mention of TypeScript configurations that have worked for some folks, but not others.

Unless TypeScript changes course, I think affected users will have to choose between mocking imports and using a compiler that forbids mocking imports. My recommendation would be to use dependency injection rather than module imports for anything that you intend to mock.

For what it's worth, I don't think I agree with the choice the TypeScript team has made here. I'm no fan of mocking imports (I've yet to see a test suite that mocked imports and wasn't shot full of accidental test pollution). But regardless of that, I don't think it was wise to break so much existing code without providing an alternative.

**Comment by squidfunk** [comment]
I ran into the same problem and discovered that we could use `tslib` to work around the new restrictions imposed by TypeScript 3.9.2, at least for testing:

1. Install an older version  `tslib` with `npm install tslib@1.13.0`
2. Add `"importHelpers": true` to the `tsconfig.json` which you use for testing

While this is certainly not future-proof, it's at least a working solution until a better way is found.

**Comment by nico1510** [comment]
@squidfunk nice workaround!! I really hope that we find a future-proof solution but for now this will work thanks a lot :+1:

**Comment by squidfunk** [comment]
I think I've got a working hack, which doesn't depend on a specific version of `tslib` and works with TS > 3.9.

1. Set `importHelpers:  false`, so TypeScript will include all emit helpers in each file
2. We want to change `__createBinding`, as that's the one that breaks `spyOn` due to not being writable, thus we need to replace `__createBinding` with the definition from `tslib < 2`. I've had success using a custom require hooks with `pirates` and the following hack (i.e. a monkey patch):

``` js
const { addHook } = require("pirates")

addHook(code => {
  return code.replace(
    /__createBinding(.*?^}[)]{2};)\n/gms,
    "__createBinding = (o, m, k, l) => { \n" +
    "  if (l === undefined) l = k; \n" +
    "  o[l] = m[k];\n" +
    "};\n"
  )
}, { exts: [".ts"] })
```

Then, make sure the code is run before your tests, i.e. with `node -r ...` or something similar.

**Comment by fatso83** [comment]
@squidfunk Not sure where to put that code. Hints? This is interesting to users of Sinon, as it is similar to issues encountered by users of Webpack and other bundlers producing transpiled ESM.

**Comment by squidfunk** [comment]
@fatso83 Just put it in a file, i.e. `register.js` and ensure it's loaded before your program, e.g.

```
node -r register.js <program>
```

Also make sure to set `importHelpers` to `true` in `tsconfig.json` to make sure `tslib` is used.

**Comment by sgravrock** [comment]
This is now covered in the FAQ: https://jasmine.github.io/pages/faq.html#module-spy

**Comment by the-spyke** [comment]
The solution with `__createBinding` doesn't work as not all exports use it. For example, `export { asd } from './asd';` get converted into plane `Object.defineProperty`.
