### ISSUE TITLE
Feature request: Add a way to test failed expectations

### ISSUE THREAD

**Issue by SLaks** [jasmine/jasmine#1823]
I'm writing a shared utility that calls Jasmine `expect()` to verify complex state (for example, to verify that HTML elements are a11y-compliant in various ways).

I want to write a unit test for this utility that verifies that its expectations correctly fail with correct/helpful error messages.

In other words:

```js
function checkSomeStuff(stuff) {
  expect(...).to...();
  expect(...).to...();
  expect(...).to...();
}

describe('checkSomeStuff', () => {
  it ('passes with valid stuff', () => {
    checkSomeStuff(valid stuff);
  });  // This is fine.

  it ('fails with invalid stuff', () => {
    expect(() => checkSomeStuff(invalid stuff))
        .toFailExpectationsWith(/.* your stuff is invalid because.*some reason/);
  });  // This is no way to write this.
});
```

AFAICT, it is currently completely impossible to make a test pass (only) when an `expect()` call fails.

Can you please add some kind of `toFailExpectationsWith()` matcher, which would record expectation failures and allow the output error messages to be asserted about?

**Comment by sgravrock** [comment]
I can definitely see the value of that. Jasmine solves the same problem by booting two completely independent copies of itself. But that's not a particularly easy thing to do (maybe impossible outside of Jasmine itself?) and the resulting tests aren't very nice.

I think the interface that you propose would be particularly difficult to implement, given the existing structure of the code that runs expectations and routes failures to reporters. What about something like this?

```
    var result = jasmine.getEnv().testMatcher('toBe', 'expectedThing', 'actualThing');
    expect(result).toEqual({
      passed: false,
      message: "Expected 'expectedThing' to be 'actualThing'."
    });
```

That would still support testing the integration between custom matchers and the parts of Jasmine that process the results, including things like custom equality testers and custom object formatters. But it would be easier to implement and I don't think it would drive up the code complexity as much.

**Comment by SLaks** [comment]
That would only really be useful for writing tests for custom matchers; I'm trying to test code that calls `expect()` _from the code under test_ (like in the example) to make sure that the `expect()` calls are doing what I want them to.

I don't know enough about Jasmine's structure to suggest implementation details, but how about a global field that redirects `expect()`'s failure reporting?

Something like (pseudocode)

```
const reportedFailures = [];
expect.customReportFailure = (...args) => reportedFailures.push(args);
await userCode();
expect.customReportFailure = null;
expect(reportedFailures)....;
```

**Comment by slackersoft** [comment]
There is a lot going on inside Jasmine when you make a call to `expect` and I'm not sure how much of the internals we want to expose in order to make this kind of test easy. The goal behind some of the refactoring of custom matchers in Jasmine 2.0 was to make them easier to test (before loading them into Jasmine itself). But it doesn't sound like what you're trying to test here is the matchers themselves, but some other function that happens to invoke some number of expectations.

In general I would recommend against trying to actually test this function directly. Your tests that use it to check the functionality in the rest of the system should do that effectively. Even if you're building a library that exposes this method but doesn't use it directly, it sounds like you'd largely be writing tests about Jasmine and not your code, so you might want to evaluate what it is that you need to assert on.

Hope this helps.

**Comment by sgravrock** [comment]
Agreed. I think this is too niche to directly support.

[`throwUnless`](https://jasmine.github.io/api/5.1/global.html#throwUnless) handles the general case of testing that matchers integrate with Jasmine's equality system etc. correctly. The other option, for people who really want to integration-test code that calls `expect`, is to run the `expect`-calling code in a separate Jasmine CLI process and look at the output.
