### ISSUE TITLE
Consider queueMicrotask in clearStack

### ISSUE THREAD

**Issue by iliakan** [jasmine/jasmine#1835]
Right now, `MessageChannel/setTimeout` is used in browsers to clear stack (see https://github.com/jasmine/jasmine/blob/main/src/core/ClearStack.js#L41).

I tried to use Jasmine for running tests in the invisible iframe, and some browsers (Chrome namely) throttle such operations for out-of-view iframes. Brought me to something like 1 sec delay between tests. So tests took too long. 

I suggest to use `queueMicrotask` as a top-priority variant if available. Supported everywhere excepts IE. No throttling. Modern stuff.  The code is exactly the same as `setTimeoutImpl`, just use `queueMicrotask`.

**Comment by slackersoft** [comment]
Definitely intriguing... I'm a bit hesitant to introduce _another_, **higher priority** way for Jasmine to schedule itself to run your tests with async code. When we changed the code previously to use `MessageChannel` and work with async code differently, it broke a bunch of the interop that [Karma](https://github.com/karma-runner/karma) was doing, because Jasmine was always the highest priority thing in the queue, and nothing else got to do work.

I'm also a bit curious to know what the use case is for running your tests in a hidden iframe. Knowing this helps us prioritize the small amounts of time we have to work on Jasmine to have the highest impact.

**Comment by iliakan** [comment]
For me, I was running tests in an invisible `iframe`, and found out that they run terribly slow.

The root of the problem proved to be that `setTimeout` and `MessageChannel` are throttled to about 1 second.

So I had to fix it like this:

```js
// by default clearStack uses MessageChannel/setTimeout, they are throttled if iframe not visible
// so tests take a lot of time
jasmineRequire.clearStack = function() {
  return global => queueMicrotask.bind(global);
};
```

**Comment by sgravrock** [comment]
I can't reproduce the invisible iframe issue. My guess is that newer versions of Chrome don't have that problem. I *can* reproduce a similar issue when running in a minimized Chrome window. The throttling there is so severe that individual async tests that normally run very quickly time out.  Changing how Jasmine clears the stack isn't likely to fix that.

Iframe issues aside, it looks there are some very attractive performance improvements to be had here. Running Jasmine's own test suite (mostly very fast, mostly synchronous) on my own computer I get a 70% speed-up in Chrome, 55% in Node, 34% in Firefox, and a whopping 97% in Safari. (I'd expect to see a more modest, but still noticeable, speed-up in the average test suite on the average developer's computer.) That seems worth going after.

That said, I think this change carries a relatively high risk of breaking things as well as a relatively high risk of causing buggy async specs (especially ones that cause errors after signalling completion) to behave differently. I'd like to make sure that 4.0 has had adequate soak time before we make a change like this. The download stats make it look like we're already there, but [karma-jasmine is still pinned to Jasmine 3.x](https://github.com/karma-runner/karma-jasmine/issues/303). That suggests that almost no Angular users have actually switched to Jasmine 4 yet, and a significant portion of Jasmine 4 downloads may be from people who are actually running 3.x via Karma.

I think this is worth doing, but we should probably wait until 3-6 months after karma-jasmine releases support for Jasmine 4.

**Comment by sgravrock** [comment]
I did the above analysis with a clearStack implementation that just called queueMicrotask. We can't actually ship something like that because it prevents browsers from showing output or responding to user input except when a spec does a setTimeout. That's OK for Jasmine's very fast suite but it breaks down for large mostly-synchronous suites or suites containing numerous slow synchronous specs. To avoid those problems, all of the existing clearStack implementations do an actual setTimeout every 10 calls. So I did something similar:


```
getJasmineRequireObj().clearStack = function(j$) {
  let times = 0;

  function getClearStack(global) {
    return function(fn) {
      times++;

      if (times >= 10) {
        times = 0;
        setTimeout(fn);
      } else {
        queueMicrotask(fn);
      }
    };
  }

  return getClearStack;
};
```

and discovered that the performance gains I'd measured previously were entirely due to the missing setTimeout. In fact, the implementation above is 2.5-10x slower in Chrome and FF than what we have today. Performance on Node is roughly the same either way. The only environment where it's faster is Safari: I see a ~65% improvement in Safari 15 on my machine.

Unless anyone sees flaws in my implementation above that could have caused the slowdowns I experienced, I don't think this is something we can move forward with.

**Comment by dcsaszar** [comment]
> Unless anyone sees flaws in my implementation above that could have caused the slowdowns I experienced, I don't think this is something we can move forward with.

Here we go:

I tracked the time spent between consecutive calls `setTimeout` and put them in a histogram.
It turns out that after four fast `setTimeout` the browser starts throttling (clamping) to 4ms. I.e. the histogram tends to no longer grow in the positions 0 to 3.

This is less of a problem in an actual test suite, but hits immediately with a focused spec. (#2008)

In theory, jasmine could implement something like this internally and warn about browser throttling.

For Firefox, the throttling can be avoided by passing in `prefs: { 'dom.clamp.timeout.nesting.level': -1 }`.
Other browsers give the user less control over the clamping, so we need a workaround that in some form resets the browser's internal `setTimeout` threshold.

What I've tried so far:

### requestIdleCallback before throttling kicks in
```js
if (willStartThrottling) setTimeout(() => requestIdleCallback(fn))
```
* Works OK in Chrome.
* Makes Firefox very slow.
### postMessage before throttling kicks in
```js
if (willStartThrottling) setTimeout(() => postMessage(fn))

// for `postMessage` I copied `messageChannelImpl` and removed the `currentCallCount` parts.
```
* Good results in Chrome, Webkit, and Firefox.
* Firefox needs `dom.clamp.timeout.nesting.level: -1` to keep focused test fast.

I tried these implementations of `willStartThrottling`:
* Simple: `true` for every fourth `setTimeout` call.
* Adaptive: `true` if four consecutive `setTimeout` calls were less than 4 ms apart each. Results in a ~ 6 % gain over the simple approach in Webkit-based browsers.

## Measurements

<img width="898" alt="image" src="https://github.com/user-attachments/assets/c7203ba4-da5e-49e5-b40f-d716170ddc3f">

https://plotly.com/~dcsaszar/100/

## Ideas
* Reproduce my results on another test suite
* Decide for "Adaptive" or "Simple" depending on the code complexity and Webkit performance requirements
* Reopen this issue
* Implement `postMessage before throttling kicks in`
* Add a hint about Firefox and `prefs: { 'dom.clamp.timeout.nesting.level': -1 }` to the docs (which?)
* Drop `messageChannelImpl` and Safari UA detection code
* Close related issues (#2008, #2034)

**Comment by sgravrock** [comment]
Interesting analysis. It might be a few days or more before I have time to dig into this but I wanted to take a moment to say thanks.

**Comment by dcsaszar** [comment]
Implementation of "Simple": https://github.com/dcsaszar/jasmine/tree/dave-queue-microtask
