### ISSUE TITLE
Intermittent unit test failures after upgrading from version 3.5.0 to 3.6.0

### ISSUE THREAD

**Issue by timvandermeij** [jasmine/jasmine#1840]
Mozilla's PDF.js project is using Jasmine for its unit tests. After upgrading Jasmine from version 3.5.0 to 3.6.0 we got intermittent unit test failures. They were resolved again when we downgraded to version 3.5.0. The main error we got, on random tests, was `Unhandled promise rejection: AbortException: Worker was terminated.`.

I don't have a minimal test case because of the random behavior, but it can be reproduced using the following steps:

1. `git clone https://github.com/mozilla/pdf.js.git`
2. `cd pdf.js`
3. Edit `package.json` to set `jasmine` to `3.6.0`.
3. `npm install`
4. `gulp unittest`

If you run the unit tests once or twice, it should already fail with random tests throwing an `AbortException`. If you revert to 3.5.0, the problem disappears.

* Version used: 3.6.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 14.6.0
* Operating System and version (desktop or mobile): Arch Linux
* Link to your project: https://github.com/mozilla/pdf.js

**Comment by sgravrock** [comment]
We made some changes in 3.6 to tighten up Jasmine's treatment of unhandled promise rejections, and it's possible that that's causing Jasmine to surface errors in your test suite that previously went unnoticed. I see a couple of places in the pdf.js codebase where an `AbortException` is created with the message `Worker was terminated`. Presumably one or more of those is the ultimate source of the error. 

I haven't dug deeply into this, but based on your description and a quick look at the pdf.js code my guess is that there are a few tests that run async code but tell Jasmine that they're done before all of that async code has finished running. When that happens, code from that test can interleave with -- and be affected by -- other tests. That can lead to intermittent failures like you're describing.

That sort of problem can be... let's just say "fun" to track down. But in this case there are a small handful of candidate sources that could be throwing the exception, and that helps. It might be easiest to work backwards from those sites. For each potential throw site, do all of the tests that call that it (a) wait for all of that code to finish running, and (b) report errors to Jasmine?

Since test order is a likely factor, running the tests in a consistent order can make debugging *much* easier. To do that:

1. Run the tests in such a way that the browser window won't get closed as soon as they're done. (This probably has to do with the pdf.js build system, not Jasmine itself.)
2. Reload until a failure occurs.
3. Click the link next to the word "seed" in the status bar.
4. Subsequent reloads will use the same random seed, and thus the same test order. With any luck the error will reproduce more consistently.

I hope this helps.

**Comment by timvandermeij** [comment]
Thank you for the information! Indeed, intermittents are never nice to work with, but I think this gives us a good direction to look further. PDF.js is highly asynchronous, but we didn't know that there was a behavior change in 3.6 that might bring pre-existing issues in the tests to the surface.

I'm closing this in the hope that we'll find the issue on our side. If not, we'll report back.

**Comment by slackersoft** [comment]
Some additional info my my digging in. I was only able to reproduce any issues in Chromium. Firefox (nightly and stable) and Chrome stable don't show any issues, even when running with the same seed that fails in Chromium (74824).

**Comment by timvandermeij** [comment]
I just wanted to report back that we fixed 6 of out 7 intermittents that were found after the Jasmine upgrade. It indeed turned out to be caused (mostly indirectly) by our own code. There is one remaining that is _very_ intermittent, but I'm certain given the other ones that it's also caused by our code somehow and we'll find the cause of it. Thank you for your assistance!

**Comment by sgravrock** [comment]
Thanks for following up. I'm glad things are going well. Good luck chasing down that last one, and let me know if I can do anything else to help.
