### ISSUE TITLE
toHaveBeenCalledWith and updated object

### ISSUE THREAD

**Issue by sevkioruc** [jasmine/jasmine#1846]
Hello to everyone,

This function take a book as parameter and this function is in a component.

The test written below was successful. But I was expecting it to fail.
 
- What do you think is the reason for this ?

- How can I make an in-depth match ?

````js
addBook(book) {
    ...
}
````

````js
it('....',() => {
   spyOn(component, 'addBook');

   const newBook = {
       name: 'Dummy  Name',
       author: 'Dummy Author Name',
       ...
   }

   component.addBook(newBook);
   
   newBook.name = 'New dummy name';

   expect(component.addBook).toHaveBeenCalledWith(newBook);
})
````

**Comment by sgravrock** [comment]
By default, spies capture their arguments by reference. (This is partly to conserve memory and partly because not all objects can be cloned.) As a result, the expectation in your example does a deep equality comparison between `newBook` and itself, which will always pass.

I would rewrite your example like this:

```
it('....',() => {
   spyOn(component, 'addBook');

   const newBook = {
       name: 'Dummy  Name',
       author: 'Dummy Author Name',
   }

   component.addBook(newBook);
   
   const expectedBook = {
      ...newBook,
      name: 'New dummy name'
   };

   expect(component.addBook).toHaveBeenCalledWith(expectedBook);
});
```

If that's not an option for some reason (e.g. perhaps it's your code under test that's mutating the argument to the spy and you can't avoid that), you can tell a spy to do a shallow clone of its arguments at the time that they're captured: `component.addBook.calls.saveArgumentsByValue();`. That will also cause the spec to fail.

**Comment by sevkioruc** [comment]
Yes now it worked as I wanted. Thanks for the help.
Good work.
