### ISSUE TITLE
How do I test es modules?

### ISSUE THREAD

**Issue by Neutrino-Sunset** [jasmine/jasmine#1852]
I don't see aything in the documentation that describes how to test code in es modules. It certainly doesn't seem to work out of the box.

[ESM](https://github.com/standard-things/esm) has been asolution to this in the past, but that project appears to be dead now.

Transpiling via Babel whatever is not a solution since that transpiles to CommonJs format and you end up testing something that behaves very differently from what you're actually building.

**Comment by sgravrock** [comment]
I assume you're using the Jasmine NPM module. It doesn't have support for ES modules yet, although I'm hoping to land that on master soon. In the meantime, there are a couple of potential options. ES modules should work fine in the browser as long as the script tags are set up correctly. This is do-able with Jasmine standalone or, I'm told, with Karma. [This approach](https://github.com/jasmine/jasmine-npm/issues/150#issuecomment-463674937) minus the stack trace changes should also work, although I haven't tried myself.

**Comment by zombieleet** [comment]
@sgravrock I have a setup I am currently using but the problem is that I can't collect coverage from the setup

**Comment by sgravrock** [comment]
@zombieleet That's tough to address without knowing a lot more about your setup. Your best bet might be to ask for help from the folks who maintain the code coverage tool that you're using.

**Comment by zombieleet** [comment]
@sgravrock I just switched to c8 with the same setup and everything works fine now

**Comment by sgravrock** [comment]
ES module support is on the main branch of jasmine-npm, but isn't released yet. If you want to try it out:

* Depend on `https://github.com/jasmine/jasmine-npm.git` instead of a released version of the `jasmine` package.
* Make sure any spec files or helpers that should be loaded as ES modules have names ending in `.mjs`.
* If you're using Node 10 or 11, run `node --experimental-modules /path/to/jasmine` instead of `jasmine`.

Bug reports and other feedback are appreciated.

**Comment by sgravrock** [comment]
ES modules are supported in version 3.6.2 of the Jasmine npm package, which was released yesterday. See <https://jasmine.github.io/setup/nodejs.html#using-es-modules>.
