### ISSUE TITLE
Object reset inside it function callback

### ISSUE THREAD

**Issue by db-conception** [jasmine/jasmine#1864]
Hi,

I am a newbie in typescript and jasmine. 

I have a problem, when I test my object outside the it function, the fields of my object are right. But inside my lambda function callback passed to the it function, my object is reset. 

```javascript
 describe('add to cart from empty cart', () => {
    
    it("1 == 1", () => expect(1).toBe(1));
    // jasmine.clock().install();
    service = new CartService( new DataService());
    let prod = {id: 3, libelle: "Produit", price : 10, price_html : "10€"} as Product;
    it(`start with cart who doesn't contains the product ${prod.id}`,
      () => expect( ((<any>service).collector as Cart).containsKey(prod.id)).toBe(false) );
    
    console.log("before addproduct", service["collector"]);
    
    service.addProduct(prod);  

    console.log("after addproduct", service["collector"]);

    it(`end with cart who does contains the product ${prod.id}`,
      () => { 
        console.log("on anonymous function end with", service["collector"]);
        expect( ((<any>service).collector as Cart).containsKey(prod.id)).toBe(true)
      
      });
  })
```

As you can see on the console printing, my object lost data inside the it callback : https://i.imgur.com/3d7wdc6.png

I think it is not a ts problem. Because I try to reproduce in a js fiddle the problem with my "own it method" and I do not reproduce the bug : https://jsfiddle.net/f2d3jtxm/

Can you help to understand why ? How to fix it ?

Please see the full file joined
[ts it callback lost data.zip](https://github.com/svi3c/jasmine-ts/files/5500910/ts.it.callback.lost.data.zip)

## Version of jasmin 
3.6.3

**Comment by db-conception** [comment]
The problem is resolve when I comment two instruction from my beforeEach function 

```javascript
beforeEach(() => {
    TestBed.configureTestingModule({});
    // service = jasmine.createSpyObj('CartService', {
    //   collector : new Cart()

    // }) as CartService;
    //service = new CartService( new DataService());
    // service = TestBed.inject(CartService);
  });
```

Can you explain me why ?

**Comment by sgravrock** [comment]
It sounds like you were expecting `service` to retain the value that it was set to in the inner `describe` callback, not the value it was set to in the `beforeEach` callback.

The `describe` callbacks are called first, while Jasmine is initializing. The inner one sets `service` to one value. Later on, immediately before each test runs, the `beforeEach` callback is run. It overwrites the previous value of `service` with a new one each time. Commenting out the code in the `beforeEach` fixes that problem but introduces a new one: Now the exact same object is reused for all the tests, which means they can affect each others' behavior. The fix is to do all setup inside the test itself, in a `beforeEach`, or in a `beforeAll`, never directly inside `describe`.

For the same reason, `service.addProduct(prod)` in the inner `describe` runs before any of the tests, not in between two particular ones.

A good general rule of thumb is not to do anything inside `describe` except for calling Jasmine functions like `describe`, `beforeEach`, and `it`.

**Comment by db-conception** [comment]
Thank you very much
