### ISSUE TITLE
Possible bug when using asymmetric matchers and withArgs()

### ISSUE THREAD

**Issue by vitaly-rudenko** [jasmine/jasmine#1877]
## Suite that reproduces the behavior
```js
const anything = { asymmetricMatch: () => true };
const spy = jasmine.createSpy('spy');

spy.withArgs().and.returnValue('no arguments');
spy.withArgs(null).and.returnValue('null');
spy.withArgs(undefined).and.returnValue('undefined');
spy.withArgs(false).and.returnValue('false');
spy.withArgs(anything).and.returnValue('anything');

expect(spy()).toBe('no arguments');
expect(spy(null)).toBe('null');
expect(spy(undefined)).toBe('undefined');
expect(spy(false)).toBe('false');
expect(spy(123)).toBe('anything');
```

## Expected Behavior
Due to specific spy's initialization order, I expected these tests to succeed.

## Current Behavior
This line:
```js
spy.withArgs(anything).and.returnValue('anything');
```
Causes these errors:
```
Expected 'anything' to be 'null'.
Error: Spy 'spy' received a call with arguments [ 123 ] but all configured strategies specify other arguments.
```

## Possible Solution
Perhaps argument checks should be executed in their initialization order.
If current behavior is intended, I would like to know if there is any workaround or at least an explanation.

## Context
I would like to be able to create very specific spies with predictive behavior.

## Your Environment
* Version used: 3.6.3
* Environment name and version (e.g. Chrome 39, node.js 5.4): node 12.9.0

**Comment by sgravrock** [comment]
This is an interesting edge case. I can simplify it to this:

```
const anything = { asymmetricMatch: () => true };
const spy = jasmine.createSpy('spy');

spy.withArgs(false).and.returnValue('false');
spy.withArgs(anything).and.returnValue('anything');

expect(spy(123)).toBe('anything');
```

`spy.withArgs` either registers a new strategy or returns an existing one that matches the specified arguments. This is so that you can reconfigure a previously registered strategy. Since `anything` matches anything, `spy.withArgs(anything)` returns one of the previously registered single argument strategies rather than adding a new one. The result is a single strategy which matches the single argument `false` and returns `anything`. I'm sure that's not what you expected, but I think it's an inevitable result of both allowing spy strategies to be reconfigured and allowing asymmetric matchers to be used with spy strategies.

In your case I recommend using `callFake` instead of `withArgs`:

```
spy.and.callFake(function() `{
   if (arguments.length === 0) {
      return 'no arguments';
   // ...
   } else if (arguments[0] === 'false) {
      return 'false';
   } else {
      return 'anything';
});
```

In general, avoid creating multiple spy strategies that can match the same call. Even it works, it's likely to be hard to understand.

**Comment by vitaly-rudenko** [comment]
Oh, I see, it reuses the spy.
That's nice, though it feels weird for (anything) and (false) to be considered the same.
But I guess there's no solution for withArgs() in this edge case, except for callFake(), which is not very good for my purposes.
Thanks for the explanation.

**Comment by sgravrock** [comment]
>  That's nice, though it feels weird for (anything) and (false) to be considered the same.

The custom asymmetric matcher in your example compares equal to any value, including unusual ones like false, undefined, null, NaN, etc. If that's not what you want, you can write a more specific matcher, e.g.:

```
const anythingButFalse = { asymmetricMatch: (compareTo) => compareTo !== false };
```

**Comment by vitaly-rudenko** [comment]
I mean, that's what I want it to do, though I didn't expect it to be used to search for existing spies.
I expected asymmetric matching to only be used for argument matching when the spy is actually executed:
```js
spy.withArgs(jasmine.any(Boolean)).and.returnValue('ok');
expect(spy(false)).toBe('ok');
expect(spy(false)).toBe('ok');
```

But it's somewhat restricting that the same logic is used to reuse existing spies like these:
```js
spy.withArgs(false) === spy.withArgs(anything)
```

What feels more predictive is this:
```js
spy.withArgs(false) === spy.withArgs(false)
spy.withArgs(anything) === spy.withArgs(anything)
spy.withArgs(false) !== spy.withArgs(anything)
```
Though I see possible problems with this approach, e.g. if "anything" is generated each time, then jasmine would have no way to tell that they are the same: ```spy.withArgs(anything()) === spy.withArgs(anything())```

What do you think?

**Comment by sgravrock** [comment]
Equality in Jasmine (and other JS testing frameworks) is [much more complicated than that](https://github.com/jasmine/jasmine/blob/324bc201c287c1550c5c6626fcc52637ca285105/src/core/matchers/matchersUtil.js#L86-L643), even in the context of `spy.withArgs`. I'm not eager to add to that complexity.

But there's a bigger problem. Let's say that `withArgs` behaved the way you want it to. What happens when the spy is actually called. If a spy has one behavior configured for when it's called with any argument and another behavior configured for when it's called with `true`, which behavior is used when the spy gets called with `false`? I had to try it out to find out what the current version of Jasmine does, even though I built the feature that we're talking about. The code above asks the spy to do two contradictory things. It asks it to respond to being called with `false` by returning `"false"` and by returning `"anything"`, and it's not possible to do both of those things. Jasmine currently resolves that conflict in one way, but there's no guarantee that that won't change in the future. And there's no guarantee that future maintainers of the test will interpret the contradiction the way you do.

There are two ways to resolve that contradiction:
1. Modify the asymmetric matcher so that it doesn't overlap with other uses of `withArgs` on the same spy, or
2. Use `.and.callFake` instead asymmetric matchers.

I know you don't like those options but I really think they're the best way to write the kind of test you've described.

**Comment by vitaly-rudenko** [comment]
I'm well aware that your equality check is quite comprehensive, but I don't think it's a good reason to close this issue.
I don't have much experience in other JS testing frameworks, I'll check their behavior later.
What I'm trying to do, though, is to copy behavior of Mockito (Java framework for mocking).

> What happens when the spy is actually called. If a spy has one behavior configured for when it's called with any argument and another behavior configured for when it's called with true, which behavior is used when the spy gets called with false?

They should work in order they were initialized. I think it's reasonable and seems like a better solution for me (comparing to how it works now).

Here's an example of Mockito (these tests pass):
```java
public class MatcherTests {
    TestClass test;

    @BeforeEach
    void setup() {
        test = mock(TestClass.class);
    }

    @Test
    void test1() {
        when(test.method(anyBoolean())).thenReturn("any");
        when(test.method(true)).thenReturn("true");

        assertEquals(test.method(false), "any");
        assertEquals(test.method(true), "true");
    }

    @Test
    void test2() {
        when(test.method(true)).thenReturn("true");
        when(test.method(anyBoolean())).thenReturn("any");

        assertEquals(test.method(false), "any");
        assertEquals(test.method(true), "any");
    }

    static class TestClass {
        String method(boolean test) {
            return "none";
        }
    }
}
```

**Comment by vitaly-rudenko** [comment]
Yeah I've checked Sinon and Jest-When and they also work not as I expected:
```js
const spy = sinon.stub();
spy.withArgs(sinon.match.bool).returns('any');
spy.withArgs(true).returns('true');

sinon.assert.match(spy(false), 'any');
sinon.assert.match(spy(true), 'true'); // fails

// ---

const { when } = require('jest-when');

const spy = jest.fn();

when(spy).calledWith(expect.anything()).mockReturnValue('any');
when(spy).calledWith(true).mockReturnValue('true');

expect(spy(false)).toBe('any');
expect(spy(true)).toBe('true');
```

Okay then, I guess that's how things are ¯\_(ツ)_/¯ 
Thanks for the response!
