### ISSUE TITLE
Jasmine Typescript UnitTest with reference path

### ISSUE THREAD

**Issue by VishakVKurup123** [jasmine/jasmine#1887]
I facing an issue running jasmine tests for typescript.
My target project is having a similar structure.

[scripts.zip](https://github.com/jasmine/jasmine/files/6127142/scripts.zip)

[tests.zip](https://github.com/jasmine/jasmine/files/6127149/tests.zip)

When I run the npm test I get the following error:

**npm : tests/Student.test.ts(4,26): error TS2304: Cannot find name 'MyTestApp'.**

The issue can be solved if we use import/export statements but my target project is huge and cannot change at this moment. Can anyone give a solution? npm build runs without any error. 

**Expected result**
Tests should run

**Actual result**
Test fail to run and shows error
**npm : tests/unit.test.ts(4,26): error TS2304: Cannot find name 'MyTestApp'.**

Note: I tried using rewire, but it fails to find other modules referred by script file.

**Comment by sgravrock** [comment]
It's hard to tell what the cause of the error is from the sample that you provided. It's missing some things, all of the code that could have generated the error message is commented out, and I can't tell where the `tests` and `Scripts` directories are relative to each other on your computer. My guess is that the `Scripts` directory is located somewhere other than `../Scripts` relative to the `tests` directory, and you need to fix the file paths in the test to match the way your project is actually laid out.

Jasmine doesn't change anything about how modules load, and it doesn't know anything about rewire. So `require` should resolve paths the same way as it does anywhere else, and rewire should work the way the rewire documentation says it does.

I hope this helps. If you still think your problem is Jasmine-related, feel free to put together a complete, self-contained, minimal, runable example in a single zip file (or better yet using a site like https://codepen.io/ ) and I'll take another look.

**Comment by sgravrock** [comment]
Closing because this doesn't look like a bug in Jasmine and we haven't heard anything in a while. If you're still having trouble, feel free to open a new issue with a complete, self-contained, minimal, runable example that demonstrates the problem.
