### ISSUE TITLE
Continued support for async tests with done callbacks

### ISSUE THREAD

**Issue by bordecal** [jasmine/jasmine#1893]
In [version 3.7.0](https://github.com/jasmine/jasmine/releases/tag/v3.7.0), a change was introduced to "Warn if a spec or before/after function both takes a callback and returns a promise".  Unfortunately, I can't seem to locate any explanation of why this change was introduced.  There doesn't seem to be any mention in the documentation or the repo issues, and commit 51ad18cb2814e6ed04b266e34526674f53703aba doesn't seem to have been included in a pull request that might provide additional detail.

Following introduction of this change, any use of a `done` callback in a promise-returning test results in reporting of the following deprecation warning:

> DEPRECATION: An asynchronous before/it/after function took a done callback but also returned a promise. This is not supported and will stop working in the future. Either remove the done callback (recommended) or change the function to not return a promise.

While I certainly understand that `done` callbacks are often used unnecessarily with promise-returning tests, there are use cases that seem quite legitimate.  For example, one may need to verify expectations in the subscription callback of an observable within a test that also needs to use promises outside that subscription:

```ts
it('does something', async (done: DoneFn) => {
    await somethingOrOther();

    someObservable.subscribe(() => {
        // Verify expectations here
        done();
    };

    await somethingElse();
});
```

While it is generally possible to adjust such tests to avoid either the returned promise or the `done` callback, this usually has a deleterious impact on test readability (sometimes minor, sometimes quite substantial).  If enabling the authoring of tests that are easy to understand is a goal for Jasmine, might it be worthwhile to find a way to continue to support use of a `done` callback in a promise-returning runnable?

**Comment by slackersoft** [comment]
[This](https://github.com/jasmine/jasmine/issues/1731) is probably the original discussion around the feature. For the various issue definitely take a look at @sgravrock's [comment](https://github.com/jasmine/jasmine/issues/1731#issuecomment-513334260). The deprecation message here is to alert the user that they've probably done something that has unpredictable results.

**Comment by bordecal** [comment]
Given the impact on test readability, might it be worthwhile to think about changing the logic for detecting "doneness" so that resolution of the returned promise is not considered if the implementation callback function has the `done` callback parameter?

**Comment by sgravrock** [comment]
The problem is that for every person who thinks the `done` parameter should takes precedence, there's someone who thinks the promise should take precedence, someone who thinks that whichever one completes first should count, and someone who thinks that Jasmine should wait until they both complete. 

I also don't think that the change would improve readability. From your comments in this issue, I think I understand that you're using `async` only to be able to `await` inside the function and want Jasmine to rely only on the `done` callback. But if I encountered it in the wild I'd have assumed that the intent was for the test to finish when `done` was called or when the returned promise resolved, whichever happened first.

FWIW, I would either rewrite the test to use promises or do something like this to make it clear that async-ness is not how it signals completion:

```
it('does something', (done: DoneFn) => {
   (async function() {
       await somethingOrOther();

       someObservable.subscribe(() => {
           // Verify expectations here
           done();
       };

       await somethingElse();
    }());
});
```

**Comment by coyoteecd** [comment]
@bordecal for what is worth, I have been using toPromise() to address that particular scenario in the past, e.g.

```js
it('does something', async () => {
    await somethingOrOther();

    await expectAsync(someObservable..toPromise()}.toBeResolvedTo(....);

    await somethingElse();
});
```

This has an added advantage when writing failing tests: if you put expectations in the error callback and the observable succeeds, you'll never notice because the expects in the error callback never execute (we actually ran into this). Whereas the toPromise() approach will give you a failing test because you expect a rejected promise and you got a resolved one.

**Comment by thw0rted** [comment]
As a data point, I return a promise because I want rejection of the promise to fail the test.  The first test that tripped this warning was

````ts
    it("emits an item when search completes", done => {
        loader.items$.subscribe(added => {
            expect(added.length).toBe(1);
            expect(added[0].docId).toBe("Doc 0");
            done();
        });

        return loader.start();
    });
````

If the Promise returned by `loader.start()` resolves, nothing happens, but if it rejects, the test fails.  I could convert this to an `async` function and `await` it instead, which I think behaves the same way, but it seems like both constructs should be supported.

You say that some people expect the test to finish when the returned Promise completes even if `done` was not called, but that sounds like an obvious error to me -- if you provide a `done` argument in a non-async spec, and don't call it, the test cannot ever finish.  The `done` function takes precedence over test function return.  Why should the async case be any different?  It's a consistent model.

**Comment by thw0rted** [comment]
Actually I'm not sure how to rewrite this.

Making the spec `async` always "returns a Promise" and thus hits this warning.

I tried changing the last line to `expectAsync(loader.start()).not.toBeRejected();`, but this fails with `...ran a "toBeRejected" expectation after it finished.` and actually suggests that you return its result, contradicting the error message in the OP here.

The only other solution I can come up with is incredibly cumbersome, separately tracking whether the observable subscription has fired *and* that the Promise has resolved and calling `done` after both.  (I saw the suggestion to convert the Observable to a Promise but I do have other tests where the subscription has to fire more than once, so that's out.)

**Comment by sgravrock** [comment]
@thw0rted If I understand correctly, the promise returned from `loader.start` will always be either resolved or rejected before the subscribe callback is called. If that's the case, I'd write the spec like this:

```
    it("emits an item when search completes", async => {
        let addedItems;
        loader.items$.subscribe(added => addedItems = added);

        await loader.start();
        expect(addedItems.length).toBe(1);
        expect(addedItems[0].docId).toBe("Doc 0");
    });
```

Or if you prefer promises to async/await:

```
    it("emits an item when search completes", => {
        let addedItems;
        loader.items$.subscribe(added => addedItems = added);

        return loader.start().then(() => {
            expect(addedItems.length).toBe(1);
            expect(addedItems[0].docId).toBe("Doc 0");
        });
    });
```

If the returned promise might be resolved after the subscribe callback is called, you can do this:

```
    it("emits an item when search completes", => {
        const subscribePromise = new Promise(resolve => {
            loader.items$.subscribe(added => resolve(added));
        });
        const startPromise = loader.start();

        return Promise.all([subscribePromise, startPromise])
            .then(added => {
                const [added, ignored} = await Promise.all([startPromise, subscribePromise]);
                expect(added.length).toBe(1);
                expect(added[0].docId).toBe("Doc 0");
            });
    });
```

(All untested, so beware of mistakes.) The common thread is that each form constructs a single promise chain that resolves or rejects exactly once, and returns that.

**Comment by sgravrock** [comment]
On a broader note: I'm happy to help folks write better async tests (subject to the limits of my free time and motivation, of course). This stuff can be hard and an extra pair or three of experienced eyes can help. But I'm unlikely to spend more time debating whether & how Jasmine should support mixing forms of async in a single spec.

I added the deprecation warning because I'd seen the problems that people were running into as a result of trying to mix multiple forms of async. That's something that was never intended to work, never had a stable behavior, is likely to break (again) in the future, and is likely to confuse other readers of the specs.

On that last point: I appreciate that some of you posting in this thread think that your interpretation of mixing callbacks and promises is obviously correct. But plenty of other people think it's just as obvious that they're right and you're wrong. If you doubt that, please dig through the issues here and especially at Jest and Mocha. You'll find plenty of equally reasonable people arguing, with equal persuasiveness, for behaviors that conflict with what you want.

An API that any two people are likely to understand differently is a poor API that's bound to cause problems (and in this case, already has). That would be a good reason to avoid it even if there weren't any other drawbacks.

My plan is to leave the warning in and continue to treat this as the "if it breaks you get to keep both pieces" situation that it's always been, at least for the rest of 3.x. I understand that that's disappointing to some of you. But any choice here is going to disappoint somebody.

If you really want to be able to mix promises and callbacks, you can always do it by wrapping `it`, like so:

```
function mixedAsyncIt(name, fn) {
    it(name, function(done) {
        function innerDone() {
            // Decide whether to call done() now
        }
        fn(innerDone)
            .then(function() {
                // Decide whether to call done() now
            },
            function(error) {
                // Decide whether to call done.fail(error) now
            });
    });
}
```

But I advise against it.

**Comment by thw0rted** [comment]
Thanks for your prompt response, and I think I understand where you're coming from a bit better now.  I went away and had a think, and what I realized is that a good test function should test one thing.  The test should complete when that one thing has happened and you can make your expectations.  You just have to carefully consider the flow of the test -- which as you say can be hard! -- and either `await` your way to that outcome or put a `done()` at that point.

In my case, I realized that the one thing (the observable emits) was already calling `done`, and just writing `loader.start().catch(fail)` would take handle ensuring that the promise does not reject.  I don't actually care if the test completed before that promise resolves (it shouldn't be able to), and even if it somehow rejects after the test completes, Jasmine should warn me that `fail` was called too late.  (Right?)

**Comment by sgravrock** [comment]
>  I don't actually care if the test completed before that promise resolves (it shouldn't be able to), and even if it somehow rejects after the test completes, Jasmine should warn me that fail was called too late. (Right?)

Yes (usually), but probably not the way that you'd want it to. Calls to `done.fail` after the spec finishes are treated like any unhandled exception or unhandled promise rejection: They get reported as failures of the spec or suite that's running at the time of the error. This is partly because the result of the original spec has already been sent to [reporters](https://jasmine.github.io/api/edge/Reporter.html) by then and can't be changed. 

Worse, if your test keeps running code after it tells Jasmine that it's done, then it'll interleave with the execution of other tests and with Jasmine itself. That's a sure way to get difficult-to-diagnose random test failures as the code from one test interferes with the code from another. The only way to get reliable async tests is to write them so that they signal completion exactly once, after all the code that they've caused to run is done running. (This is true of every testing framework I've seen that supports asynchronous tests, not just Jasmine or other Javascript testing frameworks.)

It sounds like `loader` might be designed in a way that makes it difficult or impossible for other code to know when it's really done. My suggestion is to try writing some code in your application (not using Jasmine) that calls `loader.start()`, waits for it to finish, and logs "done". Then use logging or a debugger to prove to yourself that no code related to `loader` runs after the message is printed. If you can do that, then you've figured out how to write the test. If you can't do that, then you probably can't write a reliable test without first fixing `loader`.
