### ISSUE TITLE
Report spec for unhandled promise rejections

### ISSUE THREAD

**Issue by swendlandt** [jasmine/jasmine#1896]
## Expected Behavior
When an unhandled promise rejection is detected by Node.js the test run should fail and it should be visible which spec caused the unhandled promise rejection.

## Current Behavior
The test run fails but it is not visible from which spec the unhandled promise rejection originated.

## Possible Solution
Wrap promises to include the spec and report it in the error

## Suite that reproduces the behavior (for bugs)
```javascript
describe("sample", function() {
    it("causes unhandled promise rejection", () => {
        setTimeout(() => Promise.reject());
    }
});
```
## Context
This is a problem especially for big projects where many contributors add their tests.

## Your Environment
* Version used: 3.6.0
* node.js 12.19

**Comment by sgravrock** [comment]
Jasmine treats an unhandled promise rejection as a failure of the spec or suite that was running when the rejection occurred. (That's really all it can do, since asynchronous functions don't have "ancestry" that would allow Jasmine to determine where they came from.) If you're seeing unhandled rejections that aren't reported correctly, the most likely cause is a spec that continues executing, and causing errors, after it's already told Jasmine that it's done. That's exactly what's happening in the sample that you posted. It's a synchronous spec, so Jasmine understands that it's done as soon as it returns. But it causes the unhandled promise rejection later on. Because the spec that caused the rejection is already finished when it happens, Jasmine has no way of associating the rejection with the spec.

Have a look at the [async tutorial](https://jasmine.github.io/tutorials/async), and check for specs that signal completion before they're actually finished.

**Comment by swendlandt** [comment]
I understand that the root cause is a badly written test here. But if you have a big project with many tests from different contributors it can be difficult to find out which test is causing the failure.

Because of this it would be a helpful feature to somehow see which spec spawned the rejected promise. I am also not sure if it is possible though.

**Comment by slackersoft** [comment]
If the promise is returned by an async spec, then Jasmine should already be listening for when that promise gets rejected to move on to the next part of your suite. The problem here is that Jasmine doesn't have a reference to the Promise to be able to do anything about it. I would be happy to talk through some suggestions on how folks might handle this type of problem, but I'm not sure what Jasmine itself can do in this situation.

**Comment by sgravrock** [comment]
This would be an extremely valuable enhancement. Too bad it's impossible. The problem is that function calls don't have an "ancestry" that's visible at runtime, except in three very specific circumstances:

* If the function is called synchronously, `new Error().stack` will contain a human-readable description of the call stack.
* If the function is called synchronously, there might be a (nonstandard and deprecated) `caller` property that refers to the function's caller.
* If the runtime is a new enough version of V8 *and* the function's caller `await`ed the return value of the function, `new Error().stack` will include asynchronous calls.

It's important to understand just how limited that third case is. The only way to get an async stack trace is if there's an unbroken chain of `await`s connecting the promise rejection to a rejection handler. In other words, you can only track where a rejection "came from" if it's correctly handled.

Although Jasmine can't solve this problem, there are a couple of things you can do to mitigate it:

1. Work in small steps. The smaller the code change you made since the last time you were green, the easier it is to find the source of an unhandled rejection.
2. Use static analysis tools to detect code that doesn't handle promise rejections. I haven't tried it myself, but the typescript-eslint [no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md) rule appears to do just that.
