### ISSUE TITLE
Provide runtime abstraction like Jest

### ISSUE THREAD

**Issue by evenstensberg** [jasmine/jasmine#1911]
## Are you creating an issue in the correct repository?
Yes

## Expected Behavior
It would be great to test with Jasmine in the browser with React. A proposed solution will make this work.

## Current Behavior
No way to test React with Jasmine

## Possible Solution
Copy Jest

## Suite that reproduces the behavior (for bugs)
N/A
## Context

Jasmine is great, and it could be better with this. When doing this, you end up with a very powerful and programatic platform that you can run tests from. I hope you will implement this! 

## Your Environment
N/A

**Comment by slackersoft** [comment]
Once you're looking at running your tests in the browser, there typically isn't quite as much customization for tests that you need. You'll already need to be compiling your files and everything to produce code the browser can actually run, so you shouldn't need to do all of the setup included in our [react with npm tutorial](https://jasmine.github.io/tutorials/react_with_npm).

Once you've got your toolchain setup to build your files you should be able to use [jasmine-browser-runner](https://github.com/jasmine/jasmine-browser) to start up a server to serve your tests and even run them in CI. This is what Jasmine itself uses to run it's own tests in browsers. The current implementation just serves files from disk since most projects toolchains are setup to build the files more-or-less continuously.

If you would like to see a _specific_ improvement to the browser running capabilities, we'd be happy to review a [pull request](https://github.com/jasmine/jasmine-browser/pulls).

**Comment by evenstensberg** [comment]
Thx!
