### ISSUE TITLE
Unhandled promise rejection: false positive

### ISSUE THREAD

**Issue by andreashuber69** [jasmine/jasmine#1917]
## Are you creating an issue in the correct repository?
I think so, I was directed here from https://github.com/karma-runner/karma/issues/3683

## Expected Behavior
No error should be reported, the rejecting promise **is** being handled, see below.

## Current Behavior
I'm getting the message:
```
Unhandled promise rejection: Error: Operation failed.
```
## Possible Solution
This problem was introduced with #1778, it appears the logic detecting unhandled rejections does not wait for the promise to complete. 

## Suite that reproduces the behavior (for bugs)
```typescript
describe("", () => {
    it("", async () => {
        const rejectingPromise = Promise.reject(new Error("Operation failed."));
        await new Promise<void>((resolve) => setTimeout(resolve, 100));

        try {
            await rejectingPromise;
        } catch {
        }
    });
});
```

## Context
I have a test where rejections are awaited out of order with other promises.

## Your Environment
```
git clone https://github.com/andreashuber69/karma-false-positive-repro.git
cd karma-false-positive-repro
npm ci
npm run test
```

**Comment by sgravrock** [comment]
The problem is that the JavaScript runtime can't predict which rejections will be handled in the future and which won't. So it applies a simple rule: whenever control is returned to the runtime, an unhandled rejection event is fired for every promise that has been rejected and not awaited (or `.then`-d). Jasmine relies on that event to determine whether an unhandled rejection occurs.

The usual solution is to avoid rejecting the promise until you're ready to await it. You might find the discussion and examples in #1648 helpful.

**Comment by andreashuber69** [comment]
Hi

Thanks for your answer.

> The usual solution is to avoid rejecting the promise until you're ready to await it. You might find the discussion and examples in #1648 helpful.

The repro I provided is a much dumbed down version of a real world situation I have. It is hard to explain, but what I'm doing is somewhat equivalent to using Promise.all to fire off a bunch of requests in parallel. If one of those requests fails, I get the mentioned false positive from jasmine.

I don't see how I can resolve this without changing the semantics of my test. Does jasmine await the promise returned from the function passed to `it()`?

**Comment by sgravrock** [comment]
> Does jasmine await the promise returned from the function passed to it()?

Yes. [(Actually it calls then on it, but that shouldn't make a difference.)](https://github.com/jasmine/jasmine/blob/68db3f6fcf17426148edffb165c12517bdb84f9b/src/core/QueueRunner.js#L158)

You could try explicitly handling the rejection immediately after creating the promise:

```
        const rejectingPromise = Promise.reject(new Error("Operation failed."));
        rejectingPromise.catch(() => {});
        await new Promise<void>((resolve) => setTimeout(resolve, 100));
        // [...]
```

That should suppress the spec failure, at the cost of preventing both Jasmine and the JS runtime from letting you know if the rejection otherwise goes unhandled.

**Comment by andreashuber69** [comment]
Sorry for not getting back to you earlier.

> ...
> That should suppress the spec failure, at the cost of preventing both Jasmine and the JS runtime from letting you know if the rejection otherwise goes unhandled.

True, but I think it is unfortunate that I have to change my test just to suppress an error that clearly is a false positive.
Due to the small impact for me, I won't pursue this any further. Thanks for your help!

**Comment by ektapaulzagade-coder1998** [comment]
I am facing issue "Unhandled promise rejection: ObjectUnsubscribedError: object unsubscribed" while running unit test case. sometime they only show component name with error how can i solve this error

**Comment by johncrim** [comment]
I spun my wheels a bit fixing a similar issue, and jasmine now provides a way to silence the errors. (... in addition to the option described above, of adding a handler to the rejected promise before `await`ing.) Specifically, I ran into `Unhandled promise rejection` errors in Angular + karma + jasmine tests, and due to a bug in Zone.js the error text was dumped to the console multiple times, even though there was only 1 unhandled promise rejection. 

The documentation on [`jasmine.spyOnGlobalErrorsAsync`](https://jasmine.github.io/api/edge/jasmine.html#.spyOnGlobalErrorsAsync) is a little sparse, so I'm providing this example to help others looking for a solution to this issue:

I used `beforeEach` and `afterEach` to silence/prevent the unhandled rejection errors for all tests in the suite.

```ts
describe('something being tested', () => {

    let resolveAfterTest: () => void;
    let jasmineGlobalSpyPromise: Promise<void>;

    beforeEach(async () => {
      // Prevent jasmine failures for unhandled promise rejections for the tests in this suite
      jasmineGlobalSpyPromise = jasmine.spyOnGlobalErrorsAsync(async () => {
        await new Promise<void>((resolve) => {
          resolveAfterTest = resolve;
        });
      });
    });

    afterEach(async () => {
      // End for jasmine.spyOnGlobalErrorsAsync
      resolveAfterTest();
      await jasmineGlobalSpyPromise;
    });
...
```
