### ISSUE TITLE
Async execution of spied async function with rejected result

### ISSUE THREAD

**Issue by maziart** [jasmine/jasmine#1926]
## Description
Consider the following scenario:
We have an async function (a function that returns a promise) and we want it to return a fake rejected promise in a test case. This function itself will be called asynchronously. 

In our particular scenario, we are using `supertest` to test an API's behavior. But we have reproduced it simply with a `setTimeout` call.

``` JavaScript
  it('should pass', async () => {
    const obj = {
      async foo() {
        expect(1).toBe(2);
      },
    };

    spyOn(obj, 'foo').and.returnValue(Promise.reject('some-error'));

    await new Promise((resolve) => {
      setTimeout(async () => {
        expectAsync(obj.foo()).toBeRejectedWith('some-error');

        resolve({});
      });
    });
  });
```

## Expected Behavior

Expected the above test to pass.

## Current Behavior

Fails with the following output:

``` bash
 An error was thrown in an afterAll
   Expected 1 to be 2.

 An error was thrown in an afterAll
   Expected a promise to be rejected with 'some-error' but it was resolved.
```

## Possible Solution

If we replace the `spyOn` line with this line it would pass.

``` JavaScript

spyOn(obj, 'foo').and.callFake(() => Promise.reject('some-error'));

```

**Comment by sgravrock** [comment]
There's something odd about the output you posted. The "An error was thrown in an afterAll" message only appears in `jasmine` v2.x, but `expectAsync` was added in `jasmine-core` 3.2.0. I can't be sure, but it looks like you might have somehow ended up with incompatible versions of those two packages installed. Please upgrade to the latest versions of both.

That said, although I can't reproduce the *exact* output you're getting, I think there are two main things to fix:

1. As you've discovered, you need to do `spyOn(obj, 'foo').and.callFake(() => Promise.reject('some-error'));`. Otherwise you create an unhandled promise rejection. Jasmine treats unhandled promise rejections as errors, because they usually are. See <https://jasmine.github.io/pages/faq.html#return-reject>.
2. Async matchers are asynchronous, so you need to either `await` them or return the promise that they return. Otherwise your spec can complete before the matcher is evaluated. See the examples in <https://jasmine.github.io/api/3.8/async-matchers.html>, as well as <https://jasmine.github.io/pages/faq.html#late-failures>.

I also recommend rejecting promises with `Error` objects rather than bare strings. Errors have stack traces, which can make it easier to track down where an unexpected rejection came from.

Bringing it all together, this passes in Jasmine 3.8.0:

```
  it('should pass', async () => {
    const obj = {
      async foo() {
        expect(1).toBe(2);
      },
    };

    spyOn(obj, 'foo').and.callFake(() => Promise.reject(new Error('some-error')));

    await new Promise((resolve) => {
      setTimeout(async () => {
        await expectAsync(obj.foo()).toBeRejectedWithError('some-error');

        resolve({});
      });
    });
  });
```

**Comment by maziart** [comment]
Regarding versions:
I am using jasmine 3.8.0 and it has added its own dependency jasmine-core 3.8.0. I'm also using jasmine-console-reporter 3.1.0, I'm not sure if it matters. 

Actually, I didn't know about the return-reject FAQ.  But, now that I have heard it, I do not agree with it. This value is not "unhandled", a function is actually calling and handling it.

BUT, I understand that this `setTimeout` makes it "unhandled" because a rejected promise will become a microtask and be executed before that setTimeout task. So maybe I should bug `supertest` for their behavior. 

As I mentioned in the original post, I know that `callFake` solves the problem. I actually came here to suggest a method to return a rejected promise but then I found out that a `rejectWith` already exists. 

But regarding the `Promise.reject` usage, I think a lot of developers will face the same issue and lose a lot of time trying to figure out the problem. I think there is something that jasmine can do about this situation. That is actually handling the promise in `returnValue` function and creating another promise that will be rejected after the test finishes if not handled. 

If a pull request is welcome for this, I can try to implement that in my spare time.


BTW, thanks for the `await` and `Error` hints.

**Comment by sgravrock** [comment]
>  I am using jasmine 3.8.0 and it has added its own dependency jasmine-core 3.8.0. I'm also using jasmine-console-reporter 3.1.0, I'm not sure if it matters.

It doesn't affect the behavior of the spec, but it might affect how hard it is to debug. jasmine-console-reporter doesn't appear to show all the errors that Jasmine reports when your sample above is run (I see three when I use the default ConsoleReporter, two in the output you posted above, and one when I use jasmine-console-reporter with the example configuration shown in its README.

> Actually, I didn't know about the return-reject FAQ. But, now that I have heard it, I do not agree with it. This value is not "unhandled", a function is actually calling and handling it.

The code you posted causes Node to emit an unhandled rejection event. That means that *by definition* it's an unhandled rejection. That's a matter of fact, not opinion. Disagreeing with it doesn't change anything.

To get a better view of what's going on, let's take Jasmine out of the equation. This code is structurally similar to your example spec and has the same async behavior but doesn't use any libraries.


```
$ cat demo.js 
async function test() {
  const obj = {
    async foo() {}
  };

  const rejectedPromise = Promise.reject('some-error');
  obj.foo = () => rejectedPromise;

  console.log("about to await");
  await new Promise((resolve) => {
    setTimeout(async () => {
      console.log("inside setTimeout callback");
      obj.foo().then(
        () => {},
        () => console.log("caught the error")
      )

      resolve({});
    });
  });
}

test();
```

When I run it on Node 16, the "inside setTimeout callback" message never appears because Node detects the unhandled rejection and kills the process before the `setTimeout` even fires:

```
$ node demo.js 
about to await
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "some-error".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
$
```

(Browsers and older versions of Node will warn about the unhandled rejection but not halt execution. The timing of the warning varies but they all report it as an unhandled rejection.)

Although the code would have eventually connected a rejection handler to the process, that hadn't happened yet when Node checked for unhandled rejection.


> BUT, I understand that this setTimeout makes it "unhandled" because a rejected promise will become a microtask and be executed before that setTimeout task.

That might be accurate, but it's pretty tightly tied to how Node currently implements things. I think a safer way to think about it is this: Any time control is returned to the JS runtime, the runtime **may** fire an unhandled rejection event for any promise that has been rejected and doesn't have a rejection handler chained off of it. To avoid an unhandled rejection error you should connect the handler before you reject the promise, or at least before you return control to the JS runtime after rejecting it.

> But regarding the Promise.reject usage, I think a lot of developers will face the same issue and lose a lot of time trying to figure out the problem. I think there is something that jasmine can do about this situation. That is actually handling the promise in returnValue function and creating another promise that will be rejected after the test finishes if not handled.

I appreciate your willingness to put in the work, but there are some practical challenges involved in implementing that. It requires doing a couple of things that I don't think are possible (portably and reliably identifying promises, and determining whether a promise has a rejection handler attached). But even if I thought it was possible, I would still probably say no. Testing tools should help diagnose buggy code, not make it run "correctly". Tools that try to paper over the way the language actually works and make it "easier" actually hurt users in the long run. That's especially true when it comes to async. It's a lot harder to learn how async works when it works differently in your tests than elsewhere, and when your testing tools hide your bugs from you.

That said, I agree that `.and.returnValue(Promise.reject(...))` is common mistake and an easy one to make. I've done it too. I'm open to suggestions for any ways that Jasmine can better diagnose this kind of problem. Feel free to open a new issue if you have any such suggestions. (I'd encourage you to put together a quick proof of concept first, to make sure that the thing you're proposing is possible.)

Closing. I hope the information above helps you.
