### ISSUE TITLE
update README.md with basic usage examples (request)

### ISSUE THREAD

**Issue by AndreWillomitzer** [jasmine/jasmine#1941]
## Request Description

Hello! I have contributed to Jasmine in the past (added the extra errors to done() & expectation failures), and I was wondering if you would allow me to add some usage examples in the README for the Jasmine framework. 

For example, have a heading "Usage" and some code blocks of different "it, describe" examples. For sure it's straightforward to pick up how to use it by looking up tutorials but having it in the README would allow the user to see some examples if they just need a more simple test.
## Current Behavior

Currently in the repository the README has installation instructions but not a usage example section which I think could be good. 
## Possible Solution

I could explain a bit about what a spec is vs. a suite, and then maybe a couple examples using "it, describe" and expect/expectToBe. Nothing major just some simple things to show how a Jasmine test would be structured at a basic level.

## Context

It has not affected me personally but I know sometimes when I look around I see usage examples in README files so it could be a good idea.

I hope you will consider letting me contribute again :) 
All the best,
Andre

**Comment by sgravrock** [comment]
I think it would be good to have a pointer to appropriate documentation (possibly <https://jasmine.github.io/tutorials/your_first_suite>). I'd prefer not to have anything more detailed than that. The README has a lot of different audiences with a lot of different needs. I think it's better to keep it short and easy to skim. I'd also prefer to minimize the amount of duplicate documentation that needs to be maintained. Looking at other testing frameworks, I see that most of them include pointers to documentation in their READMEs rather than usage examples. The exceptions are ones that are small enough for the README itself to serve as nearly comprehensive documentation.
