### ISSUE TITLE
Increase the usage of compound assignment operators

### ISSUE THREAD

**Issue by elfring** [jasmine/jasmine#1947]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of compound operators](https://262.ecma-international.org/12.0/#sec-assignment-operators "Description for assignment operators") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's#\b(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-/%^]|\*\*?|&&?|\|\|?|\?\?|<<|>>>?)#$+{target} $+{operator}=#gm' $(find ~/Projekte/Jasmine/lokal -name '*.js')
```

:crystal_ball: How will [development interests](https://eslint.org/docs/rules/operator-assignment "Rule description") evolve further also according to update candidates in 71 lines of this software?

**Comment by sgravrock** [comment]
No.

I see that you've been opening issues like this in a number of projects over the last several months. It looks to me like you're running automated code-style checkers against various repos and opening vague issues when they find code that doesn't conform to one style rule or another. You've received feedback from multiple maintainers about [the work you're making for them](https://github.com/librosa/librosa/issues/1403#issuecomment-968121326) and [the vagueness of the issues you're opening](https://github.com/symfony/symfony/issues/42955#issuecomment-915861270). I see that some people are just closing your (repeated) issues without comment.

Even well-intentioned behavior can be abusive if you keep doing it after people tell you that it's harmful. Please stop.

If you want advice on how to propose this kind of low-value stylistic change, I'm happy to provide it. Just ask. But I doubt I have anything to say that you haven't already heard from someone else.

**Comment by elfring** [comment]
>It looks to me like you're running automated code-style checkers against various repos …

I dare to point change possibilities out (which can be generated also with the help of the mentioned Perl command example).
Other analysis tools can eventually show similar hints.


>You've received feedback from multiple maintainers about the work you're making for them

Proposed source code adjustments can trigger usual software development considerations, can't they?


>and the vagueness of the issues you're opening.

Various communication and understanding difficulties can occasionally happen accordingly.
Is my suggestion concrete enough for another issue according to possible improvements for the Jasmine testing framework? :thinking:


>Even well-intentioned behavior can be abusive if you keep doing it after people tell you that it's harmful.

The responses are mixed depending on the affected software components.


>If you want advice on how to propose this kind of low-value stylistic change, I'm happy to provide it.

:thought_balloon: Which proposal variants would you find better acceptable?

**Comment by slackersoft** [comment]
The Jasmine team has decided to standardize on common Javascript formatting/linting components like Prettier and ESLint. We're really not interesting in using a line of Perl command that the submitter can't even show an example of a before and after when making the suggestion.

If you're looking to get your "GitHub Points" up and get commits in many repos or lots of "contributions" with issues on different open source repositories, this is not a good way to accomplish those goals. Instead this is a good way to get yourself reported for harassment.

 If you're looking to propose a change to Jasmine (or any other open source project), I would suggest being especially clear about the thing that is causing you pain when using or trying to work on the project and why it is painful. Then, you can propose a different outcome **in the text of your issue**, not in a buried link. Providing only a Perl command and a link puts all of the effort on us, the maintainers, to figure out what that command does. This would require us to trust someone we don't know enough to have provided a command that is safe to run on our own computers.

This particular change seems to actually be a request to turn on the ESLint option to require all code in Jasmine to use things like `a += 2` instead of `a = a + 2`. This change seems irrelevant to good code, and would probably cause a lot of diff noise.

**Comment by sgravrock** [comment]
I had a longer response in the works. But @slackersoft pretty well covered everything I would have said.

FWIW, while I'm not willing to run that Perl code, I enabled the mentioned eslint rule and found that it flagged exactly one "issue". So the proposed change boils down to this:

```
--- a/src/core/MockDate.js
+++ b/src/core/MockDate.js
@@ -31,7 +31,7 @@ getJasmineRequireObj().MockDate = function(j$) {
 
     self.tick = function(millis) {
       millis = millis || 0;
-      currentTime = currentTime + millis;
+      currentTime += millis;
     };
```

There's no way that change could ever be worth the time we've already spent on it.
