### ISSUE TITLE
SpecRunner.html: Random behaviour when executing tests

### ISSUE THREAD

**Issue by failfastmoveon** [jasmine/jasmine#1954]
Hi,
The Jasmine instructions do not get executed consistently when using Jasmine via Jasmine Spec Runner Standalone.

##Expected behaviour:
1. Tests always get executed.
2. Test results are always displayed.

##Actual behaviour:
When I open my SpecHelper.html page the first time, or refresh the browser window multiple times, I get one of the following non-deterministic results:

1. Success - Message: **1 spec, 0 failures, randomized with seed 000048**, tests get executed successfully
2. Error - Message - **AfterAll Error: 'describe' should only be used in 'describe' function**
3. No action - Message - **Incomplete: No specs found**, , randomized with seed _xxxxx_

Result 3 is the most difficult to understand, because it seems like the test gets executed - but not the "it()" statements.
The Console seems to indicate that when the "No Specs found" occurs, the line of code before and after the it() statement get executed, but not the it() statement itself.

## Suite that reproduces the behavior (for bugs)
**mytests.spec.js**
```
require(["/scripts/require-init.js"],
   (config) => {
      require( ['vue','jquery'],
                    ( vue , $ ) => {

  // Test
  describe('A Test Dummy', () => {
            console.log("Before test");
            it ("Gets executed", () =>
              {
                console.log("During test.");
                expect(1).toEqual(1);
              });
            console.log("After test");
          });
        });
    });
```

**require-init.js:_**
```
require.config({
    baseUrl: './',
    paths: {
        vue: "https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue",
        jquery: "https://code.jquery.com/jquery-3.6.0.min",
    }
});
```

_Console Output on result 3 ("No specs found")_ - 
```
Before test
After test
```

_Console Output on result 2 ("AfterAll Error")_ - 
```
Uncaught Error: 'describe' should only be used in 'describe' function
    at ensureIsNotNested (jasmine.js:2137:15)
    at Env.describe (jasmine.js:2161:7)
    at describe (jasmine.js:8243:18)
    at mytests.spec.js:7:3
    at Object.execCb (require-2.3.6.js:5:16727)
    at e.check (require-2.3.6.js:5:10499)
    at enable (require-2.3.6.js:5:13242)
    at e.init (require-2.3.6.js:5:9605)
    at require-2.3.6.js:5:15109
```
## Context
I'm trying to use these tests as part of learning how to do Javascript test automation, and I'm stumped as to what is even going on.
There is no console information beyond the provided console log messages that might indicate an error or warning.
I am using either "php -S localhost:8000", "python -m SimpleHTTPServer", or Apache2 - with the same outcomes.

I have tried to narrow this down as far as I could. 
The behaviour seems to be correlated with my Chrome profile (I have multiple profiles, on the same Chrome browser, with same plugins - experimenting with and without clearing cache before refresh):

1. Profile A - works almost all the time, with result 1, on rare occasions result 3, distribution maybe 90-10.
2. Profile B - occasionally works. Usually result 3, sometimes result 1, distribution maybe 80-20.
3. Profile C - Never works. Produces result 2 or 3, roughly 50-50.

Experimented with Firefox and Edge, these consistently produce result 3 (100% of the time).

Issue first encountered in jasmine-standalone-3.10.1, 
Problem persists after migrating to jasmine-standalone-4.0.0.

What I can most certainly rule out is the commonly encountered issue that "Jasmine isn't configured" - that could not explain why _it sometimes works_.

## Environment
* Version(s) used: jasmine-standalone-3.10.1, alternatively: jasmine-standalone-4.0.0
* Environment name and version: latest Chrome
* Operating System and version: Windows 11, Desktop.
* Tried on multiple machines, same outcome.

**Comment by sgravrock** [comment]
I think the problem is that RequireJS doesn't necessarily call the callback in mytests.spec.js before the Jasmine suite starts running (or even before it finishes). So depending on the timing you can get a successful run, an error, or a run with no specs defined. The fix is to modify boot1.js so that `env.execute()` is called after RequireJS has loaded your spec files. It's been many years since I've worked with RequireJS, but something like this should work:

```
const specFiles = [
   "mytests.spec.js",
   // maybe more 
];
require(specFiles, function() {
   env.execute();
});
```

You may also need to remove whatever's currently requiring your spec files so that they aren't loaded twice.

**Comment by failfastmoveon** [comment]
I made the modifications to boot1 which you suggested, and in step 1 commented out the second line below from the HTML SpecRunner:
```
      <script src = "/spec/faction-quiz/boot1.js"></script>
      <script type="text/javascript" src="/spec/mytests.spec.js"></script>
```
That gave me a 100% "no tests found." 
When I then commented the line back in, I do see a change in behaviour: now all three profiles and the other browsers behave identically, and _all_ of them now seem to have an approximately even distribution across all the results, but now a fourth, pretty weird, result has been introduced:
```
, randomized with seed 43203
```
Yes - it says exactly that: No message for specs or failures at all - not even 0. Based on the green color, it's considered a "pass" outcome, unlike the gray color which is considered a "non-execution" outcome.

So I think we really boiled it down to a race condition in the browser.
Oddly enough, I wonder why it doesn't work when only requiring the spec in boot1, but it _somehow sometimes_ works when requiring them multiple times.

**Comment by sgravrock** [comment]
First, some background information that might be helpful: It sounds like you expect that Jasmine will call each `it()` callback before the containing `describe()` callback finishes. But that's not the case. Jasmine processes your suite in two phases. First, it calls `describe()` callbacks to discover what suites and specs you have. Then, after you call `env.execute()`, it runs the individual specs. So assuming that you mean "test" as a synonym for "spec" or "the thing I create by calling `it()`", the log message `console.log("After test");` should always occur *before* the spec runs. That's not the main problem here, but hopefully a better understanding of Jasmine's execution model will help you debug things.

There's a lot going on here, and it's tough to be sure exactly what the problem is without seeing and being able to run your actual code. But I think it boils down to using require.js incorrectly in a way that causes race conditions. Some general rules of thumb:

* Files that contain `require` or `define` calls should only be loaded via `require`, never via script tags.
* If file A uses functions, objects, etc. that are defined in file B, it should declare b as a dependency: https://requirejs.org/docs/api.html#defdep
* If you need to run some code (i.e. `env.execute()`) after a file loads, it should be run from the callback that you pass to the `require` call that loads the file. There's an example near the bottom of https://requirejs.org/docs/start.html .
* Using `window.onload` and RequireJS in the same application is almost always a mistake because it creates a race condition.

For Jasmine to work correctly, the order of operations needs to be:
1. The Jasmine env is created exactly once. (You probably get this for free as long as `boot0.js` is included before you require any of your spec files.)
2. All calls to `describe()` and `it()` happen exactly once.
3. The Jasmine env's `execute()` method is called exactly once.

(You might also need to call `htmlReporter.initialize()` immediately before `env.execute()` and not earlier -- I'm not sure about that, but it certainly wouldn't hurt.)

You can see a fully worked (albeit very out of date) example at https://github.com/sgravrock/typescript-migration-demo/tree/master/jasmine .

The way I'd debug the problem you're describing is by adding three `console.log` calls:

* "creating env" in `boot0.js` immediately before `var env = jasmine.getEnv();`
* "calling describe" in your spec file immediately before `describe('A Test Dummy'`
* "executing env" as the very first line of the `Env` class's `Execute` method in `jasmine.js` (right after line 1819 in v4.0.0)

The messages should appear exactly once each, and in that order. Anything else suggests a problem with require.js usage.
