### ISSUE TITLE
synchronous onPrepare before running specs

### ISSUE THREAD

**Issue by spleshakov-univision** [jasmine/jasmine#1971]
hello,

I need to run onPrepare function, where I run some setup work, synchronously, before running specs.

1. The first approach I tried was to just declare an async onPrepare function, which also includes the code for specifying reporters, and then do
```
await onPrepare();
await jasmine.execute();
```
In the result I get `jasmine.getEnv() is not a function`. I assume because `getEnv()` becomes available as `.execute()` is ran

2. The next approach I tried was to create a helper file with my sync code, specify it in the config and run `jasmine.execute();`. The problem that I noticed that the helper file is executed asynchronously with the specs and I get a spec error before the helper function finishes (basically because of race condition)

The questions I have is - if what I described in # 2 is a bug (that helpers are synchronous)? If not, is there any way to run onPrepare function synchronously before specs?

MacOS
node v16.13.2
jasmine v4.1.0

Thank you

**Comment by sgravrock** [comment]
It's hard to tell what's going on here because you've included almost none of your code. But I'll make a couple of educated guesses. Based on the behavior you described, I'm going to assume that the setup code is asynchronous even though you say it's synchronous.

My guess is that the first version didn't work because `jasmine` is a local variable rather than the `jasmine` global exported by the `jasmine-core` class. If it's an instance of [this class](https://jasmine.github.io/api/npm/4.1/Jasmine), you can access the env as `jasmine.env`.

My guess is that the second version didn't work because your setup code is asynchronous. Helpers load synchronously, which just means that you can't usefully run async code from them. That's not a bug.

If you need some code to run once before any of your specs run, you can either use your first approach or put it in an [asynchronous `beforeAll`](https://jasmine.github.io/tutorials/async).

Hopefully that's enough to point you in the right direction. If you need more help, please put together a repo with a complete, minimal, self-contained reproduction of the problem.

**Comment by sgravrock** [comment]
It looks like you're still trying to do async work at the top level of a reporter. As I said before, that won't work. I still don't know how to reproduce the other problems you've mentioned. But this works:

```
let Jasmine = require('jasmine');
let customReporter = require("./custom-reporter");

let asyncCode = (delayMs, value) => {
  return new Promise(resolve => setTimeout(resolve, delayMs))
    .then(() => value);
}

(async () => {
  let returnedValue = await asyncCode(500, 'customReporter');
  let jasmine = new Jasmine();
  
  jasmine.exitOnCompletion = false;
  jasmine.loadConfig({
    'spec_files': ['*.spec.js']
  })
  jasmine.addReporter(customReporter(returnedValue));
  // this also works:
  //jasmine.env.addReporter(customReporter(returnedValue));
  const result = await jasmine.execute();
})();
```

**Comment by spleshakov-univision** [comment]
This does work indeed. The issue is resolved, thank you
