### ISSUE TITLE
Errors when loading file that imports WASM module

### ISSUE THREAD

**Issue by dcbroad3** [jasmine/jasmine#1979]
I am seeing errors that seem very closely related to those noted in #1954.
I am building a small WASM module using Rust & wasm-pack, then importing it like:

`import * as wasm from '../path/to/module';`

This is in an Angular project, and the WASM module works perfectly at runtime. 

However, when I run my test suite, I get dozens of errors from Jasmine all in the format:
`Error: 'describe' should only be used in 'describe' function`
I noted this is the same error listed as result 2 in #1954.
[Link to test run](https://github.com/factoriolab/factoriolab/runs/7420918761?check_suite_focus=true)

I tried creating a small repo using Angular CLI to reproduce the error. If I make the tiniest possible WASM module and refer to it in a brand new Angular project, then Jasmine reports 0 of 0 tests run successfully. This scenario looks similar to result 3 in #1954, except the messaging is different, it says 0 of 0 specs, not "No specs found".

However, unlike in #1954, this _never_ works. 

If I import the WASM module using a declared import, like `import('../path/to/module').then(() => {})`, then Jasmine runs just fine. However, my code is all intended to be synchronous, and I would rather not have to refactor my entire code base just to make Jasmine run. For now, I am working around this issue by using Angular fileReplacements to swap out the file that imports the WASM module for a mock file when running tests. 

Here is the import in question: [link](https://github.com/factoriolab/factoriolab/blob/473ddca9a53ff60f5dc6f10e6d08d6a90e039c0e/src/app/utilities/simplex.utility.ts#L14)
Note this link refers to a commit before I switched to using a mock so the tests would pass.

**Comment by sgravrock** [comment]
When I try to run the specs in your project, Chrome hangs so badly that I have to reboot my computer to get it working again. As far as I know there's no other way to look at the generated JS code with the build tools you're using, so all I can do is make an educated guess.

I could be wrong about this, but my understanding is that loading wasm code is inherently async even when it's packaged by something like webpack. So the generated code might look something like this:

```
importTheWasmModule().then(function() {
   // ...
  describe('A suite', function() {
     // ...
  });
});
```

The problem is that there's no way for Karma (or anything else) to wait for async code that runs inside of a plain old script tag. So it tells Jasmine to run as soon as the script is loaded and executed. But the wasm module hasn't loaded yet, so the describe call happens after Jasmine starts to run.

If I'm right about what's going on, I can think of two options. The first is what you've already done: stub out the wasm module. The second is to convert everything to ES modules and load them directly when running specs rather than bundling with Webpack. That *should* work if the wasm stuff is sufficiently well-behaved. But it's likely to be a big lift: you'd need to get quite intimately familar with the Angular build system. You'd also need to either find a plugin that adds ES module support to Karma or switch to something that supports ES modules out of the box, like jasmine-browser-runner. That's not an attractive option, but it might be the only way forward if you want to run your tests in the browser and have them actually run wasm code.

See also [this Mocha issue](https://github.com/mochajs/mocha/issues/4890) which I suspect is basically the same problem.

**Comment by dcbroad3** [comment]
Thanks for the prompt and detailed reply! 

> When I try to run the specs in your project, Chrome hangs so badly that I have to reboot my computer to get it working again.

Well I don't like the sound of that at all, I've certainly never had that happen before. 

> So it tells Jasmine to run as soon as the script is loaded and executed. But the wasm module hasn't loaded yet, so the describe call happens after Jasmine starts to run.

I gotta say, this seems to make a lot of sense in the context of the error I'm getting back. 

> The second is to convert everything (especially the spec files themselves) to ES modules and load them directly when running specs rather than bundling with Webpack.

> See also https://github.com/mochajs/mocha/issues/4890 which I suspect is basically the same problem.

I had seen that issue and figured it was related too, forgot about it when writing up this issue though. The difference is I don't actually even want to test the wasm module itself, I'm just trying to test the code around it. 

It sounds like my workaround might be the most viable approach. I'll give this more thought and come back if I find a better way (I hate how hacky this feels), but if this is not an issue that can be solved in Jasmine there's probably no need to keep the issue open.

**Comment by sgravrock** [comment]
Some additional context that might be helpful for anyone else who deals with this:

https://github.com/WebAssembly/esm-integration/tree/main/proposals/esm-integration

What I understand from that is that WebAssembly modules are not currently loadable as ES modules. Code like `import * as wasm from '../path/to/module'` is likely being transpiled to something like this:

```
let req = fetch("./myModule.wasm");

let imports = {
  aModule: {
    anImport
  }
};

WebAssembly
  .instantiateStreaming(req, imports)
  .then(
    obj => obj.instance.exports.foo()
  );
  ```

That confirms that wasm loading is asynchronous, and thus can't be used directly or indirectly from spec files that are loaded via plain old script tags.
