### ISSUE TITLE
SyntaxError: Unexpected token ... in jasmine-core node module when using karma launcher on older TVs

### ISSUE THREAD

**Issue by iprecali1** [jasmine/jasmine#1981]
## Current behaviour
when launching unit test on older Tizen TV with custom karma launcher i get `SyntaxError: Unexpected token ...` for node module jasmine-core

```
(Tizen 4.0) ERROR [2m 47s]
  Uncaught SyntaxError: Unexpected token ...
  at node_modules/jasmine-core/lib/jasmine-core/jasmine.js:9583:30
  
  SyntaxError: Unexpected token ...
```
## Environment Details
node version: 16.14.2,
npm version: 8.19.2,
jasmine-core version 4.4.0,
karma-jasmine version 5.1.0,
karma version: 6.4.1,
Platform: Samsung Tizen 4.0 (2018), Web Engine: Chromium M56
## Question
Is there a way to polyfill the jasmine-core module so it runs on older TVs?

**Comment by sgravrock** [comment]
> Is there a way to polyfill the jasmine-core module so it runs on older TVs?

Possibly, but it might not be easy and it might not keep working if you upgrade Jasmine in the future. You'd need to both transpile jasmine-core back to a dialect of JavaScript that the TV understands and also polyfill all of the newer library features it uses. Given the age of the browser, that could be a lot of work. The polyfills would potentially affect the behavior of your code as well, allowing code that relies on the polyfilled features to pass even though it won't work on the TV outside of Jasmine. Since Jasmine now assumes an ES2017 environment, future versions could introduce more incompatibilities with the TV you're running on.

Your other option is to find the newest version of Jasmine that works on the TV without modification and use that. Jasmine 2.5.2 was current when Chromium M56 was released but you might not have to go back that far. 3.x supported both Internet Explorer and some fairly old Safari versions so there's a good chance that it'll work on old Chromium versions as well.
