### ISSUE TITLE
[Help] How do I use it(newcomer)?

### ISSUE THREAD

**Issue by diuming** [jasmine/jasmine#1983]
Hi,
I'm a newcomer about javescript and typescript.

I installed `jasmine`, `@types/jasmine` and `jasmine-ts-console-reporter` at global.
I don't want to install them every time when I new a npm package.(Is it a correct concept for jasmine testing?)

How do I use them in my typescript test file. take a look my test file `index.spec.ts` please.
thanks

```
/usr/bin/node-16.18.0/lib
├── @types/jasmine@4.3.0
├── corepack@0.14.1
├── jasmine-ts-console-reporter@3.1.1
├── jasmine@4.4.0
├── npm@8.19.2
└── typescript@4.8.4
```

index.spec.ts(I don't know how import `descibe`)
```
//  error: Cannot find name 'describe'
describe("The 'toBe' matcher compares with ===", function () {
    it("and has a positive case", function () {
        expect(true).toBe(true);
    });
    it("and can have a negative case", function () {
        expect(false).not.toBe(true);
    });
});
```

**Comment by sgravrock** [comment]
Have a look at https://jasmine.github.io/setup/nodejs.html and <https://jasmine.github.io/pages/faq.html#typescript>.

Some things to be aware of:

* Functions like `describe` aren't imported, they're provided as globals. (Although [you can change that if you want](https://jasmine.github.io/tutorials/use_without_globals).) My guess is that you're trying to run your spec file directly rather than using the `jasmine` executable, and the globals aren't there because Jasmine hasn't been loaded.
* Although you *can* install libraries and dev tools locally, it's not a good idea. If you have multiple projects, you'll inevitably end up in a situation where two of your projects need different versions of something. The resulting problems can be hard to diagnose, and the only solution is to install the packages locally instead of globally.
* `jasmine-ts-console-reporter` is pretty old (last updated in the Jasmine 2.x era). It might not be compatible with Jasmine 4, and improvements in TypeScript might have eliminated the problem it solves. I suggest starting without it, and only adding it if you've got everything else working and you're seeing incorrect stack traces.

I hope this helps.
