### ISSUE TITLE
Jasmine not throwing errors when it should

### ISSUE THREAD

**Issue by radzk** [jasmine/jasmine#1987]
Hi. I spent a fair amount of time and I'm not even sure at which project to report it. I need to better understand what is going on with my code attached below. Its ran in Jasmine. It seems that jasmine does not report me errors when something fails inside RxJS subscription. When it's "outside", I can see the error correctly.

So here is my code (fork from other library)
https://stackblitz.com/edit/ngx-formly-ui-material-e6cvcq?file=src/app/app.component.ts
If you check the console, there's nothing there except the console logs executed before the error occurred. The error itself is silenced.

The same component code ran (outside unit tests) throws errors properly.

**Comment by sgravrock** [comment]
If I try wrapping the subscription in a try/catch like this, the error is never logged.

```
try {
    const sub = of('test').subscribe(() => {
        // ...
        console.log('sub end');
    });
} catch (e) {
    console.error(e);
}
```

The exception never reaches Jasmine because RxJS catches it.

**Comment by sgravrock** [comment]
Also: although the subscription might run synchronously in this particular case, expecting it to be synchronous when it's actually async is a common pitfall. When working with any async primitive (observables, callbacks, promises, async/await, whatever) my advice is to write an async test that waits for the code under test to signal that it's done, even if you're sure that your current version will run synchronously. That will also allow you to surface any errors that got routed through the observable/callback/promise/whatever.

**Comment by radzk** [comment]
Thanks. I still have some headache about it.

So here is the same code ran in jasmine - throws no errors (the same link as above):
https://stackblitz.com/edit/ngx-formly-ui-material-e6cvcq?file=src%2Fapp%2Fapp.component.ts

And here I prepared the same environment, but its ran just like an angular app, no jasmine.
https://stackblitz.com/edit/ngx-formly-ui-material-kqnfen?file=src%2Fapp%2Fapp.component.ts

This troubles me because the second one throws nice errors in console and in the view saying whats wrong with the code.
I mean, why would the RXJS subscription catch the errors itself, but only in jasmine's environment...? Sorry, I still don't understand that part. Would Jasmine change something about how subscriptions work in rxjs library...?


> Also: although the subscription might run synchronously in this particular case, expecting it to be synchronous when it's actually async is a common pitfall. When working with any async primitive (observables, callbacks, promises, async/await, whatever) my advice is to write an async test that waits for the code under test to signal that it's done, even if you're sure that your current version will run synchronously. That will also allow you to surface any errors that got routed through the observable/callback/promise/whatever.

All I wanted to do here was to replicate the mocked observables, like when its mocked -> mockedService.someFunction.and.returnValue(of([])). The errors I've been fighting with for last two days were only appearing during tests and after blind step by step debug it turned out there was no mock value for one function which usually returns an array (= resulted with code trying to access the first element of undefined). It was serious pain to find it.

**Comment by sgravrock** [comment]
Jasmine doesn't change anything about how observables (or almost anything else) work, although it's possible that the Angular testing tools do.

When I run your last example, I see two significant things. First, the "Sync check - after sub" message appears. That shows that the exception is still being caught. Second the error log appears *after* the "Sync check - after sub" message. That shows that, contrary to what you expected, at least some aspect of the observable's behavior is asynchronous.

To reliably test this, you need to write an asynchronous test that waits until the code under test is finished. And it needs to re-throw any errors that happen in the observables so Jasmine can find out about that. Right now that's impossible because all the async behavior is hidden inside the component. You need a way for your test to get notified of both completion and errors. Most likely the easiest way to do that is to expose the observable so it can be consumed from outside the component. Most of that's about Angular and about your code, not about Jasmine: You'd have the same problem if you were trying to write a plain old function that waited for your code to finish and reported whether it failed. But see the [async testing tutorial](https://jasmine.github.io/tutorials/async) and also [the async section of the FAQ](https://jasmine.github.io/pages/faq.html#async). 

Some general tips that might help you:
* Don't try to write synchronous tests for code that uses async features, even if you think it'll run synchronously.
* Make sure async tests wait for the code under test to finish. You may need to redesign the code under test to achieve that.
* Console logs are a good tool for debugging async problems, but pay close attention to the order the messages appear in.
* Study the rxjs docs until everything makes sense. Don't skip anything. Even esoteric-seeming parts like hot vs cold observables and the details of how different kinds of subjects work can quickly become necessary knowledge for testing code that uses rxjs. 

I hope this helps.

**Comment by Yahya-Cheikh-Maazouz** [comment]
......
