### ISSUE TITLE
Cannot import module?

### ISSUE THREAD

**Issue by sdasda7777** [jasmine/jasmine#1994]
### Your question

I seem to be unable to import a module class into a spec file. May be a bug, but likely it's me missing some vital information. The structure copies the structure of the sample project in the standalone distribution.

`SpecRunner.html`:

![image](https://user-images.githubusercontent.com/17746796/212477934-b862e1f5-fddf-4700-a215-dbe7f3db0588.png)

`src/Record.js`:

![image](https://user-images.githubusercontent.com/17746796/212478068-a20ee8f9-2aa9-4c90-b96f-b88f95ea756f.png)

`spec/RecordSpec.js`:
Neither of these imports work, I get the same error for all of them (Ea). With no import, I get a different error (Eb).

![image](https://user-images.githubusercontent.com/17746796/212477976-c33e28b4-67ca-45d5-b574-cdaa6e6ab67d.png)

Ea:
![image](https://user-images.githubusercontent.com/17746796/212478291-65342826-9d63-42d9-986b-af8ffd900d5d.png)

Eb:
![image](https://user-images.githubusercontent.com/17746796/212478402-9b49c423-7dd6-45b7-8169-7777b1e4abb5.png)

### Example code that demonstrates the problem

```JavaScript
^
```

### jasmine-core version

4.5.0

### Does the problem occur with the latest version of jasmine-core?

Yes

### Node.js or browser version

latest-ish Chrome

### Operating System

Windows 10

**Comment by sgravrock** [comment]
You can only use `import` inside an ES module. `RecordSpec.js` isn't an ES module because it's loaded with a regular `<script>` tag rather than `<script type="module">`. You also can't load ES modules from a `file://' URL, which you might be doing if you're using the standalone distribution.

To make it all work you need to load all your scripts using `<script type="module">`, including spec files, and serve them via HTTP or HTTPS with the correct `Content-type` header. If you want the suite to run reliably on Safari you'll also have to add some code to [route errors to Jasmine](https://github.com/jasmine/jasmine-browser-runner/blob/6edfc41e89d3f3e75e59b2965ece76d123e80de8/lib/support/loadEsModule.js#L7-L16)

Jasmine-browser-runner has [built-in support for ES modules](https://jasmine.github.io/setup/browser.html#es-module-support) that takes care of all that, although you'd have to rename your files to `.mjs`.

**Comment by sdasda7777** [comment]
Ah, I see, thank you for clearing this up.
