### ISSUE TITLE
"waitFor" in react-testing-library doesn't work with Jasmine

### ISSUE THREAD

**Issue by tstordyallison** [jasmine/jasmine#2003]
### Steps to Reproduce

1. Construct a react-testing-library test, that uses [``waitFor``](https://testing-library.com/docs/dom-testing-library/api-async/#waitfor).
2. Use jasmine with ``oneFailurePerSpec``, so it "throws" an exception when running inside the ``waitFor``. 

### Expected Behavior

``waitFor`` should work as normal - where it runs the expectation repeatedly until it reaches either a successful assertion, or timeout. 

### Actual Behavior

``waitFor`` catches the ``ExpectationFailed`` error, and correctly repeats the assertion (as long as ``oneFailurePerSpec`` is enabled). 

But for each attempt, it records a new "failedExpectation" - so at the end of the test we have many, many failures (also amusing given we have ``oneFailurePerSpec`` turned on!). 

### Example code that reproduces the problem

```JavaScript
it("Initial input value is supported", async () => {

    const view = render(<ComboBox source={["alpha", "beta", "gamma"]} />);
    
    await waitFor(() => { expect(input.getAttribute("value")).toBe("gamma") } );

})
```

### Possible Solution

Rock and a hard place! Happy to hear any ideas - either tweaks to ``waitFor`` or in jasmine. 

If feels like when we are in the ``waitFor``, we need to allow raising the expectation but not recording it. This would be something different to ``oneFailurePerSpec`` in my mind. It also would be contextual, which is harder (though happy if this resulted in a jasmine API/context pattern - and I could go asking for it in ``react-testing-library``, or just use it in my code). 

Ideally also, we wouldn't need ``oneFailurePerSpec`` turned on. I was only doing that as without it, nothing at all happens - as jasmine (understandably) doesn't throw an error at all. 

### Context

Hard to use react-testing-library without lots of manual "waiting". We have a ``waitForPredicate`` helper, but it's not ideal to do that and then do the expect as well. 

Example of what we see cropping up:

```JavaScript
await waitForPredicate(() => view.getAllByRole("option").length === 2);
expect(view.getAllByRole("option").length).toBe(2)
```

### jasmine-core version

3.4.0 (sorry!) - I'm 99% sure this will happen on all versions though. 

### Node.js or browser version

node 16

### Operating System

Windows 10

**Comment by sgravrock** [comment]
> Rock and a hard place! 

Indeed.

I'm not sure how to solve this in a way that doesn't create worse problems. 

React-testing-library's design assumes that failed expectations throw exceptions, and don't count unless the exception propagates back to the testing framework. But that's not the way Jasmine works. (And Jasmine had already not worked that way for nine years when react-testing-library first came out.) If expectations work the way react-testing-library assumes, then this code can't work any more:

```
it('does something async', function(done) {
   doSomethingAsync(function(result) {
      expect(result).toBeCorrect();
      done();
   });
});
```

That sort of code (which is *extremely* common) relies on expectation failures "counting" even if they can't propagate an exception back up to the rest of Jasmine.

Making expectation behavior configurable has problems too. For one thing, `waitsFor` usage and code that makes the same assumptions as the example above can occur in the same suite or even in the same spec. So even if it's opt-in, it's still a footgun. Then there's the problem of explaining how async testing works when it works two different ways depending on how Jasmine is configured. And fielding "why don't my expectations work" issues from users who don't mention their Jasmine configuration because they don't realize it's relevant.

I'm not sure I want to take on the complexity of a second expectation-processing mode just for react-testing-library easier to use. My knee jerk reaction is that the juice probably isn't worth the squeeze. But even setting that aside, I think we'd need something that's opt-in at the call site, difficult to misuse, and designed in a way that makes its purpose and effects obvious. I'm not sure what that would look like.

**Comment by sgravrock** [comment]
> 3.4.0 (sorry!) - I'm 99% sure this will happen on all versions though.

You're right that it'll happen on all versions. But even if Jasmine did ship something to better support react-testing-library, it wouldn't be backported to 3.x.

**Comment by sgravrock** [comment]
Maybe something like this, which I think is in line with your suggestion of making it contextual?

```
await waitFor(() => { expect(input.getAttribute("value")).forTestingLibraryWaitsfor().toBe("gamma") } );
```

But I'm not sure it's all that much less obnoxious than what you're already doing. And it still wouldn't work if the `waitFor` call was in an async callback.

**Comment by yajaru** [comment]
It seems to me like the fundamental issue here is that there are two separate things being tied together in the "expect" API. The first is the DSL for assertions (which is useful even outside the context of jasmine) and, the second is the mechanism that reports the error back to jasmine to be gathered and displayed. In the RTL example, we'd really like to access just the DSL but, since the reporting comes along with it, we end up constrained by that extra functionality.

My thought is that we could add a an API for just the DSL and put it under a different function ("check" comes to mind but it doesn't feel quite right with the assertion names) and that would throw a plain JS exception instead of reporting back to jasmine. 

I think this would solve for the RTL use case and, it would manage to avoid the confusion arising from overloading the expect API. Since a user would need to explicitly opt-in to this behavior by using the alternative function, we would be able to make them aware of the behavioral difference between the 2 forms.

**Comment by sgravrock** [comment]
> My thought is that we could add a an API for just the DSL and put it under a different function ("check" comes to mind but it doesn't feel quite right with the assertion names) and that would throw a plain JS exception instead of reporting back to jasmine.

I think any name other than "expect" is going to feel at least somewhat awkward. And I think that's partly a good thing: someone who thinks the proposed feature is a synonym for "expect" is more likely to stick with "expect" if code using the new feature reads worse. If anything, "check" isn't awkward enough. I'd favor something like "throwUnless", which might also give the reader a fighting chance at correctly guessing the implications of using it.

> Since a user would need to explicitly opt-in to this behavior by using the alternative function, we would be able to make them aware of the behavioral difference between the 2 forms.

Well, we can try. Some people will actually read the docs before trying out a feature that they're unfamiliar with. But not everyone will.

**Comment by tstordyallison** [comment]
``throwUnless`` (or something like it) would also be reasonable for a linter to pick up too, which is appealing.
