### ISSUE TITLE
Use globalThis instead of jasmineGlobal

### ISSUE THREAD

**Issue by 0o001** [jasmine/jasmine#2015]
### Your question

Wouldn't it be better to use globalThis instead of the code here?

### Example code that demonstrates the problem

```JavaScript
https://github.com/jasmine/jasmine/blob/main/lib/jasmine-core/jasmine.js#L27
```

### jasmine-core version

latest

### Node.js or browser version

node 18, 20

### Operating System

All

**Comment by sgravrock** [comment]
I'd certainly use globalThis if I were writing that code from scratch today. It might be worth making the switch if we ever have to change how the global object is detected for other reasons. But I don't think it's worth switching to globalThis just for the sake of switching to globalThis.

It would allow us to turn this:

```
  if (
    typeof module !== 'undefined' &&
    module.exports &&
    typeof exports !== 'undefined'
  ) {
    if (typeof global !== 'undefined') {
      jasmineGlobal = global;
    } else {
      jasmineGlobal = {};
    }
    jasmineRequire = exports;
  } else {
    if (
      typeof window !== 'undefined' &&
      typeof window.toString === 'function' &&
      window.toString() === '[object GjsGlobal]'
    ) {
      jasmineGlobal = window;
    }
    jasmineRequire = jasmineGlobal.jasmineRequire = {};
  }
```

into something more like this:

```
 if (
    typeof module !== 'undefined' &&
    module.exports &&
    typeof exports !== 'undefined'
  ) {
    jasmineRequire = exports;
  } else {
    jasmineRequire = globalThis.jasmineRequire = {};
  }
```

Which is nice enough, and would provide a small maintainability benefit... if that code needed any maintenance. But nobody's had to touch it since 2017. (2016, if you only count code that actually affects jasmineGlobal.) So the benefit is purely cosmetic. 

The old code didn't become any less correct when globalThis arrived. It's just no longer the tidiest way to do the job. That has to be weighed against the fact that the existing code has been working correctly across all supported environments for 7 years.
