### ISSUE TITLE
Expected object to be a kind of Object, but was <anonymous>

### ISSUE THREAD

**Issue by fabianobonomini** [jasmine/jasmine#2019]
- node 18.18.1
- jasmine 5.1.0

I am trying to do an .Equal Assertion on a code and I got this error
`Expected object to be a kind of Object, but was <anonymous>({ MY OBJECT}`

before I was using jasmine-node and this error never occur. any Ideas? 
If you need I can share an example

**Comment by fabianobonomini** [comment]
hi @sgravrock , first of all. thank you for your help.

I have a test similar to this one 

```
const myAsyncSutFunction = async () => {
// doing something return an object
} 
it('should assert an object', async () => {
myAsyncSutFunction.then( async ( outputData ) => {
expect(outputData).toEqual({
myExpectedPrperty: 'my expected value'
})
}).catch((e) => {
          expect(e.stack).toBe(false);
          
        });
```

**Comment by sgravrock** [comment]
That doesn't run. (There's at least one significant error that stops it from even getting to the `toEqual` expectation.) And it's missing the actual value being compared against, which is important since the error message you reported describes a mismatch between the expected and actual values. The most likely cause of the error is that the code you haven't show is creating a different type of object than the one you're passing to `toEqual`.  

But I also see a significant bug which could cause the problem you're seeing if it's also present in your real code. The spec signals completion to Jasmine before the expectation runs. This is because it calls multiple async operations including `.then`, but doesn't wait for `then` to complete. That causes the code in the `.then` callback to interleave with the execution of other specs. Code in `myAsyncSutFunction` could also interleave with other specs, depending on how `myAsyncSutFunction` is written. If your real code fetches `outputData` from a global mock or similar source, a similar bug could cause another spec to reconfigure that mock before the value is fetched by this spec.

Try using `async`/`await` consistently:

```
it('should assert an object', async () => {
    const outputData = await myAsyncSutFunction():
    expect(outputData).toEqual({
        myExpectedProperty: 'my expected value'
    });
});
```

Or, if you really want to use promises directly, make sure the spec returns a promise that is only resolved when the spec is actually finished:

```
it('should assert an object', () => {
    // Important: the result of .then() is returned.
    return myAsyncSutFunction()
         // Note: the then callback should not be declared async.
         // It's not easy to mix promises and async/await without causing bugs.
         .then(( outputData ) => {
            expect(outputData).toEqual({
                myExpectedPrperty: 'my expected value'
            })
        });
   });
});
```

Suggested reading:
* [The async tutorial](https://jasmine.github.io/tutorials/async)
* [Which async style should I use, and why?](https://jasmine.github.io/pages/faq.html#preferred-style)
* [Why are some asynchronous spec failures reported as suite errors or as failures of a different spec?](https://jasmine.github.io/pages/faq.html#late-failures)

I hope that helps. That's all the guessing I'm willing to do. If you want more help, I'll need a minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that actually runs and produces the error you're asking for help with.
