### ISSUE TITLE
Returning rejected promises prints unhelpful stacktraces

### ISSUE THREAD

**Issue by DanKaplanSES** [jasmine/jasmine#2022]
### Steps to Reproduce

1. Create a test that returns a `Promise.reject()`
2. Run the test

You can find a working repository here: https://github.com/DanKaplanSES/boilerplate-jasmine-typescript/tree/promise-rejection-no-stacktrace

### Expected Behavior

A test failure with a stacktrace that includes the `Promise.reject()` line. Or to put it another way, a stacktrace similar to a test that fails with `expect(true).toBeFalsy();`

### Actual Behavior

```bash
2) Example returns a rejected promise
  Message:
    it thrown
  Stack:
```

### Example code that reproduces the problem

```JavaScript
import "jasmine";

describe("Example", function () {
  // modify the values of this map
  const functionPromiseMap: { [index: string]: "resolve" | "reject" } = {
    beforeAll: "resolve",
    beforeEach: "resolve",
    afterEach: "resolve",
    afterAll: "resolve",
    it: "reject",
  };

  function returnPromise(functionName: string): Promise<void> {
    const resolveOrRejectString = functionPromiseMap[functionName];
    return Promise[resolveOrRejectString](functionName);
  }

  beforeAll(() => {
    return returnPromise("beforeAll");
  });

  beforeEach(() => {
    return returnPromise("beforeEach");
  });

  afterEach(() => {
    return returnPromise("afterEach");
  });

  afterAll(() => {
    return returnPromise("afterAll");
  });

  it("passes with synchronous code", () => {
    expect(true).toBeTruthy();
  });
  
  it("fails with synchronous code", () => {
    expect(true).toBeFalsy();
  });

  it("returns a rejected promise", () => {
    return returnPromise("it");
  });
});
```

### Context

This is difficult to troubleshoot, especially when the rejected promise occurs in a `beforeEach` (or similar) that calls complex code.

### jasmine-core version

5.1.1

### Versions of other relevant packages

```json  
"devDependencies": {
    "@types/jasmine": "^5.1.1",
    "@types/node": "^20.8.10",
    "jasmine": "^5.1.0",
    "jasmine-console-reporter": "^3.1.0",
    "nyc": "^15.1.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  },
```

### Node.js or browser version

node v18.17.1

### Operating System

Windows 10

**Comment by sgravrock** [comment]
Thanks for providing a working repro. I appreciate that since it takes the guesswork out.

You can fix this in your code by always rejecting promises with an instance of `Error` (and there's the eslint prefer-promise-reject-errors rule to help with that). But I don't think there's much Jasmine can do once a promise has been rejected with a non-`Error` reason. The problem is that only `Error` instances have stack traces. So unless the promise is rejected with an `Error`, there's no way to recover the source of the rejection later on.

When an expectation fails, Jasmine is able to obtain a stack trace by constructing its own `Error`. But that only works because the source of the failure is still on the call stack. That's not the case with a returned promise or an unhandled promise rejection.

**Comment by sgravrock** [comment]
I added https://jasmine.github.io/pages/faq.html#promise-no-stacktrace for this.
