### ISSUE TITLE
There Should be an Option to Show a Message on Assert Success

### ISSUE THREAD

**Issue by samuelfreiberg** [jasmine/jasmine#2023]
### Feature Proposal

The .withContext() method should display the message regardless of a success or failure. When debugging tests, you want to see the flow of the testing - why wouldn't you be able to see that a certain assert passed? This makes debugging extremely difficult.

### Context

It helps make debugging easier. You're able to see the flow of testing. You're able to see the state of the tests at different points. A specific use case:

Let's say I have a test with 3 asserts, and this test failed due to a timeout. If I could see the assert messages on passes, I could get a better idea of where the test was when the timeout hit. This is just one example of many. 

### Example

```JavaScript
.withContext('Message') always shows in the logs regardless of pass/fail. For pass, the color of the text could be green. For failure, red.
```

**Comment by sgravrock** [comment]
I suggest using [`jasmine.debugLog()`](https://jasmine.github.io/api/5.1/jasmine.html#.debugLog) for that. Unlike passed expectations, it's designed for debugging. Passed expectations weren't designed as a tool for tracking progress through a spec, and trying to retrofit that functionality onto them at this stage would cause problems.

The biggest issue with outputting passed expectations is that the error messages would often be misleading. Matchers don't know whether they're being negated. When a matcher that generates custom messages passes, it has to generate a message that would make sense if it was negated. So with your proposed feature, `something: Expected instance of Number not to be an instance of Number` would cause Jasmine to output `something: Expected instance of Number not to be an instance of Number`. I think most people would be confused by that.

Other concerns:
* Overloading `withContext` to mean both "add this to the failure message" and also "report this assertion if it passes and a particular config option is turned on" could be confusing.
* Enabling this option would likely cause problems in large test suites unless the user remembered to focus on a particular spec at the same time.
* Much of the implementation work would be on the reporter side. That limits the reach of the proposed feature, since a huge portion of Jasmine's user base relies on third party reporters that are de facto unmaintained.
