### ISSUE TITLE
Include skipped specs in report?

### ISSUE THREAD

**Issue by gregsabo** [jasmine/jasmine#274]
I would like for specs and suites which are skipped (either with xit() or perhaps some other way) to be present in the results object to make it possible to display them. I believe Rspec does this. I'd like to be able to use pending tests as a sort of todo list.

**Comment by bcherny** [comment]
Is it possible to hide skip tests from console output?

**Comment by slackersoft** [comment]
Skipped specs (`xit` and `xdescribe`) should not be displayed in console output from jasmine, but a pending spec will be.

**Comment by bcherny** [comment]
skipped specs (non-`fit` and non-`fdescribe`) *are* displayed with jasmine 2.3.0 / karma 0.12.31.

**Comment by slackersoft** [comment]
Jasmine reports all specs that it attempts to run to all of the reporters that are registered. `xit`, `xdescribe`, non-`fit` and non-`fdescribe` are all reported with a status of `disabled`. It sounds like karma's reporter may be treating `disabled` the same way as `pending` which would cause the behavior you're seeing.

The only change for this is 2.3.0 is that now specs will always report with a disabled status, instead of only specs that were specifically `xit` instead of a child of `xdescribe`, etc.
