### ISSUE TITLE
Force Jasmine run to fail if any uncaught errors occur

### ISSUE THREAD

**Issue by brentsnook** [jasmine/jasmine#326]
I think the test run should fail if any uncaught errors occur on the page.

We had a nasty situation where a compilation error in a Jasmine spec file caused the test run to pass as if nothing had gone wrong. The syntax error prevented the examples from being registered and it was as if the spec hadn't even existed. I can see how one syntax error could cause a whole spec to fall into decay if it isn't regularly touched.

I tried to hack in a fix as suggested at https://gist.github.com/mattyod/3911612 but the problem with this is getting that spec to load first before any of the others are evaluated. The hacky workaround is the name this file beginning with 'aaa' or something so it loads first.

Here's the Gist:  https://gist.github.com/brentsnook/4721960

**Comment by jchesterpivotal** [comment]
As a note, we have encountered this as well. Is there any sense of when it might be addressed? The Tracker icebox entry seems to have been untouched since 2015.

This can leave folk like myself with a false sense of security, because everything "passes". It's only when you see different numbers of tests run in different browsers or headless browsers that it becomes obvious that something is amiss.

To me BDD and TDD are about improving assurance and trust in the code, to allow more fearless refactoring and improvement. That I will never be able to truly _know_, starting with baseline Jasmine, that all the tests and specs I provided were actually run, is upsetting.

**Comment by sgravrock** [comment]
I understand why this feature is desirable. I hack it into `boot.js` pretty much every time I start a project that uses Jasmine standalone. It hasn't been implemented in Jasmine yet because it's a breaking change and it's likely to be a little tricky to get right for all users. There are plenty of systems that trigger the global `error` event during successful initialization, and we don't want to break their test suites on a point release. We also need to think carefully about situations where the code under test depends on libraries that raise errors during initialization. So while I'd also like to see this feature, it's going to take some careful work and I think it has to wait for a major version bump.

**Comment by berlin-ab** [comment]
Bumping this feature request. We just introduced this workaround to our project. It would be nice if it were a configurable option at least.

**Comment by slackersoft** [comment]
This functionality should be coming in 3.0. Check out the [3.0-features branch](https://github.com/jasmine/jasmine/tree/3.0-features).

No, I don't have an ETA for release right now :)

**Comment by ardalis** [comment]
A couple of months later, any ETA for 3.0 now? :)

**Comment by slackersoft** [comment]
Jasmine 3.0 was released today. Please check out the [release notes](https://github.com/jasmine/jasmine/blob/master/release_notes/3.0.md) and use the 2.99 release to check for changed functionality.

**Comment by ardalis** [comment]
Sweet! Nice timing!
