### ISSUE TITLE
jasmine.Clock.useMock doesn't mock Date

### ISSUE THREAD

**Issue by cwarden** [jasmine/jasmine#361]
It would be useful if `jasmine.Clock.useMock` mocked `Date` such that `jasmine.Clock.tick` incremented the times returned by `Date` after `jasmine.Clock.useMock` is called.  This would make it compatible with `_.throttle`, the implementation of which changed in documentcloud/underscore#820.

**Comment by bobbyrenwick** [comment]
I'm not sure how useful this comment is for anyone else but today I lost time to `jasmine.clock().mockDate()` not working for any function that the result of using `_.debounce` or `_.throttle`.

This is because both `underscore` and `lodash` get a reference to Date.now (if available) at parse time, so the mocked date is never used.

I have worked around this by using this in my tests:

```js
var _ = require("underscore");
_.now = function() {
    return new Date().getTime();
};
```

**Comment by DeadMG** [comment]
I think that may be a new version of Underscore- the version we have does not do that. That sounds to me like it's an Underscore problem rather than a Jasmine problem.

**Comment by guncha** [comment]
To use `jasmine.clock()` with `debounce` or `throttle` (with lodash at least), you have to create a new lodash instance that using the mocked timing functions, i.e.:

```javascript
jasmine.clock().install()
lodash.runInContext(window).throttle // <- this function will use mocked setTimeout 
```

Then you have to pass it to the code you're trying to test.

**Comment by DeadMG** [comment]
That'll be super useful for Lodash users, as opposed to everybody else here who is discussing Underscore.
