### ISSUE TITLE
Filtering out specs in HTML report

### ISSUE THREAD

**Issue by callmevlad** [jasmine/jasmine#510]
In Jasmine 1.3, clicking on a suite or a specific spec (e.g. `TestRunner.html?spec=A spy`) would only show that spec (or tree) in the HTML report, which was really handy. Jasmine 2.0 seems to write out the entire tree, with disabled specs having a different style, which can be quite verbose (especially with thousands of specs in the report). 

Is there a way to enable 1.3-like reports in 2.0? If not, would you guys be open to a pull request to restore 1.3-like behavior (or at least have the option to revert to that mode with a query parameter)?

**Comment by slackersoft** [comment]
If anyone is still interested in this. Here's what we'd be looking for in a pull request:

`HtmlReporter` should be able to be configured to not show any disabled specs or suites. `HtmlReporter` should provide an option similar to "catch exceptions" that sets a query param.

`boot.js` should be able to configure its `HtmlReporter` for this based on a query param.

**Comment by jasonmobley** [comment]
I don't think the checkbox option is necessary for the use case described here.

The complaint is that the HtmlReporter doesn't filter its output when you're only running a specific spec, i.e. when you've given `?spec=foo` on the query string. It seems totally reasonable that the HtmlReporter would only show output for that spec, because that's exactly what you told Jasmine to do!

Is there a way to detect that the spec list has been reduced due to `?spec=foo` URL args, and filter output on that basis?

**Comment by jasonmobley** [comment]
FWIW, I agree with the choice to show disabled specs by default, e.g. those disabled/ignored via `xdescribe`. I don't think of giving `?spec=foo` URL args as "disable everything but this." I think of it as "only run this," which means I expect only that output.

**Comment by slackersoft** [comment]
Internally, what happens when you load the page with `?spec=foo` is that all of the other specs get marked as disabled for the current run. This way spec really only have 3 states: running, pending, and disabled. I think this means that making the change you propose would add another state and set of complexity to running the jasmine suite, unless I'm mistaken.
