### ISSUE TITLE
Add expected assertion count

### ISSUE THREAD

**Issue by mgol** [jasmine/jasmine#626]
Especially with async tests it's very useful to be able to check if assertion count at the end of the spec matches what was actually checked. This would also allow to catch mistakes like:

``` js
expect(some-long-expression);
```

(which I've experienced yesterday).
An API could look like:

``` js
it('a test', function () {
  this.expect(2);
  expect(true).toBe(true);
  // error: two assertions expected
});
```

or like that:

``` js
it('a test', function (2[, done]) {
  expect(true).toBe(true);
  // error: two assertions expected
});
```

**Comment by juanmendes** [comment]
I would love this feature, it exists in js-test-driver. It's really useful for asynchronous test cases to make sure all your callbacks are called.

```javascript
it('should check my variable after a timeout', function() {
     var val = true;
     setTimeout(function(){
        expect(val).toBe(false);
        done();
     }, 0);
});

The above test should fail but ends up passing because I forgot to define the `done` parameter.

**Comment by Ciantic** [comment]
It need not to be asynchronous test to be difficult to refactor so that expect is at the end of the function.

I'm testing react components, and I have expect inside the render, e.g.

```typescript
    it("should duplicate state to props of the component", function () {
        interface IProps {
            prop1? : string;
            prop2? : string;
        }
        class Component extends React.Component<IProps, void> {
            static actions;
            static defaultActions = {};
            static defaultProps: IProps = {
                prop1: "1",
                prop2: "2"
            }

            render() {
                expect(Object(this.props)).toEqual({
                    prop1: "connected 1",
                    prop2: "connected 2"
                });

                return (
                    <div></div>
                );
            }
        }

        interface IState {
            connectedComponent?: {
                prop1?: string;
                prop2?: string;
            };
        }
        let simpleRedux = new SimpleRedux<IState>({
            connectedComponent : {
                prop1: "connected 1",
                prop2: "connected 2"
            }
        });

        let ComponentConnected = simpleRedux.connector(Component)(
            s => (s.connectedComponent),
            (p => {
                throw Error("This must not be run");
            }) as any
        );

        const component: React.Component<{}, {}> = TestUtils.renderIntoDocument(
            <Provider store={simpleRedux.store}>
                <ComponentConnected />
            </Provider>
        );
    });
```

I can't neatly move it outside the render, the component given by React TestUtils is utter garbage.

It would be better to keep expect inside the render function, but this is not ideal, what if my render is not run? I still get the "success!" because I can't expect how many expectations are run.

**Comment by FagnerMartinsBrack** [comment]
@mgol @infews Can anybody confirm if there was any advancements in this matter? Is there any links to a list where we can see the discussion mentioned in the comment above? I ask this because this issue is the first result in Google when looking for "jasmine expected assertion count".

This is such a basic feature to prevent false positives when working with asynchronous functions or just a couple of mocks (to ensure tests refactor do not lose determinism in the future). QUnit has it and works like a charm, but unfortunately it doesn't have the same fluency as the jasmine style of writing tests.

**Comment by Ciantic** [comment]
@FagnerMartinsBrack I would not expect this to be fixed, same problem with Chai: https://github.com/chaijs/chai/issues/94 and it have been there for years.

**Comment by slackersoft** [comment]
Jasmine will now tell reporters the number of expectations that were made in each spec. The HTMLReporter will report to your console any specs that don't make any expectations at all. We don't want to require all specs to have expectations, as there can be reasons you may want a spec like that.

At this point, I think this is probably how it will be for the foreseeable future.

**Comment by jahtalab** [comment]
@slackersoft , I think there's no need for jasmine to require all specs to have expectations, simply by providing the number of `expect` calls the developer can choose to fail tests if there are no expectations.

Is the number of expectations accessible during the test?

**Comment by UziTech** [comment]
I created an plugin that will do this called [`jasmine-expect-count`](https://github.com/UziTech/jasmine-expect-count)

usage:

```javascript
it("should call expect 3 times", function () {
  jasmine.expectCount(3);

  expect(1).toBe(1);

  const p = new Promise(function (resolve) {
    setTimeout(function () {
      expect(2).toBe(2);
      resolve();
    }, 1);
  });

  expect(3).toBe(3);

  // if returning p is forgotten only 2 expects will be called.
  return p;
});
```

**Comment by iwllyu** [comment]
jest has this implemented
https://facebook.github.io/jest/docs/en/expect.html#expectassertionsnumber
