### ISSUE TITLE
Restore behavior for spy

### ISSUE THREAD

**Issue by gyandeeps** [jasmine/jasmine#683]
I think it would be a good to restore a spy to its original value (not talking about reset). 
Lets say I spy on an function but later on I want to remove my spy , just for clean up purpose.
This would help different parts of the test suites to create their own spies on certain global functions.

It has been done in `sinonJs` library. http://sinonjs.org/docs/#spies

**Comment by fluky** [comment]
If Jasmine automatically restores spies after each spec is run, why do I get "Error: <spyOn> : setItem has already been spied upon".  I think you must mean "resets" the spy after each.

**Comment by slackersoft** [comment]
Jasmine removes any spies that were created with `spyOn` at the end of the context where they were created. Hedging because a spy created in a `beforeAll` won't be removed until the end of that `describe`, but anywhere else it will be removed at the end of the last `afterEach` for the spec.

If you don't use `spyOn` to set up the first spy Jasmine won't know to remove it and a later `spyOn` call will fail because the external object already has a spy for the property specified.

Hope this helps. Thanks for using Jasmine!
