### ISSUE TITLE
expects in Asynchronous Support still throws an console log

### ISSUE THREAD

**Issue by akrillo89** [jasmine/jasmine#694]
If I use setTimeout and the done() function in an it block then i get a weird console log.

Uncaught Error: 'expect' was used when there was no current spec, this could be because an asynchronous test timed out.

The message tells me that u still know about this bug.

**Comment by slackersoft** [comment]
This has morphed a bit into a "how do I test X?" discussion instead of an issue with jasmine itself. If you still have questions please ask at jasmine-js@googlegroups.com where the community can help answer.

I'm going to close this, as jasmine throwing this error is expected if `expect` is called outside of an `it` etc.

Thanks for using jasmine.

**Comment by lshengjian** [comment]
describe('Message Test', function () {
  it('Message Test', function (done) {
	Message.create({title:'msg1',text:"text1"}, function (err, data) {
		expect(data.title).toBe('msg1');
		expect(data.text).toBe('text1');
		done();
	  });
   });
});

**Comment by sunilkushwaha0101** [comment]
@lshengjian your solution worked for me :)

**Comment by Deepakanandrao** [comment]
Worked for me inside subscribe() too. Thanks!
