### ISSUE TITLE
Please clarify asynchronous function support vs. concurrent test execution

### ISSUE THREAD

**Issue by ghost** [jasmine/jasmine#703]
There's some confusion whether or not tests run asynchronously or not:
http://stackoverflow.com/questions/25652895/are-test-cases-in-jasmine-2-0-run-in-parallel

It's somewhat spelled out on this page https://github.com/pivotal/jasmine/blob/master/release_notes/20.md, but I think it should be more prominent:

> The next function, whether it's a before, spec or after, will wait until this function is called or until a timeout is reached.

Perhaps this can turn into a feature request for async execution.

**Comment by davejon1970** [comment]
We have tests that are still using this version of the test framework.  These tests actually add and remove data from a database in beforeEach and afterEach methods.  They are really integration tests not unit tests.  Anyway, there are intermittent failures related to expected data from the database in the tests.  Could this be caused by this built-in time limit elapsing? What is the time limit? Can this timeout happen to tests in the same file or only in tests in different files?

**Comment by slackersoft** [comment]
The Jasmine 2.x default async timeout is 5 seconds and is defined in `jasmine.DEFAULT_TIMEOUT_INTERVAL`, I believe it is the same in 1.3 as well. This timeout only affects specs that are run asynchronously (`runs`/`waitsFor` in 1.3, `done` callback in 2.x).

Hope this helps. Thanks for using Jasmine!

**Comment by matthewadams** [comment]
@slackersoft Perhaps my understanding is flawed here: I understood that if a spec takes longer than its configured timeout (either `jasmine.DEFAULT_TIMEOUT_INTERVAL` or the timeout interval given as the last argument to the spec (`it('should ...', done => { ... }, 10000)`), the asynchronous spec fails with `- Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

We have an ever increasing number of integration specs that each take up to several seconds to complete, and we'd like to run them in parallel. Simply decreasing the spec timeout causes them to fail with the above error message.

[Your comment above](https://github.com/jasmine/jasmine/issues/703#issuecomment-62965757) seems to indicate that you _could_ run tests in parallel, but it doesn't appear to be supported based on our experimentation.

Please either explain how to run specs in parallel or confirm that tests cannot be run in parallel successfully.

**Comment by slackersoft** [comment]
Because of the single-threadedness of javascript, it isn't really possible to run your tests in parallel in a single browser window. My comment above a way in which a suite could have code from more than one spec interleaved because Jasmine doesn't have any way to stop other async code that might be running after a call to `done` or a timeout.

If you want to run specs in parallel, you'll need to split them across multiple top level suites, or implement a [custom boot](https://jasmine.github.io/edge/custom_boot.html) that has a segregate your specs/suites when calling `env.execute()`.

**Comment by brandonros** [comment]
@slackersoft 

> If you want to run specs in parallel, you'll need to split them across multiple top level suites, or implement a custom boot that has a segregate your specs/suites when calling env.execute().

Could you please expand?

**Comment by CrowdHailer** [comment]
Has anyone been able to implement the custom boot as described?
I have a test suite with several calls to the crypto API. because that work is done on another thread I would get a valuable speedup by running the tests in parallel.

**Comment by slackersoft** [comment]
I don't really have a working example of a custom boot that parallelizes the suite (especially in a browser), but I would expect it to have a consistent hashing function that could take the list of spec IDs and passing a subset of those in to the call to `execute`. The docs for most of this aren't very obvious, but I would be happy to see a pull request to help with this.
