### ISSUE TITLE
Add marker to indicate that you expect the test fail

### ISSUE THREAD

**Issue by jankoprowski** [jasmine/jasmine#744]
From time to time we are developing our protractor/jasmine tests before implementing solution. We miss feature to be able to indicate that we expect the test fail. After desired solution will be implemented test really start failing because test start passing. All what implementer mast to do is remove indicator. Is implementing such thing is possible in jasmine?

**Comment by rohit** [comment]
Ah I remember using something similar with [Cucumber](https://github.com/cucumber/cucumber/) IIRC. Basically you mark a test as failing so when you run it and it fails the test runner says: n failing tests expected to fail. BUT if a failing test passes the runner complains about it saying a test expected to fail but passed.

There is already a mechanism for marking a spec as pending. Well you just use a different method `xit/xdescribe` instead of `it/describe`. Maybe introduce new methods like `fit/fdescribe` and make jasmine expect these specs to fail and if they pass then fail the test suite?

**Comment by slackersoft** [comment]
By just expecting the test to fail in any manner you possibly cover up issues where your test was never failing for the correct reason, so you won't be able to properly make it pass. Additionally, `fit`/`fdescribe` are already taken as function names in 2.1 for focused specs.

I'm don't think this is something that we want in the jasmine core. You should be able to create an extension that added the functions and a reporter that treated them as desired.

I'm going to close this.
