### ISSUE TITLE
Warn when two tests have the same name.

### ISSUE THREAD

**Issue by jacksonrayhamilton** [jasmine/jasmine#747]
Apparently if I use `describe` and accidentally describe the same string twice, one of the `describe` calls is overridden.

Jasmine should throw an error and tell me to fix my names. It is bad if you copy and paste one test as a template, and forget to change its name, and wonder why the previous test is failing, only to find out it was overridden.

**Comment by slackersoft** [comment]
I'm not sure what you mean by "overridden". Jasmine should keep both describes around for you, they'll just be named the same thing. Jasmine doesn't try to keep any kind of unique list of spec/suite descriptions, so you shouldn't see any specs not be run just because they have the same name as another.

Can you give me an example of the suite and output you're seeing? Also, what version of jasmine are you running and how?

**Comment by jacksonrayhamilton** [comment]
My apologies; I've tested this and confirmed that two tests with the same name do run.

I was running my tests using Karma with the `karma-mocha-reporter` plugin. It looks like the *reporter* was just not *listing* both of the tests. Interestingly, this happened in another reporter (`karma-spec-reporter`) too, so either it's a Karma bug or a common design error.

**Comment by slackersoft** [comment]
Awesome, I'm going to close this then.
