### ISSUE TITLE
Reporter should receive number of specs to be run

### ISSUE THREAD

**Issue by ptomato** [jasmine/jasmine#753]
Reporters' `jasmineStarted()` method is called with an object that looks like this:
```js
{
     totalSpecsDefined: 200
}
```
However, this isn't an accurate number of specs to be run. For example, if there are focused specs, then there are far fewer run than are reported as defined.

It would be convenient for this object to report the number of specs that are expected to be run - so that a [TAP](http://testanything.org/) reporter could output a test plan at the beginning of the suite, for example.

An alternative would be to call `specStarted()` and `specDone()` for each unfocused spec so the reporter would know the specs were there, but got skipped.

**Comment by slackersoft** [comment]
`totalSpecsDefined` isn't meant to be a count of how many specs will be run. As its name implies, it is simply the count of specs (`it`, `xit`, `fit` calls) that were loaded.

Jasmine doesn't know exactly how many specs are going to be run because there is more than one way to make a spec not run. If an `xdescribe` or `fdescribe` is used, the specs under it rely on the suite object knowing whether its child specs should be run, so they aren't marked in any way.

Given this, I'm not totally sure that we want/need a count of expected specs to be run, but if you want to give it a try and submit a pull request, I'd be happy to review it.

**Comment by slackersoft** [comment]
As of 715de7aa384e089a843b8806cefa699d9455463f on master, every defined spec will report start and complete to the reporter regardless of whether they will run. This is a fix for #774, but it sounds like it also fixes this issue as well.

**Comment by ptomato** [comment]
Yes, that does indeed fix this issue. Thanks!
