### ISSUE TITLE
Programmatically adding tests?

### ISSUE THREAD

**Issue by JonnyRa** [jasmine/jasmine#754]
Hi,

Just run into a bit of an issue and can't see a way to implement it using jasmine at the moment... was wondering if you could help.

I have a master detail kindof setup in an webapp I'm working on.  It consists of a list of Fields, when you select one you then see a list of options.  I'd like to write a check that for every field the list of options is sorted alphabetically.  I'd also not like to specify all the Fields for two reasons - there is quite a few of them; and that I would like this test to apply to future fields without having to do more work.

So I'd like to generate some tests from a list of these Fields dynamically.  I thought this would be easy in jasmine because it, describe etc are just functions... however the snag here seems to be that I need to load the list of fields asynchronously first.

In a `describe` I can't provide a `done` function to make it hang around for the list to come back and in a `beforeEach/beforeAll` calling `it` doesnt seem to work... it also wont be called at all unless I already have at least one `it`.

Is there anyway I can achieve this at the moment?  I'd guess so but it feels like maybe not.

**Comment by JonnyRa** [comment]
My workaround is currently to use one test with loads of asserts in conjunction with an asyncronous runner class which I add steps to in a loop and which only calls done when all the steps are complete.

I'm basically delineating the different tests in the output by doing this

    expect(fieldName).toEqual('to be sorted');

Its a bit horrible but could be worse - at least you get to see all of the failures and not just the first from how you've implemented expect.

It feels like you should be able to do this but after having a look at the code it looks like suites aren't expecting to be modified during execution and I haven't poked around enough to see what would need to change to allow that

**Comment by slackersoft** [comment]
Jasmine doesn't support adding specs once the suite has started running. Usually, when I've needed to do this, I've been able to know the list of options ahead of time and just loop through them to make the `it` calls. e.g.

````javascript
// I just wrote this, it may not work right.
['foo', 'bar'].forEach(function(val) {
  it("should " + val, function() {
    expect(val).toEqual('foo');
  });
});
````

If your cases are coming from a server, you can either try making a synchronous ajax call so the suite won't finish loading until those specs get defined, or just duplicate the cases in your jasmine specs and do the loop inline.

Dynamically changing the suite once the run is started isn't really something we want jasmine to support. At the very least, it would screw up reporters, because we wouldn't know how many specs we were going to run. I'm going to close this.

Thanks for using jasmine!

**Comment by JonnyRa** [comment]
Fair enough.  Yeah I can see this might be a pretty big change + thinking about it I'm not sure I've ever used a testing library that could handle this.

I'm reasonably happy with the solution I'm already using
