### ISSUE TITLE
Using jasmine.clock() in async specs can cause test pollution

### ISSUE THREAD

**Issue by sgravrock** [jasmine/jasmine#790]
If an async spec calls done() from a timer that’s run by jasmine.clock(), then that spec’s calls to jasmine.clock.tick() can affect the behavior of following specs. There’s an example in Jasmine’s own test suite. This spec looks like it shouldn’t pass, and indeed it doesn’t when run by itself:
https://github.com/jasmine/jasmine/blob/8c59875afe3968a61ddcf445762a90de53cf8951/spec/core/integration/EnvSpec.js#L968-L1037

It should fail because each call to jasmine.clock().tick() happens before the setTimeout() call that registers the function that it’s suppose to execute. When the entire suite is run, it passes because of this spec:

https://github.com/jasmine/jasmine/blob/8c59875afe3968a61ddcf445762a90de53cf8951/spec/core/integration/EnvSpec.js#L811-L833

I think this is what’s happening: The call to jasmine.clock().tick() on line 829 indirectly leads to the call to done() on line 821, which in turn causes Jasmine to run the next spec while jasmine.clock().tick() is still executing. Any timers registered during an execution of jasmine.clock().tick() will be run before that execution finishes, if the specified interval is low enough. The result of all that is that the invocation of jasmine.clock().tick() in one spec ends up executing timers registered in another spec even though the mock clock was uninstalled and reinstalled in between. 

I can see a few possible ways to fix this:

1. Change the behavior of the mock clock so that you have to call jasmine.clock().tick() again to run any timers that were registered during a tick. This would bring the mock clock’s behavior more in line with real setTimeout().
2. Create a new DelayedFunctionScheduler instance each time the clock is installed.
3. Modify QueueRunner to do a real setTimeout at the end of each async spec.

The catch is that any solution is a breaking change. That’s sort of the point — to break specs that shouldn’t be passing but currently aren’t. The first would, I think, be particularly nasty to inflict on users as part of a Jasmine upgrade, even though it might be the right thing to do if we were starting from scratch. The second and third should at least only break specs that ought to fail. Although it’s a bit indirect, the third option would also have the happy side effect of preventing two specs from being on the call stack at the same time.

The other option is to do nothing to Jasmine itself, work around the problem in the specs, and update the documentation to warn about using the mock clock in async specs.

Thoughts?

**Comment by slackersoft** [comment]
Jasmine actually used to do number 1, but we changed it so that a `setTimeout(..., 0)` would trigger during the current tick to be more in line with user expectations.

We reset the `DelayedFunctionScheduler` when the clock is uninstalled currently, which should be the same as number 2.

`QueueRunner` should be properly using the real `setTimeout` as of 10f87b3b90221711b7343c2c1df4b13644fcac84, so number 3 should be fixed now.

I think the bug here is that if a previous installation of the clock is still running a tick, doing another `setTimeout` or `setInterval` shouldn't be run as part of the currently running tick. A pull request for this should either make `DelayedFunctionSchedule#reset` do the right thing here or as you suggested, make a new one for each installation and throw it away upon uninstall.

**Comment by ccorcos** [comment]
I'm still having this issue...
