### ISSUE TITLE
How come there is not a single reference about jasmine-node in the README?

### ISSUE THREAD

**Issue by bucaran** [jasmine/jasmine#794]
I understand, they are different things, but it would not hurt to mention the `jasmine-node` package IMO. 

Also, collecting a list of _getting started_ with `jasmine` examples would be nice as well. I could provide some as well.

If anyone is interested, I can get on this :metal:

Cheers!

**Comment by slackersoft** [comment]
Thanks for using jasmine. The officially supported way to use jasmine in a node/npm context is to install the npm package named [jasmine](https://npmjs.org/jasmine). Issues and such are in the [jasmine-npm](https://github.com/jasmine/jasmine-npm) github repo.

[Documentation](https://jasmine.github.io/edge/node.html) is at our documentation site [jasmine.github.io](https://jasmine.github.io). The docs for use in node are pretty bare-bones right now and could certainly be improved. We do accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls) for our documentation, if you'd like to help out, or [issues](https://github.com/jasmine/jasmine.github.io/issues) if you have things you'd like see addressed but aren't sure how.

**Comment by bucaran** [comment]
Hey. The documentation at your site talks about how to use the `jasmine` framework to write tests (certainly very important), but I would love to see more about initial setup and configuration, workflows, etc. I would love to help of course. 

What is the difference between `jasmine-node` and `jasmine-npm`?

**Comment by slackersoft** [comment]
jasmine-node was created by the community because, while jasmine tests worked in node, there wasn't an officially supported way to run them. As we've gained a bit more knowledge of how to work in node, we released jasmine-npm around the time when 2.0 was released. jasmine-npm only supports 2.x (probably more like 2.1 and above).

Ideally, there shouldn't be much in the way of setup needed, but some more documentation around what configuration is available in jasmine-npm would be good on the node.js page.
