### ISSUE TITLE
When beforeEach times out, test cases should not execute

### ISSUE THREAD

**Issue by juliemr** [jasmine/jasmine#807]
I would consider this a bug, but I'm happy to hear other opinions. Here's a quick example test case:

``` js
describe('my test', function() {

    beforeEach(function(done) {
      console.log('test start beforeEach');
      setTimeout(function () {
        console.log('test stop beforeEach');
        done();
      }, 4000)
    });

    it('test test one', function() {
      // I don't think this should ever be executed.
      console.log('test test one started');
      expect(true).toBe(false);
    });
});
```

I find it confusing that the `it` block is still executed, even though the test has already timed out.

**Comment by slackersoft** [comment]
Jasmine handles timeouts the same way it handles any other error, and just continues on to the next thing in the queue.

That behavior came up when we were working on #577 because going to the next thing in the queue may not be what the user expects, but we decided to wait on it for now. The reasoning for this is that, in this case, what should probably happen is the `QueueRunner` should jump straight to any `afterEach`s defined for the spec with similar behavior for `afterAll`s, but this would have required a fairly large change to what `QueueRunner` knows about what it is running, instead of just having a list of functions to call.

Additionally, with the new `TreeProcessor` change already going in, we weren't sure we wanted 2 big refactors in the next release.

**Comment by nckpark** [comment]
I ran into the same unexpected behavior recently. Are there any plans to address this? If nothing else, the documentation at http://jasmine.github.io/2.0/introduction.html#section-42 should be updated to make it clear that the spec will run in the case of a timeout.

**Comment by Protractor-33** [comment]
getting an error as "Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."

Protractor version:3.0.0
Jasmine:2.3.4

 jasmineNodeOpts: {
    defaultTimeoutInterval: 30000
  }
if we increase defaultTimeoutInterval its working fine,then what is the advantage of protractor compare to webdriver?
In we driver also by using implicity wait we can acheive this.Please clarify my doubt

**Comment by slackersoft** [comment]
@Protractor-33 You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

**Comment by sgravrock** [comment]
585287b fixes this if you enable the "stop spec on expectation failure" option.

**Comment by usmonster** [comment]
Thanks, @sgravrock! Where is this documented?
