### ISSUE TITLE
question about done() in beforeAll/afterAll

### ISSUE THREAD

**Issue by hankduan** [jasmine/jasmine#824]
From http://jasmine.github.io/2.0/upgrading.html#section-Asynchronous_Specs, it is pointed out that it/beforeEach/afterEach can take a done() callback. However, from experimenting, it feels like beforeAll/afterAll will take this callback too. Is this supported behavior? If so, would you please specify in the docs?

For example:
```javascript
describe('test', function() {
  var x = [];
  beforeAll(function(done) {
    setTimeout(function() {
      x.push('beforeAll');
      done();
    }, 100)
  });

  beforeEach(function(done) {
    setTimeout(function() {
      x.push('beforeEach');
      done();
    }, 100)
  });

  it('before/after all', function() {
    console.log('result: ', x);
  });
});
```

prints 
```
result:  [ 'beforeAll', 'beforeEach' ]
```

**Comment by slackersoft** [comment]
`beforeAll` and `afterAll` can also accept a `done` callback to execute asynchronously.

It looks like a mention of this got missed in the 2.1 docs when they were introduced.

If you'd like to help update the docs, they live [on github](https://github.com/jasmine/jasmine.github.io) and we accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls)

I'm going to close this issue, since it seems like your major question is answered and this is more of a documentation issue. Thanks for using jasmine!
