### ISSUE TITLE
Custom "chain" keywords.

### ISSUE THREAD

**Issue by nbish11** [jasmine/jasmine#834]
Does Jasmine offer any methods to add a custom chain?

For example:

```javascript
// currently you can negate the result 
// of any expectation using the "not" keyword
expect(true).not.toBe(false);    // test passes
```
But, how would I go about doing something like this:

```javascript
// I want to add my own "or" keyword, for example.
expect('Hello Jasmine').toMatch(/hello/i).or.toMatch(/jasmine/i);
```

**Comment by slackersoft** [comment]
Jasmine does not have the ability to add a custom expectation modifier similar to `not`. It's something we've heard of a couple times, but I haven't seen a compelling use case for it yet.

The syntax you've suggested doesn't quite work the same way that `not` does, since it is actually chained onto the matcher and not the `expect` call, so I don't think that particular syntax is something we want to support.

**Comment by slackersoft** [comment]
We haven't heard anything else from the community about this way of chaining matchers, so I'm going to close this.
