### ISSUE TITLE
toHaveBeenCalledWith(param1, undefined) is not considered equivalent to toHaveBeenCalledWith(param1)

### ISSUE THREAD

**Issue by settinghead** [jasmine/jasmine#841]
IMHO these two cases are functionally the same, and should be treated as such (i.e. a test should not fail if you declare `toHaveBeenCalledWith(param1)` but the function is called with `(param1, undefined)`.

**Comment by slackersoft** [comment]
Jasmine prefers to err on the side of being a bit more explicit in how things behave. This means that `toHaveBeenCalledWith` compares the expected argument with the actual argument list in the same way that jasmine compares all arrays, so that argument lists of different lengths are considered to be different.

Also see [this comment](https://github.com/jasmine/jasmine/issues/761#issuecomment-72065447) for more discussion.

This is the currently desired functionality from jasmine's point of view, so it isn't something we're thinking about changing at this point in time.

Thanks for using jasmine! Closing this issue, but feel free to continue the discussion.

**Comment by ankurparihar** [comment]
This doesn't make any sense. I have to clutter my code with all the undefined. God knows what'll happen if I have to deal with object-arguments.
