### ISSUE TITLE
support for JSX?

### ISSUE THREAD

**Issue by ramyathulasingam** [jasmine/jasmine#857]
I added .JS.JSX files in my Rails app to test React, all of my Jasmine specs are now failing. Are there any setup or ways to ignore .JSX files from my test suite.

**Comment by slackersoft** [comment]
Have you looked at [react-jsx-sprockets](https://github.com/jvatic/react-jsx-sprockets)? Also see the discussion in [jasmine/jasmine-gem#222](https://github.com/jasmine/jasmine-gem/pull/222).

Closing this since it sounds like if this is an issue, it is with the [jasmine-gem](https://github.com/jasmine/jasmine-gem) and not jasmine core here.

Thanks for using jasmine!

**Comment by ramyathulasingam** [comment]
Thank so much. react-jsx-sprockets did the magic
