### ISSUE TITLE
Identify the step number were jasmine + protractor test failed

### ISSUE THREAD

**Issue by rayeesnp** [jasmine/jasmine#858]
I am developing tightly coupled Protractor + Jasmine automation system with our test cases management system.

Steps in test procedure also documented in test scripts, when ever protractor test cases fails, I want to identify in which step this is failed and reported in XML

example Test expected like this

@step1 login_page.enterUserName('user1');

@step2 login_page.enterPassword('password');

@step3 home_page = login_page.selectLogin();

If this test failed @ step2, this should be reported in XML ,any thought for implementing this ?

Regards, Rayees

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing.

**Comment by rayeesnp** [comment]
I cannot find this in jasmine, can we consider as new feature request ?

**Comment by slackersoft** [comment]
Jasmine failures will already give you a line number for where the failure occurred. I'm not really sure what the `@step1` annotation could even mean in javascript, so it is unclear what feature you could be requested here.

**Comment by rayeesnp** [comment]
Let me explain the use case in details 

My test cases name "Loginto_system_and_checkvaliduser"

Procedure  in Testcase management system 
Step 1 : Enter URL
Step 2 : Enteruser Name
Step 3 : Enter Password
Step 4: Select Submit button 
Step 5: Verify user is valid or not 

Steps in javaScript 

login_page = accessURL(https://.......)
login_page.enterUserName('user1');
login_page.enterPassword('password');
home_page = login_page.selectLogin();
homa_page.verify()
  
During the automation run, if test case failed at  "step 4" ie home_page = login_page.selectLogin(); it should be able to identify which step its failed "here its 4", based on this  I want to create JIRA ticket with the summary "Test cases Loginto_system_and_checkvaliduser failed at step4 ", while creating JIRA ticket i will pull actual steps from test case management system.

Here the advantage is developer no need to go and re run the test to reproduce the issue, they can map the step number were automation failed and corresponding test case in Test case management system ? 

It make sense ? @slackersoft ?

**Comment by rayeesnp** [comment]
@slackersoft  - can you please re open this ticket? its a new feature request

**Comment by slackersoft** [comment]
Based on the example you've provided, I don't there is anything that jasmine itself can do to solve your problem. It sounds like you're generating jasmine specs from some external source and you want jasmine to turn errors back into your original source. But since jasmine only knows anything about javascript there is no way for this to be accomplished.

What you're probably going to need to do is write your own reporter that knows about your original test case and can translate the line numbers in the javascript specs from jasmine into your test cases.

Since this sounds like a completely custom solution, it isn't something we're likely to implement in jasmine itself.
