### ISSUE TITLE
Allow filtering of specs when tests being run

### ISSUE THREAD

**Issue by keirlawson** [jasmine/jasmine#865]
Currently, by using a custom boot.js file a specFilter can be used to select which tests should be run.  The problem is that this filtering happens when tests are being first registered with Jasmine, rather than when they are being run.  This means that creating a single page interactive test runner is impossible as it is not possible to filter tests based on user input without refreshing the page.

**Comment by slackersoft** [comment]
The way to specify a spec (or specs) to run as you are executing the suite is to pass an array of spec and suite ids to the `execute` function itself. This would mean that your test runner would have to know the ids for all of the spec and/or suite objects that are constructed and associate those with whatever UI you have to let the user pick specs.

Does this solve your problem?

**Comment by keirlawson** [comment]
Looks like it might, is there a public API which can be used to retrieve spec/suite IDs? I didn't find information in the documentation about that parameter for `execute`, did I miss it or has it not been documented?

**Comment by slackersoft** [comment]
Once all the specs have been loaded you should be able to call the `topSuite()` function on your jasmine `Env` (`jasmine.getEnv().topSuite()` if you're not managing the env some other way already). You should be able to then walk down that tree to get all of the `Spec` objects to retrieve their `id`s.

The `execute` function on `Env` isn't well documented because it is primarily for internal use, and this kind of use case is a bit of an advanced feature.

**Comment by keirlawson** [comment]
Would you accept a PR to document the execute param? It would be useful for my use case but I'm not keen on using undocumented features that might be subject to breaking changes within minor versions.

**Comment by slackersoft** [comment]
I'd be happy to have some better documentation for the `execute` function.
