### ISSUE TITLE
Execute a single spec process out of the top specs tree

### ISSUE THREAD

**Issue by lastboy** [jasmine/jasmine#877]
Hi all,

Correct me if I'm wrong but,
even though I'm passing the suites Ids to the "execute" method the reporter still process the entire specs tree.

Specifying the specFilter or the suites IDs - ends with updating the spec status = "disabled" on the SpecDone phase, but what about the entire lifecycle? 

Currently there's no method for setting the top level suite NOR controlling of which suite to be run.
I did an ugly hack messing up with the topSuite children. 

Can you please give a way of executing a single / multi specs?

Thank you

**Comment by slackersoft** [comment]
Disabled specs are not executed, but are reported to the reporters so that the reporters can see what happened to all of the specs that were defined.

**Comment by lastboy** [comment]
That I understand,
But why only the SpecDone phase get to be notified? The other listeners are not aware to the fact which was disabled.

Let's say I'm creating my own reporter and want to ignore those that was disabled. I cannot.

**Comment by slackersoft** [comment]
You should be able to check for the `status` of the spec in your reporter to determine if it was disabled.

**Comment by lastboy** [comment]
I agree,
But the status is being update only when the SpecDone

**Comment by slackersoft** [comment]
The `status` is unavailable until `specDone` because that is the time at which we can guarantee that we have a real status. A spec that is not `disabled` or `pending` would need some kind of `running` status in `specStarted` which would then change in `specDone`. Since the active case is the normal state of the world, we prefer to optimize for that and not have a possibly confusing or transient `status` field in `specStarted` but wait until `specDone` when we are sure we have a valid `status`.

**Comment by slackersoft** [comment]
We haven't heard anything further on this issue in a while, so I'm going to close it. Please comment here or open another issue if this isn't resolved.

Thanks for using jasmine!
