### ISSUE TITLE
Feature Request: Merge `define` description with the same name 

### ISSUE THREAD

**Issue by shamansir** [jasmine/jasmine#881]
It could be helpful for storing specs in different files:

```
theme-a/
    sub-theme.spec.js 
    another-sub-theme.spec.js 
theme-b/
    sub-theme.spec.js 
    another-sub-theme.spec.js 
```

where `sub-theme.spec.js` contains:

```javascript
define('theme-a', function() {
    define('sub-theme', function() {
         // specs
    });
});
```

and `another-sub-theme.spec.js` contains:

```javascript
define('theme-a', function() {
    define('another-sub-theme', function() {
         // specs
    });
});
```

so in the end in the output they are combined in:

```
theme-a
    sub-theme
        ...specs...
    another-sub-theme
        ...specs...
```

**Comment by slackersoft** [comment]
I'm assuming that by `define` you actually mean `describe` since there is no `define` in jasmine. You should be able to do this yourself with a [custom reporter](http://jasmine.github.io/edge/custom_reporter.html).

Currently jasmine's built-in reporters don't look at the text of your `describe`s or `it`s at all. This allows them to be fast and relatively simple to maintain.

This isn't functionality that we want in jasmine itself. Closing.

**Comment by shamansir** [comment]
(fixed the title and body `define` -> `describe` for the search)
