### ISSUE TITLE
I'd like to be able to run the Jasmine project specs in the browser without needing Ruby

### ISSUE THREAD

**Issue by aligneddev** [jasmine/jasmine#883]
In my first pull request, I went through the steps of getting Ruby working (http://geekswithblogs.net/Aligned/archive/2015/06/03/my-github-pull-request-for-jasmine-experience.aspx), but now I have a new computer and don't want to do it again :-). However, I still have a desire to contribute.

I think it'd also help lower the entry boundary for others to contribute.

I'd like to do grunt serve from the command line, then browse to the url and run the tests in the browser and debug.
I started last night, but I don't know enough to get it working. Should this use express? Is "serve" a good name for the grunt task?

**Comment by slackersoft** [comment]
I think this is a good goal, but I'm not totally sure on the best way to approach it.

I don't want the jasmine-core repo to have a bunch of code to run specs in the browser now that we have explicitly extracted that out into other packages ([jasmine-gem](https://github.com/jasmine/jasmine-gem), [jasmine-py](https://github.com/jasmine/jasmine-py), [gulp-jasmine-browser](https://github.com/jasmine/gulp-jasmine-browser), and community supported packages like [grunt-contrib-jasmine](https://github.com/gruntjs/grunt-contrib-jasmine)). I think in this situation, it would make the most sense for jasmine-core to try to use gulp-jasmine-browser to do browser based testing with only a nodejs dependency graph. This will probably require some work in order to get two versions of jasmine loaded for testing.

**Comment by kiewic** [comment]
Please consider reducing the development dependencies to node. Installing Ruby on Windows is very troublesome.

**Comment by johnjbarton** [comment]
>  it would make the most sense for jasmine-core to try to use gulp-jasmine-browser

Does this imply conversion of the existing grunt node test to gulp? 

>This will probably require some work in order to get two versions of jasmine loaded for testing.

AFAICT the execSpecsInNode test uses the previous version of jasmine (in ./node_modules) but with jasmine-core from the source code. So it's sorta 1.2 rather than 2 versions for jasmine. This is fine for smallish changes.  Is that what you have in mind for a browser based test as well?

**Comment by sgravrock** [comment]
> Does this imply conversion of the existing grunt node test to gulp?

As much as I'd like to keep gulp out of Jasmine core entirely, it probably does. I'd strongly prefer to only convert the parts that actually run Jasmine tests over to gulp and keep the rest in grunt. It might also be worth trying to modify `gulp-jasmine-browser` to be able to work inside Grunt, if possible.

> AFAICT the execSpecsInNode test uses the previous version of jasmine (in ./node_modules) but with jasmine-core from the source code. So it's sorta 1.2 rather than 2 versions for jasmine. This is fine for smallish changes. Is that what you have in mind for a browser based test as well?

I don't think that's the way to go. Making sure that the latest version of Jasmine can test itself is a key part of our development process, and we don't want to lose that. The way it works currently is that jasmine-gem publishes a dependency on the released jasmine-core but depends on a local copy in development. I think a hypothetical all-Node setup would need to do something similar.

**Comment by battk** [comment]
If you want, you can imagine that karma is just a server that automates running test runners (with fancy things like running with your updated code whenever a file is changed). There is a kama-jasmine adapter which is mostly in charge of adding jasmine to a list of src files to be loaded and a custom reporter. If you really wanted to, you could maintain your own karma-jasmine adapter so you would control the runner.

I picked karma because it almost does what you want out of the box and has reasonable ide support. It doesn't have to be karma, but pick an all node solution. I didn't really enjoy stumbling with the missing ruby related things.

**Comment by johnjbarton** [comment]
I understand the reluctance to couple jasmine and karma-jasmine, but another way to look at this is as a kind of jasmine-in-browser integration test. Yes you want to unit test jasmine in browsers, but really it's a checkup: you already passed in node.  The additional ways karma-jasmine will fail beyond jasmine-unit test issues include karma-jasmine's configuration of jasmine: maybe that is a good thing?

Just to take the other side, a chrome-only solution based on puppeteer might be an option. You need the install to be foolproof or you need the install to solve cross-browser issues. Getting both is going to be hard to find.

**Comment by wood1986** [comment]
See #1658
