### ISSUE TITLE
Spies leak into other specs

### ISSUE THREAD

**Issue by hackingbeauty** [jasmine/jasmine#888]
My team is using Jasmine-core 2.3.3.  We recently had an issue where a spy in one test leaked into another test.

From what I understand, a spy that is set up in a test automatically gets removed after the test has completed.  Developers do not have to do anything manual in order to remove a spy.

Why would a spy from one test leak into another?  What could I be doing wrong?

**Comment by r4j4h** [comment]
Are you keeping global references to them outside of your tests' closure scopes? Say in a containing describe?

I guess what I'm asking for is more information. :)

**Comment by hackingbeauty** [comment]
@r4j4h, the code below shows what I'm doing.  It was the only way I could get the spies to work.  If I just keep a reference to the spies inside of beforeEach, I run into problems.

This is the wrong thing to do?  Thanks for your help.

```javascript
describe('sample tests', function () {
    var trackSpy1, trackSpy2;

    beforeEach(function(){
      trackSpy1         = spyOn(Object, 'track');
      trackSpy2         = spyOn(window, 'track_click');
    });

    it('ensures something was called with the right arguments', function () {
      Object.doSomething();
      expect(trackSpy1).toHaveBeenCalledWith('data var 1 2 3');  
    });

  });
});
```

**Comment by hackingbeauty** [comment]
Hey, I discovered a solution to the leakage, but I'm not sure why my change works.  I'm using require.js, and when I define my spec this way the leakage occurs:

```javascript
describe('Collab Save Component', function () {

  describe('Tooltip', function() {
    var spy1, spy2;

    define(['collab/collab_savebutton' ], function( collab ) {

      beforeEach(function(){
        spyOn(_, 'contains').and.callFake(function(){
          return { };
        });
      });

      it('sample test', function(){
        ...
      });
    });
  });
});
```
However, when I encapsulate the Jasmine spec within require.js, the spy leakage does NOT occur.

```javascript
define(['collab/collab_savebutton' ], function( collab ) {

  describe('Collab Save Component', function () {

    describe('Tooltip', function() {
      var spy1, spy2;

      beforeEach(function(){
        spyOn(_, 'contains').and.callFake(function(){
          return { };
        });
      });

      it('sample test', function(){
        ...
      });
    });
  });
});
```

Any idea why my fix works? :)

**Comment by r4j4h** [comment]
Very interesting!

So before we consider require.js I want to mention that you should probably also add an `afterEach` that nulls out the `spy1` and `spy2` variables just to be clean. This might even fix the leaking issue outright.

Now since you are using require.js and encapsulating it prevents the leakage it may be related. The behavior you are showing leads me to believe its related to a scoping issue arising from require.js' asynchronous nature in relation to jasmine's.

I am curious, how does this perform?

```

describe('Collab Save Component', function () {

  define(['collab/collab_savebutton' ], function( collab ) {

    describe('Tooltip', function() {
      var spy1, spy2;

      beforeEach(function(){
        spyOn(_, 'contains').and.callFake(function(){
          return { };
        });
      });

      it('sample test', function(){
        ...
      });
    });
  });
});
```

**Comment by hackingbeauty** [comment]
The Jasmine 2.3 specs say the following about spies: "A spy only exists in the describe or it block it is defined, and will be removed after each spec.".

I am using Jasmine 2.3.3.  What must I specifically null out a spy in afterEach if the docs say it will automatically be taken care of?

What do you mean by "how does this perform"?  

Thanks!

**Comment by r4j4h** [comment]
Yes, but I have not referred to the source to see if it explicitly clears them.Considering this issue is arising when coupled with require.js, it seems there is a scoping issue. Why should manually clearing them affect things negatively, other than efficiency?

You found that running the entire test suite inside of your AMD module works well, but when defining an AMD module within a suite it breaks. Keep in mind that the A in AMD for require.js stands for Asynchronous. The Jasmine specs also say that if you testing asynchronous functions you should be using the done parameter and calling it at the appropriate time.

Perhaps that will fix your problem?

My reasoning for asking how that works, is I moved the AMD define block outside of the actual `describe` block the test is running in, but not all the way outside of the suite. I am curious to see if this allows the scopes to play nicely or if it performs the same as the initial issue and does not work.

**Comment by slackersoft** [comment]
@hackingbeauty you shouldn't need to actually hold onto the spy object when using `spyOn`. When you install the spy that way, jasmine replaces the existing function with the resulting spy object. This means that:

````javascript
var foo = spyOn(window, 'alert');
foo === window.alert;

// so
expect(foo).toHaveBeenCalled();
// is the same as
expect(window.alert).toHaveBeenCalled();
````

For the cleanup... After all of your `afterEach` blocks have been run for a spec, jasmine will put the original function that it replaced inside `spyOn` back. This doesn't do anything to an external reference to the spy that may have been made while it was installed. So your `trackSpy1` variable will still have a reference to the spy, and any code that may save off the function for later use will as well, but the source (e.g. `Object.track`) will no longer be a spy.

**Comment by slackersoft** [comment]
It sounds like you may have fixed your problem, and we haven't seen any other updates in a while. I'm going to close this issue, but please comment or open a new issue if you're still having issues.

Thanks for using jasmine!
