### ISSUE TITLE
Unable to install clock when using non-native timing functions

### ISSUE THREAD

**Issue by aron** [jasmine/jasmine#895]
The check introduced in d137b83c1c863abd2069a4a505b6858b1aad5261 to ensure that `jasmine.clock().install()` is called on native timing functions seems a little over zealous. I'm working on a project at the moment that patches the timeout functions to show developers warnings when they forget to use `clock` e.g.

```js
window.setTimeout = function () {
  console.warn('setTimeout() has been called under test, use jasmine.clock() to stub out the timing functions');
}
```

Sadly now I get the following error message. "Error: Jasmine Clock was unable to install over custom global timer functions.". Would it not be better to see if clock.install() has been called twice and then raise the error?

Here's a Jasmine test suite exhibiting the problem I'm seeing.

http://jsbin.com/kagixozaze/edit?js,output

**Comment by slackersoft** [comment]
The jasmine clock refuses to install over anything that is not the built-in timing functions at the time that jasmine is loaded into the page, because we have also had issues with other mock clocks (like Sinon) conflicting with the one provided by jasmine.

I don't think this is going to change. You should either be able to install the clock in a global `beforeEach` which would make it available in every spec, or try to get your patched `setTimeout` in before the jasmine files are loaded on the page.

Thanks for using jasmine! Closing.
