### ISSUE TITLE
Allow me to pass a reason to `xit`

### ISSUE THREAD

**Issue by donaldpipowitch** [jasmine/jasmine#912]
It seems I have no way to pass a reason, if I use `xit`. It would be great to do this to get rid of the `No reason given` warning. Can we use a reason as a third param? `xit('should foo', fooFn, 'ignore this')`

**Comment by slackersoft** [comment]
`xit` is meant to be a very short term method to stop a spec from running, so I don't think it makes sense to pass an explicit message. I could however see changing the message for an `xit` to read something like "Temporarily disabled with xit" instead of just "no message given". This would also be a bit more consistent with other BDD frameworks like rspec for ruby.

I'd would be happy to review a pull request to change the default message for `xit`.

**Comment by JoseRoman** [comment]
@slackersoft Is there any particular place in the UI where this message should be placed?

**Comment by slackersoft** [comment]
There shouldn't need to be any changes to the UI for this, it should simply be a change to how `xit` calls `pend` on the spec, so that it passes the message argument.
