### ISSUE TITLE
Negative zero values in array

### ISSUE THREAD

**Issue by Aciho** [jasmine/jasmine#918]
I'm having an issue writing a test for an array which can contain negative values of zero. This:

```javascript
expect([-0]).toEqual([0]);
```

fails, as does this:

```javascript
expect([-0]).toBe([0]);
```

I understand the logic outlined in #579, but unless I'm missing a better way of writing this test this seems like a much more common case that someone actually wanting to distinguish between 0 and -0.

**Comment by slackersoft** [comment]
Because `toBe` uses the `===` operator to do its comparison, the arrays are not delved into in the same way that `toEqual` does. Since javascript says that `[-0] !== [0]` and for that matter `[-0] != [0]` (even if `-0 === 0`) the `toBe` matcher just uses that.

If you want to use `toEqual` you should also be able to specify a [custom equality comparator](http://jasmine.github.io/edge/custom_equality.html) that allows `-0` to be equal to `0`.

**Comment by slackersoft** [comment]
Closing this, as the current desire in jasmine is that `expect(-0).not.toEqual(0)` should pass, but display the correct -0 and 0 to show the difference.

Thanks for using jasmine!
