### ISSUE TITLE
Feature: Combinatorial and Pairwise unit test generators

### ISSUE THREAD

**Issue by tohagan** [jasmine/jasmine#920]
One of the best new features in NUnit is combinatorial test case generation using their Combinatorial and Pairwise attributes. 

The [All Pairs algorithm](https://en.wikipedia.org/wiki/All-pairs_testing) has been shown to significantly improve combinatorial test coverage without the large blow out in number of combinations that an exhaustive combinatorial test generator incurs.  

[NUnit Parameterized Tests](http://nunit.org/index.php?p=parameterizedTests&r=2.6.3)
- [PairwiseAttribute](http://nunit.org/index.php?p=pairwise&r=2.6.3) - [Source code](https://github.com/nunit/nunit/blob/8bd1ae67b16166f4172d6cc46cf48e6dcdac9e96/src/NUnitFramework/framework/Internal/Builders/PairwiseStrategy.cs) - This is very useful!
- [CombinatorialAttribute](http://nunit.org/index.php?p=combinatorial&r=2.6.3) - [Source code](https://github.com/nunit/nunit/blob/8bd1ae67b16166f4172d6cc46cf48e6dcdac9e96/src/NUnitFramework/framework/Internal/Builders/CombinatorialStrategy.cs)

I'm sure they would be flattered if you used their algorithms.

I imagined Jasmine test generators would be implemented using this code pattern for V1:

      genAllPairs({ field1: [va1, val2], field2: [val3, val4] ... }).forEach(function(tuple) {
      it("with " + JSON.stringify(tuple), function() {

      });

      genAllCombinations({ field1: [va1, val2], field2: [val3, val4] ... }).forEach(function(tuple) {
      it("with " + JSON.stringify(tuple), function() {

      });

And then perhaps a V2 version that can cope with larger number of combinations and can yield a result before all tuples are all generated ...

      git( new AllPairs({ field1: [va1, val2], field2: [val3, val4]), function(tuple)  {
         it("with " + JSON.stringify(tuple), function() {
 
         });
      });

Now AllPairs() is a stateful iterator class used to generate a test case tuple sequence that the new Jasmine `git` method consumes.

You'd then want to also add fgit (focus) and xgit (exclude). You could also run each tuple over a gdescribe() test suite.

These code patterns are just my brainstorming.  Your experience and understanding of the Jasmine framework may dictate otherwise.

**Comment by slackersoft** [comment]
This isn't something we're likely to bring into the core of jasmine. Given your suggestions on how it could work, this seems like it could work very well as a plugin to jasmine, since you'd just be calling the builtin `it` function for each combination.

Jasmine prefers to be simple and extensible instead of trying to include everything out of the box. I'm going to close this issue, but feel free to ask questions on either the [jasmine-js mailing list](https://groups.google.com/forum/#!forum/jasmine-js) or the [jasmine developer list](https://groups.google.com/forum/#!forum/jasmine-js-dev) if you have issues while trying to work on something like this.
