### ISSUE TITLE
Test suite won't contain failedExpectations on spec failure

### ISSUE THREAD

**Issue by RomanKapitonov** [jasmine/jasmine#921]
I've been looking into creating custom reporters to perform sanity checks within a single page application. To perform those checks I've created several specs within one suite and was going to use custom reporter to collect errors from each suite and send them to back-office application on suiteDone callback. 

However I faced an issue with that: It seems latest version of jasmine won't contain failed expectation in suite results when it finishes. To demonstrate what I mean I created a simple [jsfiddle](https://jsfiddle.net/9s1nr9yg/) based on the examples from [here](http://jasmine.github.io/2.3/custom_reporter.html).

Take a look at suiteDone callback to see what happens. It will log the result object inspecting which will show no errors during suite execution. But if you look at specDone callback result you'll see that the spec is actually failed. 

Not sure if it's something that I'm missing or an issue with the code.

**Comment by slackersoft** [comment]
The `failedExpectations` at the suite level are only for failures in an `afterAll`. This was added because at the point that an `afterAll` fails, all the specs have reported their own success or failure, and it is too late to update them.

Any failures that occur in a `beforeAll`, `beforeEach`, `it`, or `afterEach` will be in the `failedExpectations` for the spec. (`beforeAll` goes to all the specs it affects).

This means you'll have to collect the failures from each of the `specDone` calls (and from the `suiteDone`  if you're using `afterAll`) and send them all off together. This is the current desired functionality, and not something we're really looking to change at the moment. The idea is to group the failures with the most specific thing we can for troubleshooting purposes.

**Comment by slackersoft** [comment]
Closing, as we haven't heard anything else from the community, and this is the current desired functionality.

Thanks for using jasmine!
