### ISSUE TITLE
Testing Jasmine Plugins

### ISSUE THREAD

**Issue by joezimjs** [jasmine/jasmine#926]
I'm trying to write a plugin for Jasmine that allows you to return a promise from a spec and will pass or fail that spec depending on whether or not the promise is fulfilled or rejected.

Of course, I want to write tests to make sure that my plugin works correctly, and to be thorough, I need to make sure that tests fail when the promise is rejected... so how do I make a test pass when I need to make sure that a test "successfully fails"? Essentially I'm using Jasmine to test functionality I'm adding to Jasmine.

I'm attempting to grab your solution from [nodeDefineJasmineUnderTest.js](https://github.com/jasmine/jasmine/blob/master/spec/helpers/nodeDefineJasmineUnderTest.js) but there are a few `require`s in there that reference your `src` files, which I don't have access to.

I also tried this in my tests

```js
var jc = require('jasmine-core');
var env = new jc.Env();
```

but that `env` ends up only being a function and not having `env.describe` or `env.it` or anything like that on it, like what you use in your own specs. Can you help me out?

**Comment by joezimjs** [comment]
Sooo... should I just switch to mocha and forget about creating this plugin?

**Comment by slackersoft** [comment]
I'm sorry if you felt like we were ignoring this issue. We work on jasmine in our spare time, and don't always have as much time to dedicate to the project as we would like.

I finally got a chance to look at whats is going on. Since jasmine does its own internal dependency/require stuff, the return value of `Env` straight on the root jasmine object is actually the constructor function for the `Env` you really want.

For what you are trying to do, you may not necessarily need to boot up/require a whole second jasmine so much as just create a new `Env` from the existing one. (I think this should be possible, but haven't really tried it myself).

If it turns out that you do need to get a full new core, you'll also need to `boot` it, to get it fully set up. Take a look at [`node_boot.js`](https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/boot/node_boot.js) for a bit more detail about how the running jasmine is booted.

**Comment by joezimjs** [comment]
Thanks for getting back to me. I'm sorry I got "testy". I just assumed something as popular as Jasmine would have a bit more activity.

Anyway, at this point, just calling `new jasmine.Env()` seems to be working fine. I'll have to look into it more to be certain but otherwise looks good. Thanks.

**Comment by joezimjs** [comment]
Nope. Here's what I have:

```js
describe('suite', function () {
	var env;

	beforeEach(function () {
		env = new jasmine.Env();
	});

	it('should work', function () {
		env.describe('faux suite', function () {
			env.it('faux test', function () {
				expect(true).toBe(false);
			});
		});

		env.execute();
	});
});
```

This is saying that my one spec is failing. Shouldn't the failure be contained in the inner environment so that a spec failing there won't cause a failure according to the output? That's what I'm trying to do.

**Comment by joezimjs** [comment]
nevermind that last comment, I should have been using `env.expect`.

**Comment by joezimjs** [comment]
Is this the best way to determine if a test failed in that `env`?

```
expect(env.topSuite().children[0].children[0].result.status).toBe('failed')
```

That seems to be the only way I can find out if it failed.

**Comment by slackersoft** [comment]
Usually, we register a completion handler on the env itself and do whatever verifications in there. You'll also want to get a `done` callback and call it in there, since suite execution is not guaranteed to be a blocking call. Take a look at [SpecRunningSpec.js](https://github.com/jasmine/jasmine/blob/master/spec/core/integration/SpecRunningSpec.js) for a bit more detail on how jasmine actually `execute`s the inner `env`.

**Comment by joezimjs** [comment]
I assume you're talking about the `addReporter` calls. I discovered the `spec = env.it(...)` on my own just before I came back here. That's a lot simpler and doesn't look silly with the double `.children[0]` bit.

Here's what I have right now:

```js
var promisifyJasmine = require('../jasmine2-as-promised')

describe('jasmine2-as-promised', function () {
	var env
	var FAILED = 'failed'
	var PASSED = 'passed'

	beforeEach(function () {
		env = new jasmine.Env()
	})

	it('should work', function () {
		var spec;

		env.describe('faux suite', function () {
			spec = env.it('faux test', function (done) {
				env.expect(true).toBe(false)
			})
		})

		env.execute()
		expect(spec.result.status).toBe(FAILED)
	})
})
```

I'll definitely use `done` inside `env.addReporter` for `jasmineDone` for my asynchronous tests, but assuming the thing I'm testing is synchronous, can't I just use what I have up there? It seems to work just fine.

**Comment by slackersoft** [comment]
If you're calling `execute` on an `env` you should probably be using `done`, if only to protect yourself from changes to the `QueueRunner` that might change how many steps are run before resetting the stack by calling `setTimeout`.

**Comment by joezimjs** [comment]
Alright, Thanks.
