### ISSUE TITLE
ability to configure "already been spied upon" behavior

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [jasmine/jasmine#931]
currently I get errors if I try to re-spy upon a function. 

this makes my code stateful - which is a serious issue for me. 
I need to remember if this is a spy or not. 
for example: if I decide to have a default spy after written a lot of tests,  I now need to modify the code in all tests from `spyOn(object,'myMethod')` to `object.myMethod...`. seems redundant to me.  

It would be nicer if it worked similar to jquery wrapper.. 

`$('div')` and `$($('div'))` - give the same result. 

`spyOn(obj,'myMethod')` should simply return the spy if spy already exists.

**Comment by slackersoft** [comment]
This is something we've talked about a bit before. The concern was that it might lead to confusion in the specs with users not knowing at which point the function started being spied on. That said, I would be happy to review a pull request that changed this behavior to return the existing spy instead of throwing an error.
