### ISSUE TITLE
Passing "this" to beforeAll / beforeEach / it

### ISSUE THREAD

**Issue by mc0re** [jasmine/jasmine#933]
There is a strange issue with `this`, which can be seen here:

http://plnkr.co/edit/04GzjcMez6YhTroJ3HS6?p=preview

The problem is, that `this` passed to `beforeAll` seems different from `this` passed to other methods. Check console output to see the object details:

```
Inited:  Object {counter: 1}
appSpec.js:22 Before:  Object {} <- where is "counter 1"?
appSpec.js:34 Test 1:  Object {}
appSpec.js:14 Disposing  Object {counter: 1}
appSpec.js:10 Inited:  Object {counter: 2}
appSpec.js:22 Before:  Object {countObj: null}
appSpec.js:43 Test 2:  Object {countObj: null}
appSpec.js:14 Disposing  Object {counter: 2}
```

**Comment by slackersoft** [comment]
The execution context (`this`) that is is used for a `beforeAll` and `afterAll` is by definition different than the `this` for a `beforeEach`, `it`, and `afterEach` because the `All` functions are invoked at the scope of the suite they are declared in, but the other for the individual spec.

Anything set on `this` during the `beforeAll` should be available on `this` in each `beforeEach`, `it`, `afterEach` within that scope. Each spec (`it` and constituent `beforeEach`s and `afterEach`s) also gets its own `this` so that they don't clobber each other. The `this` for any given spec is cloned out from the parent suite just before we start running the first `beforeEach` for that spec.

With how your suite is set up, it ends up adding to the outer context after the clone has already occurred. `beforeAll` is really designed for just putting the result straight onto `this` which would then get copied down to the children. It looks like your example is a bit contrived to show the issue and not your real code, but my suggestion for it would be to remove the `beforeAll` entirely and just have a `beforeEach` that does something like `this.countObj = createObject();`

Hope this helps. Thanks for using jasmine!

**Comment by mc0re** [comment]
Yes, my example was as simple as possible to illustrate the issue.
As I understand, `it` receives not just a copy of `this` sent to `beforeAll`, but a deep copy - otherwise the additional reference would be correct.

**Comment by slackersoft** [comment]
The references from the parent are copied as references to each child. So, if you were to add something at the beginning of the `beforeAll` and add a property to that object, I think you'd get the functionality you're looking for.

**Comment by slackersoft** [comment]
We haven't heard anything else on this issue in a while, and we believe that the current behavior is correct, so I'm going to close this.

Thanks for using jasmine!
