### ISSUE TITLE
Can't call `execute` twice?

### ISSUE THREAD

**Issue by donaldpipowitch** [jasmine/jasmine#935]
When I try to call `execute` more than once it seems the `beforeEach` aren't called again? How can I run Jasmine more than once? (Note: I wait for `onComplete` before running again.) The tests won't change, just the environment where they are executed. I use `jasmine-npm`, but re-`new` the `JasmineRunner` doesn't seem to work.

I currently use a dirty hack where I copy my test files for every `new JasmineRunner`.

**Comment by slackersoft** [comment]
Jasmine doesn't really expect you to call `execute` multiple times for a loaded suite, and so we haven't really tried to make sure that use case works. See #666 for some more discussion.

I believe the reason you need to actually move the files is that otherwise node is just returning the previously loaded versions, but you actually need them to be re-evaluated to get new `describe`s and everything.

Rerunning a loaded `env` is not a feature that is easy for jasmine to support, given the current architecture. I'd be happy to review a pull request that made moved jasmine closer to being able to support this, as it would necessarily require removing various state-based assumptions from the code.

Closing this for now. Thanks for using jasmine!
