### ISSUE TITLE
expected and actual value in passed result object

### ISSUE THREAD

**Issue by ravikumars** [jasmine/jasmine#936]
Currently, when a spec fails, the failedExpectation object contains the expected and actual values. However when the spec passes, the passedExpectation object omit these two. 

Why? 

There is a need for me(and maybe for others) to expose this information in official reports both for failed and passed specs. Also this is extra information that is available and that reporters could choose to ignore for passed spec if they want to.

**Comment by slackersoft** [comment]
Jasmine only holds onto the `actual` and `expected` values when the expectation fails because the `actual` could potentially be very large and we had some issues with performance and memory (see #640). The theory there is that the only time a custom reporter would really want to do anything (like display them) with the `actual` and `expected` is when they don't match.

**Comment by ravikumars** [comment]
Ah. I now see that. 

However I still feel these values are necessary particularly when jasmine is used for documenting automation runs. I see this happening more in QA where there is a need to document passed and failed tests as opposed to strictly finding issues that my happen in developer only situations.

Is it possible make it take a flag to provide this functionality or override the default when needed? Any other workarounds short of changing the jasmine code locally? 

Also the ```passedExpectation.message``` says ```Passed``` now. Is it the same reason why this happens.

<bold>Note:</bold> If the performance issue reported in the linked issue is only for PhantomJs(chrome and other browsers seem to not have issues) then can we consider adding a flag to enable it.

**Comment by slackersoft** [comment]
The message for passed expectations has been `Passed` for a long time. This is partially because of the same assumption that users would only need this kind of information in the case of a failure, but also because the otherwise the message would be very confusing.

I'll have to think about how best to allow the kind of report you're looking for without making it too easy for users to shoot themselves in the foot.

**Comment by slackersoft** [comment]
We haven't seen any interest in this from the community in a while and there have been bad performance issues with keeping things around that we don't need to, so this isn't something I think we're going to change for the foreseeable future.

Closing. Thanks for using Jasmine!
