### ISSUE TITLE
Increase the maximumSpecCallbackDepth or make it configurable

### ISSUE THREAD

**Issue by NameFILIP** [jasmine/jasmine#945]
I've spent a couple of days chasing an issue with maximumSpecCallbackDepth. It either should be configurable or at least, when the currentSpecCallbackDepth is getting reset to 0 (https://github.com/jasmine/jasmine/blob/141fd910f27eeecd27f66646efe00f7512649bd2/lib/jasmine-core/jasmine.js#L657) the user should be notified about this (for example: "Please increase the maximumSpecCallbackDepth or split your test on smaller chunks). 

Otherwise, somebody else will spend more days on debugging this issue.

Related issue: https://github.com/jasmine/jasmine/issues/366

**Comment by slackersoft** [comment]
What issue are you seeing that is being alleviated by raising the `maximumSpecCallbackDepth`? Also, please take a look at [my comment in #366](https://github.com/jasmine/jasmine/issues/366#issuecomment-150704124)

**Comment by FuzzySockets** [comment]
Having too many runnable blocks in a single test is causing the number of queueableFunctions to increase beyond the max callback depth.  When this number is greater than 20, you start getting the "Some of your tests did a full page reload!" from karma. I'm not sure exactly what triggers the runner context to reload, but it only happens when the currentSpecCallbackDepth reaches the maximumSpecCallbackDepth, which triggers the first clearStack conditional statement (resetting the currentSpecCallbackDepth to 0).  I think there is something quirky with the way runnable functions are being registered.  

I notice if I add a new describe block with a single it, that adds two more functions to allFns, which we pass to queueRunnerFactory: queueRunnerFactory({queueableFns: allFns, onComplete: reporter.jasmineDone});

**Comment by slackersoft** [comment]
@FuzzySockets what version of jasmine are you using? Spec execution was fairly heavily refactored as part of the 2.3.0 release so that line you reference no longer exists in that same form. I would be curious if the newer version fixes your problem.

As far as what karma does when a `setTimeout` is called, that sounds like it would be an issue with karma and not jasmine itself.

**Comment by FuzzySockets** [comment]
@slackersoft It happens in both 2.1.0 and 2.3.0

**Comment by NameFILIP** [comment]
I confirm that I had issues with both: 2.1 and 2.3

We had a couple of tests with quite a lot of nested `describe` and `it` blocks. These tests used to fail consistently with the error message ` 'expect' was used when there was no current spec, this could be because an asynchronous test timed out.`. They were regular tests without any async stuff. We fixed this locally by increasing the `maximumSpecCallbackDepth` to 1000. But it would be nice to fix this for the whole library.

**Comment by FuzzySockets** [comment]
I can't put my finger on exactly what is causing the reload upon timeout.  I couldn't find anything in karma that would trigger this behavior.

**Comment by slackersoft** [comment]
If you run your specs in just bare jasmine, without karma, do you see the same problem? Jasmine's own test suite is over 500 specs, and we have sample suites to test against with many thousands of tests that don't exhibit the behavior you mention.

I'm not totally against moving `maximumSpecCallbackDepth` to somewhere more configurable, but it seems like it would just be hiding an underlying issue in some other library.

**Comment by stefan-dimitrov** [comment]
@FuzzySockets @NameFILIP, what browser are your tests running on ? I'm having the same issue, my tests run on PhantomJS.

**Comment by provegard** [comment]
I'm seeing this as well. Currently running a patched Jasmine that lowers the value to 5.

My environment is Scala + Nashorn, so stacks are quite intimidating to begin with. :-)

Before lowering the value, I could run around 12 or 13 tests before tests started to "disappear".
