### ISSUE TITLE
calling jasmine.execute multiple times in node

### ISSUE THREAD

**Issue by donniev** [jasmine/jasmine#963]
Is it possible to call jasmine.execute multiple times with different files.
I have a use case where I want to run tests serially.
When I attempt to do this it appears to just run the first set over again.

```
var Jasmine=require("jasmine");
var jasmine=new Jasmine();
jasmine.execute(["test/testBasic.spec.js"]);
jasmine.execute(["test/testBasic2.spec.js"]);
jasmine.execute(["test/testBasic3.spec.js"]);
jasmine.execute(["test/*.spec.js"]);
```
Output:
```
Started
./Volumes/DataDrive/jasminetest/test/testBasic.spec.js two
/Volumes/DataDrive/jasminetest/test/testBasic.spec.js one
Started
./Volumes/DataDrive/jasminetest/test/testBasic.spec.js two
/Volumes/DataDrive/jasminetest/test/testBasic.spec.js one
Started
./Volumes/DataDrive/jasminetest/test/testBasic.spec.js two
/Volumes/DataDrive/jasminetest/test/testBasic.spec.js one
Started
./Volumes/DataDrive/jasminetest/test/testBasic.spec.js two
/Volumes/DataDrive/jasminetest/test/testBasic.spec.js one
```
The tests log the file name and I see only the first file being called four times.

If I change the order in index.js to:
```
var Jasmine=require("jasmine");
var jasmine=new Jasmine();
jasmine.execute(["test/*.spec.js"]);
jasmine.execute(["test/testBasic.spec.js"]);
jasmine.execute(["test/testBasic2.spec.js"]);
jasmine.execute(["test/testBasic3.spec.js"]);
```.
I see:
```
Started
./Volumes/DataDrive/jasminetest/test/testBasic.spec.js two
/Volumes/DataDrive/jasminetest/test/testBasic.spec.js one
Started
./Volumes/DataDrive/jasminetest/test/testBasic.spec.js two
/Volumes/DataDrive/jasminetest/test/testBasic.spec.js one
Started
./Volumes/DataDrive/jasminetest/test/testBasic.spec.js two
/Volumes/DataDrive/jasminetest/test/testBasic.spec.js one
Started
./Volumes/DataDrive/jasminetest/test/testBasic.spec.js two
/Volumes/DataDrive/jasminetest/test/testBasic.spec.js one
./Volumes/DataDrive/jasminetest/test/testBasic2.spec.js threee
F/Volumes/DataDrive/jasminetest/test/testBasic3.spec.js four
F

Failures:
1) second test secondtestIt
  Message:
    Expected true to be false.
  Stack:
    Error: Expected true to be false.
        at Object.<anonymous> (/Volumes/DataDrive/jasminetest/test/testBasic2.spec.js:8:16)

2) third test Suite third test
  Message:
    Expected true to be false.
  Stack:
    Error: Expected true to be false.
        at Object.<anonymous> (/Volumes/DataDrive/jasminetest/test/testBasic3.spec.js:8:16)
  Message:
    Expected 'one' to equal 'seven'.
  Stack:
    Error: Expected 'one' to equal 'seven'.
        at Object.<anonymous> (/Volumes/DataDrive/jasminetest/test/testBasic3.spec.js:9:17)

4 specs, 2 failures
Finished in 1.001 seconds
```
So it calls the first file 3 times and then calls all four.

**Comment by slackersoft** [comment]
The [jasmine-npm](https://github.com/jasmine/jasmine-npm) module only loads up a single underlying jasmine environment. This is because most of the configuration that is done is simply passed through to the underlying jasmine-core environment.

If you really need to do what you are suggesting, you should be able to simply make a separate `Jasmine` object for each time you want to call `execute`.

Hope this helps. Thanks for using jasmine!

**Comment by Mayank-jain34** [comment]
@slackersoft I have created two instances of jasmine first one is executing perfectly but the second one is not able to find any specs its showing error "No specs found"

**Comment by PhantomMachine** [comment]
I am encountering the same issue as @Mayank-jain34, although I've found a work-around that involves creating a second spec file for the other half of the test to reside.

**Comment by slackersoft** [comment]
When you create an install a Jasmine environment, it assumes control over all of the global Jasmine interface methods (`describe`, `it`, etc), therefore, in order to get two suites in a single process, you would need to create and install one, load up only the specs you want in that one, then create the second and load only those specs. If you really need to run all of the specs in both sets in the same process though, you really shouldn't need two Jasmine environments.

Hope this helps. Thanks for using Jasmine!

**Comment by gviedma** [comment]
I recently ran into this issue as well. The fix that worked for me was to remove the spec from the require cache like so:

```
    for (const path in require.cache) {
        if (path.includes('/path/to/spec')) {
            console.log("Clearing spec from require cache: " + path);
            delete require.cache[path];
        }
    }
```
