### ISSUE TITLE
Get the current Spec

### ISSUE THREAD

**Issue by IPWright83** [jasmine/jasmine#984]
I've not managed to spot an issue/feature request for this, but I'd really really like to be able to get the current spec from within a running test. `this` is normally undefined at the start of a test, and would fit the bill perfectly for my use case.

In my tests I'm typically auto-generating some DOM, and I'll use the ID of the spec or the description of the spec to populate some elements that I can then quiz later. This saves me hard coding everything which I prefer but I'm having to do this for each spec definition and then have to maintain the numbers adding new ones which is a pain:

    var spec1 = it("The First Spec", function() {
        var spec = spec1; // Can now consume spec
    });

    var spec2 = it("The Second Spec", function() {
        var spec = spec2; // I've had a number of times where this was spec1 accidentally... :(
    });

Ideally I'd like something like

    it("The Third Spec", function() {
      var spec = this;
    });

**Comment by slackersoft** [comment]
`this` actually should always be defined in specs in jasmine. In 1.x it was the actual instance of the `Spec` object that was running, but this leaked out other data that we did feel that users should need. In 2.0 we changed it so that the `this` is an empty object that is passed through to all of the `beforeEach`s, to the `it` and the `afterEach`s. `beforeAll` and `afterAll` should also have a this that cascades down to child specs and suites.

Given the issue you're trying to solve, I would actually recommend that you use a single container element (the default jasmine html runner provides a `div` with the id `jasmine_content` for this kind of thing) that is cleaned out between specs (I would recommend in `beforeEach` instead of `afterEach` so you can inspect it when you have a failing spec that you're focussing on). If you're using a different runner, you should also be able to create a different element that you can use for your tests. Doing it this way and cleaning up, also ensures that your specs/implementations don't accidentally use the DOM that is for a different spec.

This isn't something we're likely to change at this point, especially since it would require changing the meaning of `this` in specs.

Closing. Thanks for using jasmine!
