### ISSUE TITLE
documentation for toHaveBeenCalledTimes

### ISSUE THREAD

**Issue by piuccio** [jasmine/jasmine#994]
Hi

[toHaveBeenCalledTimes](https://github.com/jasmine/jasmine/commit/7e6e905814d70156814110ab85b7c188b85de7b5) was recently introduced in jasmine, nice addition btw. It would be nice if it was [documented here](http://jasmine.github.io/2.4/introduction.html).

**Comment by slackersoft** [comment]
The source for the [Jasmine documentation](https://jasmine.github.io) has its [own github repository](https://github.com/jasmine/jasmine.github.io). We do accept [pull requests](https://github.com/jasmine/jasmine.github.io/pulls) for our documentation, if you'd like to help out, or [issues](https://github.com/jasmine/jasmine.github.io/issues) if you have things you'd like see addressed but aren't sure how.

Closing this in favor of an issue directly in the docs. Thanks for using jasmine!

**Comment by florimon** [comment]
It is not possible to call toHaveBeenCalledTimes() with the value 0 (zero). This is because the implementation uses "if (!expected)" to test whether a value was supplied for the 'expected' argument. 

(I know the same can be accomplished with the stanza "expect(...).not.toHaveBeenCalled()" but I feel like toHaveBeenCalledTimes() should support this too).

**Comment by logankd** [comment]
I have fixed the 0 issue with a test in Pull request #1015 
https://github.com/jasmine/jasmine/pull/1015.

Thanks for adding the documentation.
